In [1]:
import pandas as pd

file_path = "../data/raw/mhd_ch4.txt"

df_mhd = pd.read_csv(file_path, skiprows=1, sep=r'\s+',header=1, engine='python') # skip first row, txt is space seperated

In [2]:
pd.set_option('display.max_columns', None)

# Ignore this part
import pandas as pd 
import io

def clean_and_load(file_path, sep='\t'):
    lines=[]
    with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
        for line in f:
            cleaned_line = line.replace('\x00', '')
            lines.append(cleaned_line)

    joined_text = "".join(lines)
    return pd.read_csv(io.StringIO(joined_text), sep=sep)

file_path = "../data/raw/mhd_ch4.txt"
df = clean_and_load(file_path)
print(df.info())

In [3]:
df_mhd.head(20)

,date,time,type,sample,standard,port,ht,tmod,tamb,temp,pflow,psamp,ploop,pamb,rt,w,ht.1,area,skew,start_time,end_time,start_level,end_level,Rl_ht,Rl_a,Rl,norm_ht,norm_a,norm_w,R_ht,R_a,R,C_ht,C_a,C,std_stdev,std_rep,Cstd,flag_ht,flag_a,flag,flag_p
0,940216,142900,air,10m,G-024,3,10.0,40.00,32.27,NaN,841.9,761.10,NaN,761.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,None,NaN
1,940216,144900,air,10m,G-024,3,10.0,40.00,32.48,NaN,840.4,761.07,NaN,761.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,None,NaN
2,940216,150900,air,10m,G-024,3,10.0,40.01,32.75,NaN,839.4,760.99,NaN,760.9,109.8,2.60,190908.0,496440.0,0.63,102.0,135.4,10063.0,10029.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,None,NaN
3,940216,152900,air,10m,G-024,3,10.0,40.00,32.92,NaN,839.6,760.96,NaN,760.9,94.8,6.85,151667.0,1065982.0,1.02,86.2,129.0,99999.0,99999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,None,None,None,NaN
4,940216,180000,air,10m,G-024,3,10.0,40.00,33.31,NaN,845.4,760.72,NaN,760.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,None,NaN
5,940216,182000,air,10m,G-024,3,10.0,40.01,33.10,NaN,846.2,760.60,NaN,760.7,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,None,NaN
6,940216,184000,air,10m,G-024,3,10.0,40.01,33.20,NaN,846.3,760.57,NaN,760.5,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,None,NaN
7,940216,190000,air,10m,G-024,3,10.0,40.00,33.39,NaN,846.5,760.45,NaN,760.4,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,None,NaN
8,940216,192000,air,10m,G-024,3,10.0,40.00,33.61,NaN,846.6,760.34,NaN,760.3,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,None,NaN
9,940216,194000,air,10m,G-024,3,10.0,40.01,33.66,NaN,844.8,760.35,NaN,760.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,None,NaN
10,940216,202300,air,10m,G-024,3,10.0,40.00,33.17,NaN,846.1,759.83,NaN,760.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,None,NaN
11,940216,204300,air,10m,G-024,3,10.0,40.00,33.05,NaN,846.3,759.91,NaN,759.8,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,None,NaN
12,940216,210300,air,10m,G-024,3,10.0,40.01,33.06,NaN,846.3,759.72,NaN,759.7,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,None,NaN
13,940216,212400,air,10m,G-024,3,10.0,40.00,33.01,NaN,846.3,759.65,NaN,759.7,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,None,NaN
14,940216,214400,air,10m,G-024,3,10.0,40.00,32.94,NaN,846.1,759.62,NaN,759.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,None,NaN
15,940216,220400,air,10m,G-024,3,10.0,40.00,32.87,NaN,845.9,759.58,NaN,759.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,None,NaN
16,940216,222400,air,10m,G-024,3,10.0,40.01,32.76,NaN,845.2,759.62,NaN,759.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,None,NaN
17,940216,224400,air,10m,G-024,3,10.0,40.00,32.71,NaN,846.1,759.55,NaN,759.5,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,None,NaN
18,940216,230400,air,10m,G-024,3,10.0,40.00,32.69,NaN,844.4,759.49,NaN,759.5,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,None,NaN
19,940216,232400,air,10m,G-024,3,10.0,40.00,32.65,NaN,844.9,759.25,NaN,759.3,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,None,NaN

In [4]:
df_mhd.iloc[[187]]

,date,time,type,sample,standard,port,ht,tmod,tamb,temp,pflow,psamp,ploop,pamb,rt,w,ht.1,area,skew,start_time,end_time,start_level,end_level,Rl_ht,Rl_a,Rl,norm_ht,norm_a,norm_w,R_ht,R_a,R,C_ht,C_a,C,std_stdev,std_rep,Cstd,flag_ht,flag_a,flag,flag_p
187,940219,110700,air,10m,G-024,3,10.0,39.99,24.06,NaN,831.3,750.55,NaN,750.6,94.8,6.88,169063.0,1257709.0,1.0,82.8,128.8,30941.0,30767.0,1.07645,1.07584,1.07645,1.0766,1.076,0.9994,1.07645,1.07584,1.07645,1821.87,1820.85,1821.87,3.172,3.415,1692.489,None,None,None,NaN

In [5]:
print(df_mhd.shape)

(817955, 42)

In [6]:
print(df_mhd.columns.tolist())

['date', 'time', 'type', 'sample', 'standard', 'port', 'ht', 'tmod', 'tamb', 'temp', 'pflow', 'psamp', 'ploop', 'pamb', 'rt', 'w', 'ht.1', 'area', 'skew', 'start_time', 'end_time', 'start_level', 'end_level', 'Rl_ht', 'Rl_a', 'Rl', 'norm_ht', 'norm_a', 'norm_w', 'R_ht', 'R_a', 'R', 'C_ht', 'C_a', 'C', 'std_stdev', 'std_rep', 'Cstd', 'flag_ht', 'flag_a', 'flag', 'flag_p']

In [7]:
print(df_mhd.isnull().sum())

date                0
time                0
type                0
sample              0
standard            0
port                0
ht                  0
tmod           112284
tamb           112285
temp           817954
pflow            2402
psamp            2330
ploop          817954
pamb             2404
rt               1590
w                1590
ht.1             1590
area             1590
skew             1590
start_time       1590
end_time         1590
start_level      1590
end_level        1590
Rl_ht           51247
Rl_a            49492
Rl              58674
norm_ht         51247
norm_a          51247
norm_w          51247
R_ht            51247
R_a             49492
R               58674
C_ht            52743
C_a             50993
C               59835
std_stdev       21817
std_rep        471913
Cstd                0
flag_ht        688213
flag_a         782254
flag           815538
flag_p         817955
dtype: int64

In [8]:
df_mhd.iloc[[1579]]

,date,time,type,sample,standard,port,ht,tmod,tamb,temp,pflow,psamp,ploop,pamb,rt,w,ht.1,area,skew,start_time,end_time,start_level,end_level,Rl_ht,Rl_a,Rl,norm_ht,norm_a,norm_w,R_ht,R_a,R,C_ht,C_a,C,std_stdev,std_rep,Cstd,flag_ht,flag_a,flag,flag_p
1579,940311,20100,std,G-024,G-024,1,0.0,40.0,23.65,NaN,853.9,760.4,NaN,760.5,96.4,7.26,163108.0,1274524.0,1.0,84.2,130.8,27106.0,27488.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.406,NaN,1692.489,*,None,None,NaN

# feature rename

import pandas as pd
file_path = "../data/raw/mhd_ch4.txt"
df_mhd = pd.read_fwf(file_path) # skiprows =3 will cause value error, save feature columns and delete it later
df_mhd

In [9]:
feature_names = [  
'date', 'time', 'type', 'sample', 'standard', 'port', 'ht', 'tmod', 'tamb', 'temp', 'pflow', 'psamp', 'ploop', 'pamb', 'rt', 'w', 
'CH4_ht.1', 'CH4_area', 'CH4_skew', 'CH4_start_time', 'CH4_end_time', 'CH4_start_level', 'CH4_end_level', 'CH4_Rl_ht', 'CH4_Rl_a', 'CH4_Rl', 'CH4_norm_ht', 'CH4_norm_a', 'CH4_norm_w', 
'CH4_R_ht', 'CH4_R_a', 'CH4_R', 'CH4_C_ht', 'CH4_C_a', 'CH4_C', 'CH4_std_stdev', 'CH4_std_rep', 'CH4_Cstd', 'CH4_flag_ht', 'CH4_flag_a', 'CH4_flag', 'CH4_flag_p'
]
df_mhd = pd.read_csv(file_path, skiprows=3, names = feature_names, sep=r'\s+', header=None)
df_mhd

/tmp/ipykernel_10767/861009909.py:6: DtypeWarning: Columns (37,40) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mhd = pd.read_csv(file_path, skiprows=3, names = feature_names, sep=r'\s+', header=None)

,date,time,type,sample,standard,port,ht,tmod,tamb,temp,pflow,psamp,ploop,pamb,rt,w,CH4_ht.1,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p
0,940216,142900,air,10m,G-024,3,10.0,40.00,32.27,NaN,841.9,761.10,NaN,761.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
1,940216,144900,air,10m,G-024,3,10.0,40.00,32.48,NaN,840.4,761.07,NaN,761.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
2,940216,150900,air,10m,G-024,3,10.0,40.01,32.75,NaN,839.4,760.99,NaN,760.9,109.8,2.60,190908.0,496440.0,0.63,102.0,135.4,10063.0,10029.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
3,940216,152900,air,10m,G-024,3,10.0,40.00,32.92,NaN,839.6,760.96,NaN,760.9,94.8,6.85,151667.0,1065982.0,1.02,86.2,129.0,99999.0,99999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,NaN,NaN,NaN,NaN
4,940216,180000,air,10m,G-024,3,10.0,40.00,33.31,NaN,845.4,760.72,NaN,760.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
817950,260518,65300,std,J-286,J-286,3,0.0,40.00,22.06,NaN,813.5,752.32,NaN,752.4,77.8,3.98,133194.0,131007.0,0.50,73.0,99.8,99999.0,62297.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.649,NaN,2015.923,A,NaN,NaN,NaN
817951,260518,71300,air,9m,J-286,1,9.0,40.00,22.32,NaN,808.6,752.28,NaN,752.2,79.0,4.57,160607.0,508996.0,0.46,73.0,102.0,99999.0,64464.0,1.02271,1.00491,1.00491,1.0227,1.0049,0.9981,1.02271,1.00491,1.00491,2061.71,2025.82,2025.82,3.649,3.666,2015.923,A,NaN,NaN,NaN
817952,260518,73300,std,J-286,J-286,3,0.0,40.00,22.19,NaN,813.1,752.27,NaN,752.4,80.6,5.17,180892.0,882007.0,0.47,73.0,109.2,84204.0,66307.0,1.07106,1.34773,1.34773,1.0712,1.3480,1.0953,1.07106,1.34773,1.34773,2159.17,2716.92,2716.92,4.605,NaN,2015.923,A,NaN,NaN,NaN
817953,260518,75300,air,9m,J-286,1,9.0,40.00,22.10,NaN,808.2,752.13,NaN,752.2,80.4,5.01,186959.0,856303.0,0.41,73.0,106.6,87769.0,65923.0,0.97017,0.83156,NaN,0.9701,0.8315,0.9433,0.97017,0.83156,NaN,1955.78,1676.37,NaN,4.605,NaN,2015.923,*,*,A,NaN
817954,260518,81300,std,J-286,J-286,3,0.0,40.00,22.23,NaN,813.3,752.09,NaN,752.0,82.0,5.46,204547.0,1177596.0,0.43,73.0,115.2,75876.0,68601.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.873,NaN,2015.923,A,NaN,NaN,NaN

In [10]:
df_mhd.head(20)

,date,time,type,sample,standard,port,ht,tmod,tamb,temp,pflow,psamp,ploop,pamb,rt,w,CH4_ht.1,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p
0,940216,142900,air,10m,G-024,3,10.0,40.00,32.27,NaN,841.9,761.10,NaN,761.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
1,940216,144900,air,10m,G-024,3,10.0,40.00,32.48,NaN,840.4,761.07,NaN,761.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
2,940216,150900,air,10m,G-024,3,10.0,40.01,32.75,NaN,839.4,760.99,NaN,760.9,109.8,2.60,190908.0,496440.0,0.63,102.0,135.4,10063.0,10029.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
3,940216,152900,air,10m,G-024,3,10.0,40.00,32.92,NaN,839.6,760.96,NaN,760.9,94.8,6.85,151667.0,1065982.0,1.02,86.2,129.0,99999.0,99999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,NaN,NaN,NaN,NaN
4,940216,180000,air,10m,G-024,3,10.0,40.00,33.31,NaN,845.4,760.72,NaN,760.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
5,940216,182000,air,10m,G-024,3,10.0,40.01,33.10,NaN,846.2,760.60,NaN,760.7,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
6,940216,184000,air,10m,G-024,3,10.0,40.01,33.20,NaN,846.3,760.57,NaN,760.5,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
7,940216,190000,air,10m,G-024,3,10.0,40.00,33.39,NaN,846.5,760.45,NaN,760.4,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
8,940216,192000,air,10m,G-024,3,10.0,40.00,33.61,NaN,846.6,760.34,NaN,760.3,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
9,940216,194000,air,10m,G-024,3,10.0,40.01,33.66,NaN,844.8,760.35,NaN,760.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
10,940216,202300,air,10m,G-024,3,10.0,40.00,33.17,NaN,846.1,759.83,NaN,760.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
11,940216,204300,air,10m,G-024,3,10.0,40.00,33.05,NaN,846.3,759.91,NaN,759.8,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
12,940216,210300,air,10m,G-024,3,10.0,40.01,33.06,NaN,846.3,759.72,NaN,759.7,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
13,940216,212400,air,10m,G-024,3,10.0,40.00,33.01,NaN,846.3,759.65,NaN,759.7,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
14,940216,214400,air,10m,G-024,3,10.0,40.00,32.94,NaN,846.1,759.62,NaN,759.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
15,940216,220400,air,10m,G-024,3,10.0,40.00,32.87,NaN,845.9,759.58,NaN,759.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
16,940216,222400,air,10m,G-024,3,10.0,40.01,32.76,NaN,845.2,759.62,NaN,759.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
17,940216,224400,air,10m,G-024,3,10.0,40.00,32.71,NaN,846.1,759.55,NaN,759.5,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
18,940216,230400,air,10m,G-024,3,10.0,40.00,32.69,NaN,844.4,759.49,NaN,759.5,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
19,940216,232400,air,10m,G-024,3,10.0,40.00,32.65,NaN,844.9,759.25,NaN,759.3,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN

In [11]:
df_mhd.tail(5)

,date,time,type,sample,standard,port,ht,tmod,tamb,temp,pflow,psamp,ploop,pamb,rt,w,CH4_ht.1,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p
817950,260518,65300,std,J-286,J-286,3,0.0,40.0,22.06,NaN,813.5,752.32,NaN,752.4,77.8,3.98,133194.0,131007.0,0.50,73.0,99.8,99999.0,62297.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.649,NaN,2015.923,A,NaN,NaN,NaN
817951,260518,71300,air,9m,J-286,1,9.0,40.0,22.32,NaN,808.6,752.28,NaN,752.2,79.0,4.57,160607.0,508996.0,0.46,73.0,102.0,99999.0,64464.0,1.02271,1.00491,1.00491,1.0227,1.0049,0.9981,1.02271,1.00491,1.00491,2061.71,2025.82,2025.82,3.649,3.666,2015.923,A,NaN,NaN,NaN
817952,260518,73300,std,J-286,J-286,3,0.0,40.0,22.19,NaN,813.1,752.27,NaN,752.4,80.6,5.17,180892.0,882007.0,0.47,73.0,109.2,84204.0,66307.0,1.07106,1.34773,1.34773,1.0712,1.3480,1.0953,1.07106,1.34773,1.34773,2159.17,2716.92,2716.92,4.605,NaN,2015.923,A,NaN,NaN,NaN
817953,260518,75300,air,9m,J-286,1,9.0,40.0,22.10,NaN,808.2,752.13,NaN,752.2,80.4,5.01,186959.0,856303.0,0.41,73.0,106.6,87769.0,65923.0,0.97017,0.83156,NaN,0.9701,0.8315,0.9433,0.97017,0.83156,NaN,1955.78,1676.37,NaN,4.605,NaN,2015.923,*,*,A,NaN
817954,260518,81300,std,J-286,J-286,3,0.0,40.0,22.23,NaN,813.3,752.09,NaN,752.0,82.0,5.46,204547.0,1177596.0,0.43,73.0,115.2,75876.0,68601.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.873,NaN,2015.923,A,NaN,NaN,NaN

In [12]:
df_mhd_real = pd.read_fwf(file_path, skiprows=3, names=feature_names, col_specs='infer')
pd.set_option('display.max_columns', None)
df_mhd_real.head(5)

,date,time,type,sample,standard,port,ht,tmod,tamb,temp,pflow,psamp,ploop,pamb,rt,w,CH4_ht.1,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p
0,940216,142900,air,10m,G-024,3,10,40.00,32.27,NaN,841.9,761.10,NaN,761.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
1,940216,144900,air,10m,G-024,3,10,40.00,32.48,NaN,840.4,761.07,NaN,761.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
2,940216,150900,air,10m,G-024,3,10,40.01,32.75,NaN,839.4,760.99,NaN,760.9,109.8,2.60,190908.0,496440.0,0.63,102.0,135.4,10063.0,10029.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
3,940216,152900,air,10m,G-024,3,10,40.00,32.92,NaN,839.6,760.96,NaN,760.9,94.8,6.85,151667.0,1065982.0,1.02,86.2,129.0,99999.0,99999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,NaN,NaN,NaN,NaN
4,940216,180000,air,10m,G-024,3,10,40.00,33.31,NaN,845.4,760.72,NaN,760.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN

In [13]:
df_mhd_real.iloc[[1579]]

,date,time,type,sample,standard,port,ht,tmod,tamb,temp,pflow,psamp,ploop,pamb,rt,w,CH4_ht.1,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p
1579,940311,20100,std,G-024,G-024,1,0,40.0,23.65,NaN,853.9,760.4,NaN,760.5,96.4,7.26,163108.0,1274524.0,1.0,84.2,130.8,27106.0,27488.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.406,NaN,1692.489,NaN,*,NaN,NaN

In [14]:
df_mhd_real.tail(5)

,date,time,type,sample,standard,port,ht,tmod,tamb,temp,pflow,psamp,ploop,pamb,rt,w,CH4_ht.1,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p
817950,260518,65300,std,J-286,J-286,3,0,40.0,22.06,NaN,813.5,752.32,NaN,752.4,77.8,3.98,133194.0,131007.0,0.50,73.0,99.8,99999.0,62297.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.649,NaN,2015.923,NaN,NaN,NaN,NaN
817951,260518,71300,air,9m,J-286,1,9,40.0,22.32,NaN,808.6,752.28,NaN,752.2,79.0,4.57,160607.0,508996.0,0.46,73.0,102.0,99999.0,64464.0,1.02271,1.00491,1.00491,1.0227,1.0049,0.9981,1.02271,1.00491,1.00491,2061.71,2025.82,2025.82,3.649,3.666,2015.923,NaN,NaN,NaN,NaN
817952,260518,73300,std,J-286,J-286,3,0,40.0,22.19,NaN,813.1,752.27,NaN,752.4,80.6,5.17,180892.0,882007.0,0.47,73.0,109.2,84204.0,66307.0,1.07106,1.34773,1.34773,1.0712,1.3480,1.0953,1.07106,1.34773,1.34773,2159.17,2716.92,2716.92,4.605,NaN,2015.923,NaN,NaN,NaN,NaN
817953,260518,75300,air,9m,J-286,1,9,40.0,22.10,NaN,808.2,752.13,NaN,752.2,80.4,5.01,186959.0,856303.0,0.41,73.0,106.6,87769.0,65923.0,0.97017,0.83156,NaN,0.9701,0.8315,0.9433,0.97017,0.83156,NaN,1955.78,1676.37,NaN,4.605,NaN,2015.923,*,*,NaN,NaN
817954,260518,81300,std,J-286,J-286,3,0,40.0,22.23,NaN,813.3,752.09,NaN,752.0,82.0,5.46,204547.0,1177596.0,0.43,73.0,115.2,75876.0,68601.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.873,NaN,2015.923,NaN,NaN,NaN,NaN

In [15]:
df_mhd.shape

(817955, 42)

df_mhd = df_mhd.drop(index=[0,1]).reset_index(drop=True)
df_mhd

df_mhd['time'].to_string
df_mhd['time'].isnull().sum()

df_mhd['date'] = df_mhd['date'].astype(str)

df_mhd['time'] = df_mhd['date'].str[6:]
df_mhd['date'] = df_mhd['date'].str[:6]

In [16]:
df_mhd.head(20)

,date,time,type,sample,standard,port,ht,tmod,tamb,temp,pflow,psamp,ploop,pamb,rt,w,CH4_ht.1,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p
0,940216,142900,air,10m,G-024,3,10.0,40.00,32.27,NaN,841.9,761.10,NaN,761.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
1,940216,144900,air,10m,G-024,3,10.0,40.00,32.48,NaN,840.4,761.07,NaN,761.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
2,940216,150900,air,10m,G-024,3,10.0,40.01,32.75,NaN,839.4,760.99,NaN,760.9,109.8,2.60,190908.0,496440.0,0.63,102.0,135.4,10063.0,10029.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
3,940216,152900,air,10m,G-024,3,10.0,40.00,32.92,NaN,839.6,760.96,NaN,760.9,94.8,6.85,151667.0,1065982.0,1.02,86.2,129.0,99999.0,99999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,NaN,NaN,NaN,NaN
4,940216,180000,air,10m,G-024,3,10.0,40.00,33.31,NaN,845.4,760.72,NaN,760.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
5,940216,182000,air,10m,G-024,3,10.0,40.01,33.10,NaN,846.2,760.60,NaN,760.7,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
6,940216,184000,air,10m,G-024,3,10.0,40.01,33.20,NaN,846.3,760.57,NaN,760.5,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
7,940216,190000,air,10m,G-024,3,10.0,40.00,33.39,NaN,846.5,760.45,NaN,760.4,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
8,940216,192000,air,10m,G-024,3,10.0,40.00,33.61,NaN,846.6,760.34,NaN,760.3,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
9,940216,194000,air,10m,G-024,3,10.0,40.01,33.66,NaN,844.8,760.35,NaN,760.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
10,940216,202300,air,10m,G-024,3,10.0,40.00,33.17,NaN,846.1,759.83,NaN,760.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
11,940216,204300,air,10m,G-024,3,10.0,40.00,33.05,NaN,846.3,759.91,NaN,759.8,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
12,940216,210300,air,10m,G-024,3,10.0,40.01,33.06,NaN,846.3,759.72,NaN,759.7,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
13,940216,212400,air,10m,G-024,3,10.0,40.00,33.01,NaN,846.3,759.65,NaN,759.7,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
14,940216,214400,air,10m,G-024,3,10.0,40.00,32.94,NaN,846.1,759.62,NaN,759.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
15,940216,220400,air,10m,G-024,3,10.0,40.00,32.87,NaN,845.9,759.58,NaN,759.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
16,940216,222400,air,10m,G-024,3,10.0,40.01,32.76,NaN,845.2,759.62,NaN,759.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
17,940216,224400,air,10m,G-024,3,10.0,40.00,32.71,NaN,846.1,759.55,NaN,759.5,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
18,940216,230400,air,10m,G-024,3,10.0,40.00,32.69,NaN,844.4,759.49,NaN,759.5,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
19,940216,232400,air,10m,G-024,3,10.0,40.00,32.65,NaN,844.9,759.25,NaN,759.3,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN

In [17]:
df_mhd.iloc[[185]]

,date,time,type,sample,standard,port,ht,tmod,tamb,temp,pflow,psamp,ploop,pamb,rt,w,CH4_ht.1,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p
185,940219,102700,cal1060,G-024,G-024,1,0.0,40.01,23.16,NaN,846.8,1058.3,NaN,751.2,95.2,7.51,205489.0,1651923.0,1.0,82.6,130.2,30872.0,30727.0,0.92736,1.00177,0.92736,1.3073,1.4122,1.0901,0.92736,1.00177,0.92736,1569.54,1695.49,1692.49,3.18,NaN,1692.489,NaN,NaN,NaN,NaN

In [18]:
df_mhd['type'].unique()

array(['air', 'std', 'tank', 'tank100', 'cal560', 'cal660', 'cal860',
       'cal960', 'cal1060', 'blank', 'labair', 'cal15', 'cal30', 'cal45',
       'cal60', 'cal75', 'cal90', 'cal105', 'cal120', 'cal135', 'cal150',
       'cal165', 'cal180', 'cal200', 'cal225', 'cal250', 'cal300',
       'cal500', 'cal', '-'], dtype=object)

In [24]:
fillna_col = ['CH4_flag_ht', 'CH4_flag_a', 'CH4_flag', 'CH4_flag_p']
for i in fillna_col:
    df_mhd[i].fillna(' ')
df_mhd.head()

,date,time,type,sample,standard,port,ht,tmod,tamb,temp,pflow,psamp,ploop,pamb,rt,w,CH4_ht.1,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p
0,940216,142900,air,10m,G-024,3,10.0,40.00,32.27,NaN,841.9,761.10,NaN,761.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
1,940216,144900,air,10m,G-024,3,10.0,40.00,32.48,NaN,840.4,761.07,NaN,761.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
2,940216,150900,air,10m,G-024,3,10.0,40.01,32.75,NaN,839.4,760.99,NaN,760.9,109.8,2.60,190908.0,496440.0,0.63,102.0,135.4,10063.0,10029.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
3,940216,152900,air,10m,G-024,3,10.0,40.00,32.92,NaN,839.6,760.96,NaN,760.9,94.8,6.85,151667.0,1065982.0,1.02,86.2,129.0,99999.0,99999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,NaN,NaN,NaN,NaN
4,940216,180000,air,10m,G-024,3,10.0,40.00,33.31,NaN,845.4,760.72,NaN,760.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN

In [19]:
df_mhd.to_csv("../data/processed/mhd_ch4_formatted_v1.csv", index=False)

In [20]:
data = pd.read_csv("../data/processed/mhd_ch4_formatted_v1.csv")
data['type'].unique()

/tmp/ipykernel_10767/3969392065.py:1: DtypeWarning: Columns (37,40) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("../data/processed/mhd_ch4_formatted_v1.csv")

array(['air', 'std', 'tank', 'tank100', 'cal560', 'cal660', 'cal860',
       'cal960', 'cal1060', 'blank', 'labair', 'cal15', 'cal30', 'cal45',
       'cal60', 'cal75', 'cal90', 'cal105', 'cal120', 'cal135', 'cal150',
       'cal165', 'cal180', 'cal200', 'cal225', 'cal250', 'cal300',
       'cal500', 'cal', '-'], dtype=object)

In [23]:
data[data['sample']=='dynamic']

,date,time,type,sample,standard,port,ht,tmod,tamb,temp,pflow,psamp,ploop,pamb,rt,w,CH4_ht.1,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p
380175,90224,94200,tank,dynamic,J-116,9,0.0,40.00,20.48,NaN,801.2,768.51,NaN,768.7,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00000,0.00000,NaN,0.0000,0.0000,0.0000,0.00000,0.00000,NaN,0.00,0.00,NaN,3.588,NaN,1888.518,F,F,NaN,NaN
380177,90224,95200,tank,dynamic,J-116,9,0.0,40.00,20.49,NaN,810.5,768.53,NaN,768.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00000,0.00000,NaN,0.0000,0.0000,0.0000,0.00000,0.00000,NaN,0.00,0.00,NaN,3.573,NaN,1888.518,F,F,NaN,NaN
380179,90224,100200,tank,dynamic,J-116,9,0.0,39.99,20.49,NaN,802.2,768.57,NaN,768.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00000,0.00000,NaN,0.0000,0.0000,0.0000,0.00000,0.00000,NaN,0.00,0.00,NaN,3.570,NaN,1888.518,F,F,NaN,NaN
380181,90224,101200,tank,dynamic,J-116,9,0.0,39.99,20.28,NaN,794.5,768.62,NaN,768.7,98.8,8.34,42373.0,387982.0,1.05,85.0,137.0,27157.0,27257.0,0.26525,0.26496,0.26525,0.2653,0.2650,0.9989,0.26525,0.26496,0.26525,500.92,500.38,500.92,3.570,NaN,1888.518,NaN,NaN,NaN,NaN
380183,90224,102200,tank,dynamic,J-116,9,0.0,39.99,20.42,NaN,811.0,768.64,NaN,768.5,98.8,8.31,42377.0,387030.0,1.07,85.0,137.0,26984.0,27134.0,0.26534,0.26506,0.26534,0.2653,0.2651,0.9977,0.26534,0.26506,0.26534,501.11,500.58,501.11,3.570,NaN,1888.518,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475105,121101,122500,blank,dynamic,J-151,7,0.0,40.00,20.37,NaN,729.8,729.70,NaN,729.8,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1873.252,NaN,NaN,NaN,NaN
477235,121201,122500,blank,dynamic,J-151,7,0.0,40.00,20.20,NaN,762.5,762.64,NaN,762.5,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00000,0.00000,0.00000,0.0000,0.0000,0.0000,0.00000,0.00000,0.00000,0.00,0.00,0.00,2.267,NaN,1873.252,NaN,NaN,NaN,NaN
479436,130101,122500,blank,dynamic,J-151,7,0.0,40.00,19.58,NaN,756.4,756.32,NaN,756.3,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00000,0.00000,NaN,0.0000,0.0000,0.0000,0.00000,0.00000,NaN,0.00,0.00,NaN,2.574,NaN,1873.252,F,F,NaN,NaN
481657,130201,123600,blank,dynamic,J-151,7,0.0,40.00,19.82,NaN,750.3,750.38,NaN,750.3,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00000,0.00000,NaN,0.0000,0.0000,0.0000,0.00000,0.00000,NaN,0.00,0.00,NaN,2.329,NaN,1873.252,F,F,NaN,NaN
483643,130301,125100,blank,dynamic,J-158,7,0.0,40.00,19.28,NaN,772.2,772.10,NaN,772.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00000,0.00000,0.00000,0.0000,0.0000,0.0000,0.00000,0.00000,0.00000,0.00,0.00,0.00,1.962,NaN,1873.197,NaN,NaN,NaN,NaN

READ tac_ch4.txt

In [24]:
import pandas as pd

file_path = "../data/raw/tac_ch4.txt"

df_tac = pd.read_csv(file_path, skiprows=1, sep=r'\s+', header=1) # skip first row, txt is space seperated

In [25]:
df_tac

,date,time,type,sample,standard,port,dry,wet,stdev,std_rep,...,h2o,stdev.1,press,press_stdev,temp,temp_stdev,temp.1,temp.2,temp.3,valve
0,120111,162730,unknown,-,USN-20112109,0,1944.517,1945.109,42.208,NaN,...,-0.02232,0.00175,140.00525,0.01396,44.90277,0.01251,32.14167,44.77072,NaN,31442.617
1,120111,162830,unknown,-,USN-20112109,0,1972.043,1972.643,57.714,NaN,...,-0.02232,0.00170,140.00435,0.01518,44.92952,0.00415,32.36250,44.91882,NaN,31543.971
2,120111,162930,unknown,-,USN-20112109,0,1940.176,1940.768,65.419,NaN,...,-0.02243,0.00221,140.00513,0.01176,44.93352,0.00128,32.59792,44.99702,NaN,31626.549
3,120111,163030,unknown,-,USN-20112109,0,2021.915,2022.526,80.016,NaN,...,-0.02217,0.00256,140.00745,0.01437,44.92616,0.00253,32.81506,45.02549,NaN,31687.379
4,120111,163130,unknown,-,USN-20112109,0,1976.217,1976.825,57.151,NaN,...,-0.02259,0.00192,140.00314,0.01321,44.91914,0.00165,32.98813,45.02443,NaN,31726.805
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295869,121005,84830,air,54m,USN-20112109,8,1889.822,1885.213,0.223,0.21,...,0.18023,0.00042,139.99887,0.01703,45.00093,0.00023,35.70686,44.98597,NaN,30923.232
295870,121005,84930,air,54m,USN-20112109,8,1889.385,1884.777,0.197,0.21,...,0.18023,0.00041,139.99811,0.02215,45.00074,0.00020,35.71851,44.98595,NaN,30925.715
295871,121005,85030,air,54m,USN-20112109,8,1889.844,1885.232,0.217,0.21,...,0.18034,0.00046,139.99934,0.01784,45.00039,0.00020,35.72079,44.98594,NaN,30926.928
295872,121005,85130,air,54m,USN-20112109,8,1890.200,1885.582,0.186,0.21,...,0.18056,0.00049,140.00098,0.01534,45.00001,0.00019,35.71106,44.98581,NaN,30929.023
295873,121005,85230,air,54m,USN-20112109,8,1890.031,1885.414,0.321,0.21,...,0.18053,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
print(df_tac.columns.tolist())

['date', 'time', 'type', 'sample', 'standard', 'port', 'dry', 'wet', 'stdev', 'std_rep', 'std_stdev', 'target_error', 'Cdrift', 'C', 'N', 'Nfiltered', 'time.1', 'h2o', 'stdev.1', 'press', 'press_stdev', 'temp', 'temp_stdev', 'temp.1', 'temp.2', 'temp.3', 'valve']

In [27]:
df_tac.shape

(295874, 27)

deal the problem that flag sign is connected with featurre C (such as 1827x)

In [28]:
df_tac.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 295874 entries, 0 to 295873
Data columns (total 27 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   date          295874 non-null  int64
 1   time          295874 non-null  int64
 2   type          295874 non-null  object
 3   sample        295874 non-null  object
 4   standard      295874 non-null  object
 5   port          295874 non-null  int64
 6   dry           295874 non-null  float64
 7   wet           295874 non-null  float64
 8   stdev         295874 non-null  float64
 9   std_rep       102697 non-null  float64
 10  std_stdev     105763 non-null  float64
 11  target_error  529 non-null     float64
 12  Cdrift        292724 non-null  float64
 13  C             295504 non-null  object
 14  N             295874 non-null  int64
 15  Nfiltered     202010 non-null  float64
 16  time.1        295874 non-null  float64
 17  h2o           270966 non-null  float64
 18  stdev.1       270875 non-null  float64
 19  press         295873 non-null  float64
 20  press_stdev   295873 non-null  float64
 21  temp          295873 non-null  float64
 22  temp_stdev    295873 non-null  float64
 23  temp.1        295873 non-null  float64
 24  temp.2        295873 non-null  float64
 25  temp.3        0 non-null       float64
 26  valve         295873 non-null  float64
dtypes: float64(19), int64(4), object(4)
memory usage: 60.9+ MB

C should be flaot?
convert into float first

In [29]:
df_tac['C'].head(20)

0     1955.527x
1     1983.217x
2     1951.159x
3     2033.386x
4     1987.416x
5     1988.226F
6     1985.406F
7     1915.031F
8     1940.282F
9     1981.204F
10    1931.891F
11    1980.398F
12    1947.380F
13    1949.511F
14    1909.053F
15    1939.482F
16    1913.494F
17    1949.543F
18    1934.023F
19    1895.129F
Name: C, dtype: object

In [30]:
import numpy as np

def split_flag (val):
    if pd.isna(val):
        return np.nan, np.nan
    
    val_str = str(val).strip()
    # check if last val is a character(Flag)
    if val_str[-1].isalpha() or val_str[-1] == '*':
        c_val = float(val_str[:-1])
        flag_val = val_str[-1]
    else:
        c_val = float(val_str) # normal value, then direcly convert to float
        flag_val = " " # no flag, give it a space
    
    return c_val, flag_val

In [31]:
df_tac['C'], df_tac['ch4_flag'] = zip(*df_tac['C'].map(split_flag))

print(df_tac[['C', 'ch4_flag']].head(20))
df_tac['C']

           C ch4_flag
0   1955.527        x
1   1983.217        x
2   1951.159        x
3   2033.386        x
4   1987.416        x
5   1988.226        F
6   1985.406        F
7   1915.031        F
8   1940.282        F
9   1981.204        F
10  1931.891        F
11  1980.398        F
12  1947.380        F
13  1949.511        F
14  1909.053        F
15  1939.482        F
16  1913.494        F
17  1949.543        F
18  1934.023        F
19  1895.129        F

0         1955.527
1         1983.217
2         1951.159
3         2033.386
4         1987.416
            ...
295869    1900.195
295870    1899.755
295871    1900.217
295872    1900.576
295873    1900.406
Name: C, Length: 295874, dtype: float64

In [32]:
df_tac.head(20)

,date,time,type,sample,standard,port,dry,wet,stdev,std_rep,...,stdev.1,press,press_stdev,temp,temp_stdev,temp.1,temp.2,temp.3,valve,ch4_flag
0,120111,162730,unknown,-,USN-20112109,0,1944.517,1945.109,42.208,NaN,...,0.00175,140.00525,0.01396,44.90277,0.01251,32.14167,44.77072,NaN,31442.617,x
1,120111,162830,unknown,-,USN-20112109,0,1972.043,1972.643,57.714,NaN,...,0.00170,140.00435,0.01518,44.92952,0.00415,32.36250,44.91882,NaN,31543.971,x
2,120111,162930,unknown,-,USN-20112109,0,1940.176,1940.768,65.419,NaN,...,0.00221,140.00513,0.01176,44.93352,0.00128,32.59792,44.99702,NaN,31626.549,x
3,120111,163030,unknown,-,USN-20112109,0,2021.915,2022.526,80.016,NaN,...,0.00256,140.00745,0.01437,44.92616,0.00253,32.81506,45.02549,NaN,31687.379,x
4,120111,163130,unknown,-,USN-20112109,0,1976.217,1976.825,57.151,NaN,...,0.00192,140.00314,0.01321,44.91914,0.00165,32.98813,45.02443,NaN,31726.805,x
5,120111,163230,unknown,-,USN-20112109,0,1977.023,1977.629,107.839,NaN,...,0.00258,139.99792,0.01910,44.91655,0.00026,33.13750,45.00900,NaN,31758.904,F
6,120111,163330,unknown,-,USN-20112109,0,1974.220,1974.855,94.284,NaN,...,0.00115,140.00032,0.01554,44.91776,0.00100,33.26172,44.98967,NaN,31785.496,F
7,120111,163430,unknown,-,USN-20112109,0,1904.261,1904.902,51.648,NaN,...,0.00000,140.00146,0.01652,44.92261,0.00181,33.35547,44.97134,NaN,31807.650,F
8,120111,163530,unknown,-,USN-20112109,0,1929.363,1930.012,59.736,NaN,...,0.00000,139.99977,0.01241,44.92999,0.00249,33.42248,44.95708,NaN,31827.049,F
9,120111,163630,unknown,-,USN-20112109,0,1970.042,1970.705,71.395,NaN,...,0.00000,140.00076,0.01586,44.93916,0.00306,33.47794,44.94679,NaN,31844.387,F
10,120111,163730,unknown,-,USN-20112109,0,1921.022,1921.668,30.451,NaN,...,0.00000,140.00096,0.01696,44.94887,0.00277,33.51382,44.94103,NaN,31857.955,F
11,120111,163830,unknown,-,USN-20112109,0,1969.241,1969.904,70.028,NaN,...,0.00000,140.00214,0.01152,44.95813,0.00269,33.56085,44.93909,NaN,31872.648,F
12,120111,163930,unknown,-,USN-20112109,0,1936.419,1937.071,39.461,NaN,...,0.00000,139.99553,0.01358,44.96662,0.00232,33.58278,44.93938,NaN,31882.432,F
13,120111,164030,unknown,-,USN-20112109,0,1938.537,1939.190,142.405,NaN,...,0.00000,140.00235,0.01529,44.97430,0.00199,33.63235,44.94104,NaN,31896.764,F
14,120111,164130,unknown,-,USN-20112109,0,1898.318,1898.957,15.359,NaN,...,0.00000,140.00854,0.01686,44.98050,0.00164,33.68164,44.94359,NaN,31912.176,F
15,120111,164230,unknown,-,USN-20112109,0,1928.567,1929.216,31.420,NaN,...,0.00000,140.02963,0.08316,44.98534,0.00135,33.73897,44.94599,NaN,31961.027,F
16,120111,164330,unknown,-,USN-20112109,0,1902.733,1903.373,36.078,NaN,...,0.00000,140.01212,0.02237,44.98892,0.00090,33.78395,44.94802,NaN,32437.586,F
17,120111,164430,unknown,-,USN-20112109,0,1938.570,1939.222,30.627,NaN,...,0.00000,139.99870,0.01410,44.99151,0.00075,33.82721,44.94981,NaN,32555.811,F
18,120111,164530,unknown,-,USN-20112109,0,1923.141,1923.788,37.563,NaN,...,0.00000,140.00996,0.01495,44.99374,0.00071,33.89363,44.95130,NaN,32657.541,F
19,120111,164630,unknown,-,USN-20112109,0,1884.477,1885.111,16.566,NaN,...,0.00000,140.00494,0.01437,44.99538,0.00038,33.98176,44.95257,NaN,32746.449,F

In [33]:
feature_name_tacch4 = [
  'date', 'time', 'type', 'sample', 'standard', 'port', 
 'ch4_dry', 'ch4_wet', 'ch4_stdev', 'ch4_std_rep', 'ch4_std_stdev',
  'ch4_target_error','ch4_Cdrift', 'ch4_C', 'ch4_N', 'ch4_Nfiltered',
  'cycle_time', 'h2o', 'h2o_stdev', 'cavity_press', 'cavity_press_stdev', 
  'cavity_temp', 'cavity_temp_stdev', 'das_temp', 'etalon_temp', 
  'warmbox_temp', 'outlet_valve','ch4_flag'
]

In [34]:
df_tac.columns = feature_name_tacch4

In [35]:
df_tac.head(20)

,date,time,type,sample,standard,port,ch4_dry,ch4_wet,ch4_stdev,ch4_std_rep,...,h2o_stdev,cavity_press,cavity_press_stdev,cavity_temp,cavity_temp_stdev,das_temp,etalon_temp,warmbox_temp,outlet_valve,ch4_flag
0,120111,162730,unknown,-,USN-20112109,0,1944.517,1945.109,42.208,NaN,...,0.00175,140.00525,0.01396,44.90277,0.01251,32.14167,44.77072,NaN,31442.617,x
1,120111,162830,unknown,-,USN-20112109,0,1972.043,1972.643,57.714,NaN,...,0.00170,140.00435,0.01518,44.92952,0.00415,32.36250,44.91882,NaN,31543.971,x
2,120111,162930,unknown,-,USN-20112109,0,1940.176,1940.768,65.419,NaN,...,0.00221,140.00513,0.01176,44.93352,0.00128,32.59792,44.99702,NaN,31626.549,x
3,120111,163030,unknown,-,USN-20112109,0,2021.915,2022.526,80.016,NaN,...,0.00256,140.00745,0.01437,44.92616,0.00253,32.81506,45.02549,NaN,31687.379,x
4,120111,163130,unknown,-,USN-20112109,0,1976.217,1976.825,57.151,NaN,...,0.00192,140.00314,0.01321,44.91914,0.00165,32.98813,45.02443,NaN,31726.805,x
5,120111,163230,unknown,-,USN-20112109,0,1977.023,1977.629,107.839,NaN,...,0.00258,139.99792,0.01910,44.91655,0.00026,33.13750,45.00900,NaN,31758.904,F
6,120111,163330,unknown,-,USN-20112109,0,1974.220,1974.855,94.284,NaN,...,0.00115,140.00032,0.01554,44.91776,0.00100,33.26172,44.98967,NaN,31785.496,F
7,120111,163430,unknown,-,USN-20112109,0,1904.261,1904.902,51.648,NaN,...,0.00000,140.00146,0.01652,44.92261,0.00181,33.35547,44.97134,NaN,31807.650,F
8,120111,163530,unknown,-,USN-20112109,0,1929.363,1930.012,59.736,NaN,...,0.00000,139.99977,0.01241,44.92999,0.00249,33.42248,44.95708,NaN,31827.049,F
9,120111,163630,unknown,-,USN-20112109,0,1970.042,1970.705,71.395,NaN,...,0.00000,140.00076,0.01586,44.93916,0.00306,33.47794,44.94679,NaN,31844.387,F
10,120111,163730,unknown,-,USN-20112109,0,1921.022,1921.668,30.451,NaN,...,0.00000,140.00096,0.01696,44.94887,0.00277,33.51382,44.94103,NaN,31857.955,F
11,120111,163830,unknown,-,USN-20112109,0,1969.241,1969.904,70.028,NaN,...,0.00000,140.00214,0.01152,44.95813,0.00269,33.56085,44.93909,NaN,31872.648,F
12,120111,163930,unknown,-,USN-20112109,0,1936.419,1937.071,39.461,NaN,...,0.00000,139.99553,0.01358,44.96662,0.00232,33.58278,44.93938,NaN,31882.432,F
13,120111,164030,unknown,-,USN-20112109,0,1938.537,1939.190,142.405,NaN,...,0.00000,140.00235,0.01529,44.97430,0.00199,33.63235,44.94104,NaN,31896.764,F
14,120111,164130,unknown,-,USN-20112109,0,1898.318,1898.957,15.359,NaN,...,0.00000,140.00854,0.01686,44.98050,0.00164,33.68164,44.94359,NaN,31912.176,F
15,120111,164230,unknown,-,USN-20112109,0,1928.567,1929.216,31.420,NaN,...,0.00000,140.02963,0.08316,44.98534,0.00135,33.73897,44.94599,NaN,31961.027,F
16,120111,164330,unknown,-,USN-20112109,0,1902.733,1903.373,36.078,NaN,...,0.00000,140.01212,0.02237,44.98892,0.00090,33.78395,44.94802,NaN,32437.586,F
17,120111,164430,unknown,-,USN-20112109,0,1938.570,1939.222,30.627,NaN,...,0.00000,139.99870,0.01410,44.99151,0.00075,33.82721,44.94981,NaN,32555.811,F
18,120111,164530,unknown,-,USN-20112109,0,1923.141,1923.788,37.563,NaN,...,0.00000,140.00996,0.01495,44.99374,0.00071,33.89363,44.95130,NaN,32657.541,F
19,120111,164630,unknown,-,USN-20112109,0,1884.477,1885.111,16.566,NaN,...,0.00000,140.00494,0.01437,44.99538,0.00038,33.98176,44.95257,NaN,32746.449,F

In [36]:
df_tac.to_csv("../data/processed/tac_ch4_formatted_v1.csv", index=False)

In [37]:
import pandas as pd

file_path = "../data/raw/tac_co2.txt"

df_taco2 = pd.read_csv(file_path, skiprows=1, sep=r'\s+', header=1) # skip first row, txt is space seperated

In [38]:
df_taco2.head(20)

,date,time,type,sample,standard,port,dry,wet,stdev,std_rep,...,h2o,stdev.1,press,press_stdev,temp,temp_stdev,temp.1,temp.2,temp.3,valve
0,120111,162730,unknown,-,USN-20112109,0,403.464,403.606,1.063,NaN,...,-0.02232,0.00175,140.00525,0.01396,44.90277,0.01251,32.14167,44.77072,NaN,31442.617
1,120111,162830,unknown,-,USN-20112109,0,402.944,403.085,1.308,NaN,...,-0.02232,0.00170,140.00435,0.01518,44.92952,0.00415,32.36250,44.91882,NaN,31543.971
2,120111,162930,unknown,-,USN-20112109,0,400.992,401.133,1.802,NaN,...,-0.02243,0.00221,140.00513,0.01176,44.93352,0.00128,32.59792,44.99702,NaN,31626.549
3,120111,163030,unknown,-,USN-20112109,0,401.753,401.893,1.516,NaN,...,-0.02217,0.00256,140.00745,0.01437,44.92616,0.00253,32.81506,45.02549,NaN,31687.379
4,120111,163130,unknown,-,USN-20112109,0,401.479,401.622,0.743,NaN,...,-0.02259,0.00192,140.00314,0.01321,44.91914,0.00165,32.98813,45.02443,NaN,31726.805
5,120111,163230,unknown,-,USN-20112109,0,401.215,401.356,0.619,NaN,...,-0.02248,0.00258,139.99792,0.01910,44.91655,0.00026,33.13750,45.00900,NaN,31758.904
6,120111,163330,unknown,-,USN-20112109,0,401.416,401.565,0.727,NaN,...,-0.02362,0.00115,140.00032,0.01554,44.91776,0.00100,33.26172,44.98967,NaN,31785.496
7,120111,163430,unknown,-,USN-20112109,0,404.622,404.779,2.342,NaN,...,-0.02471,0.00000,140.00146,0.01652,44.92261,0.00181,33.35547,44.97134,NaN,31807.650
8,120111,163530,unknown,-,USN-20112109,0,401.350,401.506,2.698,NaN,...,-0.02471,0.00000,139.99977,0.01241,44.92999,0.00249,33.42248,44.95708,NaN,31827.049
9,120111,163630,unknown,-,USN-20112109,0,410.890,411.049,3.356,NaN,...,-0.02471,0.00000,140.00076,0.01586,44.93916,0.00306,33.47794,44.94679,NaN,31844.387
10,120111,163730,unknown,-,USN-20112109,0,402.361,402.517,2.391,NaN,...,-0.02471,0.00000,140.00096,0.01696,44.94887,0.00277,33.51382,44.94103,NaN,31857.955
11,120111,163830,unknown,-,USN-20112109,0,401.677,401.833,0.485,NaN,...,-0.02471,0.00000,140.00214,0.01152,44.95813,0.00269,33.56085,44.93909,NaN,31872.648
12,120111,163930,unknown,-,USN-20112109,0,401.610,401.765,1.532,NaN,...,-0.02471,0.00000,139.99553,0.01358,44.96662,0.00232,33.58278,44.93938,NaN,31882.432
13,120111,164030,unknown,-,USN-20112109,0,402.768,402.924,1.124,NaN,...,-0.02471,0.00000,140.00235,0.01529,44.97430,0.00199,33.63235,44.94104,NaN,31896.764
14,120111,164130,unknown,-,USN-20112109,0,401.136,401.292,0.942,NaN,...,-0.02471,0.00000,140.00854,0.01686,44.98050,0.00164,33.68164,44.94359,NaN,31912.176
15,120111,164230,unknown,-,USN-20112109,0,402.675,402.832,1.384,NaN,...,-0.02471,0.00000,140.02963,0.08316,44.98534,0.00135,33.73897,44.94599,NaN,31961.027
16,120111,164330,unknown,-,USN-20112109,0,400.283,400.439,0.809,NaN,...,-0.02471,0.00000,140.01212,0.02237,44.98892,0.00090,33.78395,44.94802,NaN,32437.586
17,120111,164430,unknown,-,USN-20112109,0,402.536,402.692,1.415,NaN,...,-0.02471,0.00000,139.99870,0.01410,44.99151,0.00075,33.82721,44.94981,NaN,32555.811
18,120111,164530,unknown,-,USN-20112109,0,402.707,402.864,1.649,NaN,...,-0.02471,0.00000,140.00996,0.01495,44.99374,0.00071,33.89363,44.95130,NaN,32657.541
19,120111,164630,unknown,-,USN-20112109,0,400.225,400.380,1.611,NaN,...,-0.02471,0.00000,140.00494,0.01437,44.99538,0.00038,33.98176,44.95257,NaN,32746.449

In [39]:
df_taco2['C']

0          406.300x
1          405.776x
2          403.811x
3          404.577x
4          404.301x
             ...
6828985     437.131
6828986     438.124
6828987     438.832
6828988     437.999
6828989     437.717
Name: C, Length: 6828990, dtype: object

In [41]:
df_taco2['C'], df_taco2['co2_flag'] = zip(*df_taco2['C'].map(split_flag))

print(df_taco2[['C', 'co2_flag']].head(20))
df_taco2['C']

          C co2_flag
0   406.300
1   405.776
2   403.811
3   404.577
4   404.301
5   404.035
6   404.238
7   407.466
8   404.171
9   413.777
10  405.189
11  404.500
12  404.433
13  405.599
14  403.956
15  405.506
16  403.097
17  405.365
18  405.538
19  403.039

0          406.300
1          405.776
2          403.811
3          404.577
4          404.301
            ...
6828985    437.131
6828986    438.124
6828987    438.832
6828988    437.999
6828989    437.717
Name: C, Length: 6828990, dtype: float64

In [42]:
df_taco2.columns.tolist()

['date',
 'time',
 'type',
 'sample',
 'standard',
 'port',
 'dry',
 'wet',
 'stdev',
 'std_rep',
 'std_stdev',
 'target_error',
 'Cdrift',
 'C',
 'N',
 'Nfiltered',
 'time.1',
 'h2o',
 'stdev.1',
 'press',
 'press_stdev',
 'temp',
 'temp_stdev',
 'temp.1',
 'temp.2',
 'temp.3',
 'valve',
 'co2_flag']

In [43]:
feature_name_tacco2 = [
  'date', 'time', 'type', 'sample', 'standard', 'port', 
 'co2_dry', 'co2_wet', 'co2_stdev', 'co2_std_rep', 'co2_std_stdev',
  'co2_target_error','co2_Cdrift', 'co2_C', 'co2_N', 'co2_Nfiltered',
  'cycle_time', 'h2o', 'h2o_stdev', 'cavity_press', 'cavity_press_stdev', 
  'cavity_temp', 'cavity_temp_stdev', 'das_temp', 'etalon_temp', 
  'warmbox_temp', 'outlet_valve','co2_flag'
]

In [44]:
df_taco2.columns = feature_name_tacco2

In [45]:
df_taco2.head(20)

,date,time,type,sample,standard,port,co2_dry,co2_wet,co2_stdev,co2_std_rep,...,h2o_stdev,cavity_press,cavity_press_stdev,cavity_temp,cavity_temp_stdev,das_temp,etalon_temp,warmbox_temp,outlet_valve,co2_flag
0,120111,162730,unknown,-,USN-20112109,0,403.464,403.606,1.063,NaN,...,0.00175,140.00525,0.01396,44.90277,0.01251,32.14167,44.77072,NaN,31442.617,
1,120111,162830,unknown,-,USN-20112109,0,402.944,403.085,1.308,NaN,...,0.00170,140.00435,0.01518,44.92952,0.00415,32.36250,44.91882,NaN,31543.971,
2,120111,162930,unknown,-,USN-20112109,0,400.992,401.133,1.802,NaN,...,0.00221,140.00513,0.01176,44.93352,0.00128,32.59792,44.99702,NaN,31626.549,
3,120111,163030,unknown,-,USN-20112109,0,401.753,401.893,1.516,NaN,...,0.00256,140.00745,0.01437,44.92616,0.00253,32.81506,45.02549,NaN,31687.379,
4,120111,163130,unknown,-,USN-20112109,0,401.479,401.622,0.743,NaN,...,0.00192,140.00314,0.01321,44.91914,0.00165,32.98813,45.02443,NaN,31726.805,
5,120111,163230,unknown,-,USN-20112109,0,401.215,401.356,0.619,NaN,...,0.00258,139.99792,0.01910,44.91655,0.00026,33.13750,45.00900,NaN,31758.904,
6,120111,163330,unknown,-,USN-20112109,0,401.416,401.565,0.727,NaN,...,0.00115,140.00032,0.01554,44.91776,0.00100,33.26172,44.98967,NaN,31785.496,
7,120111,163430,unknown,-,USN-20112109,0,404.622,404.779,2.342,NaN,...,0.00000,140.00146,0.01652,44.92261,0.00181,33.35547,44.97134,NaN,31807.650,
8,120111,163530,unknown,-,USN-20112109,0,401.350,401.506,2.698,NaN,...,0.00000,139.99977,0.01241,44.92999,0.00249,33.42248,44.95708,NaN,31827.049,
9,120111,163630,unknown,-,USN-20112109,0,410.890,411.049,3.356,NaN,...,0.00000,140.00076,0.01586,44.93916,0.00306,33.47794,44.94679,NaN,31844.387,
10,120111,163730,unknown,-,USN-20112109,0,402.361,402.517,2.391,NaN,...,0.00000,140.00096,0.01696,44.94887,0.00277,33.51382,44.94103,NaN,31857.955,
11,120111,163830,unknown,-,USN-20112109,0,401.677,401.833,0.485,NaN,...,0.00000,140.00214,0.01152,44.95813,0.00269,33.56085,44.93909,NaN,31872.648,
12,120111,163930,unknown,-,USN-20112109,0,401.610,401.765,1.532,NaN,...,0.00000,139.99553,0.01358,44.96662,0.00232,33.58278,44.93938,NaN,31882.432,
13,120111,164030,unknown,-,USN-20112109,0,402.768,402.924,1.124,NaN,...,0.00000,140.00235,0.01529,44.97430,0.00199,33.63235,44.94104,NaN,31896.764,
14,120111,164130,unknown,-,USN-20112109,0,401.136,401.292,0.942,NaN,...,0.00000,140.00854,0.01686,44.98050,0.00164,33.68164,44.94359,NaN,31912.176,
15,120111,164230,unknown,-,USN-20112109,0,402.675,402.832,1.384,NaN,...,0.00000,140.02963,0.08316,44.98534,0.00135,33.73897,44.94599,NaN,31961.027,
16,120111,164330,unknown,-,USN-20112109,0,400.283,400.439,0.809,NaN,...,0.00000,140.01212,0.02237,44.98892,0.00090,33.78395,44.94802,NaN,32437.586,
17,120111,164430,unknown,-,USN-20112109,0,402.536,402.692,1.415,NaN,...,0.00000,139.99870,0.01410,44.99151,0.00075,33.82721,44.94981,NaN,32555.811,
18,120111,164530,unknown,-,USN-20112109,0,402.707,402.864,1.649,NaN,...,0.00000,140.00996,0.01495,44.99374,0.00071,33.89363,44.95130,NaN,32657.541,
19,120111,164630,unknown,-,USN-20112109,0,400.225,400.380,1.611,NaN,...,0.00000,140.00494,0.01437,44.99538,0.00038,33.98176,44.95257,NaN,32746.449,

In [46]:
df_taco2.to_csv("../data/processed/tac_co2_formatted_v1.csv", index=False)