In [19]:
import pandas as pd

file_path = "../data/raw/mhd_ch4.txt"

df_mhd=pd.read_fwf(
    file_path,
    skiprows=1,
    header=1,
    keep_default_na=False
)
df_mhd

,date,time,type,sample,standard,port,ht,tmod,tamb,temp,pflow,psamp,ploop,pamb,rt,w,ht.1,area,skew,start_time,end_time,start_level,end_level,Rl_ht,Rl_a,Rl,norm_ht,norm_a,norm_w,R_ht,R_a,R,C_ht,C_a,C,std_stdev,std_rep,Cstd,flag_ht,flag_a,flag,flag_p
0,940216,142900,air,10m,G-024,3,10,40.00,32.27,nan,841.9,761.10,nan,761.1,0.0,0.00,0,0,0.00,0.00,0.00,0.00,0.00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,1692.489,F,F,,
1,940216,144900,air,10m,G-024,3,10,40.00,32.48,nan,840.4,761.07,nan,761.2,0.0,0.00,0,0,0.00,0.00,0.00,0.00,0.00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,1692.489,F,F,,
2,940216,150900,air,10m,G-024,3,10,40.01,32.75,nan,839.4,760.99,nan,760.9,109.8,2.60,190908,496440,0.63,102.0,135.4,10063,10029,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,1692.489,F,F,,
3,940216,152900,air,10m,G-024,3,10,40.00,32.92,nan,839.6,760.96,nan,760.9,94.8,6.85,151667,1065982,1.02,86.20,129.0,99999,99999,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,1692.489,,,,
4,940216,180000,air,10m,G-024,3,10,40.00,33.31,nan,845.4,760.72,nan,760.6,0.0,0.00,0,0,0.00,0.00,0.00,0.00,0.00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,1692.489,F,F,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
817950,260518,65300,std,J-286,J-286,3,0,40.00,22.06,nan,813.5,752.32,nan,752.4,77.8,3.98,133194,131007,0.50,73.00,99.80,99999,62297,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,3.649,nan,2015.923,,,A,
817951,260518,71300,air,9m,J-286,1,9,40.00,22.32,nan,808.6,752.28,nan,752.2,79.0,4.57,160607,508996,0.46,73.00,102.0,99999,64464,1.02271,1.00491,1.00491,1.0227,1.0049,0.9981,1.02271,1.00491,1.00491,2061.71,2025.82,2025.82,3.649,3.666,2015.923,,,A,
817952,260518,73300,std,J-286,J-286,3,0,40.00,22.19,nan,813.1,752.27,nan,752.4,80.6,5.17,180892,882007,0.47,73.00,109.2,84204,66307,1.07106,1.34773,1.34773,1.0712,1.3480,1.0953,1.07106,1.34773,1.34773,2159.17,2716.92,2716.92,4.605,nan,2015.923,,,A,
817953,260518,75300,air,9m,J-286,1,9,40.00,22.10,nan,808.2,752.13,nan,752.2,80.4,5.01,186959,856303,0.41,73.00,106.6,87769,65923,0.97017,0.83156,nan,0.9701,0.8315,0.9433,0.97017,0.83156,nan,1955.78,1676.37,nan,4.605,nan,2015.923,*,*,A,
817954,260518,81300,std,J-286,J-286,3,0,40.00,22.23,nan,813.3,752.09,nan,752.0,82.0,5.46,204547,1177596,0.43,73.00,115.2,75876,68601,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,14.873,nan,2015.923,,,A,

In [20]:
pd.set_option('display.max_columns', None)

In [21]:
feature_names = [  
'date', 'time', 'type', 'sample', 'standard', 'port', 'ht', 'tmod', 'tamb', 'lab_temp', 'pflow', 'psamp', 'ploop', 'pamb', 'CH4_rt', 'CH4_w', 
'CH4_ht', 'CH4_area', 'CH4_skew', 'CH4_start_time', 'CH4_end_time', 'CH4_start_level', 'CH4_end_level', 'CH4_Rl_ht', 'CH4_Rl_a', 'CH4_Rl', 'CH4_norm_ht', 'CH4_norm_a', 'CH4_norm_w', 
'CH4_R_ht', 'CH4_R_a', 'CH4_R', 'CH4_C_ht', 'CH4_C_a', 'CH4_C', 'CH4_std_stdev', 'CH4_std_rep', 'CH4_Cstd', 'CH4_flag_ht', 'CH4_flag_a', 'CH4_flag', 'CH4_flag_p'
]
df_mhd.columns = feature_names

In [25]:
import pandas as pd

file_path = "../data/raw/mhd_ch4.txt"

df_mhd_csvred = pd.read_csv(file_path, skiprows=1, sep=r'\s+',header=1, engine='python') # skip first row, txt is space seperated

In [26]:
feature_names = [  
'date', 'time', 'type', 'sample', 'standard', 'port', 'ht', 'tmod', 'tamb', 'lab_temp', 'pflow', 'psamp', 'ploop', 'pamb', 'CH4_rt', 'CH4_w', 
'CH4_ht', 'CH4_area', 'CH4_skew', 'CH4_start_time', 'CH4_end_time', 'CH4_start_level', 'CH4_end_level', 'CH4_Rl_ht', 'CH4_Rl_a', 'CH4_Rl', 'CH4_norm_ht', 'CH4_norm_a', 'CH4_norm_w', 
'CH4_R_ht', 'CH4_R_a', 'CH4_R', 'CH4_C_ht', 'CH4_C_a', 'CH4_C', 'CH4_std_stdev', 'CH4_std_rep', 'CH4_Cstd', 'CH4_flag_ht', 'CH4_flag_a', 'CH4_flag', 'CH4_flag_p'
]
df_mhd_csvred.columns = feature_names

In [27]:
df_mhd_csvred['type'].unique()

array(['air', 'std', 'tank', 'tank100', 'cal560', 'cal660', 'cal860',
       'cal960', 'cal1060', 'blank', 'labair', 'cal15', 'cal30', 'cal45',
       'cal60', 'cal75', 'cal90', 'cal105', 'cal120', 'cal135', 'cal150',
       'cal165', 'cal180', 'cal200', 'cal225', 'cal250', 'cal300',
       'cal500', 'cal', '-'], dtype=object)

In [30]:
data_mhd = df_mhd_csvred.iloc[:, :-4]

In [31]:
data_mhd.head(20)

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd
0,940216,142900,air,10m,G-024,3,10.0,40.00,32.27,NaN,841.9,761.10,NaN,761.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
1,940216,144900,air,10m,G-024,3,10.0,40.00,32.48,NaN,840.4,761.07,NaN,761.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
2,940216,150900,air,10m,G-024,3,10.0,40.01,32.75,NaN,839.4,760.99,NaN,760.9,109.8,2.60,190908.0,496440.0,0.63,102.0,135.4,10063.0,10029.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
3,940216,152900,air,10m,G-024,3,10.0,40.00,32.92,NaN,839.6,760.96,NaN,760.9,94.8,6.85,151667.0,1065982.0,1.02,86.2,129.0,99999.0,99999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
4,940216,180000,air,10m,G-024,3,10.0,40.00,33.31,NaN,845.4,760.72,NaN,760.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
5,940216,182000,air,10m,G-024,3,10.0,40.01,33.10,NaN,846.2,760.60,NaN,760.7,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
6,940216,184000,air,10m,G-024,3,10.0,40.01,33.20,NaN,846.3,760.57,NaN,760.5,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
7,940216,190000,air,10m,G-024,3,10.0,40.00,33.39,NaN,846.5,760.45,NaN,760.4,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
8,940216,192000,air,10m,G-024,3,10.0,40.00,33.61,NaN,846.6,760.34,NaN,760.3,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
9,940216,194000,air,10m,G-024,3,10.0,40.01,33.66,NaN,844.8,760.35,NaN,760.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
10,940216,202300,air,10m,G-024,3,10.0,40.00,33.17,NaN,846.1,759.83,NaN,760.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
11,940216,204300,air,10m,G-024,3,10.0,40.00,33.05,NaN,846.3,759.91,NaN,759.8,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
12,940216,210300,air,10m,G-024,3,10.0,40.01,33.06,NaN,846.3,759.72,NaN,759.7,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
13,940216,212400,air,10m,G-024,3,10.0,40.00,33.01,NaN,846.3,759.65,NaN,759.7,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
14,940216,214400,air,10m,G-024,3,10.0,40.00,32.94,NaN,846.1,759.62,NaN,759.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
15,940216,220400,air,10m,G-024,3,10.0,40.00,32.87,NaN,845.9,759.58,NaN,759.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
16,940216,222400,air,10m,G-024,3,10.0,40.01,32.76,NaN,845.2,759.62,NaN,759.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
17,940216,224400,air,10m,G-024,3,10.0,40.00,32.71,NaN,846.1,759.55,NaN,759.5,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
18,940216,230400,air,10m,G-024,3,10.0,40.00,32.69,NaN,844.4,759.49,NaN,759.5,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
19,940216,232400,air,10m,G-024,3,10.0,40.00,32.65,NaN,844.9,759.25,NaN,759.3,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489

In [33]:
df_mhd_flag = df_mhd.iloc[:, -4:]
df_mhd_flag.head(20)

   CH4_flag_ht CH4_flag_a CH4_flag CH4_flag_p
0            F          F
1            F          F
2            F          F
3
4            F          F
5            F          F
6            F          F
7            F          F
8            F          F
9            F          F
10           F          F
11           F          F
12           F          F
13           F          F
14           F          F
15           F          F
16           F          F
17           F          F
18           F          F
19           F          F

In [34]:
df_mhd_flag.index = data_mhd.index 
data_mhd = pd.concat([data_mhd, df_mhd_flag], axis=1)

In [35]:
data_mhd.head(20)

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p
0,940216,142900,air,10m,G-024,3,10.0,40.00,32.27,NaN,841.9,761.10,NaN,761.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
1,940216,144900,air,10m,G-024,3,10.0,40.00,32.48,NaN,840.4,761.07,NaN,761.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
2,940216,150900,air,10m,G-024,3,10.0,40.01,32.75,NaN,839.4,760.99,NaN,760.9,109.8,2.60,190908.0,496440.0,0.63,102.0,135.4,10063.0,10029.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
3,940216,152900,air,10m,G-024,3,10.0,40.00,32.92,NaN,839.6,760.96,NaN,760.9,94.8,6.85,151667.0,1065982.0,1.02,86.2,129.0,99999.0,99999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,,,,
4,940216,180000,air,10m,G-024,3,10.0,40.00,33.31,NaN,845.4,760.72,NaN,760.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
5,940216,182000,air,10m,G-024,3,10.0,40.01,33.10,NaN,846.2,760.60,NaN,760.7,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
6,940216,184000,air,10m,G-024,3,10.0,40.01,33.20,NaN,846.3,760.57,NaN,760.5,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
7,940216,190000,air,10m,G-024,3,10.0,40.00,33.39,NaN,846.5,760.45,NaN,760.4,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
8,940216,192000,air,10m,G-024,3,10.0,40.00,33.61,NaN,846.6,760.34,NaN,760.3,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
9,940216,194000,air,10m,G-024,3,10.0,40.01,33.66,NaN,844.8,760.35,NaN,760.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
10,940216,202300,air,10m,G-024,3,10.0,40.00,33.17,NaN,846.1,759.83,NaN,760.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
11,940216,204300,air,10m,G-024,3,10.0,40.00,33.05,NaN,846.3,759.91,NaN,759.8,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
12,940216,210300,air,10m,G-024,3,10.0,40.01,33.06,NaN,846.3,759.72,NaN,759.7,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
13,940216,212400,air,10m,G-024,3,10.0,40.00,33.01,NaN,846.3,759.65,NaN,759.7,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
14,940216,214400,air,10m,G-024,3,10.0,40.00,32.94,NaN,846.1,759.62,NaN,759.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
15,940216,220400,air,10m,G-024,3,10.0,40.00,32.87,NaN,845.9,759.58,NaN,759.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
16,940216,222400,air,10m,G-024,3,10.0,40.01,32.76,NaN,845.2,759.62,NaN,759.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
17,940216,224400,air,10m,G-024,3,10.0,40.00,32.71,NaN,846.1,759.55,NaN,759.5,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
18,940216,230400,air,10m,G-024,3,10.0,40.00,32.69,NaN,844.4,759.49,NaN,759.5,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
19,940216,232400,air,10m,G-024,3,10.0,40.00,32.65,NaN,844.9,759.25,NaN,759.3,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,

In [36]:
data_mhd.iloc[[185]]

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p
185,940219,102700,cal1060,G-024,G-024,1,0.0,40.01,23.16,NaN,846.8,1058.3,NaN,751.2,95.2,7.51,205489.0,1651923.0,1.0,82.6,130.2,30872.0,30727.0,0.92736,1.00177,0.92736,1.3073,1.4122,1.0901,0.92736,1.00177,0.92736,1569.54,1695.49,1692.49,3.18,NaN,1692.489,,,,

In [37]:
data_mhd.tail(20)

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p
817935,260518,15200,air,9m,J-286,1,9.0,40.0,22.26,NaN,809.6,752.85,NaN,752.8,113.2,9.18,197243.0,2001935.0,1.05,98.2,155.8,40780.0,42701.0,1.00339,1.00870,1.00870,1.0034,1.0087,1.0048,1.00339,1.00870,1.00870,2022.75,2033.45,2033.45,3.637,3.669,2015.923,,,A,
817936,260518,21200,std,J-286,J-286,3,0.0,40.0,22.16,NaN,813.9,752.79,NaN,752.8,114.4,9.20,196511.0,2002566.0,1.13,99.6,157.4,42026.0,43238.0,1.01184,0.99099,0.99099,1.0119,0.9910,0.9827,1.01184,0.99099,0.99099,2039.79,1997.77,1997.77,3.652,NaN,2015.923,,,A,
817937,260518,23200,air,9m,J-286,1,9.0,40.0,22.12,NaN,810.1,752.81,NaN,752.8,114.8,9.23,196801.0,2010329.0,1.06,99.8,158.0,42408.0,43352.0,1.01358,0.98600,NaN,1.0138,0.9862,0.9794,1.01358,0.98600,NaN,2043.30,1987.70,NaN,3.652,NaN,2015.923,*,*,A,
817938,260518,25200,std,J-286,J-286,3,0.0,40.0,22.25,NaN,813.7,752.55,NaN,752.5,119.8,9.66,191747.0,2074401.0,1.14,104.6,163.8,47450.0,47746.0,0.99568,1.01543,1.01543,0.9956,1.0153,1.0141,0.99568,1.01543,1.01543,2007.22,2047.02,2047.02,3.619,NaN,2015.923,,,A,
817939,260518,31200,air,9m,J-286,1,9.0,40.0,22.29,NaN,809.4,752.55,NaN,752.7,118.0,9.48,194562.0,2051993.0,1.07,102.8,161.4,45678.0,46131.0,1.02278,0.98695,NaN,1.0228,0.9870,0.9721,1.02278,0.98695,NaN,2061.85,1989.62,NaN,3.619,NaN,2015.923,*,*,A,
817940,260518,33200,std,J-286,J-286,3,0.0,40.0,22.22,NaN,813.7,752.45,NaN,752.6,123.0,9.85,188684.0,2083568.0,1.06,107.4,167.0,50407.0,50450.0,1.00494,1.00229,1.00229,1.0048,1.0022,0.9982,1.00494,1.00229,1.00229,2025.88,2020.55,2020.55,3.619,NaN,2015.923,,,A,
817941,260518,35200,air,9m,J-286,1,9.0,40.0,22.02,NaN,809.1,752.43,NaN,752.5,121.2,9.70,191559.0,2078579.0,1.12,106.0,165.0,48891.0,48854.0,1.02860,0.99765,NaN,1.0285,0.9976,0.9741,1.02860,0.99765,NaN,2073.57,2011.19,NaN,3.451,NaN,2015.923,*,*,A,
817942,260518,41200,std,J-286,J-286,3,0.0,40.0,22.35,NaN,813.5,752.49,NaN,752.5,125.8,10.07,183801.0,2083586.0,1.09,110.0,170.4,52965.0,52830.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.451,NaN,2015.923,,,A,
817943,260518,43200,air,9m,J-286,1,9.0,40.0,22.05,NaN,808.8,752.36,NaN,752.2,125.4,10.07,186644.0,2113592.0,1.05,109.6,169.6,52684.0,52367.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.417,NaN,2015.923,,,A,
817944,260518,45200,std,J-286,J-286,3,0.0,40.0,22.44,NaN,813.3,752.23,NaN,752.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.479,NaN,2015.923,,,A,
817945,260518,51200,air,9m,J-286,1,9.0,40.0,22.20,NaN,808.8,752.26,NaN,752.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.479,NaN,2015.923,,,A,
817946,260518,53300,std,J-286,J-286,3,0.0,40.0,22.62,NaN,813.0,752.25,NaN,752.3,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.545,NaN,2015.923,,,A,
817947,260518,55300,air,9m,J-286,1,9.0,40.0,22.20,NaN,808.5,752.24,NaN,752.2,76.8,0.00,0.0,0.0,0.53,73.0,98.6,99999.0,60611.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.545,NaN,2015.923,,,A,
817948,260518,61300,std,J-286,J-286,3,0.0,40.0,22.17,NaN,813.4,752.25,NaN,752.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.611,NaN,2015.923,,,A,
817949,260518,63300,air,9m,J-286,1,9.0,40.0,22.25,NaN,808.6,752.26,NaN,752.5,78.0,4.06,137477.0,182060.0,0.47,73.0,100.2,99999.0,62502.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.611,NaN,2015.923,,,A,
817950,260518,65300,std,J-286,J-286,3,0.0,40.0,22.06,NaN,813.5,752.32,NaN,752.4,77.8,3.98,133194.0,131007.0,0.50,73.0,99.8,99999.0,62297.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.649,NaN,2015.923,,,A,
817951,260518,71300,air,9m,J-286,1,9.0,40.0,22.32,NaN,808.6,752.28,NaN,752.2,79.0,4.57,160607.0,508996.0,0.46,73.0,102.0,99999.0,64464.0,1.02271,1.00491,1.00491,1.0227,1.0049,0.9981,1.02271,1.00491,1.00491,2061.71,2025.82,2025.82,3.649,3.666,2015.923,,,A,
817952,260518,73300,std,J-286,J-286,3,0.0,40.0,22.19,NaN,813.1,752.27,NaN,752.4,80.6,5.17,180892.0,882007.0,0.47,73.0,109.2,84204.0,66307.0,1.07106,1.34773,1.34773,1.0712,1.3480,1.0953,1.07106,1.34773,1.34773,2159.17,2716.92,2716.92,4.605,NaN,2015.923,,,A,
817953,260518,75300,air,9m,J-286,1,9.0,40.0,22.10,NaN,808.2,752.13,NaN,752.2,80.4,5.01,186959.0,856303.0,0.41,73.0,106.6,87769.0,65923.0,0.97017,0.83156,NaN,0.9701,0.8315,0.9433,0.97017,0.83156,NaN,1955.78,1676.37,NaN,4.605,NaN,2015.923,*,*,A,
817954,260518,81300,std,J-286,J-286,3,0.0,40.0,22.23,NaN,813.3,752.09,NaN,752.0,82.0,5.46,204547.0,1177596.0,0.43,73.0,115.2,75876.0,68601.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.873,NaN,2015.923,,,A,

In [38]:
data_mhd.iloc[[28373]]

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p
28373,950404,111600,tank,H-006,G-032,5,0.0,39.99,20.35,NaN,848.6,761.75,NaN,761.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.682,NaN,1679.840,,,,

In [39]:
df_mhd.to_csv("../data/processed/mhd_ch4_formatted_v1.csv", index=False)

In [ ]:
import pandas as pd

file_path = "../data/raw/tac_ch4.txt"

df_tac = pd.read_csv(file_path, skiprows=1, sep=r'\s+', header=1) 
# skip first row, txt is space seperated

In [6]:
df_tac.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6828990 entries, 0 to 6828989
Data columns (total 27 columns):
 #   Column        Dtype
---  ------        -----
 0   date          int64
 1   time          int64
 2   type          object
 3   sample        object
 4   standard      object
 5   port          int64
 6   dry           float64
 7   wet           float64
 8   stdev         float64
 9   std_rep       float64
 10  std_stdev     float64
 11  target_error  float64
 12  Cdrift        float64
 13  C             object
 14  N             int64
 15  Nfiltered     float64
 16  time.1        float64
 17  h2o           float64
 18  stdev.1       float64
 19  press         float64
 20  press_stdev   float64
 21  temp          float64
 22  temp_stdev    float64
 23  temp.1        float64
 24  temp.2        float64
 25  temp.3        float64
 26  valve         float64
dtypes: float64(19), int64(4), object(4)
memory usage: 1.4+ GB

In [7]:
df_tac['C'].head(20)

0     1955.527x
1     1983.217x
2     1951.159x
3     2033.386x
4     1987.416x
5     1988.226F
6     1985.406F
7     1915.031F
8     1940.282F
9     1981.204F
10    1931.891F
11    1980.398F
12    1947.380F
13    1949.511F
14    1909.053F
15    1939.482F
16    1913.494F
17    1949.543F
18    1934.023F
19    1895.129F
Name: C, dtype: object

In [8]:
import numpy as np

def split_flag (val):
    if pd.isna(val):
        return np.nan, np.nan
    
    val_str = str(val).strip()
    # check if last val is a character(Flag)
    if val_str[-1].isalpha() or val_str[-1] == '*':
        c_val = float(val_str[:-1])
        flag_val = val_str[-1]
    else:
        c_val = float(val_str) # normal value, then direcly convert to float
        flag_val = " " # no flag, give it a space
    
    return c_val, flag_val

In [9]:
df_tac['C'], df_tac['ch4_flag'] = zip(*df_tac['C'].map(split_flag))

print(df_tac[['C', 'ch4_flag']].head(20))
df_tac['C']

           C ch4_flag
0   1955.527        x
1   1983.217        x
2   1951.159        x
3   2033.386        x
4   1987.416        x
5   1988.226        F
6   1985.406        F
7   1915.031        F
8   1940.282        F
9   1981.204        F
10  1931.891        F
11  1980.398        F
12  1947.380        F
13  1949.511        F
14  1909.053        F
15  1939.482        F
16  1913.494        F
17  1949.543        F
18  1934.023        F
19  1895.129        F

0          1955.527
1          1983.217
2          1951.159
3          2033.386
4          1987.416
             ...
6828985    2059.287
6828986    2062.687
6828987    2065.768
6828988    2061.963
6828989    2061.248
Name: C, Length: 6828990, dtype: float64

In [10]:
df_tac.head(20)

,date,time,type,sample,standard,port,dry,wet,stdev,std_rep,std_stdev,target_error,Cdrift,C,N,Nfiltered,time.1,h2o,stdev.1,press,press_stdev,temp,temp_stdev,temp.1,temp.2,temp.3,valve,ch4_flag
0,120111,162730,unknown,-,USN-20112109,0,1944.517,1945.109,42.208,NaN,NaN,NaN,1955.510,1955.527,0,100.0,3.733,-0.02232,0.00175,140.00525,0.01396,44.90277,0.01251,32.14167,44.77072,NaN,31442.617,x
1,120111,162830,unknown,-,USN-20112109,0,1972.043,1972.643,57.714,NaN,NaN,NaN,1983.192,1983.217,0,100.0,3.733,-0.02232,0.00170,140.00435,0.01518,44.92952,0.00415,32.36250,44.91882,NaN,31543.971,x
2,120111,162930,unknown,-,USN-20112109,0,1940.176,1940.768,65.419,NaN,NaN,NaN,1951.144,1951.159,0,100.0,3.733,-0.02243,0.00221,140.00513,0.01176,44.93352,0.00128,32.59792,44.99702,NaN,31626.549,x
3,120111,163030,unknown,-,USN-20112109,0,2021.915,2022.526,80.016,NaN,NaN,NaN,2033.346,2033.386,0,100.0,3.733,-0.02217,0.00256,140.00745,0.01437,44.92616,0.00253,32.81506,45.02549,NaN,31687.379,x
4,120111,163130,unknown,-,USN-20112109,0,1976.217,1976.825,57.151,NaN,NaN,NaN,1987.390,1987.416,0,100.0,3.625,-0.02259,0.00192,140.00314,0.01321,44.91914,0.00165,32.98813,45.02443,NaN,31726.805,x
5,120111,163230,unknown,-,USN-20112109,0,1977.023,1977.629,107.839,NaN,NaN,NaN,1988.200,1988.226,0,100.0,3.733,-0.02248,0.00258,139.99792,0.01910,44.91655,0.00026,33.13750,45.00900,NaN,31758.904,F
6,120111,163330,unknown,-,USN-20112109,0,1974.220,1974.855,94.284,NaN,NaN,NaN,1985.381,1985.406,0,100.0,3.500,-0.02362,0.00115,140.00032,0.01554,44.91776,0.00100,33.26172,44.98967,NaN,31785.496,F
7,120111,163430,unknown,-,USN-20112109,0,1904.261,1904.902,51.648,NaN,NaN,NaN,1915.027,1915.031,0,100.0,3.500,-0.02471,0.00000,140.00146,0.01652,44.92261,0.00181,33.35547,44.97134,NaN,31807.650,F
8,120111,163530,unknown,-,USN-20112109,0,1929.363,1930.012,59.736,NaN,NaN,NaN,1940.270,1940.282,0,100.0,3.500,-0.02471,0.00000,139.99977,0.01241,44.92999,0.00249,33.42248,44.95708,NaN,31827.049,F
9,120111,163630,unknown,-,USN-20112109,0,1970.042,1970.705,71.395,NaN,NaN,NaN,1981.180,1981.204,0,100.0,3.471,-0.02471,0.00000,140.00076,0.01586,44.93916,0.00306,33.47794,44.94679,NaN,31844.387,F
10,120111,163730,unknown,-,USN-20112109,0,1921.022,1921.668,30.451,NaN,NaN,NaN,1931.882,1931.891,0,100.0,3.625,-0.02471,0.00000,140.00096,0.01696,44.94887,0.00277,33.51382,44.94103,NaN,31857.955,F
11,120111,163830,unknown,-,USN-20112109,0,1969.241,1969.904,70.028,NaN,NaN,NaN,1980.374,1980.398,0,100.0,3.562,-0.02471,0.00000,140.00214,0.01152,44.95813,0.00269,33.56085,44.93909,NaN,31872.648,F
12,120111,163930,unknown,-,USN-20112109,0,1936.419,1937.071,39.461,NaN,NaN,NaN,1947.366,1947.380,0,100.0,3.562,-0.02471,0.00000,139.99553,0.01358,44.96662,0.00232,33.58278,44.93938,NaN,31882.432,F
13,120111,164030,unknown,-,USN-20112109,0,1938.537,1939.190,142.405,NaN,NaN,NaN,1949.497,1949.511,0,100.0,3.412,-0.02471,0.00000,140.00235,0.01529,44.97430,0.00199,33.63235,44.94104,NaN,31896.764,F
14,120111,164130,unknown,-,USN-20112109,0,1898.318,1898.957,15.359,NaN,NaN,NaN,1909.050,1909.053,0,100.0,3.562,-0.02471,0.00000,140.00854,0.01686,44.98050,0.00164,33.68164,44.94359,NaN,31912.176,F
15,120111,164230,unknown,-,USN-20112109,0,1928.567,1929.216,31.420,NaN,NaN,NaN,1939.470,1939.482,0,100.0,3.412,-0.02471,0.00000,140.02963,0.08316,44.98534,0.00135,33.73897,44.94599,NaN,31961.027,F
16,120111,164330,unknown,-,USN-20112109,0,1902.733,1903.373,36.078,NaN,NaN,NaN,1913.490,1913.494,0,100.0,3.562,-0.02471,0.00000,140.01212,0.02237,44.98892,0.00090,33.78395,44.94802,NaN,32437.586,F
17,120111,164430,unknown,-,USN-20112109,0,1938.570,1939.222,30.627,NaN,NaN,NaN,1949.529,1949.543,0,100.0,3.412,-0.02471,0.00000,139.99870,0.01410,44.99151,0.00075,33.82721,44.94981,NaN,32555.811,F
18,120111,164530,unknown,-,USN-20112109,0,1923.141,1923.788,37.563,NaN,NaN,NaN,1934.013,1934.023,0,100.0,3.562,-0.02471,0.00000,140.00996,0.01495,44.99374,0.00071,33.89363,44.95130,NaN,32657.541,F
19,120111,164630,unknown,-,USN-20112109,0,1884.477,1885.111,16.566,NaN,NaN,NaN,1895.130,1895.129,0,100.0,3.471,-0.02471,0.00000,140.00494,0.01437,44.99538,0.00038,33.98176,44.95257,NaN,32746.449,F

In [11]:
feature_name_tacch4 = [
  'date', 'time', 'type', 'sample', 'standard', 'port', 
 'ch4_dry', 'ch4_wet', 'ch4_stdev', 'ch4_std_rep', 'ch4_std_stdev',
  'ch4_target_error','ch4_Cdrift', 'ch4_C', 'ch4_N', 'ch4_Nfiltered',
  'cycle_time', 'h2o', 'h2o_stdev', 'cavity_press', 'cavity_press_stdev', 
  'cavity_temp', 'cavity_temp_stdev', 'das_temp', 'etalon_temp', 
  'warmbox_temp', 'outlet_valve','ch4_flag'
]

In [12]:
df_tac.columns = feature_name_tacch4

In [13]:
df_tac.head(20)

,date,time,type,sample,standard,port,ch4_dry,ch4_wet,ch4_stdev,ch4_std_rep,ch4_std_stdev,ch4_target_error,ch4_Cdrift,ch4_C,ch4_N,ch4_Nfiltered,cycle_time,h2o,h2o_stdev,cavity_press,cavity_press_stdev,cavity_temp,cavity_temp_stdev,das_temp,etalon_temp,warmbox_temp,outlet_valve,ch4_flag
0,120111,162730,unknown,-,USN-20112109,0,1944.517,1945.109,42.208,NaN,NaN,NaN,1955.510,1955.527,0,100.0,3.733,-0.02232,0.00175,140.00525,0.01396,44.90277,0.01251,32.14167,44.77072,NaN,31442.617,x
1,120111,162830,unknown,-,USN-20112109,0,1972.043,1972.643,57.714,NaN,NaN,NaN,1983.192,1983.217,0,100.0,3.733,-0.02232,0.00170,140.00435,0.01518,44.92952,0.00415,32.36250,44.91882,NaN,31543.971,x
2,120111,162930,unknown,-,USN-20112109,0,1940.176,1940.768,65.419,NaN,NaN,NaN,1951.144,1951.159,0,100.0,3.733,-0.02243,0.00221,140.00513,0.01176,44.93352,0.00128,32.59792,44.99702,NaN,31626.549,x
3,120111,163030,unknown,-,USN-20112109,0,2021.915,2022.526,80.016,NaN,NaN,NaN,2033.346,2033.386,0,100.0,3.733,-0.02217,0.00256,140.00745,0.01437,44.92616,0.00253,32.81506,45.02549,NaN,31687.379,x
4,120111,163130,unknown,-,USN-20112109,0,1976.217,1976.825,57.151,NaN,NaN,NaN,1987.390,1987.416,0,100.0,3.625,-0.02259,0.00192,140.00314,0.01321,44.91914,0.00165,32.98813,45.02443,NaN,31726.805,x
5,120111,163230,unknown,-,USN-20112109,0,1977.023,1977.629,107.839,NaN,NaN,NaN,1988.200,1988.226,0,100.0,3.733,-0.02248,0.00258,139.99792,0.01910,44.91655,0.00026,33.13750,45.00900,NaN,31758.904,F
6,120111,163330,unknown,-,USN-20112109,0,1974.220,1974.855,94.284,NaN,NaN,NaN,1985.381,1985.406,0,100.0,3.500,-0.02362,0.00115,140.00032,0.01554,44.91776,0.00100,33.26172,44.98967,NaN,31785.496,F
7,120111,163430,unknown,-,USN-20112109,0,1904.261,1904.902,51.648,NaN,NaN,NaN,1915.027,1915.031,0,100.0,3.500,-0.02471,0.00000,140.00146,0.01652,44.92261,0.00181,33.35547,44.97134,NaN,31807.650,F
8,120111,163530,unknown,-,USN-20112109,0,1929.363,1930.012,59.736,NaN,NaN,NaN,1940.270,1940.282,0,100.0,3.500,-0.02471,0.00000,139.99977,0.01241,44.92999,0.00249,33.42248,44.95708,NaN,31827.049,F
9,120111,163630,unknown,-,USN-20112109,0,1970.042,1970.705,71.395,NaN,NaN,NaN,1981.180,1981.204,0,100.0,3.471,-0.02471,0.00000,140.00076,0.01586,44.93916,0.00306,33.47794,44.94679,NaN,31844.387,F
10,120111,163730,unknown,-,USN-20112109,0,1921.022,1921.668,30.451,NaN,NaN,NaN,1931.882,1931.891,0,100.0,3.625,-0.02471,0.00000,140.00096,0.01696,44.94887,0.00277,33.51382,44.94103,NaN,31857.955,F
11,120111,163830,unknown,-,USN-20112109,0,1969.241,1969.904,70.028,NaN,NaN,NaN,1980.374,1980.398,0,100.0,3.562,-0.02471,0.00000,140.00214,0.01152,44.95813,0.00269,33.56085,44.93909,NaN,31872.648,F
12,120111,163930,unknown,-,USN-20112109,0,1936.419,1937.071,39.461,NaN,NaN,NaN,1947.366,1947.380,0,100.0,3.562,-0.02471,0.00000,139.99553,0.01358,44.96662,0.00232,33.58278,44.93938,NaN,31882.432,F
13,120111,164030,unknown,-,USN-20112109,0,1938.537,1939.190,142.405,NaN,NaN,NaN,1949.497,1949.511,0,100.0,3.412,-0.02471,0.00000,140.00235,0.01529,44.97430,0.00199,33.63235,44.94104,NaN,31896.764,F
14,120111,164130,unknown,-,USN-20112109,0,1898.318,1898.957,15.359,NaN,NaN,NaN,1909.050,1909.053,0,100.0,3.562,-0.02471,0.00000,140.00854,0.01686,44.98050,0.00164,33.68164,44.94359,NaN,31912.176,F
15,120111,164230,unknown,-,USN-20112109,0,1928.567,1929.216,31.420,NaN,NaN,NaN,1939.470,1939.482,0,100.0,3.412,-0.02471,0.00000,140.02963,0.08316,44.98534,0.00135,33.73897,44.94599,NaN,31961.027,F
16,120111,164330,unknown,-,USN-20112109,0,1902.733,1903.373,36.078,NaN,NaN,NaN,1913.490,1913.494,0,100.0,3.562,-0.02471,0.00000,140.01212,0.02237,44.98892,0.00090,33.78395,44.94802,NaN,32437.586,F
17,120111,164430,unknown,-,USN-20112109,0,1938.570,1939.222,30.627,NaN,NaN,NaN,1949.529,1949.543,0,100.0,3.412,-0.02471,0.00000,139.99870,0.01410,44.99151,0.00075,33.82721,44.94981,NaN,32555.811,F
18,120111,164530,unknown,-,USN-20112109,0,1923.141,1923.788,37.563,NaN,NaN,NaN,1934.013,1934.023,0,100.0,3.562,-0.02471,0.00000,140.00996,0.01495,44.99374,0.00071,33.89363,44.95130,NaN,32657.541,F
19,120111,164630,unknown,-,USN-20112109,0,1884.477,1885.111,16.566,NaN,NaN,NaN,1895.130,1895.129,0,100.0,3.471,-0.02471,0.00000,140.00494,0.01437,44.99538,0.00038,33.98176,44.95257,NaN,32746.449,F

In [14]:
df_tac.to_csv("../data/processed/tac_ch4_formatted_v1.csv", index=False)

In [15]:
df_tac.iloc[[244665]]

,date,time,type,sample,standard,port,ch4_dry,ch4_wet,ch4_stdev,ch4_std_rep,ch4_std_stdev,ch4_target_error,ch4_Cdrift,ch4_C,ch4_N,ch4_Nfiltered,cycle_time,h2o,h2o_stdev,cavity_press,cavity_press_stdev,cavity_temp,cavity_temp_stdev,das_temp,etalon_temp,warmbox_temp,outlet_valve,ch4_flag
244665,120831,44230,air,54m,USN-20112109,8,1893.926,1888.617,0.32,0.401,0.4,NaN,1904.594,1904.596,20,NaN,2.95,0.20732,0.00054,139.9978,0.01741,45.00043,0.0001,35.375,44.98233,NaN,31054.5,

In [16]:
df_tac.tail(5)

,date,time,type,sample,standard,port,ch4_dry,ch4_wet,ch4_stdev,ch4_std_rep,ch4_std_stdev,ch4_target_error,ch4_Cdrift,ch4_C,ch4_N,ch4_Nfiltered,cycle_time,h2o,h2o_stdev,cavity_press,cavity_press_stdev,cavity_temp,cavity_temp_stdev,das_temp,etalon_temp,warmbox_temp,outlet_valve,ch4_flag
6828985,250722,70630,air,185m,CFF-011,10,2057.675,2056.587,2.062,0.129,0.129,0.309,2059.288,2059.287,16,NaN,3.625,0.03994,0.00025,139.99831,0.00999,45.00000,0.00000,33.04913,45.07225,45.00000,33654.016,
6828986,250722,70730,air,185m,CFF-011,10,2061.071,2059.976,5.347,0.129,0.129,0.309,2062.687,2062.687,16,NaN,3.562,0.04013,0.00062,139.99857,0.01007,45.00006,0.00025,33.00881,45.07200,45.00000,33653.953,
6828987,250722,70830,air,185m,CFF-011,10,2064.147,2063.058,4.733,0.129,0.129,0.309,2065.766,2065.768,17,NaN,3.471,0.03988,0.00049,139.99689,0.01431,44.99976,0.00044,33.00000,45.07159,44.99929,33653.434,
6828988,250722,70930,air,185m,CFF-011,10,2060.348,2059.262,6.968,0.129,0.129,0.309,2061.963,2061.963,16,NaN,3.625,0.03981,0.00040,140.00513,0.01337,44.99944,0.00051,32.97287,45.07100,44.99900,33658.930,
6828989,250722,71030,air,185m,CFF-011,10,2059.633,2058.548,5.357,0.129,0.129,0.309,2061.248,2061.248,16,NaN,3.625,0.03981,0.00054,139.99606,0.01112,44.99900,0.00000,32.94081,45.07094,44.99850,33655.355,

In [17]:
import pandas as pd

file_path = "../data/raw/tac_co2.txt"

df_taco2 = pd.read_csv(file_path, skiprows=1, sep=r'\s+', header=1) # skip first row, txt is space seperated

In [18]:
df_taco2.head(20)

,date,time,type,sample,standard,port,dry,wet,stdev,std_rep,std_stdev,target_error,Cdrift,C,N,Nfiltered,time.1,h2o,stdev.1,press,press_stdev,temp,temp_stdev,temp.1,temp.2,temp.3,valve
0,120111,162730,unknown,-,USN-20112109,0,403.464,403.606,1.063,NaN,NaN,NaN,406.303,406.300x,0,100.0,3.733,-0.02232,0.00175,140.00525,0.01396,44.90277,0.01251,32.14167,44.77072,NaN,31442.617
1,120111,162830,unknown,-,USN-20112109,0,402.944,403.085,1.308,NaN,NaN,NaN,405.779,405.776x,0,100.0,3.733,-0.02232,0.00170,140.00435,0.01518,44.92952,0.00415,32.36250,44.91882,NaN,31543.971
2,120111,162930,unknown,-,USN-20112109,0,400.992,401.133,1.802,NaN,NaN,NaN,403.813,403.811x,0,100.0,3.733,-0.02243,0.00221,140.00513,0.01176,44.93352,0.00128,32.59792,44.99702,NaN,31626.549
3,120111,163030,unknown,-,USN-20112109,0,401.753,401.893,1.516,NaN,NaN,NaN,404.580,404.577x,0,100.0,3.733,-0.02217,0.00256,140.00745,0.01437,44.92616,0.00253,32.81506,45.02549,NaN,31687.379
4,120111,163130,unknown,-,USN-20112109,0,401.479,401.622,0.743,NaN,NaN,NaN,404.304,404.301x,0,100.0,3.625,-0.02259,0.00192,140.00314,0.01321,44.91914,0.00165,32.98813,45.02443,NaN,31726.805
5,120111,163230,unknown,-,USN-20112109,0,401.215,401.356,0.619,NaN,NaN,NaN,404.038,404.035F,0,100.0,3.733,-0.02248,0.00258,139.99792,0.01910,44.91655,0.00026,33.13750,45.00900,NaN,31758.904
6,120111,163330,unknown,-,USN-20112109,0,401.416,401.565,0.727,NaN,NaN,NaN,404.241,404.238F,0,100.0,3.500,-0.02362,0.00115,140.00032,0.01554,44.91776,0.00100,33.26172,44.98967,NaN,31785.496
7,120111,163430,unknown,-,USN-20112109,0,404.622,404.779,2.342,NaN,NaN,NaN,407.469,407.466F,0,100.0,3.500,-0.02471,0.00000,140.00146,0.01652,44.92261,0.00181,33.35547,44.97134,NaN,31807.650
8,120111,163530,unknown,-,USN-20112109,0,401.350,401.506,2.698,NaN,NaN,NaN,404.174,404.171F,0,100.0,3.500,-0.02471,0.00000,139.99977,0.01241,44.92999,0.00249,33.42248,44.95708,NaN,31827.049
9,120111,163630,unknown,-,USN-20112109,0,410.890,411.049,3.356,NaN,NaN,NaN,413.781,413.777F,0,100.0,3.471,-0.02471,0.00000,140.00076,0.01586,44.93916,0.00306,33.47794,44.94679,NaN,31844.387
10,120111,163730,unknown,-,USN-20112109,0,402.361,402.517,2.391,NaN,NaN,NaN,405.192,405.189F,0,100.0,3.625,-0.02471,0.00000,140.00096,0.01696,44.94887,0.00277,33.51382,44.94103,NaN,31857.955
11,120111,163830,unknown,-,USN-20112109,0,401.677,401.833,0.485,NaN,NaN,NaN,404.503,404.500F,0,100.0,3.562,-0.02471,0.00000,140.00214,0.01152,44.95813,0.00269,33.56085,44.93909,NaN,31872.648
12,120111,163930,unknown,-,USN-20112109,0,401.610,401.765,1.532,NaN,NaN,NaN,404.435,404.433F,0,100.0,3.562,-0.02471,0.00000,139.99553,0.01358,44.96662,0.00232,33.58278,44.93938,NaN,31882.432
13,120111,164030,unknown,-,USN-20112109,0,402.768,402.924,1.124,NaN,NaN,NaN,405.602,405.599F,0,100.0,3.412,-0.02471,0.00000,140.00235,0.01529,44.97430,0.00199,33.63235,44.94104,NaN,31896.764
14,120111,164130,unknown,-,USN-20112109,0,401.136,401.292,0.942,NaN,NaN,NaN,403.958,403.956F,0,100.0,3.562,-0.02471,0.00000,140.00854,0.01686,44.98050,0.00164,33.68164,44.94359,NaN,31912.176
15,120111,164230,unknown,-,USN-20112109,0,402.675,402.832,1.384,NaN,NaN,NaN,405.509,405.506F,0,100.0,3.412,-0.02471,0.00000,140.02963,0.08316,44.98534,0.00135,33.73897,44.94599,NaN,31961.027
16,120111,164330,unknown,-,USN-20112109,0,400.283,400.439,0.809,NaN,NaN,NaN,403.100,403.097F,0,100.0,3.562,-0.02471,0.00000,140.01212,0.02237,44.98892,0.00090,33.78395,44.94802,NaN,32437.586
17,120111,164430,unknown,-,USN-20112109,0,402.536,402.692,1.415,NaN,NaN,NaN,405.368,405.365F,0,100.0,3.412,-0.02471,0.00000,139.99870,0.01410,44.99151,0.00075,33.82721,44.94981,NaN,32555.811
18,120111,164530,unknown,-,USN-20112109,0,402.707,402.864,1.649,NaN,NaN,NaN,405.541,405.538F,0,100.0,3.562,-0.02471,0.00000,140.00996,0.01495,44.99374,0.00071,33.89363,44.95130,NaN,32657.541
19,120111,164630,unknown,-,USN-20112109,0,400.225,400.380,1.611,NaN,NaN,NaN,403.041,403.039F,0,100.0,3.471,-0.02471,0.00000,140.00494,0.01437,44.99538,0.00038,33.98176,44.95257,NaN,32746.449

In [19]:
df_taco2['C']

0          406.300x
1          405.776x
2          403.811x
3          404.577x
4          404.301x
             ...
6828985     437.131
6828986     438.124
6828987     438.832
6828988     437.999
6828989     437.717
Name: C, Length: 6828990, dtype: object

In [20]:
df_taco2['C'], df_taco2['co2_flag'] = zip(*df_taco2['C'].map(split_flag))

print(df_taco2[['C', 'co2_flag']].head(20))
df_taco2['C']

          C co2_flag
0   406.300        x
1   405.776        x
2   403.811        x
3   404.577        x
4   404.301        x
5   404.035        F
6   404.238        F
7   407.466        F
8   404.171        F
9   413.777        F
10  405.189        F
11  404.500        F
12  404.433        F
13  405.599        F
14  403.956        F
15  405.506        F
16  403.097        F
17  405.365        F
18  405.538        F
19  403.039        F

0          406.300
1          405.776
2          403.811
3          404.577
4          404.301
            ...
6828985    437.131
6828986    438.124
6828987    438.832
6828988    437.999
6828989    437.717
Name: C, Length: 6828990, dtype: float64

In [21]:
df_taco2.columns.tolist()

['date',
 'time',
 'type',
 'sample',
 'standard',
 'port',
 'dry',
 'wet',
 'stdev',
 'std_rep',
 'std_stdev',
 'target_error',
 'Cdrift',
 'C',
 'N',
 'Nfiltered',
 'time.1',
 'h2o',
 'stdev.1',
 'press',
 'press_stdev',
 'temp',
 'temp_stdev',
 'temp.1',
 'temp.2',
 'temp.3',
 'valve',
 'co2_flag']

In [22]:
feature_name_tacco2 = [
  'date', 'time', 'type', 'sample', 'standard', 'port', 
 'co2_dry', 'co2_wet', 'co2_stdev', 'co2_std_rep', 'co2_std_stdev',
  'co2_target_error','co2_Cdrift', 'co2_C', 'co2_N', 'co2_Nfiltered',
  'cycle_time', 'h2o', 'h2o_stdev', 'cavity_press', 'cavity_press_stdev', 
  'cavity_temp', 'cavity_temp_stdev', 'das_temp', 'etalon_temp', 
  'warmbox_temp', 'outlet_valve','co2_flag'
]

In [23]:
df_taco2.columns = feature_name_tacco2
df_taco2.head(20)

,date,time,type,sample,standard,port,co2_dry,co2_wet,co2_stdev,co2_std_rep,co2_std_stdev,co2_target_error,co2_Cdrift,co2_C,co2_N,co2_Nfiltered,cycle_time,h2o,h2o_stdev,cavity_press,cavity_press_stdev,cavity_temp,cavity_temp_stdev,das_temp,etalon_temp,warmbox_temp,outlet_valve,co2_flag
0,120111,162730,unknown,-,USN-20112109,0,403.464,403.606,1.063,NaN,NaN,NaN,406.303,406.300,0,100.0,3.733,-0.02232,0.00175,140.00525,0.01396,44.90277,0.01251,32.14167,44.77072,NaN,31442.617,x
1,120111,162830,unknown,-,USN-20112109,0,402.944,403.085,1.308,NaN,NaN,NaN,405.779,405.776,0,100.0,3.733,-0.02232,0.00170,140.00435,0.01518,44.92952,0.00415,32.36250,44.91882,NaN,31543.971,x
2,120111,162930,unknown,-,USN-20112109,0,400.992,401.133,1.802,NaN,NaN,NaN,403.813,403.811,0,100.0,3.733,-0.02243,0.00221,140.00513,0.01176,44.93352,0.00128,32.59792,44.99702,NaN,31626.549,x
3,120111,163030,unknown,-,USN-20112109,0,401.753,401.893,1.516,NaN,NaN,NaN,404.580,404.577,0,100.0,3.733,-0.02217,0.00256,140.00745,0.01437,44.92616,0.00253,32.81506,45.02549,NaN,31687.379,x
4,120111,163130,unknown,-,USN-20112109,0,401.479,401.622,0.743,NaN,NaN,NaN,404.304,404.301,0,100.0,3.625,-0.02259,0.00192,140.00314,0.01321,44.91914,0.00165,32.98813,45.02443,NaN,31726.805,x
5,120111,163230,unknown,-,USN-20112109,0,401.215,401.356,0.619,NaN,NaN,NaN,404.038,404.035,0,100.0,3.733,-0.02248,0.00258,139.99792,0.01910,44.91655,0.00026,33.13750,45.00900,NaN,31758.904,F
6,120111,163330,unknown,-,USN-20112109,0,401.416,401.565,0.727,NaN,NaN,NaN,404.241,404.238,0,100.0,3.500,-0.02362,0.00115,140.00032,0.01554,44.91776,0.00100,33.26172,44.98967,NaN,31785.496,F
7,120111,163430,unknown,-,USN-20112109,0,404.622,404.779,2.342,NaN,NaN,NaN,407.469,407.466,0,100.0,3.500,-0.02471,0.00000,140.00146,0.01652,44.92261,0.00181,33.35547,44.97134,NaN,31807.650,F
8,120111,163530,unknown,-,USN-20112109,0,401.350,401.506,2.698,NaN,NaN,NaN,404.174,404.171,0,100.0,3.500,-0.02471,0.00000,139.99977,0.01241,44.92999,0.00249,33.42248,44.95708,NaN,31827.049,F
9,120111,163630,unknown,-,USN-20112109,0,410.890,411.049,3.356,NaN,NaN,NaN,413.781,413.777,0,100.0,3.471,-0.02471,0.00000,140.00076,0.01586,44.93916,0.00306,33.47794,44.94679,NaN,31844.387,F
10,120111,163730,unknown,-,USN-20112109,0,402.361,402.517,2.391,NaN,NaN,NaN,405.192,405.189,0,100.0,3.625,-0.02471,0.00000,140.00096,0.01696,44.94887,0.00277,33.51382,44.94103,NaN,31857.955,F
11,120111,163830,unknown,-,USN-20112109,0,401.677,401.833,0.485,NaN,NaN,NaN,404.503,404.500,0,100.0,3.562,-0.02471,0.00000,140.00214,0.01152,44.95813,0.00269,33.56085,44.93909,NaN,31872.648,F
12,120111,163930,unknown,-,USN-20112109,0,401.610,401.765,1.532,NaN,NaN,NaN,404.435,404.433,0,100.0,3.562,-0.02471,0.00000,139.99553,0.01358,44.96662,0.00232,33.58278,44.93938,NaN,31882.432,F
13,120111,164030,unknown,-,USN-20112109,0,402.768,402.924,1.124,NaN,NaN,NaN,405.602,405.599,0,100.0,3.412,-0.02471,0.00000,140.00235,0.01529,44.97430,0.00199,33.63235,44.94104,NaN,31896.764,F
14,120111,164130,unknown,-,USN-20112109,0,401.136,401.292,0.942,NaN,NaN,NaN,403.958,403.956,0,100.0,3.562,-0.02471,0.00000,140.00854,0.01686,44.98050,0.00164,33.68164,44.94359,NaN,31912.176,F
15,120111,164230,unknown,-,USN-20112109,0,402.675,402.832,1.384,NaN,NaN,NaN,405.509,405.506,0,100.0,3.412,-0.02471,0.00000,140.02963,0.08316,44.98534,0.00135,33.73897,44.94599,NaN,31961.027,F
16,120111,164330,unknown,-,USN-20112109,0,400.283,400.439,0.809,NaN,NaN,NaN,403.100,403.097,0,100.0,3.562,-0.02471,0.00000,140.01212,0.02237,44.98892,0.00090,33.78395,44.94802,NaN,32437.586,F
17,120111,164430,unknown,-,USN-20112109,0,402.536,402.692,1.415,NaN,NaN,NaN,405.368,405.365,0,100.0,3.412,-0.02471,0.00000,139.99870,0.01410,44.99151,0.00075,33.82721,44.94981,NaN,32555.811,F
18,120111,164530,unknown,-,USN-20112109,0,402.707,402.864,1.649,NaN,NaN,NaN,405.541,405.538,0,100.0,3.562,-0.02471,0.00000,140.00996,0.01495,44.99374,0.00071,33.89363,44.95130,NaN,32657.541,F
19,120111,164630,unknown,-,USN-20112109,0,400.225,400.380,1.611,NaN,NaN,NaN,403.041,403.039,0,100.0,3.471,-0.02471,0.00000,140.00494,0.01437,44.99538,0.00038,33.98176,44.95257,NaN,32746.449,F

In [24]:
df_taco2.to_csv("../data/processed/tac_co2_formatted_v1.csv", index=False)