In [2]:
import pandas as pd

file_path = "../data/raw/mhd_ch4.txt"

df_mhd = pd.read_fwf(file_path) # skip first row, txt is space seperated

# Ignore this part
import pandas as pd 
import io

def clean_and_load(file_path, sep='\t'):
    lines=[]
    with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
        for line in f:
            cleaned_line = line.replace('\x00', '')
            lines.append(cleaned_line)

    joined_text = "".join(lines)
    return pd.read_csv(io.StringIO(joined_text), sep=sep)

file_path = "../data/raw/mhd_ch4.txt"
df = clean_and_load(file_path)
print(df.info())

In [3]:
df_mhd.head(20)

,Created: 19 May,26,12:50 GMT,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41
0,- -,NaN,-,-,-,-,inlet,-,-,lab,...,CH4,CH4,CH4,CH4,CH4,CH4,CH4,CH4,CH4,CH4
1,date time,NaN,type,sample,standard,port,ht,tmod,tamb,temp,...,C_ht,C_a,C,std_stdev,std_rep,Cstd,flag_ht,flag_a,flag,flag_p
2,940216 142900,NaN,air,10m,G-024,3,10,40.00,32.27,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
3,940216 144900,NaN,air,10m,G-024,3,10,40.00,32.48,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
4,940216 150900,NaN,air,10m,G-024,3,10,40.01,32.75,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
5,940216 152900,NaN,air,10m,G-024,3,10,40.00,32.92,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,NaN,NaN,NaN,NaN
6,940216 180000,NaN,air,10m,G-024,3,10,40.00,33.31,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
7,940216 182000,NaN,air,10m,G-024,3,10,40.01,33.10,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
8,940216 184000,NaN,air,10m,G-024,3,10,40.01,33.20,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
9,940216 190000,NaN,air,10m,G-024,3,10,40.00,33.39,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
10,940216 192000,NaN,air,10m,G-024,3,10,40.00,33.61,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
11,940216 194000,NaN,air,10m,G-024,3,10,40.01,33.66,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
12,940216 202300,NaN,air,10m,G-024,3,10,40.00,33.17,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
13,940216 204300,NaN,air,10m,G-024,3,10,40.00,33.05,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
14,940216 210300,NaN,air,10m,G-024,3,10,40.01,33.06,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
15,940216 212400,NaN,air,10m,G-024,3,10,40.00,33.01,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
16,940216 214400,NaN,air,10m,G-024,3,10,40.00,32.94,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
17,940216 220400,NaN,air,10m,G-024,3,10,40.00,32.87,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
18,940216 222400,NaN,air,10m,G-024,3,10,40.01,32.76,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
19,940216 224400,NaN,air,10m,G-024,3,10,40.00,32.71,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN

In [4]:
df_mhd.iloc[[187]]

,Created: 19 May,26,12:50 GMT,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41
187,940219 102700,NaN,cal1060,G-024,G-024,1,0,40.01,23.16,NaN,...,1569.54,1695.49,1692.49,3.180,NaN,1692.489,NaN,NaN,NaN,NaN

In [5]:
print(df_mhd.shape)

(817957, 42)

In [6]:
print(df_mhd.columns.tolist())

['Created: 19 May', '26', '12:50 GMT', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41']

In [7]:
print(df_mhd.isnull().sum())

Created: 19 May         0
26                 817957
12:50 GMT               1
Unnamed: 3              0
Unnamed: 4              0
Unnamed: 5              0
Unnamed: 6              0
Unnamed: 7         112284
Unnamed: 8         112284
Unnamed: 9         817955
Unnamed: 10          2402
Unnamed: 11          2329
Unnamed: 12        817955
Unnamed: 13          2404
Unnamed: 14          1590
Unnamed: 15          1590
Unnamed: 16          1590
Unnamed: 17          1590
Unnamed: 18          1590
Unnamed: 19          1590
Unnamed: 20          1590
Unnamed: 21          1590
Unnamed: 22          1590
Unnamed: 23         51247
Unnamed: 24         49492
Unnamed: 25         58674
Unnamed: 26         51247
Unnamed: 27         51247
Unnamed: 28         51247
Unnamed: 29         51247
Unnamed: 30         49492
Unnamed: 31         58674
Unnamed: 32         52743
Unnamed: 33         50993
Unnamed: 34         59835
Unnamed: 35         21816
Unnamed: 36        471914
Unnamed: 37             0
Unnamed: 38        779684
Unnamed: 39        780175
Unnamed: 40        726145
Unnamed: 41        817955
dtype: int64

In [2]:
# feature rename

import pandas as pd
file_path = "../data/raw/mhd_ch4.txt"
df_mhd = pd.read_fwf(file_path) # skiprows =3 will cause value error, save feature columns and delete it later
df_mhd

,Created: 19 May,26,12:50 GMT,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41
0,- -,NaN,-,-,-,-,inlet,-,-,lab,...,CH4,CH4,CH4,CH4,CH4,CH4,CH4,CH4,CH4,CH4
1,date time,NaN,type,sample,standard,port,ht,tmod,tamb,temp,...,C_ht,C_a,C,std_stdev,std_rep,Cstd,flag_ht,flag_a,flag,flag_p
2,940216 142900,NaN,air,10m,G-024,3,10,40.00,32.27,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
3,940216 144900,NaN,air,10m,G-024,3,10,40.00,32.48,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
4,940216 150900,NaN,air,10m,G-024,3,10,40.01,32.75,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
817952,260518 065300,NaN,std,J-286,J-286,3,0,40.00,22.06,NaN,...,NaN,NaN,NaN,3.649,NaN,2015.923,NaN,NaN,A,NaN
817953,260518 071300,NaN,air,9m,J-286,1,9,40.00,22.32,NaN,...,2061.71,2025.82,2025.82,3.649,3.666,2015.923,NaN,NaN,A,NaN
817954,260518 073300,NaN,std,J-286,J-286,3,0,40.00,22.19,NaN,...,2159.17,2716.92,2716.92,4.605,NaN,2015.923,NaN,NaN,A,NaN
817955,260518 075300,NaN,air,9m,J-286,1,9,40.00,22.10,NaN,...,1955.78,1676.37,NaN,4.605,NaN,2015.923,*,*,A,NaN
817956,260518 081300,NaN,std,J-286,J-286,3,0,40.00,22.23,NaN,...,NaN,NaN,NaN,14.873,NaN,2015.923,NaN,NaN,A,NaN

In [3]:
feature_names = [  
'date', 'time', 'type', 'sample', 'standard', 'port', 'ht', 'tmod', 'tamb', 'temp', 'pflow', 'psamp', 'ploop', 'pamb', 'rt', 'w', 
'CH4_ht.1', 'CH4_area', 'CH4_skew', 'CH4_start_time', 'CH4_end_time', 'CH4_start_level', 'CH4_end_level', 'CH4_Rl_ht', 'CH4_Rl_a', 'CH4_Rl', 'CH4_norm_ht', 'CH4_norm_a', 'CH4_norm_w', 
'CH4_R_ht', 'CH4_R_a', 'CH4_R', 'CH4_C_ht', 'CH4_C_a', 'CH4_C', 'CH4_std_stdev', 'CH4_std_rep', 'CH4_Cstd', 'CH4_flag_ht', 'CH4_flag_a', 'CH4_flag', 'CH4_flag_p'
]
df_mhd.columns = feature_names

In [4]:
df_mhd.head(20)

,date,time,type,sample,standard,port,ht,tmod,tamb,temp,...,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p
0,- -,NaN,-,-,-,-,inlet,-,-,lab,...,CH4,CH4,CH4,CH4,CH4,CH4,CH4,CH4,CH4,CH4
1,date time,NaN,type,sample,standard,port,ht,tmod,tamb,temp,...,C_ht,C_a,C,std_stdev,std_rep,Cstd,flag_ht,flag_a,flag,flag_p
2,940216 142900,NaN,air,10m,G-024,3,10,40.00,32.27,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
3,940216 144900,NaN,air,10m,G-024,3,10,40.00,32.48,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
4,940216 150900,NaN,air,10m,G-024,3,10,40.01,32.75,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
5,940216 152900,NaN,air,10m,G-024,3,10,40.00,32.92,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,NaN,NaN,NaN,NaN
6,940216 180000,NaN,air,10m,G-024,3,10,40.00,33.31,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
7,940216 182000,NaN,air,10m,G-024,3,10,40.01,33.10,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
8,940216 184000,NaN,air,10m,G-024,3,10,40.01,33.20,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
9,940216 190000,NaN,air,10m,G-024,3,10,40.00,33.39,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
10,940216 192000,NaN,air,10m,G-024,3,10,40.00,33.61,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
11,940216 194000,NaN,air,10m,G-024,3,10,40.01,33.66,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
12,940216 202300,NaN,air,10m,G-024,3,10,40.00,33.17,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
13,940216 204300,NaN,air,10m,G-024,3,10,40.00,33.05,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
14,940216 210300,NaN,air,10m,G-024,3,10,40.01,33.06,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
15,940216 212400,NaN,air,10m,G-024,3,10,40.00,33.01,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
16,940216 214400,NaN,air,10m,G-024,3,10,40.00,32.94,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
17,940216 220400,NaN,air,10m,G-024,3,10,40.00,32.87,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
18,940216 222400,NaN,air,10m,G-024,3,10,40.01,32.76,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
19,940216 224400,NaN,air,10m,G-024,3,10,40.00,32.71,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN

In [5]:
df_mhd = df_mhd.drop(index=[0,1]).reset_index(drop=True)
df_mhd

,date,time,type,sample,standard,port,ht,tmod,tamb,temp,...,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p
0,940216 142900,NaN,air,10m,G-024,3,10,40.00,32.27,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
1,940216 144900,NaN,air,10m,G-024,3,10,40.00,32.48,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
2,940216 150900,NaN,air,10m,G-024,3,10,40.01,32.75,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
3,940216 152900,NaN,air,10m,G-024,3,10,40.00,32.92,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,NaN,NaN,NaN,NaN
4,940216 180000,NaN,air,10m,G-024,3,10,40.00,33.31,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
817950,260518 065300,NaN,std,J-286,J-286,3,0,40.00,22.06,NaN,...,NaN,NaN,NaN,3.649,NaN,2015.923,NaN,NaN,A,NaN
817951,260518 071300,NaN,air,9m,J-286,1,9,40.00,22.32,NaN,...,2061.71,2025.82,2025.82,3.649,3.666,2015.923,NaN,NaN,A,NaN
817952,260518 073300,NaN,std,J-286,J-286,3,0,40.00,22.19,NaN,...,2159.17,2716.92,2716.92,4.605,NaN,2015.923,NaN,NaN,A,NaN
817953,260518 075300,NaN,air,9m,J-286,1,9,40.00,22.10,NaN,...,1955.78,1676.37,NaN,4.605,NaN,2015.923,*,*,A,NaN
817954,260518 081300,NaN,std,J-286,J-286,3,0,40.00,22.23,NaN,...,NaN,NaN,NaN,14.873,NaN,2015.923,NaN,NaN,A,NaN

In [6]:
df_mhd['time'].to_string
df_mhd['time'].isnull().sum()

np.int64(817955)

In [7]:
df_mhd['date'] = df_mhd['date'].astype(str)

df_mhd['time'] = df_mhd['date'].str[6:]
df_mhd['date'] = df_mhd['date'].str[:6]

In [9]:
df_mhd.head(20)

,date,time,type,sample,standard,port,ht,tmod,tamb,temp,...,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p
0,940216,142900,air,10m,G-024,3,10,40.00,32.27,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
1,940216,144900,air,10m,G-024,3,10,40.00,32.48,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
2,940216,150900,air,10m,G-024,3,10,40.01,32.75,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
3,940216,152900,air,10m,G-024,3,10,40.00,32.92,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,NaN,NaN,NaN,NaN
4,940216,180000,air,10m,G-024,3,10,40.00,33.31,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
5,940216,182000,air,10m,G-024,3,10,40.01,33.10,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
6,940216,184000,air,10m,G-024,3,10,40.01,33.20,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
7,940216,190000,air,10m,G-024,3,10,40.00,33.39,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
8,940216,192000,air,10m,G-024,3,10,40.00,33.61,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
9,940216,194000,air,10m,G-024,3,10,40.01,33.66,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
10,940216,202300,air,10m,G-024,3,10,40.00,33.17,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
11,940216,204300,air,10m,G-024,3,10,40.00,33.05,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
12,940216,210300,air,10m,G-024,3,10,40.01,33.06,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
13,940216,212400,air,10m,G-024,3,10,40.00,33.01,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
14,940216,214400,air,10m,G-024,3,10,40.00,32.94,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
15,940216,220400,air,10m,G-024,3,10,40.00,32.87,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
16,940216,222400,air,10m,G-024,3,10,40.01,32.76,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
17,940216,224400,air,10m,G-024,3,10,40.00,32.71,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
18,940216,230400,air,10m,G-024,3,10,40.00,32.69,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
19,940216,232400,air,10m,G-024,3,10,40.00,32.65,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN

In [10]:
df_mhd.iloc[[185]]

,date,time,type,sample,standard,port,ht,tmod,tamb,temp,...,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p
185,940219,102700,cal1060,G-024,G-024,1,0,40.01,23.16,NaN,...,1569.54,1695.49,1692.49,3.180,NaN,1692.489,NaN,NaN,NaN,NaN

In [11]:
df_mhd.to_csv("../data/processed/mhd_ch4_formatted_v1.csv", index=False)

READ tac_ch4.txt

In [1]:
import pandas as pd

file_path = "../data/raw/tac_ch4.txt"

df_tac = pd.read_csv(file_path, skiprows=1, sep=r'\s+', header=1) # skip first row, txt is space seperated

In [2]:
df_tac

,date,time,type,sample,standard,port,dry,wet,stdev,std_rep,...,h2o,stdev.1,press,press_stdev,temp,temp_stdev,temp.1,temp.2,temp.3,valve
0,120111,162730,unknown,-,USN-20112109,0,1944.517,1945.109,42.208,NaN,...,-0.02232,0.00175,140.00525,0.01396,44.90277,0.01251,32.14167,44.77072,NaN,31442.617
1,120111,162830,unknown,-,USN-20112109,0,1972.043,1972.643,57.714,NaN,...,-0.02232,0.00170,140.00435,0.01518,44.92952,0.00415,32.36250,44.91882,NaN,31543.971
2,120111,162930,unknown,-,USN-20112109,0,1940.176,1940.768,65.419,NaN,...,-0.02243,0.00221,140.00513,0.01176,44.93352,0.00128,32.59792,44.99702,NaN,31626.549
3,120111,163030,unknown,-,USN-20112109,0,2021.915,2022.526,80.016,NaN,...,-0.02217,0.00256,140.00745,0.01437,44.92616,0.00253,32.81506,45.02549,NaN,31687.379
4,120111,163130,unknown,-,USN-20112109,0,1976.217,1976.825,57.151,NaN,...,-0.02259,0.00192,140.00314,0.01321,44.91914,0.00165,32.98813,45.02443,NaN,31726.805
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6828985,250722,70630,air,185m,CFF-011,10,2057.675,2056.587,2.062,0.129,...,0.03994,0.00025,139.99831,0.00999,45.00000,0.00000,33.04913,45.07225,45.00000,33654.016
6828986,250722,70730,air,185m,CFF-011,10,2061.071,2059.976,5.347,0.129,...,0.04013,0.00062,139.99857,0.01007,45.00006,0.00025,33.00881,45.07200,45.00000,33653.953
6828987,250722,70830,air,185m,CFF-011,10,2064.147,2063.058,4.733,0.129,...,0.03988,0.00049,139.99689,0.01431,44.99976,0.00044,33.00000,45.07159,44.99929,33653.434
6828988,250722,70930,air,185m,CFF-011,10,2060.348,2059.262,6.968,0.129,...,0.03981,0.00040,140.00513,0.01337,44.99944,0.00051,32.97287,45.07100,44.99900,33658.930
6828989,250722,71030,air,185m,CFF-011,10,2059.633,2058.548,5.357,0.129,...,0.03981,0.00054,139.99606,0.01112,44.99900,0.00000,32.94081,45.07094,44.99850,33655.355

In [3]:
print(df_tac.columns.tolist())

['date', 'time', 'type', 'sample', 'standard', 'port', 'dry', 'wet', 'stdev', 'std_rep', 'std_stdev', 'target_error', 'Cdrift', 'C', 'N', 'Nfiltered', 'time.1', 'h2o', 'stdev.1', 'press', 'press_stdev', 'temp', 'temp_stdev', 'temp.1', 'temp.2', 'temp.3', 'valve']

In [4]:
df_tac.shape

(6828990, 27)

deal the problem that flag sign is connected with featurre C (such as 1827x)

In [5]:
df_tac.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6828990 entries, 0 to 6828989
Data columns (total 27 columns):
 #   Column        Dtype
---  ------        -----
 0   date          int64
 1   time          int64
 2   type          object
 3   sample        object
 4   standard      object
 5   port          int64
 6   dry           float64
 7   wet           float64
 8   stdev         float64
 9   std_rep       float64
 10  std_stdev     float64
 11  target_error  float64
 12  Cdrift        float64
 13  C             object
 14  N             int64
 15  Nfiltered     float64
 16  time.1        float64
 17  h2o           float64
 18  stdev.1       float64
 19  press         float64
 20  press_stdev   float64
 21  temp          float64
 22  temp_stdev    float64
 23  temp.1        float64
 24  temp.2        float64
 25  temp.3        float64
 26  valve         float64
dtypes: float64(19), int64(4), object(4)
memory usage: 1.4+ GB

C should be flaot?
convert into float first

In [6]:
df_tac['C'].head(20)

0     1955.527x
1     1983.217x
2     1951.159x
3     2033.386x
4     1987.416x
5     1988.226F
6     1985.406F
7     1915.031F
8     1940.282F
9     1981.204F
10    1931.891F
11    1980.398F
12    1947.380F
13    1949.511F
14    1909.053F
15    1939.482F
16    1913.494F
17    1949.543F
18    1934.023F
19    1895.129F
Name: C, dtype: object

In [7]:
import numpy as np

def split_flag (val):
    if pd.isna(val):
        return np.nan, np.nan
    
    val_str = str(val).strip()
    # check if last val is a character(Flag)
    if val_str[-1].isalpha() or val_str[-1] == '*':
        c_val = float(val_str[:-1])
        flag_val = val_str[-1]
    else:
        c_val = float(val_str) # normal value, then direcly convert to float
        flag_val = " " # no flag, give it a space
    
    return c_val, flag_val

In [8]:
df_tac['C'], df_tac['CH4_flag'] = zip(*df_tac['C'].map(split_flag))

print(df_tac[['C', 'CH4_flag']].head(20))
df_tac['C']

           C CH4_flag
0   1955.527        x
1   1983.217        x
2   1951.159        x
3   2033.386        x
4   1987.416        x
5   1988.226        F
6   1985.406        F
7   1915.031        F
8   1940.282        F
9   1981.204        F
10  1931.891        F
11  1980.398        F
12  1947.380        F
13  1949.511        F
14  1909.053        F
15  1939.482        F
16  1913.494        F
17  1949.543        F
18  1934.023        F
19  1895.129        F

0          1955.527
1          1983.217
2          1951.159
3          2033.386
4          1987.416
             ...
6828985    2059.287
6828986    2062.687
6828987    2065.768
6828988    2061.963
6828989    2061.248
Name: C, Length: 6828990, dtype: float64

In [9]:
df_tac.head(20)

,date,time,type,sample,standard,port,dry,wet,stdev,std_rep,...,stdev.1,press,press_stdev,temp,temp_stdev,temp.1,temp.2,temp.3,valve,CH4_flag
0,120111,162730,unknown,-,USN-20112109,0,1944.517,1945.109,42.208,NaN,...,0.00175,140.00525,0.01396,44.90277,0.01251,32.14167,44.77072,NaN,31442.617,x
1,120111,162830,unknown,-,USN-20112109,0,1972.043,1972.643,57.714,NaN,...,0.00170,140.00435,0.01518,44.92952,0.00415,32.36250,44.91882,NaN,31543.971,x
2,120111,162930,unknown,-,USN-20112109,0,1940.176,1940.768,65.419,NaN,...,0.00221,140.00513,0.01176,44.93352,0.00128,32.59792,44.99702,NaN,31626.549,x
3,120111,163030,unknown,-,USN-20112109,0,2021.915,2022.526,80.016,NaN,...,0.00256,140.00745,0.01437,44.92616,0.00253,32.81506,45.02549,NaN,31687.379,x
4,120111,163130,unknown,-,USN-20112109,0,1976.217,1976.825,57.151,NaN,...,0.00192,140.00314,0.01321,44.91914,0.00165,32.98813,45.02443,NaN,31726.805,x
5,120111,163230,unknown,-,USN-20112109,0,1977.023,1977.629,107.839,NaN,...,0.00258,139.99792,0.01910,44.91655,0.00026,33.13750,45.00900,NaN,31758.904,F
6,120111,163330,unknown,-,USN-20112109,0,1974.220,1974.855,94.284,NaN,...,0.00115,140.00032,0.01554,44.91776,0.00100,33.26172,44.98967,NaN,31785.496,F
7,120111,163430,unknown,-,USN-20112109,0,1904.261,1904.902,51.648,NaN,...,0.00000,140.00146,0.01652,44.92261,0.00181,33.35547,44.97134,NaN,31807.650,F
8,120111,163530,unknown,-,USN-20112109,0,1929.363,1930.012,59.736,NaN,...,0.00000,139.99977,0.01241,44.92999,0.00249,33.42248,44.95708,NaN,31827.049,F
9,120111,163630,unknown,-,USN-20112109,0,1970.042,1970.705,71.395,NaN,...,0.00000,140.00076,0.01586,44.93916,0.00306,33.47794,44.94679,NaN,31844.387,F
10,120111,163730,unknown,-,USN-20112109,0,1921.022,1921.668,30.451,NaN,...,0.00000,140.00096,0.01696,44.94887,0.00277,33.51382,44.94103,NaN,31857.955,F
11,120111,163830,unknown,-,USN-20112109,0,1969.241,1969.904,70.028,NaN,...,0.00000,140.00214,0.01152,44.95813,0.00269,33.56085,44.93909,NaN,31872.648,F
12,120111,163930,unknown,-,USN-20112109,0,1936.419,1937.071,39.461,NaN,...,0.00000,139.99553,0.01358,44.96662,0.00232,33.58278,44.93938,NaN,31882.432,F
13,120111,164030,unknown,-,USN-20112109,0,1938.537,1939.190,142.405,NaN,...,0.00000,140.00235,0.01529,44.97430,0.00199,33.63235,44.94104,NaN,31896.764,F
14,120111,164130,unknown,-,USN-20112109,0,1898.318,1898.957,15.359,NaN,...,0.00000,140.00854,0.01686,44.98050,0.00164,33.68164,44.94359,NaN,31912.176,F
15,120111,164230,unknown,-,USN-20112109,0,1928.567,1929.216,31.420,NaN,...,0.00000,140.02963,0.08316,44.98534,0.00135,33.73897,44.94599,NaN,31961.027,F
16,120111,164330,unknown,-,USN-20112109,0,1902.733,1903.373,36.078,NaN,...,0.00000,140.01212,0.02237,44.98892,0.00090,33.78395,44.94802,NaN,32437.586,F
17,120111,164430,unknown,-,USN-20112109,0,1938.570,1939.222,30.627,NaN,...,0.00000,139.99870,0.01410,44.99151,0.00075,33.82721,44.94981,NaN,32555.811,F
18,120111,164530,unknown,-,USN-20112109,0,1923.141,1923.788,37.563,NaN,...,0.00000,140.00996,0.01495,44.99374,0.00071,33.89363,44.95130,NaN,32657.541,F
19,120111,164630,unknown,-,USN-20112109,0,1884.477,1885.111,16.566,NaN,...,0.00000,140.00494,0.01437,44.99538,0.00038,33.98176,44.95257,NaN,32746.449,F

In [10]:
df_tac.to_csv("../data/processed/tac_ch4_formatted_v1.csv", index=False)

In [11]:
import pandas as pd

file_path = "../data/raw/tac_co2.txt"

df_taco2 = pd.read_csv(file_path, skiprows=1, sep=r'\s+', header=1) # skip first row, txt is space seperated

In [12]:
df_taco2.head(20)

,date,time,type,sample,standard,port,dry,wet,stdev,std_rep,...,h2o,stdev.1,press,press_stdev,temp,temp_stdev,temp.1,temp.2,temp.3,valve
0,120111,162730,unknown,-,USN-20112109,0,403.464,403.606,1.063,NaN,...,-0.02232,0.00175,140.00525,0.01396,44.90277,0.01251,32.14167,44.77072,NaN,31442.617
1,120111,162830,unknown,-,USN-20112109,0,402.944,403.085,1.308,NaN,...,-0.02232,0.00170,140.00435,0.01518,44.92952,0.00415,32.36250,44.91882,NaN,31543.971
2,120111,162930,unknown,-,USN-20112109,0,400.992,401.133,1.802,NaN,...,-0.02243,0.00221,140.00513,0.01176,44.93352,0.00128,32.59792,44.99702,NaN,31626.549
3,120111,163030,unknown,-,USN-20112109,0,401.753,401.893,1.516,NaN,...,-0.02217,0.00256,140.00745,0.01437,44.92616,0.00253,32.81506,45.02549,NaN,31687.379
4,120111,163130,unknown,-,USN-20112109,0,401.479,401.622,0.743,NaN,...,-0.02259,0.00192,140.00314,0.01321,44.91914,0.00165,32.98813,45.02443,NaN,31726.805
5,120111,163230,unknown,-,USN-20112109,0,401.215,401.356,0.619,NaN,...,-0.02248,0.00258,139.99792,0.01910,44.91655,0.00026,33.13750,45.00900,NaN,31758.904
6,120111,163330,unknown,-,USN-20112109,0,401.416,401.565,0.727,NaN,...,-0.02362,0.00115,140.00032,0.01554,44.91776,0.00100,33.26172,44.98967,NaN,31785.496
7,120111,163430,unknown,-,USN-20112109,0,404.622,404.779,2.342,NaN,...,-0.02471,0.00000,140.00146,0.01652,44.92261,0.00181,33.35547,44.97134,NaN,31807.650
8,120111,163530,unknown,-,USN-20112109,0,401.350,401.506,2.698,NaN,...,-0.02471,0.00000,139.99977,0.01241,44.92999,0.00249,33.42248,44.95708,NaN,31827.049
9,120111,163630,unknown,-,USN-20112109,0,410.890,411.049,3.356,NaN,...,-0.02471,0.00000,140.00076,0.01586,44.93916,0.00306,33.47794,44.94679,NaN,31844.387
10,120111,163730,unknown,-,USN-20112109,0,402.361,402.517,2.391,NaN,...,-0.02471,0.00000,140.00096,0.01696,44.94887,0.00277,33.51382,44.94103,NaN,31857.955
11,120111,163830,unknown,-,USN-20112109,0,401.677,401.833,0.485,NaN,...,-0.02471,0.00000,140.00214,0.01152,44.95813,0.00269,33.56085,44.93909,NaN,31872.648
12,120111,163930,unknown,-,USN-20112109,0,401.610,401.765,1.532,NaN,...,-0.02471,0.00000,139.99553,0.01358,44.96662,0.00232,33.58278,44.93938,NaN,31882.432
13,120111,164030,unknown,-,USN-20112109,0,402.768,402.924,1.124,NaN,...,-0.02471,0.00000,140.00235,0.01529,44.97430,0.00199,33.63235,44.94104,NaN,31896.764
14,120111,164130,unknown,-,USN-20112109,0,401.136,401.292,0.942,NaN,...,-0.02471,0.00000,140.00854,0.01686,44.98050,0.00164,33.68164,44.94359,NaN,31912.176
15,120111,164230,unknown,-,USN-20112109,0,402.675,402.832,1.384,NaN,...,-0.02471,0.00000,140.02963,0.08316,44.98534,0.00135,33.73897,44.94599,NaN,31961.027
16,120111,164330,unknown,-,USN-20112109,0,400.283,400.439,0.809,NaN,...,-0.02471,0.00000,140.01212,0.02237,44.98892,0.00090,33.78395,44.94802,NaN,32437.586
17,120111,164430,unknown,-,USN-20112109,0,402.536,402.692,1.415,NaN,...,-0.02471,0.00000,139.99870,0.01410,44.99151,0.00075,33.82721,44.94981,NaN,32555.811
18,120111,164530,unknown,-,USN-20112109,0,402.707,402.864,1.649,NaN,...,-0.02471,0.00000,140.00996,0.01495,44.99374,0.00071,33.89363,44.95130,NaN,32657.541
19,120111,164630,unknown,-,USN-20112109,0,400.225,400.380,1.611,NaN,...,-0.02471,0.00000,140.00494,0.01437,44.99538,0.00038,33.98176,44.95257,NaN,32746.449

In [13]:
df_taco2['C']

0          406.300x
1          405.776x
2          403.811x
3          404.577x
4          404.301x
             ...
6828985     437.131
6828986     438.124
6828987     438.832
6828988     437.999
6828989     437.717
Name: C, Length: 6828990, dtype: object

In [14]:
df_taco2['C'], df_taco2['CH4_flag'] = zip(*df_taco2['C'].map(split_flag))

print(df_taco2[['C', 'CH4_flag']].head(20))
df_tac['C']

          C CH4_flag
0   406.300        x
1   405.776        x
2   403.811        x
3   404.577        x
4   404.301        x
5   404.035        F
6   404.238        F
7   407.466        F
8   404.171        F
9   413.777        F
10  405.189        F
11  404.500        F
12  404.433        F
13  405.599        F
14  403.956        F
15  405.506        F
16  403.097        F
17  405.365        F
18  405.538        F
19  403.039        F

0          1955.527
1          1983.217
2          1951.159
3          2033.386
4          1987.416
             ...
6828985    2059.287
6828986    2062.687
6828987    2065.768
6828988    2061.963
6828989    2061.248
Name: C, Length: 6828990, dtype: float64

In [15]:
df_taco2.head(20)

,date,time,type,sample,standard,port,dry,wet,stdev,std_rep,...,stdev.1,press,press_stdev,temp,temp_stdev,temp.1,temp.2,temp.3,valve,CH4_flag
0,120111,162730,unknown,-,USN-20112109,0,403.464,403.606,1.063,NaN,...,0.00175,140.00525,0.01396,44.90277,0.01251,32.14167,44.77072,NaN,31442.617,x
1,120111,162830,unknown,-,USN-20112109,0,402.944,403.085,1.308,NaN,...,0.00170,140.00435,0.01518,44.92952,0.00415,32.36250,44.91882,NaN,31543.971,x
2,120111,162930,unknown,-,USN-20112109,0,400.992,401.133,1.802,NaN,...,0.00221,140.00513,0.01176,44.93352,0.00128,32.59792,44.99702,NaN,31626.549,x
3,120111,163030,unknown,-,USN-20112109,0,401.753,401.893,1.516,NaN,...,0.00256,140.00745,0.01437,44.92616,0.00253,32.81506,45.02549,NaN,31687.379,x
4,120111,163130,unknown,-,USN-20112109,0,401.479,401.622,0.743,NaN,...,0.00192,140.00314,0.01321,44.91914,0.00165,32.98813,45.02443,NaN,31726.805,x
5,120111,163230,unknown,-,USN-20112109,0,401.215,401.356,0.619,NaN,...,0.00258,139.99792,0.01910,44.91655,0.00026,33.13750,45.00900,NaN,31758.904,F
6,120111,163330,unknown,-,USN-20112109,0,401.416,401.565,0.727,NaN,...,0.00115,140.00032,0.01554,44.91776,0.00100,33.26172,44.98967,NaN,31785.496,F
7,120111,163430,unknown,-,USN-20112109,0,404.622,404.779,2.342,NaN,...,0.00000,140.00146,0.01652,44.92261,0.00181,33.35547,44.97134,NaN,31807.650,F
8,120111,163530,unknown,-,USN-20112109,0,401.350,401.506,2.698,NaN,...,0.00000,139.99977,0.01241,44.92999,0.00249,33.42248,44.95708,NaN,31827.049,F
9,120111,163630,unknown,-,USN-20112109,0,410.890,411.049,3.356,NaN,...,0.00000,140.00076,0.01586,44.93916,0.00306,33.47794,44.94679,NaN,31844.387,F
10,120111,163730,unknown,-,USN-20112109,0,402.361,402.517,2.391,NaN,...,0.00000,140.00096,0.01696,44.94887,0.00277,33.51382,44.94103,NaN,31857.955,F
11,120111,163830,unknown,-,USN-20112109,0,401.677,401.833,0.485,NaN,...,0.00000,140.00214,0.01152,44.95813,0.00269,33.56085,44.93909,NaN,31872.648,F
12,120111,163930,unknown,-,USN-20112109,0,401.610,401.765,1.532,NaN,...,0.00000,139.99553,0.01358,44.96662,0.00232,33.58278,44.93938,NaN,31882.432,F
13,120111,164030,unknown,-,USN-20112109,0,402.768,402.924,1.124,NaN,...,0.00000,140.00235,0.01529,44.97430,0.00199,33.63235,44.94104,NaN,31896.764,F
14,120111,164130,unknown,-,USN-20112109,0,401.136,401.292,0.942,NaN,...,0.00000,140.00854,0.01686,44.98050,0.00164,33.68164,44.94359,NaN,31912.176,F
15,120111,164230,unknown,-,USN-20112109,0,402.675,402.832,1.384,NaN,...,0.00000,140.02963,0.08316,44.98534,0.00135,33.73897,44.94599,NaN,31961.027,F
16,120111,164330,unknown,-,USN-20112109,0,400.283,400.439,0.809,NaN,...,0.00000,140.01212,0.02237,44.98892,0.00090,33.78395,44.94802,NaN,32437.586,F
17,120111,164430,unknown,-,USN-20112109,0,402.536,402.692,1.415,NaN,...,0.00000,139.99870,0.01410,44.99151,0.00075,33.82721,44.94981,NaN,32555.811,F
18,120111,164530,unknown,-,USN-20112109,0,402.707,402.864,1.649,NaN,...,0.00000,140.00996,0.01495,44.99374,0.00071,33.89363,44.95130,NaN,32657.541,F
19,120111,164630,unknown,-,USN-20112109,0,400.225,400.380,1.611,NaN,...,0.00000,140.00494,0.01437,44.99538,0.00038,33.98176,44.95257,NaN,32746.449,F

In [16]:
df_taco2.to_csv("../data/processed/tac_co2_formatted_v1.csv", index=False)