In [1]:
import pandas as pd

file_path = "../data/raw/mhd_ch4.txt"

df_mhd=pd.read_fwf(
    file_path,
    skiprows=1,
    header=1,
    keep_default_na=False
)
df_mhd

,date,time,type,sample,standard,port,ht,tmod,tamb,temp,...,C_ht,C_a,C,std_stdev,std_rep,Cstd,flag_ht,flag_a,flag,flag_p
0,940216,142900,air,10m,G-024,3,10,40.00,32.27,nan,...,nan,nan,nan,nan,nan,1692.489,F,F,,
1,940216,144900,air,10m,G-024,3,10,40.00,32.48,nan,...,nan,nan,nan,nan,nan,1692.489,F,F,,
2,940216,150900,air,10m,G-024,3,10,40.01,32.75,nan,...,nan,nan,nan,nan,nan,1692.489,F,F,,
3,940216,152900,air,10m,G-024,3,10,40.00,32.92,nan,...,nan,nan,nan,nan,nan,1692.489,,,,
4,940216,180000,air,10m,G-024,3,10,40.00,33.31,nan,...,nan,nan,nan,nan,nan,1692.489,F,F,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
817950,260518,65300,std,J-286,J-286,3,0,40.00,22.06,nan,...,nan,nan,nan,3.649,nan,2015.923,,,A,
817951,260518,71300,air,9m,J-286,1,9,40.00,22.32,nan,...,2061.71,2025.82,2025.82,3.649,3.666,2015.923,,,A,
817952,260518,73300,std,J-286,J-286,3,0,40.00,22.19,nan,...,2159.17,2716.92,2716.92,4.605,nan,2015.923,,,A,
817953,260518,75300,air,9m,J-286,1,9,40.00,22.10,nan,...,1955.78,1676.37,nan,4.605,nan,2015.923,*,*,A,
817954,260518,81300,std,J-286,J-286,3,0,40.00,22.23,nan,...,nan,nan,nan,14.873,nan,2015.923,,,A,

In [2]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [3]:
feature_names = [  
'date', 'time', 'type', 'sample', 'standard', 'port', 'ht', 'tmod', 'tamb', 'lab_temp', 'pflow', 'psamp', 'ploop', 'pamb', 'CH4_rt', 'CH4_w', 
'CH4_ht', 'CH4_area', 'CH4_skew', 'CH4_start_time', 'CH4_end_time', 'CH4_start_level', 'CH4_end_level', 'CH4_Rl_ht', 'CH4_Rl_a', 'CH4_Rl', 'CH4_norm_ht', 'CH4_norm_a', 'CH4_norm_w', 
'CH4_R_ht', 'CH4_R_a', 'CH4_R', 'CH4_C_ht', 'CH4_C_a', 'CH4_C', 'CH4_std_stdev', 'CH4_std_rep', 'CH4_Cstd', 'CH4_flag_ht', 'CH4_flag_a', 'CH4_flag', 'CH4_flag_p'
]
df_mhd.columns = feature_names

In [4]:
# read the file in the way that the flag space is right
import pandas as pd

file_path = "../data/raw/mhd_ch4.txt"

df_mhd_csvred = pd.read_csv(file_path, skiprows=1, sep=r'\s+',header=1, engine='python') # skip first row, txt is space seperated

In [5]:
feature_names = [  
'date', 'time', 'type', 'sample', 'standard', 'port', 'ht', 'tmod', 'tamb', 'lab_temp', 'pflow', 'psamp', 'ploop', 'pamb', 'CH4_rt', 'CH4_w', 
'CH4_ht', 'CH4_area', 'CH4_skew', 'CH4_start_time', 'CH4_end_time', 'CH4_start_level', 'CH4_end_level', 'CH4_Rl_ht', 'CH4_Rl_a', 'CH4_Rl', 'CH4_norm_ht', 'CH4_norm_a', 'CH4_norm_w', 
'CH4_R_ht', 'CH4_R_a', 'CH4_R', 'CH4_C_ht', 'CH4_C_a', 'CH4_C', 'CH4_std_stdev', 'CH4_std_rep', 'CH4_Cstd', 'CH4_flag_ht', 'CH4_flag_a', 'CH4_flag', 'CH4_flag_p'
]
df_mhd_csvred.columns = feature_names

In [6]:
df_mhd_csvred['type'].unique()

array(['air', 'std', 'tank', 'tank100', 'cal560', 'cal660', 'cal860',
       'cal960', 'cal1060', 'blank', 'labair', 'cal15', 'cal30', 'cal45',
       'cal60', 'cal75', 'cal90', 'cal105', 'cal120', 'cal135', 'cal150',
       'cal165', 'cal180', 'cal200', 'cal225', 'cal250', 'cal300',
       'cal500', 'cal', '-'], dtype=object)

In [7]:
real_data_mhd = df_mhd_csvred.iloc[:, :-4]

In [8]:
real_data_mhd.head(20)

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd
0,940216,142900,air,10m,G-024,3,10.0,40.00,32.27,NaN,841.9,761.10,NaN,761.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
1,940216,144900,air,10m,G-024,3,10.0,40.00,32.48,NaN,840.4,761.07,NaN,761.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
2,940216,150900,air,10m,G-024,3,10.0,40.01,32.75,NaN,839.4,760.99,NaN,760.9,109.8,2.60,190908.0,496440.0,0.63,102.0,135.4,10063.0,10029.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
3,940216,152900,air,10m,G-024,3,10.0,40.00,32.92,NaN,839.6,760.96,NaN,760.9,94.8,6.85,151667.0,1065982.0,1.02,86.2,129.0,99999.0,99999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
4,940216,180000,air,10m,G-024,3,10.0,40.00,33.31,NaN,845.4,760.72,NaN,760.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
5,940216,182000,air,10m,G-024,3,10.0,40.01,33.10,NaN,846.2,760.60,NaN,760.7,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
6,940216,184000,air,10m,G-024,3,10.0,40.01,33.20,NaN,846.3,760.57,NaN,760.5,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
7,940216,190000,air,10m,G-024,3,10.0,40.00,33.39,NaN,846.5,760.45,NaN,760.4,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
8,940216,192000,air,10m,G-024,3,10.0,40.00,33.61,NaN,846.6,760.34,NaN,760.3,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
9,940216,194000,air,10m,G-024,3,10.0,40.01,33.66,NaN,844.8,760.35,NaN,760.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
10,940216,202300,air,10m,G-024,3,10.0,40.00,33.17,NaN,846.1,759.83,NaN,760.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
11,940216,204300,air,10m,G-024,3,10.0,40.00,33.05,NaN,846.3,759.91,NaN,759.8,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
12,940216,210300,air,10m,G-024,3,10.0,40.01,33.06,NaN,846.3,759.72,NaN,759.7,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
13,940216,212400,air,10m,G-024,3,10.0,40.00,33.01,NaN,846.3,759.65,NaN,759.7,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
14,940216,214400,air,10m,G-024,3,10.0,40.00,32.94,NaN,846.1,759.62,NaN,759.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
15,940216,220400,air,10m,G-024,3,10.0,40.00,32.87,NaN,845.9,759.58,NaN,759.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
16,940216,222400,air,10m,G-024,3,10.0,40.01,32.76,NaN,845.2,759.62,NaN,759.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
17,940216,224400,air,10m,G-024,3,10.0,40.00,32.71,NaN,846.1,759.55,NaN,759.5,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
18,940216,230400,air,10m,G-024,3,10.0,40.00,32.69,NaN,844.4,759.49,NaN,759.5,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489
19,940216,232400,air,10m,G-024,3,10.0,40.00,32.65,NaN,844.9,759.25,NaN,759.3,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489

In [9]:
df_mhd_flag = df_mhd.iloc[:, -4:]
df_mhd_flag.head(20)

   CH4_flag_ht CH4_flag_a CH4_flag CH4_flag_p
0            F          F
1            F          F
2            F          F
3
4            F          F
5            F          F
6            F          F
7            F          F
8            F          F
9            F          F
10           F          F
11           F          F
12           F          F
13           F          F
14           F          F
15           F          F
16           F          F
17           F          F
18           F          F
19           F          F

In [10]:
df_mhd_flag.index = real_data_mhd.index 
real_data_mhd = pd.concat([real_data_mhd, df_mhd_flag], axis=1)

In [11]:
real_data_mhd.head(20)

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p
0,940216,142900,air,10m,G-024,3,10.0,40.00,32.27,NaN,841.9,761.10,NaN,761.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
1,940216,144900,air,10m,G-024,3,10.0,40.00,32.48,NaN,840.4,761.07,NaN,761.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
2,940216,150900,air,10m,G-024,3,10.0,40.01,32.75,NaN,839.4,760.99,NaN,760.9,109.8,2.60,190908.0,496440.0,0.63,102.0,135.4,10063.0,10029.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
3,940216,152900,air,10m,G-024,3,10.0,40.00,32.92,NaN,839.6,760.96,NaN,760.9,94.8,6.85,151667.0,1065982.0,1.02,86.2,129.0,99999.0,99999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,,,,
4,940216,180000,air,10m,G-024,3,10.0,40.00,33.31,NaN,845.4,760.72,NaN,760.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
5,940216,182000,air,10m,G-024,3,10.0,40.01,33.10,NaN,846.2,760.60,NaN,760.7,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
6,940216,184000,air,10m,G-024,3,10.0,40.01,33.20,NaN,846.3,760.57,NaN,760.5,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
7,940216,190000,air,10m,G-024,3,10.0,40.00,33.39,NaN,846.5,760.45,NaN,760.4,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
8,940216,192000,air,10m,G-024,3,10.0,40.00,33.61,NaN,846.6,760.34,NaN,760.3,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
9,940216,194000,air,10m,G-024,3,10.0,40.01,33.66,NaN,844.8,760.35,NaN,760.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
10,940216,202300,air,10m,G-024,3,10.0,40.00,33.17,NaN,846.1,759.83,NaN,760.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
11,940216,204300,air,10m,G-024,3,10.0,40.00,33.05,NaN,846.3,759.91,NaN,759.8,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
12,940216,210300,air,10m,G-024,3,10.0,40.01,33.06,NaN,846.3,759.72,NaN,759.7,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
13,940216,212400,air,10m,G-024,3,10.0,40.00,33.01,NaN,846.3,759.65,NaN,759.7,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
14,940216,214400,air,10m,G-024,3,10.0,40.00,32.94,NaN,846.1,759.62,NaN,759.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
15,940216,220400,air,10m,G-024,3,10.0,40.00,32.87,NaN,845.9,759.58,NaN,759.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
16,940216,222400,air,10m,G-024,3,10.0,40.01,32.76,NaN,845.2,759.62,NaN,759.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
17,940216,224400,air,10m,G-024,3,10.0,40.00,32.71,NaN,846.1,759.55,NaN,759.5,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
18,940216,230400,air,10m,G-024,3,10.0,40.00,32.69,NaN,844.4,759.49,NaN,759.5,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
19,940216,232400,air,10m,G-024,3,10.0,40.00,32.65,NaN,844.9,759.25,NaN,759.3,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,

In [12]:
real_data_mhd.iloc[[185]]

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p
185,940219,102700,cal1060,G-024,G-024,1,0.0,40.01,23.16,NaN,846.8,1058.3,NaN,751.2,95.2,7.51,205489.0,1651923.0,1.0,82.6,130.2,30872.0,30727.0,0.92736,1.00177,0.92736,1.3073,1.4122,1.0901,0.92736,1.00177,0.92736,1569.54,1695.49,1692.49,3.18,NaN,1692.489,,,,

In [13]:
real_data_mhd.tail(20)

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p
817935,260518,15200,air,9m,J-286,1,9.0,40.0,22.26,NaN,809.6,752.85,NaN,752.8,113.2,9.18,197243.0,2001935.0,1.05,98.2,155.8,40780.0,42701.0,1.00339,1.00870,1.00870,1.0034,1.0087,1.0048,1.00339,1.00870,1.00870,2022.75,2033.45,2033.45,3.637,3.669,2015.923,,,A,
817936,260518,21200,std,J-286,J-286,3,0.0,40.0,22.16,NaN,813.9,752.79,NaN,752.8,114.4,9.20,196511.0,2002566.0,1.13,99.6,157.4,42026.0,43238.0,1.01184,0.99099,0.99099,1.0119,0.9910,0.9827,1.01184,0.99099,0.99099,2039.79,1997.77,1997.77,3.652,NaN,2015.923,,,A,
817937,260518,23200,air,9m,J-286,1,9.0,40.0,22.12,NaN,810.1,752.81,NaN,752.8,114.8,9.23,196801.0,2010329.0,1.06,99.8,158.0,42408.0,43352.0,1.01358,0.98600,NaN,1.0138,0.9862,0.9794,1.01358,0.98600,NaN,2043.30,1987.70,NaN,3.652,NaN,2015.923,*,*,A,
817938,260518,25200,std,J-286,J-286,3,0.0,40.0,22.25,NaN,813.7,752.55,NaN,752.5,119.8,9.66,191747.0,2074401.0,1.14,104.6,163.8,47450.0,47746.0,0.99568,1.01543,1.01543,0.9956,1.0153,1.0141,0.99568,1.01543,1.01543,2007.22,2047.02,2047.02,3.619,NaN,2015.923,,,A,
817939,260518,31200,air,9m,J-286,1,9.0,40.0,22.29,NaN,809.4,752.55,NaN,752.7,118.0,9.48,194562.0,2051993.0,1.07,102.8,161.4,45678.0,46131.0,1.02278,0.98695,NaN,1.0228,0.9870,0.9721,1.02278,0.98695,NaN,2061.85,1989.62,NaN,3.619,NaN,2015.923,*,*,A,
817940,260518,33200,std,J-286,J-286,3,0.0,40.0,22.22,NaN,813.7,752.45,NaN,752.6,123.0,9.85,188684.0,2083568.0,1.06,107.4,167.0,50407.0,50450.0,1.00494,1.00229,1.00229,1.0048,1.0022,0.9982,1.00494,1.00229,1.00229,2025.88,2020.55,2020.55,3.619,NaN,2015.923,,,A,
817941,260518,35200,air,9m,J-286,1,9.0,40.0,22.02,NaN,809.1,752.43,NaN,752.5,121.2,9.70,191559.0,2078579.0,1.12,106.0,165.0,48891.0,48854.0,1.02860,0.99765,NaN,1.0285,0.9976,0.9741,1.02860,0.99765,NaN,2073.57,2011.19,NaN,3.451,NaN,2015.923,*,*,A,
817942,260518,41200,std,J-286,J-286,3,0.0,40.0,22.35,NaN,813.5,752.49,NaN,752.5,125.8,10.07,183801.0,2083586.0,1.09,110.0,170.4,52965.0,52830.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.451,NaN,2015.923,,,A,
817943,260518,43200,air,9m,J-286,1,9.0,40.0,22.05,NaN,808.8,752.36,NaN,752.2,125.4,10.07,186644.0,2113592.0,1.05,109.6,169.6,52684.0,52367.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.417,NaN,2015.923,,,A,
817944,260518,45200,std,J-286,J-286,3,0.0,40.0,22.44,NaN,813.3,752.23,NaN,752.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.479,NaN,2015.923,,,A,
817945,260518,51200,air,9m,J-286,1,9.0,40.0,22.20,NaN,808.8,752.26,NaN,752.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.479,NaN,2015.923,,,A,
817946,260518,53300,std,J-286,J-286,3,0.0,40.0,22.62,NaN,813.0,752.25,NaN,752.3,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.545,NaN,2015.923,,,A,
817947,260518,55300,air,9m,J-286,1,9.0,40.0,22.20,NaN,808.5,752.24,NaN,752.2,76.8,0.00,0.0,0.0,0.53,73.0,98.6,99999.0,60611.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.545,NaN,2015.923,,,A,
817948,260518,61300,std,J-286,J-286,3,0.0,40.0,22.17,NaN,813.4,752.25,NaN,752.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.611,NaN,2015.923,,,A,
817949,260518,63300,air,9m,J-286,1,9.0,40.0,22.25,NaN,808.6,752.26,NaN,752.5,78.0,4.06,137477.0,182060.0,0.47,73.0,100.2,99999.0,62502.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.611,NaN,2015.923,,,A,
817950,260518,65300,std,J-286,J-286,3,0.0,40.0,22.06,NaN,813.5,752.32,NaN,752.4,77.8,3.98,133194.0,131007.0,0.50,73.0,99.8,99999.0,62297.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.649,NaN,2015.923,,,A,
817951,260518,71300,air,9m,J-286,1,9.0,40.0,22.32,NaN,808.6,752.28,NaN,752.2,79.0,4.57,160607.0,508996.0,0.46,73.0,102.0,99999.0,64464.0,1.02271,1.00491,1.00491,1.0227,1.0049,0.9981,1.02271,1.00491,1.00491,2061.71,2025.82,2025.82,3.649,3.666,2015.923,,,A,
817952,260518,73300,std,J-286,J-286,3,0.0,40.0,22.19,NaN,813.1,752.27,NaN,752.4,80.6,5.17,180892.0,882007.0,0.47,73.0,109.2,84204.0,66307.0,1.07106,1.34773,1.34773,1.0712,1.3480,1.0953,1.07106,1.34773,1.34773,2159.17,2716.92,2716.92,4.605,NaN,2015.923,,,A,
817953,260518,75300,air,9m,J-286,1,9.0,40.0,22.10,NaN,808.2,752.13,NaN,752.2,80.4,5.01,186959.0,856303.0,0.41,73.0,106.6,87769.0,65923.0,0.97017,0.83156,NaN,0.9701,0.8315,0.9433,0.97017,0.83156,NaN,1955.78,1676.37,NaN,4.605,NaN,2015.923,*,*,A,
817954,260518,81300,std,J-286,J-286,3,0.0,40.0,22.23,NaN,813.3,752.09,NaN,752.0,82.0,5.46,204547.0,1177596.0,0.43,73.0,115.2,75876.0,68601.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.873,NaN,2015.923,,,A,

In [14]:
real_data_mhd.iloc[[28373]]

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p
28373,950404,111600,tank,H-006,G-032,5,0.0,39.99,20.35,NaN,848.6,761.75,NaN,761.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.682,NaN,1679.840,,,,

In [15]:
real_data_mhd['type'].unique()

array(['air', 'std', 'tank', 'tank100', 'cal560', 'cal660', 'cal860',
       'cal960', 'cal1060', 'blank', 'labair', 'cal15', 'cal30', 'cal45',
       'cal60', 'cal75', 'cal90', 'cal105', 'cal120', 'cal135', 'cal150',
       'cal165', 'cal180', 'cal200', 'cal225', 'cal250', 'cal300',
       'cal500', 'cal', '-'], dtype=object)

In [16]:
real_data_mhd.to_csv("../data/processed/mhd_ch4_formatted_v1.csv", index=False)

In [17]:
data = pd.read_csv("../data/processed/mhd_ch4_formatted_v1.csv", keep_default_na=False)
data['type'].unique()

/tmp/ipykernel_929/3060876692.py:1: DtypeWarning: Columns (7,8,10,11,13,14,15,16,17,18,19,20,21,22,35,37) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("../data/processed/mhd_ch4_formatted_v1.csv", keep_default_na=False)

array(['air', 'std', 'tank', 'tank100', 'cal560', 'cal660', 'cal860',
       'cal960', 'cal1060', 'blank', 'labair', 'cal15', 'cal30', 'cal45',
       'cal60', 'cal75', 'cal90', 'cal105', 'cal120', 'cal135', 'cal150',
       'cal165', 'cal180', 'cal200', 'cal225', 'cal250', 'cal300',
       'cal500', 'cal', '-'], dtype=object)

In [20]:
data[data['sample']=='dynamic']

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p
380175,90224,94200,tank,dynamic,J-116,9,0.0,40.0,20.48,,801.2,768.51,,768.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,0.0,0.0,0.0,0.0,0.0,,0.0,0.0,,3.588,,1888.518,F,F,,
380177,90224,95200,tank,dynamic,J-116,9,0.0,40.0,20.49,,810.5,768.53,,768.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,0.0,0.0,0.0,0.0,0.0,,0.0,0.0,,3.573,,1888.518,F,F,,
380179,90224,100200,tank,dynamic,J-116,9,0.0,39.99,20.49,,802.2,768.57,,768.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,0.0,0.0,0.0,0.0,0.0,,0.0,0.0,,3.57,,1888.518,F,F,,
380181,90224,101200,tank,dynamic,J-116,9,0.0,39.99,20.28,,794.5,768.62,,768.7,98.8,8.34,42373.0,387982.0,1.05,85.0,137.0,27157.0,27257.0,0.26525,0.26496,0.26525,0.2653,0.265,0.9989,0.26525,0.26496,0.26525,500.92,500.38,500.92,3.57,,1888.518,,,,
380183,90224,102200,tank,dynamic,J-116,9,0.0,39.99,20.42,,811.0,768.64,,768.5,98.8,8.31,42377.0,387030.0,1.07,85.0,137.0,26984.0,27134.0,0.26534,0.26506,0.26534,0.2653,0.2651,0.9977,0.26534,0.26506,0.26534,501.11,500.58,501.11,3.57,,1888.518,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475105,121101,122500,blank,dynamic,J-151,7,0.0,40.0,20.37,,729.8,729.7,,729.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,,,,,,,,,,,,,,1873.252,,,,
477235,121201,122500,blank,dynamic,J-151,7,0.0,40.0,20.2,,762.5,762.64,,762.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.267,,1873.252,,,,
479436,130101,122500,blank,dynamic,J-151,7,0.0,40.0,19.58,,756.4,756.32,,756.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,0.0,0.0,0.0,0.0,0.0,,0.0,0.0,,2.574,,1873.252,F,F,,
481657,130201,123600,blank,dynamic,J-151,7,0.0,40.0,19.82,,750.3,750.38,,750.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,0.0,0.0,0.0,0.0,0.0,,0.0,0.0,,2.329,,1873.252,F,F,,
483643,130301,125100,blank,dynamic,J-158,7,0.0,40.0,19.28,,772.2,772.1,,772.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.962,,1873.197,,,,

### tac_ch4.txt file

In [ ]:
import pandas as pd

file_path = "../data/raw/tac_ch4.txt"

df_tac = pd.read_csv(file_path, skiprows=1, sep=r'\s+', header=1) 
# skip first row, txt is space seperated

In [ ]:
df_tac.info()

In [ ]:
df_tac['C'].head(20)

In [ ]:
import numpy as np

def split_flag (val):
    if pd.isna(val):
        return np.nan, np.nan
    
    val_str = str(val).strip()
    # check if last val is a character(Flag)
    if val_str[-1].isalpha() or val_str[-1] == '*':
        c_val = float(val_str[:-1])
        flag_val = val_str[-1]
    else:
        c_val = float(val_str) # normal value, then direcly convert to float
        flag_val = " " # no flag, give it a space
    
    return c_val, flag_val

In [ ]:
df_tac['C'], df_tac['ch4_flag'] = zip(*df_tac['C'].map(split_flag))

print(df_tac[['C', 'ch4_flag']].head(20))
df_tac['C']

In [ ]:
df_tac.head(20)

In [ ]:
feature_name_tacch4 = [
  'date', 'time', 'type', 'sample', 'standard', 'port', 
 'ch4_dry', 'ch4_wet', 'ch4_stdev', 'ch4_std_rep', 'ch4_std_stdev',
  'ch4_target_error','ch4_Cdrift', 'ch4_C', 'ch4_N', 'ch4_Nfiltered',
  'cycle_time', 'h2o', 'h2o_stdev', 'cavity_press', 'cavity_press_stdev', 
  'cavity_temp', 'cavity_temp_stdev', 'das_temp', 'etalon_temp', 
  'warmbox_temp', 'outlet_valve','ch4_flag'
]

In [ ]:
df_tac.columns = feature_name_tacch4

In [ ]:
df_tac.head(20)

In [ ]:
df_tac.to_csv("../data/processed/tac_ch4_formatted_v1.csv", index=False)

In [ ]:
df_tac.iloc[[244665]]

In [ ]:
df_tac.tail(5)

In [ ]:
import pandas as pd

file_path = "../data/raw/tac_co2.txt"

df_taco2 = pd.read_csv(file_path, skiprows=1, sep=r'\s+', header=1) # skip first row, txt is space seperated

In [ ]:
df_taco2.head(20)

In [ ]:
df_taco2['C']

In [ ]:
df_taco2['C'], df_taco2['co2_flag'] = zip(*df_taco2['C'].map(split_flag))

print(df_taco2[['C', 'co2_flag']].head(20))
df_taco2['C']

In [ ]:
df_taco2.columns.tolist()

In [ ]:
feature_name_tacco2 = [
  'date', 'time', 'type', 'sample', 'standard', 'port', 
 'co2_dry', 'co2_wet', 'co2_stdev', 'co2_std_rep', 'co2_std_stdev',
  'co2_target_error','co2_Cdrift', 'co2_C', 'co2_N', 'co2_Nfiltered',
  'cycle_time', 'h2o', 'h2o_stdev', 'cavity_press', 'cavity_press_stdev', 
  'cavity_temp', 'cavity_temp_stdev', 'das_temp', 'etalon_temp', 
  'warmbox_temp', 'outlet_valve','co2_flag'
]

In [ ]:
df_taco2.columns = feature_name_tacco2
df_taco2.head(20)

In [ ]:
df_taco2.to_csv("../data/processed/tac_co2_formatted_v1.csv", index=False)