In [5]:
from data_convert import GCMDprocessor,TSFE
import pandas as pd
import numpy as np
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_columns", 100)
#=================
uploaded_file = '../data/test.txt'

In [7]:
processor = GCMDprocessor(uploaded_file)
df = processor._parse_file()
df.head()

,date,time,type,sample,standard,port,inlet_ht,tmod,tamb,temp,pflow,psamp,ploop,pamb,rt,w,ht,area,skew,start_time,end_time,start_level,end_level,Rl_ht,Rl_a,Rl,norm_ht,norm_a,norm_w,R_ht,R_a,R,C_ht,C_a,C,std_stdev,std_rep,Cstd,flag_ht,flag_a,flag,flag_p
datetime,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1994-02-16 14:29:00,940216,142900,air,10m,G-024,3,10,40.00,32.27,NaN,841.9,761.10,NaN,761.1,0.0,0.00,0,0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
1994-02-16 14:49:00,940216,144900,air,10m,G-024,3,10,40.00,32.48,NaN,840.4,761.07,NaN,761.2,0.0,0.00,0,0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
1994-02-16 15:09:00,940216,150900,air,10m,G-024,3,10,40.01,32.75,NaN,839.4,760.99,NaN,760.9,109.8,2.60,190908,496440,0.63,102.0,135.4,10063.0,10029.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN
1994-02-16 15:29:00,940216,152900,air,10m,G-024,3,10,40.00,32.92,NaN,839.6,760.96,NaN,760.9,94.8,6.85,151667,1065982,1.02,86.2,129.0,99999.0,99999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,,,NaN,NaN
1994-02-16 18:00:00,940216,180000,air,10m,G-024,3,10,40.00,33.31,NaN,845.4,760.72,NaN,760.6,0.0,0.00,0,0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 497 entries, 1994-02-16 14:29:00 to 1994-02-23 19:36:00
Data columns (total 42 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         497 non-null    object
 1   time         497 non-null    object
 2   type         497 non-null    object
 3   sample       497 non-null    object
 4   standard     497 non-null    object
 5   port         497 non-null    int64
 6   inlet_ht     497 non-null    int64
 7   tmod         496 non-null    float64
 8   tamb         496 non-null    float64
 9   temp         0 non-null      float64
 10  pflow        497 non-null    float64
 11  psamp        497 non-null    float64
 12  ploop        0 non-null      float64
 13  pamb         497 non-null    float64
 14  rt           497 non-null    float64
 15  w            497 non-null    float64
 16  ht           497 non-null    int64
 17  area         497 non-null    int64
 18  skew         497 non-null    float64
 19  start_time   497 non-null    float64
 20  end_time     497 non-null    float64
 21  start_level  497 non-null    float64
 22  end_level    497 non-null    float64
 23  Rl_ht        402 non-null    float64
 24  Rl_a         403 non-null    float64
 25  Rl           401 non-null    float64
 26  norm_ht      402 non-null    float64
 27  norm_a       402 non-null    float64
 28  norm_w       402 non-null    float64
 29  R_ht         402 non-null    float64
 30  R_a          403 non-null    float64
 31  R            401 non-null    float64
 32  C_ht         402 non-null    float64
 33  C_a          403 non-null    float64
 34  C            401 non-null    float64
 35  std_stdev    467 non-null    float64
 36  std_rep      180 non-null    float64
 37  Cstd         497 non-null    float64
 38  flag_ht      497 non-null    object
 39  flag_a       497 non-null    object
 40  flag         0 non-null      float64
 41  flag_p       0 non-null      float64
dtypes: float64(31), int64(4), object(7)
memory usage: 167.0+ KB

In [9]:
df.columns

Index(['date', 'time', 'type', 'sample', 'standard', 'port', 'inlet_ht',
       'tmod', 'tamb', 'temp', 'pflow', 'psamp', 'ploop', 'pamb', 'rt', 'w',
       'ht', 'area', 'skew', 'start_time', 'end_time', 'start_level',
       'end_level', 'Rl_ht', 'Rl_a', 'Rl', 'norm_ht', 'norm_a', 'norm_w',
       'R_ht', 'R_a', 'R', 'C_ht', 'C_a', 'C', 'std_stdev', 'std_rep', 'Cstd',
       'flag_ht', 'flag_a', 'flag', 'flag_p'],
      dtype='object')

In [ ]:
target = 'label_c_nan'
#建立isc_nan label
df['label_c_nan'] = df['C'].isna().astype(int)
#只取用type = air 或是std的
df = df[((df['type'] == 'air')|(df['type']=='std'))].copy() #只用std和 air的值所以數量會變
print("df passed 1 step!")

df passed 1 step!

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 469 entries, 1994-02-16 14:29:00 to 1994-02-23 19:36:00
Data columns (total 63 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   date                           469 non-null    object
 1   time                           469 non-null    object
 2   type                           469 non-null    object
 3   sample                         469 non-null    object
 4   standard                       469 non-null    object
 5   port                           469 non-null    int64
 6   inlet_ht                       469 non-null    int64
 7   tmod                           468 non-null    float64
 8   tamb                           468 non-null    float64
 9   temp                           0 non-null      float64
 10  pflow                          469 non-null    float64
 11  psamp                          469 non-null    float64
 12  ploop                          0 non-null      float64
 13  pamb                           469 non-null    float64
 14  rt                             469 non-null    float64
 15  w                              469 non-null    float64
 16  ht                             469 non-null    int64
 17  area                           469 non-null    int64
 18  skew                           469 non-null    float64
 19  start_time                     469 non-null    float64
 20  end_time                       469 non-null    float64
 21  start_level                    469 non-null    float64
 22  end_level                      469 non-null    float64
 23  Rl_ht                          374 non-null    float64
 24  Rl_a                           375 non-null    float64
 25  Rl                             373 non-null    float64
 26  norm_ht                        374 non-null    float64
 27  norm_a                         374 non-null    float64
 28  norm_w                         374 non-null    float64
 29  R_ht                           374 non-null    float64
 30  R_a                            375 non-null    float64
 31  R                              373 non-null    float64
 32  C_ht                           374 non-null    float64
 33  C_a                            375 non-null    float64
 34  C                              373 non-null    float64
 35  std_stdev                      439 non-null    float64
 36  std_rep                        180 non-null    float64
 37  Cstd                           469 non-null    float64
 38  flag_ht                        469 non-null    object
 39  flag_a                         469 non-null    object
 40  flag                           0 non-null      float64
 41  flag_p                         0 non-null      float64
 42  label_c_nan                    469 non-null    int64
 43  last_std_ht                    469 non-null    float64
 44  last_air_ht                    469 non-null    float64
 45  last_std_area                  469 non-null    float64
 46  last_air_area                  469 non-null    float64
 47  last_std_rt                    469 non-null    float64
 48  last_air_rt                    469 non-null    float64
 49  last_std_start_level           469 non-null    float64
 50  last_air_start_level           469 non-null    float64
 51  ht_to_last_std_ratio           469 non-null    float64
 52  ht_to_last_air_ratio           469 non-null    float64
 53  area_to_last_std_ratio         469 non-null    float64
 54  area_to_last_air_ratio         469 non-null    float64
 55  rt_to_last_std_ratio           469 non-null    float64
 56  rt_to_last_air_ratio           469 non-null    float64
 57  start_level_to_last_std_ratio  469 non-null    float64
 58  start_level_to_last_air_ratio  469 non-null    float64
 59  duration_rt_ratio              420 non-null    float64
 60  rt_position                    420 non-null    float64
 61  baseline_slope                 420 non-null    float64
 62  level_area_ratio               469 non-null    float64
dtypes: float64(51), int64(5), object(7)
memory usage: 234.5+ KB

In [11]:
df.head()

,date,time,type,sample,standard,port,inlet_ht,tmod,tamb,temp,pflow,psamp,ploop,pamb,rt,w,ht,area,skew,start_time,end_time,start_level,end_level,Rl_ht,Rl_a,Rl,norm_ht,norm_a,norm_w,R_ht,R_a,R,C_ht,C_a,C,std_stdev,std_rep,Cstd,flag_ht,flag_a,flag,flag_p,label_c_nan
datetime,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1994-02-16 14:29:00,940216,142900,air,10m,G-024,3,10,40.00,32.27,NaN,841.9,761.10,NaN,761.1,0.0,0.00,0,0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN,1
1994-02-16 14:49:00,940216,144900,air,10m,G-024,3,10,40.00,32.48,NaN,840.4,761.07,NaN,761.2,0.0,0.00,0,0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN,1
1994-02-16 15:09:00,940216,150900,air,10m,G-024,3,10,40.01,32.75,NaN,839.4,760.99,NaN,760.9,109.8,2.60,190908,496440,0.63,102.0,135.4,10063.0,10029.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN,1
1994-02-16 15:29:00,940216,152900,air,10m,G-024,3,10,40.00,32.92,NaN,839.6,760.96,NaN,760.9,94.8,6.85,151667,1065982,1.02,86.2,129.0,99999.0,99999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,,,NaN,NaN,1
1994-02-16 18:00:00,940216,180000,air,10m,G-024,3,10,40.00,33.31,NaN,845.4,760.72,NaN,760.6,0.0,0.00,0,0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN,1

In [12]:
#========
target_cols = ['ht', 'area', 'rt', 'start_level']

for col in target_cols:
    for t_type in ['std', 'air']:
        type_median = df.loc[df['type'] == t_type, col].median()

        only_series = df[col].where(df['type']==t_type)
        df[f'last_{t_type}_{col}'] = only_series.ffill().shift(1).fillna(type_median)

for col in ['ht', 'area', 'rt', 'start_level']:
    df[f'{col}_to_last_std_ratio'] = df[col] / (df[f'last_std_{col}'] + 1e-7)
    df[f'{col}_to_last_air_ratio'] = df[col] / (df[f'last_air_{col}'] + 1e-7)

df['duration_rt_ratio'] = (df['end_time'] -df['start_time'])/df['rt']
df['rt_position'] = (df['rt'] - df['start_time']) / df['w']
df['baseline_slope'] =(df['end_level'] -df['start_level'])/df['w']
df['level_area_ratio'] = np.maximum(df['end_level'],df['start_level'] )/(df['area']+1e-7)

In [13]:
df.head()

,date,time,type,sample,standard,port,inlet_ht,tmod,tamb,temp,pflow,psamp,ploop,pamb,rt,w,ht,area,skew,start_time,end_time,start_level,end_level,Rl_ht,Rl_a,Rl,norm_ht,norm_a,norm_w,R_ht,R_a,R,C_ht,C_a,C,std_stdev,std_rep,Cstd,flag_ht,flag_a,flag,flag_p,label_c_nan,last_std_ht,last_air_ht,last_std_area,last_air_area,last_std_rt,last_air_rt,last_std_start_level,last_air_start_level,ht_to_last_std_ratio,ht_to_last_air_ratio,area_to_last_std_ratio,area_to_last_air_ratio,rt_to_last_std_ratio,rt_to_last_air_ratio,start_level_to_last_std_ratio,start_level_to_last_air_ratio,duration_rt_ratio,rt_position,baseline_slope,level_area_ratio
datetime,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1994-02-16 14:29:00,940216,142900,air,10m,G-024,3,10,40.00,32.27,NaN,841.9,761.10,NaN,761.1,0.0,0.00,0,0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN,1,157028.0,173910.5,1177322.0,1291400.0,95.0,94.8,29192.0,27985.5,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,NaN,NaN,0.000000
1994-02-16 14:49:00,940216,144900,air,10m,G-024,3,10,40.00,32.48,NaN,840.4,761.07,NaN,761.2,0.0,0.00,0,0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN,1,157028.0,0.0,1177322.0,0.0,95.0,0.0,29192.0,0.0,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,NaN,NaN,0.000000
1994-02-16 15:09:00,940216,150900,air,10m,G-024,3,10,40.01,32.75,NaN,839.4,760.99,NaN,760.9,109.8,2.60,190908,496440,0.63,102.0,135.4,10063.0,10029.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN,1,157028.0,0.0,1177322.0,0.0,95.0,0.0,29192.0,0.0,1.215758,1.909080e+12,0.421669,4.964400e+12,1.155789,1.098000e+09,0.344718,1.006300e+11,0.304189,3.000000,-13.076923,0.020270
1994-02-16 15:29:00,940216,152900,air,10m,G-024,3,10,40.00,32.92,NaN,839.6,760.96,NaN,760.9,94.8,6.85,151667,1065982,1.02,86.2,129.0,99999.0,99999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,,,NaN,NaN,1,157028.0,190908.0,1177322.0,496440.0,95.0,109.8,29192.0,10063.0,0.965860,7.944507e-01,0.905429,2.147252e+00,0.997895,8.633880e-01,3.425562,9.937295e+00,0.451477,1.255474,0.000000,0.093809
1994-02-16 18:00:00,940216,180000,air,10m,G-024,3,10,40.00,33.31,NaN,845.4,760.72,NaN,760.6,0.0,0.00,0,0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,NaN,NaN,1,157028.0,151667.0,1177322.0,1065982.0,95.0,94.8,29192.0,99999.0,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,NaN,NaN,NaN,0.000000

In [14]:
df.columns

Index(['date', 'time', 'type', 'sample', 'standard', 'port', 'inlet_ht',
       'tmod', 'tamb', 'temp', 'pflow', 'psamp', 'ploop', 'pamb', 'rt', 'w',
       'ht', 'area', 'skew', 'start_time', 'end_time', 'start_level',
       'end_level', 'Rl_ht', 'Rl_a', 'Rl', 'norm_ht', 'norm_a', 'norm_w',
       'R_ht', 'R_a', 'R', 'C_ht', 'C_a', 'C', 'std_stdev', 'std_rep', 'Cstd',
       'flag_ht', 'flag_a', 'flag', 'flag_p', 'label_c_nan', 'last_std_ht',
       'last_air_ht', 'last_std_area', 'last_air_area', 'last_std_rt',
       'last_air_rt', 'last_std_start_level', 'last_air_start_level',
       'ht_to_last_std_ratio', 'ht_to_last_air_ratio',
       'area_to_last_std_ratio', 'area_to_last_air_ratio',
       'rt_to_last_std_ratio', 'rt_to_last_air_ratio',
       'start_level_to_last_std_ratio', 'start_level_to_last_air_ratio',
       'duration_rt_ratio', 'rt_position', 'baseline_slope',
       'level_area_ratio'],
      dtype='object')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 469 entries, 1994-02-16 14:29:00 to 1994-02-23 19:36:00
Data columns (total 63 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   date                           469 non-null    object
 1   time                           469 non-null    object
 2   type                           469 non-null    object
 3   sample                         469 non-null    object
 4   standard                       469 non-null    object
 5   port                           469 non-null    int64
 6   inlet_ht                       469 non-null    int64
 7   tmod                           468 non-null    float64
 8   tamb                           468 non-null    float64
 9   temp                           0 non-null      float64
 10  pflow                          469 non-null    float64
 11  psamp                          469 non-null    float64
 12  ploop                          0 non-null      float64
 13  pamb                           469 non-null    float64
 14  rt                             469 non-null    float64
 15  w                              469 non-null    float64
 16  ht                             469 non-null    int64
 17  area                           469 non-null    int64
 18  skew                           469 non-null    float64
 19  start_time                     469 non-null    float64
 20  end_time                       469 non-null    float64
 21  start_level                    469 non-null    float64
 22  end_level                      469 non-null    float64
 23  Rl_ht                          374 non-null    float64
 24  Rl_a                           375 non-null    float64
 25  Rl                             373 non-null    float64
 26  norm_ht                        374 non-null    float64
 27  norm_a                         374 non-null    float64
 28  norm_w                         374 non-null    float64
 29  R_ht                           374 non-null    float64
 30  R_a                            375 non-null    float64
 31  R                              373 non-null    float64
 32  C_ht                           374 non-null    float64
 33  C_a                            375 non-null    float64
 34  C                              373 non-null    float64
 35  std_stdev                      439 non-null    float64
 36  std_rep                        180 non-null    float64
 37  Cstd                           469 non-null    float64
 38  flag_ht                        469 non-null    object
 39  flag_a                         469 non-null    object
 40  flag                           0 non-null      float64
 41  flag_p                         0 non-null      float64
 42  label_c_nan                    469 non-null    int64
 43  last_std_ht                    469 non-null    float64
 44  last_air_ht                    469 non-null    float64
 45  last_std_area                  469 non-null    float64
 46  last_air_area                  469 non-null    float64
 47  last_std_rt                    469 non-null    float64
 48  last_air_rt                    469 non-null    float64
 49  last_std_start_level           469 non-null    float64
 50  last_air_start_level           469 non-null    float64
 51  ht_to_last_std_ratio           469 non-null    float64
 52  ht_to_last_air_ratio           469 non-null    float64
 53  area_to_last_std_ratio         469 non-null    float64
 54  area_to_last_air_ratio         469 non-null    float64
 55  rt_to_last_std_ratio           469 non-null    float64
 56  rt_to_last_air_ratio           469 non-null    float64
 57  start_level_to_last_std_ratio  469 non-null    float64
 58  start_level_to_last_air_ratio  469 non-null    float64
 59  duration_rt_ratio              420 non-null    float64
 60  rt_position                    420 non-null    float64
 61  baseline_slope                 420 non-null    float64
 62  level_area_ratio               469 non-null    float64
dtypes: float64(51), int64(5), object(7)
memory usage: 234.5+ KB

In [9]:
feature_cols= [#'datetime', 
  #'tamb',  'pamb' ,
  #'psamp',
  'pflow', 'tmod',  'rt', 'w',
    'ht', 'area', 'skew', 'start_time', 'end_time',
    'start_level', 'end_level', #'duration', 
    'last_std_ht','last_air_ht','last_std_area','last_air_area','last_std_rt','last_air_rt',
    'last_std_start_level','last_air_start_level','ht_to_last_std_ratio','ht_to_last_air_ratio',
    'area_to_last_std_ratio','area_to_last_air_ratio','rt_to_last_std_ratio','rt_to_last_air_ratio',
    'start_level_to_last_std_ratio','start_level_to_last_air_ratio','duration_rt_ratio',
    'rt_position','baseline_slope','level_area_ratio'
]
#=====================
feature_config ={
    'diff':{'cols': ['area', 
                    'ht','w' , 'rt' #'tmod',#'end_time','start_time',,'rt'
                ], 'periods':[1, 3, 6, 72]},

    'lag':{'cols':['area', 'rt',  'ht', #'tmod',  'psamp','pamb','tamb',,'skew'
                'pflow',
              'w'], 'periods':[1, 3, 6, 72]},
    'diff_cross':{'cols':[['ht', 'ht_lag_72'],
            ['area', 'area_lag_72'],
            ['end_time', 'start_time'],
        # ['w_roll_mean_2h', 'w_roll_mean_7h'],
          ['end_level', 'start_level'],
          ['rt', 'pflow'],
          #['ht', 'ht_lag_72'],['w', 'w_lag_72'],
          #['pflow', 'pflow_lag_1'],['skew','skew_lag_1']
          ]}, 


    'roll_std':{'cols': ['w', 'ht','area', 'end_time_start_time_diff_cross'], 'period':['1h','3h','6h', '24h', '3D', '7D']},
    
    'roll_mean_percent_res':{'cols':['rt' ,
                              'w', 'ht','area',], 'period': ['1h','3h','6h','24h', '3D', '7D']},
    
        #'log':{'cols':['last_std_ht','last_air_ht'
                   #'end_time', 
     #              ]},

    'relative_per': {'cols': ['w', 'ht'], 'period':['2h','7h']},

    'per_rank': {'cols': ['w', 'skew','ht'], 'period':['7D']},

    #=============================================

    



     'roll_median':{'cols':['rt' ,
                             'w', 'ht','area', 'pflow','area_lag_72','ht_lag_72'], 'period':['1h','3h','6h', '24h', '3D', '7D']},
     'roll_mad':{'cols':['rt' ,
                             'w', 'ht','area', 'pflow'], 'period':['1h','3h','6h', '24h', '3D', '7D']},
     'roll_median_percent_res':{'cols':['rt' ,
                             'w', 'ht','area','pflow','area_lag_72','ht_lag_72'],
                              'period':['1h','3h','6h', '24h', '3D', '7D']},

   # 'multi':{'cols':[['w', 'ht'],['area', 'pflow']]},

    'ratio':{'cols':[   ['skew','w'],
                        ['ht', 'pflow'],
                        ['ht', 'w'],
                        ['area', 'pflow'],
                        ['rt', 'pflow'],
                        ['ht', 'area'],
                        ['w', 'end_time_start_time_diff_cross'],
                       # ['rt', 'end_time_start_time_diff_cross'],

                       # ['ht', 'last_air_ht'],
                        #['w_roll_std_2h', 'w_roll_std_1D'],
                      
                        ['start_level', 'end_level'],
                  
                        ['w_roll_std_3h', 'w_roll_mean_3h'], ['ht_roll_std_3h', 'ht_roll_mean_3h'],['area_roll_std_3h', 'area_roll_mean_3h'],
                        ['w_roll_std_24h', 'w_roll_mean_24h'], ['ht_roll_std_24h', 'ht_roll_mean_24h'],['area_roll_std_24h', 'area_roll_mean_24h'],
                        #['w_roll_std_6h', 'w_roll_mean_6h'], ['ht_roll_std_6h', 'ht_roll_mean_6h'],['area_roll_std_6h', 'area_roll_mean_6h'],
                        #['ht_roll_std_24h', 'ht_roll_mean_24h']
                       # ['w_roll_std_7h', 'w_roll_mean_7h'],['ht_roll_std_7h', 'ht_roll_mean_7h'],
                        #['w_roll_std_2D', 'w_roll_mean_2D'],['ht_roll_std_2D', 'ht_roll_mean_2D'],
                        #['rt', 'last_std_rt'],
                        
                       #['end_time', 'start_time'], ['area', 'pflow'],  ['skew', 'w'],['w', 'ht']
                       ]}, 


    'per_change':{'cols':[['ht_diff_1', 'ht_lag_1']]},

    'Z_score_res':{'cols':[['w', 'w_roll_mean_3h', 'w_roll_std_3h', '3h'], #['end_time', 'end_time_roll_mean_7D', 'end_time_roll_std_7D', '7D']
                           ]},



}

In [10]:

#預測的代碼放這
X = df[feature_cols]
y = df[target]
split_idx = int(len(df)*0.8)

X_train, X_test = X.iloc[:split_idx], X.iloc[split_idx:]
y_train, y_test = y.iloc[:split_idx], y.iloc[split_idx:]
tsfe = TSFE(feature_cols=feature_cols, feature_config=feature_config)

X_train_final = tsfe.fit_transform(X_train)
y_train_final = y_train.copy()

#X_train_final  = X_train_final [feature_ml]

X_test_final = tsfe.transform(X_test)
#X_test_final  = X_test_final [feature_ml]
y_test_final = y_test.copy()
#=================

       #return X_train_final, y_train_final, X_test_final, y_test_final

In [11]:
X_train_final.head()

,pflow,tmod,rt,w,ht,area,skew,start_time,end_time,start_level,end_level,last_std_ht,last_air_ht,last_std_area,last_air_area,last_std_rt,last_air_rt,last_std_start_level,last_air_start_level,ht_to_last_std_ratio,ht_to_last_air_ratio,area_to_last_std_ratio,area_to_last_air_ratio,rt_to_last_std_ratio,rt_to_last_air_ratio,start_level_to_last_std_ratio,start_level_to_last_air_ratio,duration_rt_ratio,rt_position,baseline_slope,level_area_ratio
datetime,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1994-02-16 14:29:00,841.900024,40.000000,0.000000,0.00,0,0,0.00,0.000000,0.000000,0.0,0.0,157028.0,173910.5,1177322.0,1291400.0,95.0,94.800003,29192.0,27985.5,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.484211,1.715116,-23.712795,0.000000
1994-02-16 14:49:00,840.400024,40.000000,0.000000,0.00,0,0,0.00,0.000000,0.000000,0.0,0.0,157028.0,0.0,1177322.0,0.0,95.0,0.000000,29192.0,0.0,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.484211,1.715116,-23.712795,0.000000
1994-02-16 15:09:00,839.400024,40.009998,109.800003,2.60,190908,496440,0.63,102.000000,135.399994,10063.0,10029.0,157028.0,0.0,1177322.0,0.0,95.0,0.000000,29192.0,0.0,1.215758,1.909080e+12,0.421669,4.964400e+12,1.155789,1.098000e+09,0.344718,1.006300e+11,0.304189,3.000000,-13.076923,0.020270
1994-02-16 15:29:00,839.599976,40.000000,94.800003,6.85,151667,1065982,1.02,86.199997,129.000000,99999.0,99999.0,157028.0,190908.0,1177322.0,496440.0,95.0,109.800003,29192.0,10063.0,0.965860,7.944508e-01,0.905429,2.147252e+00,0.997895,8.633880e-01,3.425562,9.937295e+00,0.451477,1.255474,0.000000,0.093809
1994-02-16 18:00:00,845.400024,40.000000,0.000000,0.00,0,0,0.00,0.000000,0.000000,0.0,0.0,157028.0,151667.0,1177322.0,1065982.0,95.0,94.800003,29192.0,99999.0,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.451477,1.255474,0.000000,0.000000

In [ ]:
predict_file = '../data/test_test.txt'
pred_processor = GCMDprocessor(predict_file)
df_test = pred_processor._parse_file()
X_test = pred_processor._predict(df_test)

df passed 1 step!

In [4]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 533 entries, 2026-03-09 12:32:00 to 2026-03-17 00:17:00
Data columns (total 42 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         533 non-null    object
 1   time         533 non-null    object
 2   type         533 non-null    object
 3   sample       533 non-null    object
 4   standard     533 non-null    object
 5   port         533 non-null    int64
 6   inlet_ht     533 non-null    int64
 7   tmod         533 non-null    float64
 8   tamb         533 non-null    float64
 9   temp         0 non-null      float64
 10  pflow        533 non-null    float64
 11  psamp        533 non-null    float64
 12  ploop        0 non-null      float64
 13  pamb         533 non-null    float64
 14  rt           533 non-null    float64
 15  w            533 non-null    float64
 16  ht           533 non-null    int64
 17  area         533 non-null    int64
 18  skew         533 non-null    float64
 19  start_time   533 non-null    float64
 20  end_time     533 non-null    float64
 21  start_level  533 non-null    float64
 22  end_level    533 non-null    float64
 23  Rl_ht        513 non-null    float64
 24  Rl_a         521 non-null    float64
 25  Rl           510 non-null    float64
 26  norm_ht      513 non-null    float64
 27  norm_a       513 non-null    float64
 28  norm_w       513 non-null    float64
 29  R_ht         513 non-null    float64
 30  R_a          521 non-null    float64
 31  R            510 non-null    float64
 32  C_ht         513 non-null    float64
 33  C_a          521 non-null    float64
 34  C            510 non-null    float64
 35  std_stdev    533 non-null    float64
 36  std_rep      256 non-null    float64
 37  Cstd         533 non-null    float64
 38  flag_ht      533 non-null    object
 39  flag_a       533 non-null    object
 40  flag         533 non-null    object
 41  flag_p       0 non-null      float64
dtypes: float64(30), int64(4), object(8)
memory usage: 179.1+ KB

In [3]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 531 entries, 2026-03-09 12:32:00 to 2026-03-17 00:17:00
Data columns (total 30 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   pflow                          531 non-null    float32
 1   tmod                           531 non-null    float32
 2   rt                             531 non-null    float32
 3   w                              531 non-null    float32
 4   ht                             531 non-null    int64
 5   area                           531 non-null    int64
 6   skew                           531 non-null    float32
 7   start_time                     531 non-null    float32
 8   end_time                       531 non-null    float32
 9   start_level                    531 non-null    float32
 10  end_level                      531 non-null    float32
 11  last_std_ht                    531 non-null    float32
 12  last_air_ht                    531 non-null    float32
 13  last_air_area                  531 non-null    float32
 14  last_std_rt                    531 non-null    float32
 15  last_air_rt                    531 non-null    float32
 16  last_std_start_level           531 non-null    float32
 17  last_air_start_level           531 non-null    float32
 18  ht_to_last_std_ratio           531 non-null    float32
 19  ht_to_last_air_ratio           531 non-null    float32
 20  area_to_last_std_ratio         531 non-null    float32
 21  area_to_last_air_ratio         531 non-null    float32
 22  rt_to_last_std_ratio           531 non-null    float32
 23  rt_to_last_air_ratio           531 non-null    float32
 24  start_level_to_last_std_ratio  531 non-null    float32
 25  start_level_to_last_air_ratio  531 non-null    float32
 26  duration_rt_ratio              531 non-null    float32
 27  rt_position                    531 non-null    float32
 28  baseline_slope                 531 non-null    float32
 29  level_area_ratio               531 non-null    float32
dtypes: float32(28), int64(2)
memory usage: 70.5 KB