In [82]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [134]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
sns.set_theme(style='darkgrid')
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
raw_data = pd.read_csv('../data/processed/mhd_ch4_simple_v1.csv')
raw_data.head()

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p,label1,datetime_str,datetime,is_ht_999,is_area_999,is_rt_zero,is_w_zero,duration,ht_area_ratio,type_std,type_air,type_tank,type_blank,type_cal,type_other,year,month,day,hour,minute,seconds
0,940216,142900,air,10m,G-024,3,10.0,40.00,32.27,NaN,841.9,761.10,NaN,761.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216142900,1994-02-16 14:29:00,False,False,True,True,0.0,NaN,0,1,0,0,0,0,1994,2,16,14,29,0
1,940216,144900,air,10m,G-024,3,10.0,40.00,32.48,NaN,840.4,761.07,NaN,761.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216144900,1994-02-16 14:49:00,False,False,True,True,0.0,NaN,0,1,0,0,0,0,1994,2,16,14,49,0
2,940216,150900,air,10m,G-024,3,10.0,40.01,32.75,NaN,839.4,760.99,NaN,760.9,109.8,2.60,190908.0,496440.0,0.63,102.0,135.4,10063.0,10029.0,F,F,,,1,940216150900,1994-02-16 15:09:00,False,False,False,False,33.4,0.384554,0,1,0,0,0,0,1994,2,16,15,9,0
3,940216,152900,air,10m,G-024,3,10.0,40.00,32.92,NaN,839.6,760.96,NaN,760.9,94.8,6.85,151667.0,1065982.0,1.02,86.2,129.0,99999.0,99999.0,,,,,0,940216152900,1994-02-16 15:29:00,False,False,False,False,42.8,0.142279,0,1,0,0,0,0,1994,2,16,15,29,0
4,940216,180000,air,10m,G-024,3,10.0,40.00,33.31,NaN,845.4,760.72,NaN,760.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216180000,1994-02-16 18:00:00,False,False,True,True,0.0,NaN,0,1,0,0,0,0,1994,2,16,18,0,0

In [135]:
data = raw_data.copy()
data.columns

Index(['date', 'time', 'type', 'sample', 'standard', 'port', 'ht', 'tmod',
       'tamb', 'lab_temp', 'pflow', 'psamp', 'ploop', 'pamb', 'CH4_rt',
       'CH4_w', 'CH4_ht', 'CH4_area', 'CH4_skew', 'CH4_start_time',
       'CH4_end_time', 'CH4_start_level', 'CH4_end_level', 'CH4_flag_ht',
       'CH4_flag_a', 'CH4_flag', 'CH4_flag_p', 'label1', 'datetime_str',
       'datetime', 'is_ht_999', 'is_area_999', 'is_rt_zero', 'is_w_zero',
       'duration', 'ht_area_ratio', 'type_std', 'type_air', 'type_tank',
       'type_blank', 'type_cal', 'type_other', 'year', 'month', 'day', 'hour',
       'minute', 'seconds'],
      dtype='object')

In [136]:
iszero_feature = ['CH4_rt',
       'CH4_w', 'CH4_ht', 'CH4_area', 'CH4_skew', 'CH4_start_time',
       'CH4_end_time', 'CH4_start_level', 'CH4_end_level']

for col in iszero_feature:
    data[f'is_{col}_zero'] = (data[col]==0).astype(int)

In [137]:
data.head()

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p,label1,datetime_str,datetime,is_ht_999,is_area_999,is_rt_zero,is_w_zero,duration,ht_area_ratio,type_std,type_air,type_tank,type_blank,type_cal,type_other,year,month,day,hour,minute,seconds,is_CH4_rt_zero,is_CH4_w_zero,is_CH4_ht_zero,is_CH4_area_zero,is_CH4_skew_zero,is_CH4_start_time_zero,is_CH4_end_time_zero,is_CH4_start_level_zero,is_CH4_end_level_zero
0,940216,142900,air,10m,G-024,3,10.0,40.00,32.27,NaN,841.9,761.10,NaN,761.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216142900,1994-02-16 14:29:00,False,False,True,True,0.0,NaN,0,1,0,0,0,0,1994,2,16,14,29,0,1,1,1,1,1,1,1,1,1
1,940216,144900,air,10m,G-024,3,10.0,40.00,32.48,NaN,840.4,761.07,NaN,761.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216144900,1994-02-16 14:49:00,False,False,True,True,0.0,NaN,0,1,0,0,0,0,1994,2,16,14,49,0,1,1,1,1,1,1,1,1,1
2,940216,150900,air,10m,G-024,3,10.0,40.01,32.75,NaN,839.4,760.99,NaN,760.9,109.8,2.60,190908.0,496440.0,0.63,102.0,135.4,10063.0,10029.0,F,F,,,1,940216150900,1994-02-16 15:09:00,False,False,False,False,33.4,0.384554,0,1,0,0,0,0,1994,2,16,15,9,0,0,0,0,0,0,0,0,0,0
3,940216,152900,air,10m,G-024,3,10.0,40.00,32.92,NaN,839.6,760.96,NaN,760.9,94.8,6.85,151667.0,1065982.0,1.02,86.2,129.0,99999.0,99999.0,,,,,0,940216152900,1994-02-16 15:29:00,False,False,False,False,42.8,0.142279,0,1,0,0,0,0,1994,2,16,15,29,0,0,0,0,0,0,0,0,0,0
4,940216,180000,air,10m,G-024,3,10.0,40.00,33.31,NaN,845.4,760.72,NaN,760.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216180000,1994-02-16 18:00:00,False,False,True,True,0.0,NaN,0,1,0,0,0,0,1994,2,16,18,0,0,1,1,1,1,1,1,1,1,1

In [138]:
data = data.drop(data[data['year']==2026].index)
data['year'].unique()

array([1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004,
       2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015,
       2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025])

In [139]:
year_dummies = pd.get_dummies(data['year'], prefix='is_year_').astype(int)
data = pd.concat([data, year_dummies], axis=1)
data.head()

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p,label1,datetime_str,datetime,is_ht_999,is_area_999,is_rt_zero,is_w_zero,duration,ht_area_ratio,type_std,type_air,type_tank,type_blank,type_cal,type_other,year,month,day,hour,minute,seconds,is_CH4_rt_zero,is_CH4_w_zero,is_CH4_ht_zero,is_CH4_area_zero,is_CH4_skew_zero,is_CH4_start_time_zero,is_CH4_end_time_zero,is_CH4_start_level_zero,is_CH4_end_level_zero,is_year__1994,is_year__1995,is_year__1996,is_year__1997,is_year__1998,is_year__1999,is_year__2000,is_year__2001,is_year__2002,is_year__2003,is_year__2004,is_year__2005,is_year__2006,is_year__2007,is_year__2008,is_year__2009,is_year__2010,is_year__2011,is_year__2012,is_year__2013,is_year__2014,is_year__2015,is_year__2016,is_year__2017,is_year__2018,is_year__2019,is_year__2020,is_year__2021,is_year__2022,is_year__2023,is_year__2024,is_year__2025
0,940216,142900,air,10m,G-024,3,10.0,40.00,32.27,NaN,841.9,761.10,NaN,761.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216142900,1994-02-16 14:29:00,False,False,True,True,0.0,NaN,0,1,0,0,0,0,1994,2,16,14,29,0,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,940216,144900,air,10m,G-024,3,10.0,40.00,32.48,NaN,840.4,761.07,NaN,761.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216144900,1994-02-16 14:49:00,False,False,True,True,0.0,NaN,0,1,0,0,0,0,1994,2,16,14,49,0,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,940216,150900,air,10m,G-024,3,10.0,40.01,32.75,NaN,839.4,760.99,NaN,760.9,109.8,2.60,190908.0,496440.0,0.63,102.0,135.4,10063.0,10029.0,F,F,,,1,940216150900,1994-02-16 15:09:00,False,False,False,False,33.4,0.384554,0,1,0,0,0,0,1994,2,16,15,9,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,940216,152900,air,10m,G-024,3,10.0,40.00,32.92,NaN,839.6,760.96,NaN,760.9,94.8,6.85,151667.0,1065982.0,1.02,86.2,129.0,99999.0,99999.0,,,,,0,940216152900,1994-02-16 15:29:00,False,False,False,False,42.8,0.142279,0,1,0,0,0,0,1994,2,16,15,29,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,940216,180000,air,10m,G-024,3,10.0,40.00,33.31,NaN,845.4,760.72,NaN,760.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216180000,1994-02-16 18:00:00,False,False,True,True,0.0,NaN,0,1,0,0,0,0,1994,2,16,18,0,0,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

# not used
# def year_one_hot(data, feature):
    ### True = 1
    time = sorted(data[f'{feature}'].unique())
    for i in time:
        data[f'is_year_{i}'] = (data['year']==i).astype(int)

    return data

In [141]:
data = data.set_index('datetime')
data = data.reset_index()

In [142]:
# only use normal data
all_air_df = data[(data['type_air']==1)]
all_std_df = data[(data['type_std'] == 1)]

r_air_df = data[(data['type_air']==1)&(data['label1']==0)]
r_std_df = data[(data['type_std'] == 1)&(data['label1']==0)]

r_air_df  = r_air_df.set_index('datetime')
r_std_df = r_std_df.set_index('datetime')
print(r_air_df.head())
print(r_std_df.head())

                       date    time type sample standard  port    ht   tmod  \
datetime
1994-02-16 15:29:00  940216  152900  air    10m    G-024     3  10.0  40.00
1994-02-17 10:25:00  940217  102500  air    10m    G-024     3  10.0  40.00
1994-02-17 10:45:00  940217  104500  air    10m    G-024     3  10.0  40.00
1994-02-17 11:05:00  940217  110500  air    10m    G-024     3  10.0  39.99
1994-02-17 13:02:00  940217  130200  air    10m    G-024     3  10.0  40.01

                      tamb  lab_temp  pflow   psamp  ploop   pamb  CH4_rt  \
datetime
1994-02-16 15:29:00  32.92       NaN  839.6  760.96    NaN  760.9    94.8
1994-02-17 10:25:00  29.57       NaN  834.0  753.28    NaN  753.2    98.8
1994-02-17 10:45:00  27.21       NaN  832.6  753.11    NaN  753.1    95.4
1994-02-17 11:05:00  26.79       NaN  832.6  753.00    NaN  752.9    94.6
1994-02-17 13:02:00  33.31       NaN  832.0  751.72    NaN  751.6    94.8

                     CH4_w    CH4_ht   CH4_area  CH4_skew  CH4_start_time  \
datetime
1994-02-16 15:29:00   6.85  151667.0  1065982.0      1.02            86.2
1994-02-17 10:25:00   8.30  190538.0  1794447.0      1.04            85.4
1994-02-17 10:45:00   7.21  176389.0  1427808.0      1.08            83.4
1994-02-17 11:05:00   8.66  168522.0  1566793.0      1.44            82.8
1994-02-17 13:02:00   6.85  174670.0  1295644.0      1.06            83.0

                     CH4_end_time  CH4_start_level  CH4_end_level CH4_flag_ht  \
datetime
1994-02-16 15:29:00         129.0          99999.0        99999.0
1994-02-17 10:25:00         138.4          80100.0        80099.0
1994-02-17 10:45:00         132.8          60959.0        60043.0
1994-02-17 11:05:00         135.0          82021.0        67370.0
1994-02-17 13:02:00         129.2          48251.0        47542.0

                    CH4_flag_a CH4_flag CH4_flag_p  label1  datetime_str  \
datetime
1994-02-16 15:29:00                                      0  940216152900
1994-02-17 10:25:00                                      0  940217102500
1994-02-17 10:45:00                                      0  940217104500
1994-02-17 11:05:00                                      0  940217110500
1994-02-17 13:02:00                                      0  940217130200

                     is_ht_999  is_area_999  is_rt_zero  is_w_zero  duration  \
datetime
1994-02-16 15:29:00      False        False       False      False      42.8
1994-02-17 10:25:00      False        False       False      False      53.0
1994-02-17 10:45:00      False        False       False      False      49.4
1994-02-17 11:05:00      False        False       False      False      52.2
1994-02-17 13:02:00      False        False       False      False      46.2

                     ht_area_ratio  type_std  type_air  type_tank  type_blank  \
datetime
1994-02-16 15:29:00       0.142279         0         1          0           0
1994-02-17 10:25:00       0.106182         0         1          0           0
1994-02-17 10:45:00       0.123538         0         1          0           0
1994-02-17 11:05:00       0.107559         0         1          0           0
1994-02-17 13:02:00       0.134813         0         1          0           0

                     type_cal  type_other  year  month  day  hour  minute  \
datetime
1994-02-16 15:29:00         0           0  1994      2   16    15      29
1994-02-17 10:25:00         0           0  1994      2   17    10      25
1994-02-17 10:45:00         0           0  1994      2   17    10      45
1994-02-17 11:05:00         0           0  1994      2   17    11       5
1994-02-17 13:02:00         0           0  1994      2   17    13       2

                     seconds  is_CH4_rt_zero  is_CH4_w_zero  is_CH4_ht_zero  \
datetime
1994-02-16 15:29:00        0               0              0               0
1994-02-17 10:25:00        0               0              0               0
1994-02-17 10:45:00        0               0              0               0
1994-02-17 11:05:00        0               0              0               0
1994-02-17 13:02:00        0               0              0               0

                     is_CH4_area_zero  is_CH4_skew_zero  \
datetime
1994-02-16 15:29:00                 0                 0
1994-02-17 10:25:00                 0                 0
1994-02-17 10:45:00                 0                 0
1994-02-17 11:05:00                 0                 0
1994-02-17 13:02:00                 0                 0

                     is_CH4_start_time_zero  is_CH4_end_time_zero  \
datetime
1994-02-16 15:29:00                       0                     0
1994-02-17 10:25:00                       0                     0
1994-02-17 10:45:00                       0                     0
1994-02-17 11:05:00                       0                     0
1994-02-17 13:02:00                       0                     0

                     is_CH4_start_level_zero  is_CH4_end_level_zero  \
datetime
1994-02-16 15:29:00                        0                      0
1994-02-17 10:25:00                        0                      0
1994-02-17 10:45:00                        0                      0
1994-02-17 11:05:00                        0                      0
1994-02-17 13:02:00                        0                      0

                     is_year__1994  is_year__1995  is_year__1996  \
datetime
1994-02-16 15:29:00              1              0              0
1994-02-17 10:25:00              1              0              0
1994-02-17 10:45:00              1              0              0
1994-02-17 11:05:00              1              0              0
1994-02-17 13:02:00              1              0              0

                     is_year__1997  is_year__1998  is_year__1999  \
datetime
1994-02-16 15:29:00              0              0              0
1994-02-17 10:25:00              0              0              0
1994-02-17 10:45:00              0              0              0
1994-02-17 11:05:00              0              0              0
1994-02-17 13:02:00              0              0              0

                     is_year__2000  is_year__2001  is_year__2002  \
datetime
1994-02-16 15:29:00              0              0              0
1994-02-17 10:25:00              0              0              0
1994-02-17 10:45:00              0              0              0
1994-02-17 11:05:00              0              0              0
1994-02-17 13:02:00              0              0              0

                     is_year__2003  is_year__2004  is_year__2005  \
datetime
1994-02-16 15:29:00              0              0              0
1994-02-17 10:25:00              0              0              0
1994-02-17 10:45:00              0              0              0
1994-02-17 11:05:00              0              0              0
1994-02-17 13:02:00              0              0              0

                     is_year__2006  is_year__2007  is_year__2008  \
datetime
1994-02-16 15:29:00              0              0              0
1994-02-17 10:25:00              0              0              0
1994-02-17 10:45:00              0              0              0
1994-02-17 11:05:00              0              0              0
1994-02-17 13:02:00              0              0              0

                     is_year__2009  is_year__2010  is_year__2011  \
datetime
1994-02-16 15:29:00              0              0              0
1994-02-17 10:25:00              0              0              0
1994-02-17 10:45:00              0              0              0
1994-02-17 11:05:00              0              0              0
1994-02-17 13:02:00              0              0              0

                     is_year__2012  is_year__2013  is_year__2014  \
datetime
1994-02-16 15:29:00              0              0              0
1994-02-17 10:25:00              0              0              0
1994-02-17 10:45:00              0              0              0
1994-02-17 11:05:00              0              0              0
1994-02-17 13:02:00              0              0              0

                     is_year__2015  is_year__2016  is_year__2017  \
datetime
1994-02-16 15:29:00              0              0              0
1994-02-17 10:25:00              0              0              0
1994-02-17 10:45:00              0              0              0
1994-02-17 11:05:00              0              0              0
1994-02-17 13:02:00              0              0              0

                     is_year__2018  is_year__2019  is_year__2020  \
datetime
1994-02-16 15:29:00              0              0              0
1994-02-17 10:25:00              0              0              0
1994-02-17 10:45:00              0              0              0
1994-02-17 11:05:00              0              0              0
1994-02-17 13:02:00              0              0              0

                     is_year__2021  is_year__2022  is_year__2023  \
datetime
1994-02-16 15:29:00              0              0              0
1994-02-17 10:25:00              0              0              0
1994-02-17 10:45:00              0              0              0
1994-02-17 11:05:00              0              0              0
1994-02-17 13:02:00              0              0              0

                     is_year__2024  is_year__2025
datetime
1994-02-16 15:29:00              0              0
1994-02-17 10:25:00              0              0
1994-02-17 10:45:00              0              0
1994-02-17 11:05:00              0              0
1994-02-17 13:02:00              0              0
                       date    time type sample standard  port   ht   tmod  \
datetime
1994-02-17 20:00:00  940217  200000  std  G-024    G-024     1  0.0  39.99
1994-02-17 20:40:00  940217  204000  std  G-024    G-024     1  0.0  40.00
1994-02-17 21:20:00  940217  212000  std  G-024    G-024     1  0.0  40.00
1994-02-18 00:01:00  940218     100  std  G-024    G-024     1  0.0  40.00
1994-02-18 00:41:00  940218    4100  std  G-024    G-024     1  0.0  40.00

                      tamb  lab_temp  pflow   psamp  ploop   pamb  CH4_rt  \
datetime
1994-02-17 20:00:00  23.77       NaN  844.0  749.39    NaN  749.3    93.8
1994-02-17 20:40:00  22.95       NaN  844.0  749.28    NaN  749.2    94.4
1994-02-17 21:20:00  22.61       NaN  844.3  749.44    NaN  749.5    94.0
1994-02-18 00:01:00  22.50       NaN  844.4  749.96    NaN  750.1    95.0
1994-02-18 00:41:00  22.47       NaN  844.8  750.18    NaN  750.3    94.8

                     CH4_w    CH4_ht   CH4_area  CH4_skew  CH4_start_time  \
datetime
1994-02-17 20:00:00   6.76  157302.0  1150014.0      1.03            82.2
1994-02-17 20:40:00   6.77  156920.0  1148290.0      1.06            82.8
1994-02-17 21:20:00   6.77  156659.0  1148370.0      1.00            82.2
1994-02-18 00:01:00   6.84  158732.0  1175833.0      1.10            83.4
1994-02-18 00:41:00   6.84  158539.0  1174079.0      1.06            83.0

                     CH4_end_time  CH4_start_level  CH4_end_level CH4_flag_ht  \
datetime
1994-02-17 20:00:00         127.8          40868.0        40519.0
1994-02-17 20:40:00         128.4          40182.0        39822.0
1994-02-17 21:20:00         127.6          39673.0        39226.0
1994-02-18 00:01:00         129.0          39014.0        38749.0           B
1994-02-18 00:41:00         128.8          38727.0        38458.0

                    CH4_flag_a CH4_flag CH4_flag_p  label1  datetime_str  \
datetime
1994-02-17 20:00:00                                      0  940217200000
1994-02-17 20:40:00                                      0  940217204000
1994-02-17 21:20:00                                      0  940217212000
1994-02-18 00:01:00          B                           0  940218000100
1994-02-18 00:41:00                                      0  940218004100

                     is_ht_999  is_area_999  is_rt_zero  is_w_zero  duration  \
datetime
1994-02-17 20:00:00      False        False       False      False      45.6
1994-02-17 20:40:00      False        False       False      False      45.6
1994-02-17 21:20:00      False        False       False      False      45.4
1994-02-18 00:01:00      False        False       False      False      45.6
1994-02-18 00:41:00      False        False       False      False      45.8

                     ht_area_ratio  type_std  type_air  type_tank  type_blank  \
datetime
1994-02-17 20:00:00       0.136783         1         0          0           0
1994-02-17 20:40:00       0.136655         1         0          0           0
1994-02-17 21:20:00       0.136419         1         0          0           0
1994-02-18 00:01:00       0.134995         1         0          0           0
1994-02-18 00:41:00       0.135033         1         0          0           0

                     type_cal  type_other  year  month  day  hour  minute  \
datetime
1994-02-17 20:00:00         0           0  1994      2   17    20       0
1994-02-17 20:40:00         0           0  1994      2   17    20      40
1994-02-17 21:20:00         0           0  1994      2   17    21      20
1994-02-18 00:01:00         0           0  1994      2   18     0       1
1994-02-18 00:41:00         0           0  1994      2   18     0      41

                     seconds  is_CH4_rt_zero  is_CH4_w_zero  is_CH4_ht_zero  \
datetime
1994-02-17 20:00:00        0               0              0               0
1994-02-17 20:40:00        0               0              0               0
1994-02-17 21:20:00        0               0              0               0
1994-02-18 00:01:00        0               0              0               0
1994-02-18 00:41:00        0               0              0               0

                     is_CH4_area_zero  is_CH4_skew_zero  \
datetime
1994-02-17 20:00:00                 0                 0
1994-02-17 20:40:00                 0                 0
1994-02-17 21:20:00                 0                 0
1994-02-18 00:01:00                 0                 0
1994-02-18 00:41:00                 0                 0

                     is_CH4_start_time_zero  is_CH4_end_time_zero  \
datetime
1994-02-17 20:00:00                       0                     0
1994-02-17 20:40:00                       0                     0
1994-02-17 21:20:00                       0                     0
1994-02-18 00:01:00                       0                     0
1994-02-18 00:41:00                       0                     0

                     is_CH4_start_level_zero  is_CH4_end_level_zero  \
datetime
1994-02-17 20:00:00                        0                      0
1994-02-17 20:40:00                        0                      0
1994-02-17 21:20:00                        0                      0
1994-02-18 00:01:00                        0                      0
1994-02-18 00:41:00                        0                      0

                     is_year__1994  is_year__1995  is_year__1996  \
datetime
1994-02-17 20:00:00              1              0              0
1994-02-17 20:40:00              1              0              0
1994-02-17 21:20:00              1              0              0
1994-02-18 00:01:00              1              0              0
1994-02-18 00:41:00              1              0              0

                     is_year__1997  is_year__1998  is_year__1999  \
datetime
1994-02-17 20:00:00              0              0              0
1994-02-17 20:40:00              0              0              0
1994-02-17 21:20:00              0              0              0
1994-02-18 00:01:00              0              0              0
1994-02-18 00:41:00              0              0              0

                     is_year__2000  is_year__2001  is_year__2002  \
datetime
1994-02-17 20:00:00              0              0              0
1994-02-17 20:40:00              0              0              0
1994-02-17 21:20:00              0              0              0
1994-02-18 00:01:00              0              0              0
1994-02-18 00:41:00              0              0              0

                     is_year__2003  is_year__2004  is_year__2005  \
datetime
1994-02-17 20:00:00              0              0              0
1994-02-17 20:40:00              0              0              0
1994-02-17 21:20:00              0              0              0
1994-02-18 00:01:00              0              0              0
1994-02-18 00:41:00              0              0              0

                     is_year__2006  is_year__2007  is_year__2008  \
datetime
1994-02-17 20:00:00              0              0              0
1994-02-17 20:40:00              0              0              0
1994-02-17 21:20:00              0              0              0
1994-02-18 00:01:00              0              0              0
1994-02-18 00:41:00              0              0              0

                     is_year__2009  is_year__2010  is_year__2011  \
datetime
1994-02-17 20:00:00              0              0              0
1994-02-17 20:40:00              0              0              0
1994-02-17 21:20:00              0              0              0
1994-02-18 00:01:00              0              0              0
1994-02-18 00:41:00              0              0              0

                     is_year__2012  is_year__2013  is_year__2014  \
datetime
1994-02-17 20:00:00              0              0              0
1994-02-17 20:40:00              0              0              0
1994-02-17 21:20:00              0              0              0
1994-02-18 00:01:00              0              0              0
1994-02-18 00:41:00              0              0              0

                     is_year__2015  is_year__2016  is_year__2017  \
datetime
1994-02-17 20:00:00              0              0              0
1994-02-17 20:40:00              0              0              0
1994-02-17 21:20:00              0              0              0
1994-02-18 00:01:00              0              0              0
1994-02-18 00:41:00              0              0              0

                     is_year__2018  is_year__2019  is_year__2020  \
datetime
1994-02-17 20:00:00              0              0              0
1994-02-17 20:40:00              0              0              0
1994-02-17 21:20:00              0              0              0
1994-02-18 00:01:00              0              0              0
1994-02-18 00:41:00              0              0              0

                     is_year__2021  is_year__2022  is_year__2023  \
datetime
1994-02-17 20:00:00              0              0              0
1994-02-17 20:40:00              0              0              0
1994-02-17 21:20:00              0              0              0
1994-02-18 00:01:00              0              0              0
1994-02-18 00:41:00              0              0              0

                     is_year__2024  is_year__2025
datetime
1994-02-17 20:00:00              0              0
1994-02-17 20:40:00              0              0
1994-02-17 21:20:00              0              0
1994-02-18 00:01:00              0              0
1994-02-18 00:41:00              0              0

In [48]:
feature_cols = [
    #'sample'	,'standard',	
    #'port'	,'ht',
    'tmod'	,'tamb',
    'pflow', 'psamp',
    'pamb'	,
    'CH4_rt',	'CH4_w',	'CH4_ht'	,
    'CH4_area',	'CH4_skew'	,
    'CH4_start_time',	'CH4_end_time'	,'CH4_start_level',	'CH4_end_level',
    'duration', 
]

In [143]:
print(r_air_df[feature_cols].info())
print(r_air_df[feature_cols].isna().sum())

print(r_std_df[feature_cols].info())
print(r_std_df[feature_cols].isna().sum())

<class 'pandas.core.frame.DataFrame'>
Index: 352083 entries, 1994-02-16 15:29:00 to 2025-12-31 23:38:00
Data columns (total 15 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   tmod             305484 non-null  float64
 1   tamb             305484 non-null  float64
 2   pflow            351393 non-null  float64
 3   psamp            351393 non-null  float64
 4   pamb             351382 non-null  float64
 5   CH4_rt           351392 non-null  float64
 6   CH4_w            351392 non-null  float64
 7   CH4_ht           351392 non-null  float64
 8   CH4_area         351392 non-null  float64
 9   CH4_skew         351392 non-null  float64
 10  CH4_start_time   351392 non-null  float64
 11  CH4_end_time     351392 non-null  float64
 12  CH4_start_level  351392 non-null  float64
 13  CH4_end_level    351392 non-null  float64
 14  duration         351392 non-null  float64
dtypes: float64(15)
memory usage: 43.0+ MB
None
tmod               46599
tamb               46599
pflow                690
psamp                690
pamb                 701
CH4_rt               691
CH4_w                691
CH4_ht               691
CH4_area             691
CH4_skew             691
CH4_start_time       691
CH4_end_time         691
CH4_start_level      691
CH4_end_level        691
duration             691
dtype: int64
<class 'pandas.core.frame.DataFrame'>
Index: 388605 entries, 1994-02-17 20:00:00 to 2025-12-31 23:58:00
Data columns (total 15 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   tmod             333976 non-null  float64
 1   tamb             333976 non-null  float64
 2   pflow            387482 non-null  float64
 3   psamp            387490 non-null  float64
 4   pamb             387470 non-null  float64
 5   CH4_rt           387795 non-null  float64
 6   CH4_w            387795 non-null  float64
 7   CH4_ht           387795 non-null  float64
 8   CH4_area         387795 non-null  float64
 9   CH4_skew         387795 non-null  float64
 10  CH4_start_time   387795 non-null  float64
 11  CH4_end_time     387795 non-null  float64
 12  CH4_start_level  387795 non-null  float64
 13  CH4_end_level    387795 non-null  float64
 14  duration         387795 non-null  float64
dtypes: float64(15)
memory usage: 47.4+ MB
None
tmod               54629
tamb               54629
pflow               1123
psamp               1115
pamb                1135
CH4_rt               810
CH4_w                810
CH4_ht               810
CH4_area             810
CH4_skew             810
CH4_start_time       810
CH4_end_time         810
CH4_start_level      810
CH4_end_level        810
duration             810
dtype: int64

In [144]:
def fill_Nan(df, feature_col):
    df = df.copy()
    for i in feature_col:
        df[i] = df[i].ffill()
    return df

#================
def ratio_featutre_gen(df):
    df = df.copy()
    df['CH4_area_ht_ratio'] = df['CH4_area']/df['CH4_ht']
    df['CH4_w_ht_ratio'] = df['CH4_w']/df['CH4_ht']
    df['psamp_pflow_ratio'] = df['psamp']/df['pflow']
    df['w_duration_ratio'] = df['CH4_w']/df['duration']

    fill_feature_ratio = ['CH4_area_ht_ratio', 'CH4_w_ht_ratio', 'psamp_pflow_ratio','w_duration_ratio']
    for i in fill_feature_ratio :
        df[i] = df[i].fillna(0)
        
    return df

#=============== diff, lag, rolling
def diff_gen(df, feature, period):
    df = df.copy()
    df[f'{feature}_diff_{period}'] = (df[f'{feature}'].diff(period)).fillna(0)

    return df
#===============
def lag_gen (df, feature, period):
    df = df.copy()
    df[f'{feature}_lag_{period}'] = (df[f'{feature}'].shift(period)).fillna(0)
    return df

#===============
def rolling_std_gen (df, feature, period):
    df = df.copy()
    df[f'{feature}_roll_std_{period}'] = (df[f'{feature}'].rolling(window=pd.to_timedelta(period), closed='left').std()).fillna(0)# self not included, NAN->0
    return df

#===============
def rolling_mean_residual_gen(df, feature, period):
    df = df.copy()
    df[f'{feature}_roll_mean_{period}'] = df[f'{feature}'].rolling(window=pd.to_timedelta(period), closed='left').mean().fillna(0) # self not included
    df[f'{feature}_residual_{period}'] = df[f'{feature}']- df[f'{feature}_roll_mean_{period}']# self not included
    return df

In [145]:
w_all_air_df =all_air_df.copy()
w_all_std_df =all_std_df.copy()
w_all_air_df  =w_all_air_df.set_index('datetime')
w_all_std_df = w_all_std_df.set_index('datetime')

w_all_air_df = fill_Nan(w_all_air_df, feature_cols)
w_all_std_df = fill_Nan(w_all_std_df, feature_cols)

w_all_air_df = ratio_featutre_gen(w_all_air_df)
w_all_std_df = ratio_featutre_gen(w_all_std_df)

w_all_air_df.index = pd.to_datetime(w_all_air_df.index)
w_all_std_df.index = pd.to_datetime(w_all_std_df .index)

In [ ]:
# Fill Nan - normal df (wr- working right)


wr_air_df = r_air_df.copy()
wr_std_df = r_std_df.copy()
wr_air_df  = r_air_df.set_index('datetime')
wr_std_df = r_std_df.set_index('datetime')

wr_air_df = fill_Nan(wr_air_df, feature_cols)
wr_std_df = fill_Nan(wr_std_df, feature_cols)

In [77]:
# ratio feature gen
wr_air_df = ratio_featutre_gen(wr_air_df)
wr_std_df = ratio_featutre_gen(wr_std_df)

In [78]:
print(wr_std_df.index.dtype)

object

In [79]:
wr_air_df.index = pd.to_datetime(wr_air_df.index)
wr_std_df.index = pd.to_datetime(wr_std_df.index)

In [ ]:
# diff(), shift(), rolling mean(14D)
# ===== diff

diff_col = ['CH4_area', 'CH4_ht']
lag_col = ['CH4_area', 'CH4_rt', 'tmod', 'tamb','pflow', 'psamp','pamb']
rolling_mean_col = ['Ch4_rt', 'CH4_start_time', 'CH4_w', 'CH4_skew']
rolling_std_col = ['CH4_w', 'CH4_skew']
res_mean_col = ['CH4_w', 'CH4_skew']



feature_config ={
    'diff':{'cols': ['CH4_area', 'CH4_ht', 'CH4_rt'], 'periods':1},
    'lag':{'cols':['CH4_area', 'CH4_rt', 'tmod', 'tamb','pflow', 'psamp','pamb'], 'periods':1 },
    'roll_std':{'cols': ['CH4_w', 'CH4_skew'], 'period':'14D'},
    'roll_mean_res':{'cols':['Ch4_rt', 'CH4_start_time', 'CH4_w', 'CH4_skew'], 'period': '14D'}
}

def feature_eng_apply(df, config):
    df = df.copy()

    for opt, params in config.items():
        cols = params['cols']
        period = params.get('period') or params.get('periods', 1) # period's value -> periods's -> 1

        for feature in cols:
            if opt == 'diff':
                df = diff_gen(df, feature, period)
            elif opt == 'lag':
                df = lag_gen(df, feature, period)
            elif opt == 'roll_std':
                df = rolling_std_gen(df, feature, period)
            elif opt == 'roll_mean_res':
                df = rolling_mean_residual_gen(df, feature, period)
    return df 


wr_air_df = feature_eng_apply(wr_air_df, feature_config)
wr_std_df = feature_eng_apply(wr_std_df, feature_config)

In [146]:
w_all_air_df = feature_eng_apply(w_all_air_df, feature_config)
w_all_std_df = feature_eng_apply(w_all_std_df, feature_config)

In [150]:
list(w_all_air_df.columns)

['date',
 'time',
 'type',
 'sample',
 'standard',
 'port',
 'ht',
 'tmod',
 'tamb',
 'lab_temp',
 'pflow',
 'psamp',
 'ploop',
 'pamb',
 'CH4_rt',
 'CH4_w',
 'CH4_ht',
 'CH4_area',
 'CH4_skew',
 'CH4_start_time',
 'CH4_end_time',
 'CH4_start_level',
 'CH4_end_level',
 'CH4_flag_ht',
 'CH4_flag_a',
 'CH4_flag',
 'CH4_flag_p',
 'label1',
 'datetime_str',
 'is_ht_999',
 'is_area_999',
 'is_rt_zero',
 'is_w_zero',
 'duration',
 'ht_area_ratio',
 'type_std',
 'type_air',
 'type_tank',
 'type_blank',
 'type_cal',
 'type_other',
 'year',
 'month',
 'day',
 'hour',
 'minute',
 'seconds',
 'is_CH4_rt_zero',
 'is_CH4_w_zero',
 'is_CH4_ht_zero',
 'is_CH4_area_zero',
 'is_CH4_skew_zero',
 'is_CH4_start_time_zero',
 'is_CH4_end_time_zero',
 'is_CH4_start_level_zero',
 'is_CH4_end_level_zero',
 'is_year__1994',
 'is_year__1995',
 'is_year__1996',
 'is_year__1997',
 'is_year__1998',
 'is_year__1999',
 'is_year__2000',
 'is_year__2001',
 'is_year__2002',
 'is_year__2003',
 'is_year__2004',
 'is_year__2005',
 'is_year__2006',
 'is_year__2007',
 'is_year__2008',
 'is_year__2009',
 'is_year__2010',
 'is_year__2011',
 'is_year__2012',
 'is_year__2013',
 'is_year__2014',
 'is_year__2015',
 'is_year__2016',
 'is_year__2017',
 'is_year__2018',
 'is_year__2019',
 'is_year__2020',
 'is_year__2021',
 'is_year__2022',
 'is_year__2023',
 'is_year__2024',
 'is_year__2025',
 'CH4_area_ht_ratio',
 'CH4_w_ht_ratio',
 'psamp_pflow_ratio',
 'w_duration_ratio',
 'CH4_area_diff_1',
 'CH4_ht_diff_1',
 'CH4_rt_diff_1',
 'CH4_area_lag_1',
 'CH4_rt_lag_1',
 'tmod_lag_1',
 'tamb_lag_1',
 'pflow_lag_1',
 'psamp_lag_1',
 'pamb_lag_1',
 'CH4_w_roll_std_14D',
 'CH4_skew_roll_std_14D',
 'CH4_w_roll_mean_14D',
 'CH4_w_residual_14D',
 'CH4_skew_roll_mean_14D',
 'CH4_skew_residual_14D']

In [148]:
pd.option_context('display.max_columns', None)

In [152]:
list(w_all_std_df.columns)

['date',
 'time',
 'type',
 'sample',
 'standard',
 'port',
 'ht',
 'tmod',
 'tamb',
 'lab_temp',
 'pflow',
 'psamp',
 'ploop',
 'pamb',
 'CH4_rt',
 'CH4_w',
 'CH4_ht',
 'CH4_area',
 'CH4_skew',
 'CH4_start_time',
 'CH4_end_time',
 'CH4_start_level',
 'CH4_end_level',
 'CH4_flag_ht',
 'CH4_flag_a',
 'CH4_flag',
 'CH4_flag_p',
 'label1',
 'datetime_str',
 'is_ht_999',
 'is_area_999',
 'is_rt_zero',
 'is_w_zero',
 'duration',
 'ht_area_ratio',
 'type_std',
 'type_air',
 'type_tank',
 'type_blank',
 'type_cal',
 'type_other',
 'year',
 'month',
 'day',
 'hour',
 'minute',
 'seconds',
 'is_CH4_rt_zero',
 'is_CH4_w_zero',
 'is_CH4_ht_zero',
 'is_CH4_area_zero',
 'is_CH4_skew_zero',
 'is_CH4_start_time_zero',
 'is_CH4_end_time_zero',
 'is_CH4_start_level_zero',
 'is_CH4_end_level_zero',
 'is_year__1994',
 'is_year__1995',
 'is_year__1996',
 'is_year__1997',
 'is_year__1998',
 'is_year__1999',
 'is_year__2000',
 'is_year__2001',
 'is_year__2002',
 'is_year__2003',
 'is_year__2004',
 'is_year__2005',
 'is_year__2006',
 'is_year__2007',
 'is_year__2008',
 'is_year__2009',
 'is_year__2010',
 'is_year__2011',
 'is_year__2012',
 'is_year__2013',
 'is_year__2014',
 'is_year__2015',
 'is_year__2016',
 'is_year__2017',
 'is_year__2018',
 'is_year__2019',
 'is_year__2020',
 'is_year__2021',
 'is_year__2022',
 'is_year__2023',
 'is_year__2024',
 'is_year__2025',
 'CH4_area_ht_ratio',
 'CH4_w_ht_ratio',
 'psamp_pflow_ratio',
 'w_duration_ratio',
 'CH4_area_diff_1',
 'CH4_ht_diff_1',
 'CH4_rt_diff_1',
 'CH4_area_lag_1',
 'CH4_rt_lag_1',
 'tmod_lag_1',
 'tamb_lag_1',
 'pflow_lag_1',
 'psamp_lag_1',
 'pamb_lag_1',
 'CH4_w_roll_std_14D',
 'CH4_skew_roll_std_14D',
 'CH4_w_roll_mean_14D',
 'CH4_w_residual_14D',
 'CH4_skew_roll_mean_14D',
 'CH4_skew_residual_14D']

In [120]:
wr_std_df.isna().sum()

date                            0
time                            0
type                            0
sample                          0
standard                        0
port                            0
ht                              0
tmod                            0
tamb                            0
lab_temp                   388605
pflow                           0
psamp                           0
ploop                      388605
pamb                            0
CH4_rt                          0
CH4_w                           0
CH4_ht                          0
CH4_area                        0
CH4_skew                        0
CH4_start_time                  0
CH4_end_time                    0
CH4_start_level                 0
CH4_end_level                   0
CH4_flag_ht                     0
CH4_flag_a                      0
CH4_flag                        0
CH4_flag_p                      0
label1                          0
datetime_str                    0
is_ht_999                       0
is_area_999                     0
is_rt_zero                      0
is_w_zero                       0
duration                        0
ht_area_ratio                 810
type_std                        0
type_air                        0
type_tank                       0
type_blank                      0
type_cal                        0
type_other                      0
year                            0
month                           0
day                             0
hour                            0
minute                          0
seconds                         0
is_CH4_rt_zero                  0
is_CH4_w_zero                   0
is_CH4_ht_zero                  0
is_CH4_area_zero                0
is_CH4_skew_zero                0
is_CH4_start_time_zero          0
is_CH4_end_time_zero            0
is_CH4_start_level_zero         0
is_CH4_end_level_zero           0
is_year__1994                   0
is_year__1995                   0
is_year__1996                   0
is_year__1997                   0
is_year__1998                   0
is_year__1999                   0
is_year__2000                   0
is_year__2001                   0
is_year__2002                   0
is_year__2003                   0
is_year__2004                   0
is_year__2005                   0
is_year__2006                   0
is_year__2007                   0
is_year__2008                   0
is_year__2009                   0
is_year__2010                   0
is_year__2011                   0
is_year__2012                   0
is_year__2013                   0
is_year__2014                   0
is_year__2015                   0
is_year__2016                   0
is_year__2017                   0
is_year__2018                   0
is_year__2019                   0
is_year__2020                   0
is_year__2021                   0
is_year__2022                   0
is_year__2023                   0
is_year__2024                   0
is_year__2025                   0
CH4_area_ht_ratio               0
CH4_w_ht_ratio                  0
psamp_pflow_ratio               0
w_duration_ratio                0
CH4_area_diff_1                 0
CH4_ht_diff_1                   0
CH4_rt_diff_1                   0
CH4_area_lag_1                  0
CH4_rt_lag_1                    0
tmod_lag_1                      0
tamb_lag_1                      0
pflow_lag_1                     0
psamp_lag_1                     0
pamb_lag_1                      0
CH4_w_roll_std_14D              0
CH4_skew_roll_std_14D           0
CH4_w_roll_mean_14D             0
CH4_w_residual_14D              0
CH4_skew_roll_mean_14D          0
CH4_skew_residual_14D           0
dtype: int64

In [ ]:
# corr, heatmap

In [121]:
ml_col_all =[

 'tmod',
 'tamb',
 'pflow',
 'psamp',

 'pamb',
 'CH4_rt',
 'CH4_w',
 'CH4_ht',
 'CH4_area',
 'CH4_skew',
 'CH4_start_time',
 'CH4_end_time',
 'CH4_start_level',
 'CH4_end_level',





 'label1',
 
 'is_ht_999',
 'is_area_999',
 'is_rt_zero',
 'is_w_zero',

 'duration',


 'is_CH4_rt_zero',
 'is_CH4_w_zero',
 'is_CH4_ht_zero',
 'is_CH4_area_zero',
 'is_CH4_skew_zero',
 'is_CH4_start_time_zero',
 'is_CH4_end_time_zero',
 'is_CH4_start_level_zero',
 'is_CH4_end_level_zero',
 'is_year__1994',
 'is_year__1995',
 'is_year__1996',
 'is_year__1997',
 'is_year__1998',
 'is_year__1999',
 'is_year__2000',
 'is_year__2001',
 'is_year__2002',
 'is_year__2003',
 'is_year__2004',
 'is_year__2005',
 'is_year__2006',
 'is_year__2007',
 'is_year__2008',
 'is_year__2009',
 'is_year__2010',
 'is_year__2011',
 'is_year__2012',
 'is_year__2013',
 'is_year__2014',
 'is_year__2015',
 'is_year__2016',
 'is_year__2017',
 'is_year__2018',
 'is_year__2019',
 'is_year__2020',
 'is_year__2021',
 'is_year__2022',
 'is_year__2023',
 'is_year__2024',
 'is_year__2025',

 'CH4_area_ht_ratio',
 'CH4_w_ht_ratio',
 'psamp_pflow_ratio',
 'w_duration_ratio',

 'CH4_area_diff_1',
 'CH4_ht_diff_1',
 'CH4_rt_diff_1',
 'CH4_area_lag_1',
 'CH4_rt_lag_1',
 'tmod_lag_1',
 'tamb_lag_1',
 'pflow_lag_1',
 'psamp_lag_1',
 'pamb_lag_1',

 'CH4_w_roll_std_14D',
 'CH4_skew_roll_std_14D',
 'CH4_w_roll_mean_14D',
 'CH4_w_residual_14D',
 'CH4_skew_roll_mean_14D',
 'CH4_skew_residual_14D']

In [125]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from sklearn.preprocessing import RobustScaler

def datasplit_autoencoder(df, start_year, end_year, ml_cols_all):
    train_mask = (df['year'] >= start_year) & (df['year'] <= end_year)
    train_df = df[train_mask].copy()

    X_train = train_df[ml_cols_all]
    print(X_train.describe())
    scaler = RobustScaler()
    X_train_scaled = X_train.copy()
    num_cols = [c for c in X_train.columns if 'is_' not in c]
    X_train_scaled[num_cols] = scaler.fit_transform(X_train[num_cols]) # not sclaer 'is_' columns
    
    # Autoencoder
    input_dim = X_train_scaled.shape[1]

    model = Sequential([
        Dense(32, activation='relu', input_shape=(input_dim, )),
        Dense(16, activation='relu'),
        Dense(8, activation='relu'),
        Dense(16, activation='relu'),
        Dense(32, activation='relu'),
        Dense(input_dim, activation='linear')
    ])

    model.compile(optimizer='adam', loss='mse')
    model.fit(X_train_scaled, X_train_scaled, epochs=50, batch_size=32, validation_split=0.1)
    return model, scaler

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from sklearn.preprocessing import RobustScaler
from tensorflow.keras.layers import Input, Dense, BatchNormalization,Dropout
from tensorflow.keras.models import Model

def datasplit_autoencoder(df, start_year, end_year, ml_cols_all):
    train_mask = (df['year'] >= start_year) & (df['year'] <= end_year)
    train_df = df[train_mask].copy()

    X_train = train_df[ml_cols_all]
    print(X_train.describe())
    scaler = RobustScaler()
    X_train_scaled = X_train.copy()
    num_cols = [c for c in X_train.columns if 'is_' not in c]
    X_train_scaled[num_cols] = scaler.fit_transform(X_train[num_cols]) # not sclaer 'is_' columns
    

    input_auto = X_train_scaled.shape[1]
# Autoenco
    inp = Input(shape=(input_auto, ))
    e = Dense(32, activation='relu')(inp)
    #e = BatchNormalization()(e)
    e = Dense(64, activation='relu')(e)
    #e = BatchNormalization()(e)
    e = Dropout(0.1)(e)
    bottleneck = Dense(8, name="bottleneck")(e)

    #Decoder
    d = Dense(64, activation='relu')(bottleneck)
   # d = BatchNormalization()(d)
    d = Dense(128, activation='relu')(d)
    out = Dense(input_auto)(d)


    autoencoder = Model(inp, out)
    autoencoder.compile(optimizer='adam', loss='mse')

    autoencoder.summary()


    autoencoder.fit(X_train_scaled, X_train_scaled, epochs=50, batch_size=32, validation_split=0.1)
    return autoencoder, scaler

In [126]:
start_year = 1994
end_year = 2004

air_fitted_model, air_fitted_scaler = datasplit_autoencoder(wr_air_df, start_year , end_year, ml_col_all)
std_fitted_model, std_fitted_scaler = datasplit_autoencoder(wr_std_df, start_year, end_year,  ml_col_all)

                tmod           tamb          pflow          psamp  \
count  115249.000000  115249.000000  115249.000000  115249.000000
mean       39.642425      23.871124     819.061056     756.455097
std         2.635811      22.069524      27.857699       9.459144
min        20.250000      16.120000     379.000000     716.100000
25%        40.000000      20.410000     803.500000     750.710000
50%        40.000000      20.730000     814.600000     757.360000
75%        40.000000      21.120000     838.800000     763.170000
max        43.770000     186.000000     877.600000     782.570000

                pamb         CH4_rt          CH4_w        CH4_ht  \
count  115249.000000  115249.000000  115249.000000  1.152490e+05
mean      756.484142      99.663742       7.829053  1.654126e+05
std         9.512825       2.383501       0.350782  2.429475e+04
min       716.000000       0.000000       0.000000  0.000000e+00
25%       750.700000      98.600000       7.610000  1.499530e+05
50%       757.400000     100.000000       7.760000  1.598230e+05
75%       763.200000     101.000000       7.980000  1.803220e+05
max       878.600000     114.000000      33.590000  1.563059e+06

           CH4_area       CH4_skew  CH4_start_time   CH4_end_time  \
count  1.152490e+05  115249.000000   115249.000000  115249.000000
mean   1.408683e+06       1.060904       86.173175     136.817097
std    2.238594e+05       0.040099        2.165919       3.510426
min    0.000000e+00       0.000000        0.000000       0.000000
25%    1.248619e+06       1.030000       85.000000     135.000000
50%    1.376992e+06       1.060000       86.000000     137.200000
75%    1.573490e+06       1.090000       87.000000     139.200000
max    9.022030e+06       1.530000      102.000000     152.000000

       CH4_start_level  CH4_end_level    label1       duration  \
count    115249.000000  115249.000000  115249.0  115249.000000
mean      27464.192678   27592.370537       0.0      50.643922
std        8515.214367    8621.142632       0.0       2.834139
min           0.000000       0.000000       0.0       0.000000
25%       21349.000000   21397.000000       0.0      48.400000
50%       24714.000000   24872.000000       0.0      50.200000
75%       33224.000000   33437.000000       0.0      53.200000
max       99999.000000   99999.000000       0.0      68.800000

       is_CH4_rt_zero  is_CH4_w_zero  is_CH4_ht_zero  is_CH4_area_zero  \
count   115249.000000  115249.000000   115249.000000     115249.000000
mean         0.000174       0.000182        0.000182          0.000182
std          0.013172       0.013498        0.013498          0.013498
min          0.000000       0.000000        0.000000          0.000000
25%          0.000000       0.000000        0.000000          0.000000
50%          0.000000       0.000000        0.000000          0.000000
75%          0.000000       0.000000        0.000000          0.000000
max          1.000000       1.000000        1.000000          1.000000

       is_CH4_skew_zero  is_CH4_start_time_zero  is_CH4_end_time_zero  \
count     115249.000000           115249.000000         115249.000000
mean           0.000174                0.000174              0.000174
std            0.013172                0.013172              0.013172
min            0.000000                0.000000              0.000000
25%            0.000000                0.000000              0.000000
50%            0.000000                0.000000              0.000000
75%            0.000000                0.000000              0.000000
max            1.000000                1.000000              1.000000

       is_CH4_start_level_zero  is_CH4_end_level_zero  is_year__1994  \
count            115249.000000          115249.000000  115249.000000
mean                  0.000174               0.000174       0.084834
std                   0.013172               0.013172       0.278635
min                   0.000000               0.000000       0.000000
25%                   0.000000               0.000000       0.000000
50%                   0.000000               0.000000       0.000000
75%                   0.000000               0.000000       0.000000
max                   1.000000               1.000000       1.000000

       is_year__1995  is_year__1996  is_year__1997  is_year__1998  \
count  115249.000000  115249.000000  115249.000000  115249.000000
mean        0.099029       0.097415       0.086829       0.085389
std         0.298702       0.296524       0.281586       0.279461
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000       0.000000
50%         0.000000       0.000000       0.000000       0.000000
75%         0.000000       0.000000       0.000000       0.000000
max         1.000000       1.000000       1.000000       1.000000

       is_year__1999  is_year__2000  is_year__2001  is_year__2002  \
count  115249.000000  115249.000000  115249.000000  115249.000000
mean        0.089840       0.091636       0.088070       0.090942
std         0.285954       0.288513       0.283398       0.287528
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000       0.000000
50%         0.000000       0.000000       0.000000       0.000000
75%         0.000000       0.000000       0.000000       0.000000
max         1.000000       1.000000       1.000000       1.000000

       is_year__2003  is_year__2004  is_year__2005  is_year__2006  \
count  115249.000000  115249.000000       115249.0       115249.0
mean        0.093849       0.092166            0.0            0.0
std         0.291620       0.289261            0.0            0.0
min         0.000000       0.000000            0.0            0.0
25%         0.000000       0.000000            0.0            0.0
50%         0.000000       0.000000            0.0            0.0
75%         0.000000       0.000000            0.0            0.0
max         1.000000       1.000000            0.0            0.0

       is_year__2007  is_year__2008  is_year__2009  is_year__2010  \
count       115249.0       115249.0       115249.0       115249.0
mean             0.0            0.0            0.0            0.0
std              0.0            0.0            0.0            0.0
min              0.0            0.0            0.0            0.0
25%              0.0            0.0            0.0            0.0
50%              0.0            0.0            0.0            0.0
75%              0.0            0.0            0.0            0.0
max              0.0            0.0            0.0            0.0

       is_year__2011  is_year__2012  is_year__2013  is_year__2014  \
count       115249.0       115249.0       115249.0       115249.0
mean             0.0            0.0            0.0            0.0
std              0.0            0.0            0.0            0.0
min              0.0            0.0            0.0            0.0
25%              0.0            0.0            0.0            0.0
50%              0.0            0.0            0.0            0.0
75%              0.0            0.0            0.0            0.0
max              0.0            0.0            0.0            0.0

       is_year__2015  is_year__2016  is_year__2017  is_year__2018  \
count       115249.0       115249.0       115249.0       115249.0
mean             0.0            0.0            0.0            0.0
std              0.0            0.0            0.0            0.0
min              0.0            0.0            0.0            0.0
25%              0.0            0.0            0.0            0.0
50%              0.0            0.0            0.0            0.0
75%              0.0            0.0            0.0            0.0
max              0.0            0.0            0.0            0.0

       is_year__2019  is_year__2020  is_year__2021  is_year__2022  \
count       115249.0       115249.0       115249.0       115249.0
mean             0.0            0.0            0.0            0.0
std              0.0            0.0            0.0            0.0
min              0.0            0.0            0.0            0.0
25%              0.0            0.0            0.0            0.0
50%              0.0            0.0            0.0            0.0
75%              0.0            0.0            0.0            0.0
max              0.0            0.0            0.0            0.0

       is_year__2023  is_year__2024  is_year__2025  CH4_area_ht_ratio  \
count       115249.0       115249.0       115249.0      115249.000000
mean             0.0            0.0            0.0           8.501348
std              0.0            0.0            0.0           0.415360
min              0.0            0.0            0.0           0.000000
25%              0.0            0.0            0.0           8.233555
50%              0.0            0.0            0.0           8.452328
75%              0.0            0.0            0.0           8.619625
max              0.0            0.0            0.0          31.802954

       CH4_w_ht_ratio  psamp_pflow_ratio  w_duration_ratio  CH4_area_diff_1  \
count   115249.000000      115249.000000     115249.000000     1.152490e+05
mean         0.000048           0.924914          0.154981     2.133702e+00
std          0.000006           0.044970          0.010488     1.968173e+05
min          0.000000           0.876444          0.000000    -7.697601e+06
25%          0.000044           0.901879          0.143269    -2.532000e+03
50%          0.000049           0.936260          0.157917     6.500000e+01
75%          0.000051           0.940138          0.163750     2.637000e+03
max          0.000757           2.022063          0.848232     7.690064e+06

       CH4_ht_diff_1  CH4_rt_diff_1  CH4_area_lag_1   CH4_rt_lag_1  \
count   1.152490e+05  115249.000000    1.152490e+05  115249.000000
mean    3.092435e-02       0.000052    1.408671e+06      99.662867
std     2.513886e+04       1.887317    2.238977e+05       2.401510
min    -1.419869e+06    -102.200000    0.000000e+00       0.000000
25%    -3.900000e+02      -0.200000    1.248618e+06      98.600000
50%     4.000000e+00       0.000000    1.376992e+06     100.000000
75%     3.980000e+02       0.200000    1.573490e+06     101.000000
max     1.404209e+06     102.400000    9.022030e+06     114.000000

          tmod_lag_1     tamb_lag_1    pflow_lag_1    psamp_lag_1  \
count  115249.000000  115249.000000  115249.000000  115249.000000
mean       39.642078      23.870947     819.054001     756.448484
std         2.638396      22.069634      27.961976       9.718037
min         0.000000       0.000000       0.000000       0.000000
25%        40.000000      20.410000     803.500000     750.710000
50%        40.000000      20.730000     814.600000     757.360000
75%        40.000000      21.120000     838.800000     763.170000
max        43.770000     186.000000     877.600000     782.570000

          pamb_lag_1  CH4_w_roll_std_14D  CH4_skew_roll_std_14D  \
count  115249.000000       115249.000000          115249.000000
mean      756.477530            0.070071               0.035567
std         9.770315            0.220266               0.013884
min         0.000000            0.000000               0.000000
25%       750.700000            0.022224               0.032360
50%       757.400000            0.028250               0.033541
75%       763.200000            0.038253               0.034711
max       878.600000           18.123147               0.403051

       CH4_w_roll_mean_14D  CH4_w_residual_14D  CH4_skew_roll_mean_14D  \
count        115249.000000       115249.000000           115249.000000
mean              7.827437            0.001616                1.060860
std               0.328787            0.208740                0.014333
min               0.000000          -25.630000                0.000000
25%               7.618064           -0.016315                1.051032
50%               7.753217            0.005014                1.057433
75%               7.974136            0.027200                1.068063
max              33.590000           33.590000                1.145000

       CH4_skew_residual_14D
count          115249.000000
mean                0.000045
std                 0.038597
min                -1.064758
25%                -0.027588
50%                -0.000115
75%                 0.027897
max                 1.070000

/home/ellie/research_project/.venv/lib/python3.13/site-packages/keras/src/layers/core/dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 3.3854 - val_loss: 6.0195
Epoch 2/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - loss: 0.9706 - val_loss: 9.1333
Epoch 3/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 1.0435 - val_loss: 8.8025
Epoch 4/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - loss: 0.8086 - val_loss: 4.3861
Epoch 5/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.7462 - val_loss: 5.5894
Epoch 6/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.6451 - val_loss: 4.0887
Epoch 7/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - loss: 0.6576 - val_loss: 4.2494
Epoch 8/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - loss: 0.5429 - val_loss: 4.0387
Epoch 9/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - loss: 0.4718 - val_loss: 99.0213
Epoch 10/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - loss: 0.5983 - val_loss: 4.1482
Epoch 11/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.3692 - val_loss: 4.7787
Epoch 12/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.5188 - val_loss: 3.7929
Epoch 13/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.3242 - val_loss: 6.8851
Epoch 14/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.4074 - val_loss: 10.3065
Epoch 15/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.3988 - val_loss: 4.8335
Epoch 16/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.3653 - val_loss: 4.0302
Epoch 17/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.4617 - val_loss: 4.3338
Epoch 18/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.4556 - val_loss: 4.3675
Epoch 19/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - loss: 0.2948 - val_loss: 8.7227
Epoch 20/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.3486 - val_loss: 3.7064
Epoch 21/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.4144 - val_loss: 3.7843
Epoch 22/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - loss: 0.4769 - val_loss: 13.2966
Epoch 23/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.3135 - val_loss: 3.7416
Epoch 24/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.3292 - val_loss: 4.1992
Epoch 25/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.3134 - val_loss: 3.9070
Epoch 26/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.3369 - val_loss: 6.4076
Epoch 27/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.3652 - val_loss: 3.7474
Epoch 28/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.4900 - val_loss: 6.6135
Epoch 29/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.2502 - val_loss: 3.8475
Epoch 30/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - loss: 0.3832 - val_loss: 12.3551
Epoch 31/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.3056 - val_loss: 3.5752
Epoch 32/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - loss: 0.3447 - val_loss: 3.4985
Epoch 33/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.3401 - val_loss: 3.7095
Epoch 34/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - loss: 0.3195 - val_loss: 3.4030
Epoch 35/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - loss: 0.3386 - val_loss: 5.7202
Epoch 36/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - loss: 0.3374 - val_loss: 3.5047
Epoch 37/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - loss: 0.2281 - val_loss: 3.4708
Epoch 38/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - loss: 0.2649 - val_loss: 3.9848
Epoch 39/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - loss: 0.3474 - val_loss: 10.6230
Epoch 40/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - loss: 0.3277 - val_loss: 6.7197
Epoch 41/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - loss: 0.3419 - val_loss: 3.9276
Epoch 42/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - loss: 0.3455 - val_loss: 5.8677
Epoch 43/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - loss: 0.3096 - val_loss: 4.2425
Epoch 44/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - loss: 0.3230 - val_loss: 3.7488
Epoch 45/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - loss: 0.2772 - val_loss: 3.6802
Epoch 46/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.2773 - val_loss: 3.4682
Epoch 47/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - loss: 0.2984 - val_loss: 3.7902
Epoch 48/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.3369 - val_loss: 3.6851
Epoch 49/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - loss: 0.2851 - val_loss: 5.6097
Epoch 50/50
3242/3242 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - loss: 0.2607 - val_loss: 3.5648
                tmod           tamb          pflow          psamp  \
count  131884.000000  131884.000000  131884.000000  131884.000000
mean       40.000973      20.888220     824.874647     756.477657
std         0.040022       1.245573      24.949481       9.484430
min        39.810000      16.870000     476.000000     715.140000
25%        40.000000      20.490000     806.600000     750.770000
50%        40.000000      20.660000     817.300000     757.410000
75%        40.000000      21.120000     846.500000     763.170000
max        43.860000      37.540000     937.600000     782.630000

                pamb         CH4_rt          CH4_w         CH4_ht  \
count  131884.000000  131884.000000  131884.000000  131884.000000
mean      756.536659      99.722215       7.826261  159892.015870
std         9.851263       1.967097       0.310223   13869.936146
min       715.200000      93.600000       5.550000  115356.000000
25%       750.800000      98.600000       7.610000  148905.750000
50%       757.400000     100.000000       7.750000  157342.500000
75%       763.200000     101.000000       7.970000  168125.000000
max      1405.100000     105.200000       9.320000  197765.000000

           CH4_area       CH4_skew  CH4_start_time   CH4_end_time  \
count  1.318840e+05  131884.000000   131884.000000  131884.000000
mean   1.361027e+06       1.060940       86.234529     136.877453
std    1.562335e+05       0.035622        1.818289       2.971999
min    7.360000e+05       0.790000       81.000000     110.000000
25%    1.237415e+06       1.030000       85.000000     135.000000
50%    1.338121e+06       1.060000       86.000000     137.200000
75%    1.452905e+06       1.090000       87.000000     139.400000
max    1.784719e+06       1.290000       91.200000     145.400000

       CH4_start_level  CH4_end_level    label1       duration  \
count    131884.000000  131884.000000  131884.0  131884.000000
mean      27203.723287   27324.245109       0.0      50.642924
std        8354.309682    8455.662064       0.0       2.748580
min       18798.000000   18850.000000       0.0      25.800000
25%       21285.000000   21325.000000       0.0      48.400000
50%       24302.000000   24517.000000       0.0      50.000000
75%       32894.250000   33120.000000       0.0      53.200000
max       99999.000000   99999.000000       0.0      59.400000

       is_CH4_rt_zero  is_CH4_w_zero  is_CH4_ht_zero  is_CH4_area_zero  \
count        131884.0       131884.0        131884.0          131884.0
mean              0.0            0.0             0.0               0.0
std               0.0            0.0             0.0               0.0
min               0.0            0.0             0.0               0.0
25%               0.0            0.0             0.0               0.0
50%               0.0            0.0             0.0               0.0
75%               0.0            0.0             0.0               0.0
max               0.0            0.0             0.0               0.0

       is_CH4_skew_zero  is_CH4_start_time_zero  is_CH4_end_time_zero  \
count          131884.0                131884.0              131884.0
mean                0.0                     0.0                   0.0
std                 0.0                     0.0                   0.0
min                 0.0                     0.0                   0.0
25%                 0.0                     0.0                   0.0
50%                 0.0                     0.0                   0.0
75%                 0.0                     0.0                   0.0
max                 0.0                     0.0                   0.0

       is_CH4_start_level_zero  is_CH4_end_level_zero  is_year__1994  \
count                 131884.0               131884.0  131884.000000
mean                       0.0                    0.0       0.078539
std                        0.0                    0.0       0.269018
min                        0.0                    0.0       0.000000
25%                        0.0                    0.0       0.000000
50%                        0.0                    0.0       0.000000
75%                        0.0                    0.0       0.000000
max                        0.0                    0.0       1.000000

       is_year__1995  is_year__1996  is_year__1997  is_year__1998  \
count  131884.000000  131884.000000  131884.000000  131884.000000
mean        0.093393       0.090754       0.085378       0.086144
std         0.290983       0.287260       0.279445       0.280577
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000       0.000000
50%         0.000000       0.000000       0.000000       0.000000
75%         0.000000       0.000000       0.000000       0.000000
max         1.000000       1.000000       1.000000       1.000000

       is_year__1999  is_year__2000  is_year__2001  is_year__2002  \
count  131884.000000  131884.000000  131884.000000  131884.000000
mean        0.091603       0.093006       0.096380       0.094970
std         0.288466       0.290442       0.295113       0.293174
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000       0.000000
50%         0.000000       0.000000       0.000000       0.000000
75%         0.000000       0.000000       0.000000       0.000000
max         1.000000       1.000000       1.000000       1.000000

       is_year__2003  is_year__2004  is_year__2005  is_year__2006  \
count  131884.000000  131884.000000       131884.0       131884.0
mean        0.095266       0.094568            0.0            0.0
std         0.293582       0.292618            0.0            0.0
min         0.000000       0.000000            0.0            0.0
25%         0.000000       0.000000            0.0            0.0
50%         0.000000       0.000000            0.0            0.0
75%         0.000000       0.000000            0.0            0.0
max         1.000000       1.000000            0.0            0.0

       is_year__2007  is_year__2008  is_year__2009  is_year__2010  \
count       131884.0       131884.0       131884.0       131884.0
mean             0.0            0.0            0.0            0.0
std              0.0            0.0            0.0            0.0
min              0.0            0.0            0.0            0.0
25%              0.0            0.0            0.0            0.0
50%              0.0            0.0            0.0            0.0
75%              0.0            0.0            0.0            0.0
max              0.0            0.0            0.0            0.0

       is_year__2011  is_year__2012  is_year__2013  is_year__2014  \
count       131884.0       131884.0       131884.0       131884.0
mean             0.0            0.0            0.0            0.0
std              0.0            0.0            0.0            0.0
min              0.0            0.0            0.0            0.0
25%              0.0            0.0            0.0            0.0
50%              0.0            0.0            0.0            0.0
75%              0.0            0.0            0.0            0.0
max              0.0            0.0            0.0            0.0

       is_year__2015  is_year__2016  is_year__2017  is_year__2018  \
count       131884.0       131884.0       131884.0       131884.0
mean             0.0            0.0            0.0            0.0
std              0.0            0.0            0.0            0.0
min              0.0            0.0            0.0            0.0
25%              0.0            0.0            0.0            0.0
50%              0.0            0.0            0.0            0.0
75%              0.0            0.0            0.0            0.0
max              0.0            0.0            0.0            0.0

       is_year__2019  is_year__2020  is_year__2021  is_year__2022  \
count       131884.0       131884.0       131884.0       131884.0
mean             0.0            0.0            0.0            0.0
std              0.0            0.0            0.0            0.0
min              0.0            0.0            0.0            0.0
25%              0.0            0.0            0.0            0.0
50%              0.0            0.0            0.0            0.0
75%              0.0            0.0            0.0            0.0
max              0.0            0.0            0.0            0.0

       is_year__2023  is_year__2024  is_year__2025  CH4_area_ht_ratio  \
count       131884.0       131884.0       131884.0      131884.000000
mean             0.0            0.0            0.0           8.496790
std              0.0            0.0            0.0           0.379714
min              0.0            0.0            0.0           6.100593
25%              0.0            0.0            0.0           8.231779
50%              0.0            0.0            0.0           8.448949
75%              0.0            0.0            0.0           8.611361
max              0.0            0.0            0.0           9.686998

       CH4_w_ht_ratio  psamp_pflow_ratio  w_duration_ratio  CH4_area_diff_1  \
count   131884.000000      131884.000000     131884.000000    131884.000000
mean         0.000049           0.917791          0.154968         1.316361
std          0.000004           0.025912          0.009980      4193.874225
min          0.000039           0.808266          0.128283   -447510.000000
25%          0.000047           0.891813          0.143130     -1401.000000
50%          0.000050           0.930741          0.158159        10.000000
75%          0.000052           0.937160          0.163992      1420.000000
max          0.000071           1.525723          0.326357    436973.000000

       CH4_ht_diff_1  CH4_rt_diff_1  CH4_area_lag_1   CH4_rt_lag_1  \
count   131884.00000  131884.000000    1.318840e+05  131884.000000
mean        -0.00712       0.000056    1.361017e+06      99.721448
std        519.50247       0.426534    1.562784e+05       1.986167
min     -37632.00000      -4.800000    0.000000e+00       0.000000
25%       -256.00000      -0.200000    1.237411e+06      98.600000
50%          1.00000       0.000000    1.338121e+06     100.000000
75%        255.00000       0.200000    1.452905e+06     101.000000
max      43043.00000       4.200000    1.784719e+06     105.200000

          tmod_lag_1     tamb_lag_1    pflow_lag_1    psamp_lag_1  \
count  131884.000000  131884.000000  131884.000000  131884.000000
mean       40.000669      20.888064     824.868511     756.471879
std         0.117193       1.246900      25.052624       9.710473
min         0.000000       0.000000       0.000000       0.000000
25%        40.000000      20.490000     806.600000     750.770000
50%        40.000000      20.660000     817.300000     757.410000
75%        40.000000      21.120000     846.500000     763.170000
max        43.860000      37.540000     937.600000     782.630000

          pamb_lag_1  CH4_w_roll_std_14D  CH4_skew_roll_std_14D  \
count  131884.000000       131884.000000          131884.000000
mean      756.530882            0.035645               0.033472
std        10.069109            0.038354               0.001623
min         0.000000            0.000000               0.000000
25%       750.800000            0.021822               0.032497
50%       757.400000            0.028157               0.033493
75%       763.200000            0.036635               0.034459
max      1405.100000            0.511948               0.045370

       CH4_w_roll_mean_14D  CH4_w_residual_14D  CH4_skew_roll_mean_14D  \
count        131884.000000       131884.000000           131884.000000
mean              7.823130            0.003130                1.060910
std               0.308371            0.075906                0.013223
min               0.000000           -2.034454                0.000000
25%               7.614071           -0.017227                1.051674
50%               7.750777            0.003962                1.056680
75%               7.972864            0.025387                1.067495
max               8.714240            7.980000                1.116667

       CH4_skew_residual_14D
count          131884.000000
mean                0.000031
std                 0.033959
min                -0.253859
25%                -0.027551
50%                -0.000627
75%                 0.027368
max                 1.110000

/home/ellie/research_project/.venv/lib/python3.13/site-packages/keras/src/layers/core/dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 10s 2ms/step - loss: 0.1172 - val_loss: 0.0801
Epoch 2/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0670 - val_loss: 0.0871
Epoch 3/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - loss: 0.0609 - val_loss: 0.0911
Epoch 4/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - loss: 0.0561 - val_loss: 0.0943
Epoch 5/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0544 - val_loss: 0.1065
Epoch 6/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0542 - val_loss: 0.0923
Epoch 7/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0530 - val_loss: 0.0915
Epoch 8/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0511 - val_loss: 0.0895
Epoch 9/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0514 - val_loss: 0.0906
Epoch 10/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0515 - val_loss: 0.0926
Epoch 11/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0501 - val_loss: 0.1184
Epoch 12/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0496 - val_loss: 0.0968
Epoch 13/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0481 - val_loss: 0.0996
Epoch 14/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - loss: 0.0475 - val_loss: 0.0956
Epoch 15/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0459 - val_loss: 0.1003
Epoch 16/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0438 - val_loss: 0.1124
Epoch 17/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0441 - val_loss: 0.1127
Epoch 18/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0450 - val_loss: 0.1193
Epoch 19/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0431 - val_loss: 0.1248
Epoch 20/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0412 - val_loss: 0.1369
Epoch 21/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - loss: 0.0420 - val_loss: 0.1492
Epoch 22/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0413 - val_loss: 0.1546
Epoch 23/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - loss: 0.0393 - val_loss: 0.1465
Epoch 24/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0401 - val_loss: 0.1677
Epoch 25/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0400 - val_loss: 0.1688
Epoch 26/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0388 - val_loss: 0.1593
Epoch 27/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - loss: 0.0386 - val_loss: 0.1629
Epoch 28/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0378 - val_loss: 0.1663
Epoch 29/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0379 - val_loss: 0.1748
Epoch 30/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0377 - val_loss: 0.1827
Epoch 31/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - loss: 0.0384 - val_loss: 0.1830
Epoch 32/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0372 - val_loss: 0.2022
Epoch 33/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0364 - val_loss: 0.2047
Epoch 34/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0376 - val_loss: 0.1930
Epoch 35/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0380 - val_loss: 0.2204
Epoch 36/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0384 - val_loss: 0.2169
Epoch 37/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0360 - val_loss: 0.2128
Epoch 38/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - loss: 0.0375 - val_loss: 0.2146
Epoch 39/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0363 - val_loss: 0.2194
Epoch 40/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0364 - val_loss: 0.1991
Epoch 41/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0359 - val_loss: 0.2113
Epoch 42/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - loss: 0.0375 - val_loss: 0.2123
Epoch 43/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0354 - val_loss: 0.2187
Epoch 44/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0361 - val_loss: 0.1988
Epoch 45/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step - loss: 0.0358 - val_loss: 0.2172
Epoch 46/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0351 - val_loss: 0.2101
Epoch 47/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - loss: 0.0346 - val_loss: 0.1978
Epoch 48/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - loss: 0.0351 - val_loss: 0.2234
Epoch 49/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0354 - val_loss: 0.2009
Epoch 50/50
3710/3710 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - loss: 0.0340 - val_loss: 0.2094

In [127]:
import joblib

air_fitted_model.save('air_model_0625.keras')
joblib.dump(air_fitted_scaler, 'air_scaler_0625.pkl')

std_fitted_model.save('std_model_0625.keras')
joblib.dump(std_fitted_scaler, 'std_scaler_0625.pkl')

['std_scaler_0625.pkl']

In [ ]:
import numpy as np
X_all_train_air= w_all_air_df[ml_col_all ]
X_all_train_std= w_all_std_df[ml_col_all ]

X_train_air_scaled = X_all_train_air.copy()
X_train_std_scaled = X_all_train_std.copy()

num_cols = [c for c in X_all_train_air.columns if 'is_' not in c]
X_train_air_scaled[num_cols] = air_fitted_scaler.fit_transform(X_all_train_air[num_cols]) # not sclaer 'is_' columns

num_cols = [c for c in X_all_train_std.columns if 'is_' not in c]
X_train_std_scaled[num_cols] = std_fitted_scaler.fit_transform(X_all_train_std[num_cols]) # not sclaer 'is_' columns
    

# all data scale
#X_all_scaled_air = air_fitted_scaler.transform(X_train_air_scaled[ml_col_all])
#X_all_scaled_std = std_fitted_scaler.transform(X_train_std_scaled[ml_col_all])

# all data fit model 
X_pred_air = air_fitted_model.predict(X_train_air_scaled)
X_pred_std = std_fitted_model.predict(X_train_std_scaled)

print("X_all_train_air shape",X_train_air_scaled.shape )
print("X_pred_air", X_pred_air.shape)
# calculate mse values
mse_air = np.mean(np.power(X_train_std_scaled- X_pred_air, 2), axis=1)
mse_std = np.mean(np.power(X_train_std_scaled - X_pred_std, 2), axis=1)

# mse stores to original dataframe
all_air_df['reconstruction_error'] = mse_air
all_std_df['reconstruction_error'] = mse_air

 2490/11522 ━━━━━━━━━━━━━━━━━━━━ 15:04 100ms/step

#### plotting

In [ ]:
# air plot
import matplotlib.pyplot as plt
air_train_mask = (all_air_df['year'] >= start_year) & (all_air_df['year'] <= end_year)
air_threshold = np.mean(mse_air[air_train_mask]) + 3 * np.std(mse_air[air_train_mask])

plt.figure(figsize=(15, 6))
plt.plot(all_air_df.index, all_air_df['reconstruction_error'], label='Reconstruction Error', alpha=0.6)
plt.axhline(y=air_threshold, color='r', linestyle='--', label=f'Threshold ({air_threshold: .4f})')
plt.title('Autoencoder Anomaly Detection : 30 -Year Reconstruction Error')
plt.xlabel('Time (Index)')
plt.ylabel('Error')
plt.legend()
plt.show()

In [ ]:
#std plot
import matplotlib.pyplot as plt
std_train_mask = (all_std_df['year'] >= start_year) & (all_std_df['year'] <= end_year)
std_threshold = np.mean(mse_std[std_train_mask]) + 3 * np.std(mse_std[std_train_mask])

plt.figure(figsize=(15, 6))
plt.plot(all_std_df.index, all_std_df['reconstruction_error'], label='Reconstruction Error', alpha=0.6)
plt.axhline(y=std_threshold, color='r', linestyle='--', label=f'Threshold ({std_threshold: .4f})')
plt.title('Autoencoder Anomaly Detection : 30 -Year Reconstruction Error')
plt.xlabel('Time (Index)')
plt.ylabel('Error')
plt.legend()
plt.show()

分 type : 只做std, air
可以準備正常和不正常的
----
is_zero+ 補值
ratio faeture
----
會隨時間飄移" rolling_mean, Residual
會可能瞬間失效: diff, shift
代表品質穩定度: rolling_std

end_time = start + width?
----
跳躍式變化: 氣溫，儀器，
    diff(): 
    shift:
長期趨勢變化:peak rt 時間
    rolling mean(14D): 
        start_time, end_time 不做
        skew, width(rolling_std)
        area, height(diff, rolling_mean)
計算殘差(Residual)
rt, start_time(感覺不用?)
----
只拿正常資料做訓練，label1==0
---
RobustScaler 計算均值和離差， 0, 1 (is_zero 等欄位不要放), 直接合併在數值後面
----
1. isolation forest
    標準化數值+ 原始旗標(label1)
2. Autoencoder
    只用最穩的十年，然後再30年一次丟進去看誤差
    
    [標準化數值 +原始旗標]
    threshold 計算方式:
    用計算好的autoencoder 去預測 正常 的訓練資料
    計算正常資料的 重購誤差
    threshold = 3* 訓練集誤差的平均值 + 3* 訓練集誤差標準差
    未來只要: 誤差> threshold -> 異常。

    

要不要計算變化率? a - (a-1) / (t_1) - (t_1-1)

diff 設和前一筆的差距，lag設前一天的那一筆，rolling_std 和mean都設成兩個禮拜，季節標準差和平均?
is 欄位不做標準化，先拿五年來訓練，然後拿後五年的來測試。
-------------------------------------
instrument參數會隨時間飄移，原始數據可能導致模型被誤導以為是正常的數值變化(但其實是drift)?
要做residual: 
-- 
突發型: 當下值- rolling_median (median 對異常值比較不敏感)
飄移型: rt issue, 溫度問題,  當下值-rolling_mean
精度型: bad percision? std_rolling，純粹波動變大?
-----
is_no_peak 特徵: 如果面積為零 
is_rt_anomaly: 譬如rt的residuak 超過 3 * std

-----
殘差加權? 對面積計算residual? 當residual > threshold ，且rt不怎麼變= local contamination?
---
Z-score threshold: 3* std?
IQR threshold: upper = Q3 + 1.5 *IQR
Lower = Q1 - 1.5 * IQR

In [ ]:
data[(data['CH4_area']<=0.1)&(data['label1']==0)].head()

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p,label1,datetime_str,datetime,is_ht_999,is_area_999,is_rt_zero,is_w_zero,duration,ht_area_ratio,type_std,type_air,type_tank,type_blank,type_cal,type_other,year,month,day,hour,minute,seconds
2090,940322,93400,air,10m,G-024,3,10.0,40.01,25.09,NaN,836.9,754.15,NaN,NaN,90.2,0.0,0.0,0.0,0.76,83.6,90.8,28394.0,44771.0,,,,,0,940322093400,1994-03-22 09:34:00,False,False,False,True,7.2,NaN,0,1,0,0,0,0,1994,3,22,9,34,0
2643,940403,43400,cal560,G-024,G-024,1,0.0,40.01,22.21,NaN,848.6,561.72,NaN,751.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,,,,,0,940403043400,1994-04-03 04:34:00,False,False,True,True,0.0,NaN,0,0,0,0,1,0,1994,4,3,4,34,0
2647,940403,55400,cal660,G-024,G-024,1,0.0,40.01,22.12,NaN,846.6,659.73,NaN,749.4,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,,,,,0,940403055400,1994-04-03 05:54:00,False,False,True,True,0.0,NaN,0,0,0,0,1,0,1994,4,3,5,54,0
2651,940403,71400,cal860,G-024,G-024,1,0.0,40.01,22.29,NaN,845.8,858.71,NaN,748.6,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,,,,,0,940403071400,1994-04-03 07:14:00,False,False,True,True,0.0,NaN,0,0,0,0,1,0,1994,4,3,7,14,0
2655,940403,83400,cal960,G-024,G-024,1,0.0,40.00,22.40,NaN,844.7,958.48,NaN,748.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,,,,,0,940403083400,1994-04-03 08:34:00,False,False,True,True,0.0,NaN,0,0,0,0,1,0,1994,4,3,8,34,0

#========== feature eng

In [ ]:
df = data.copy()


env_feature = ['tmod','tamb', 'pflow', 'psamp','pamb']
df.head()

,datetime,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p,label1,datetime_str,is_ht_999,is_area_999,is_rt_zero,is_w_zero,duration,ht_area_ratio,type_std,type_air,type_tank,type_blank,type_cal,type_other,year,month,day,hour,minute,seconds,CH4_area_ht_ratio,CH4_w_ht_ratio,psamp_pflow_ratio
0,1994-02-16 14:29:00,940216,142900,air,10m,G-024,3,10.0,40.00,32.27,NaN,841.9,761.10,NaN,761.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216142900,False,False,True,True,0.0,NaN,0,1,0,0,0,0,1994,2,16,14,29,0,0.000000,0.000000,0.904027
1,1994-02-16 14:49:00,940216,144900,air,10m,G-024,3,10.0,40.00,32.48,NaN,840.4,761.07,NaN,761.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216144900,False,False,True,True,0.0,NaN,0,1,0,0,0,0,1994,2,16,14,49,0,0.000000,0.000000,0.905604
2,1994-02-16 15:09:00,940216,150900,air,10m,G-024,3,10.0,40.01,32.75,NaN,839.4,760.99,NaN,760.9,109.8,2.60,190908.0,496440.0,0.63,102.0,135.4,10063.0,10029.0,F,F,,,1,940216150900,False,False,False,False,33.4,0.384554,0,1,0,0,0,0,1994,2,16,15,9,0,2.600415,0.000014,0.906588
3,1994-02-16 15:29:00,940216,152900,air,10m,G-024,3,10.0,40.00,32.92,NaN,839.6,760.96,NaN,760.9,94.8,6.85,151667.0,1065982.0,1.02,86.2,129.0,99999.0,99999.0,,,,,0,940216152900,False,False,False,False,42.8,0.142279,0,1,0,0,0,0,1994,2,16,15,29,0,7.028437,0.000045,0.906336
4,1994-02-16 18:00:00,940216,180000,air,10m,G-024,3,10.0,40.00,33.31,NaN,845.4,760.72,NaN,760.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216180000,False,False,True,True,0.0,NaN,0,1,0,0,0,0,1994,2,16,18,0,0,0.000000,0.000000,0.899834

In [ ]:
air_df[air_df['label1']==1].tail(20)

,datetime,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p,label1,datetime_str,is_ht_999,is_area_999,is_rt_zero,is_w_zero,duration,ht_area_ratio,type_std,type_air,type_tank,type_blank,type_cal,type_other,year,month,day,hour,minute,seconds
804022,2025-11-01 06:25:00,251101,62500,air,9m,J-280,1,9.0,40.0,20.43,NaN,796.9,740.74,NaN,741.2,95.0,7.89,163112.0,1436377.0,1.13,81.8,134.0,24054.0,24332.0,*,*,A,,1,251101062500,False,False,False,False,52.2,0.113558,0,1,0,0,0,0,2025,11,1,6,25,0
804454,2025-11-07 09:30:00,251107,93000,air,9m,J-280,1,9.0,40.0,21.14,NaN,802.4,743.45,NaN,743.6,94.8,7.93,163084.0,1444796.0,1.09,81.4,134.0,24222.0,24470.0,*,*,A,,1,251107093000,False,False,False,False,52.6,0.112877,0,1,0,0,0,0,2025,11,7,9,30,0
805306,2025-11-19 09:46:00,251119,94600,air,9m,J-280,1,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,A,,1,251119094600,False,False,True,True,0.0,NaN,0,1,0,0,0,0,2025,11,19,9,46,0
805309,2025-11-19 10:45:00,251119,104500,air,9m,J-280,1,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95.6,7.94,176810.0,1543478.0,1.10,82.2,134.2,25408.0,25662.0,F,F,A,,1,251119104500,False,False,False,False,52.0,0.114553,0,1,0,0,0,0,2025,11,19,10,45,0
805311,2025-11-19 11:25:00,251119,112500,air,9m,J-280,1,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95.6,7.94,177101.0,1544468.0,1.11,82.2,134.2,25383.0,25696.0,F,F,A,,1,251119112500,False,False,False,False,52.0,0.114668,0,1,0,0,0,0,2025,11,19,11,25,0
805313,2025-11-19 12:05:00,251119,120500,air,9m,J-280,1,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95.6,7.96,176365.0,1542233.0,1.10,82.0,134.2,25401.0,25718.0,F,F,A,,1,251119120500,False,False,False,False,52.2,0.114357,0,1,0,0,0,0,2025,11,19,12,5,0
805315,2025-11-19 12:45:00,251119,124500,air,9m,J-280,1,9.0,40.0,21.67,NaN,NaN,NaN,NaN,NaN,95.6,7.94,176750.0,1543711.0,1.11,82.2,134.2,25416.0,25704.0,F,F,A,,1,251119124500,False,False,False,False,52.0,0.114497,0,1,0,0,0,0,2025,11,19,12,45,0
805374,2025-11-20 08:46:00,251120,84600,air,9m,J-280,1,9.0,40.0,21.72,NaN,826.0,765.72,NaN,765.6,94.8,7.95,169925.0,1508920.0,1.10,81.4,134.0,24146.0,24398.0,*,*,A,,1,251120084600,False,False,False,False,52.6,0.112614,0,1,0,0,0,0,2025,11,20,8,46,0
805611,2025-11-23 16:48:00,251123,164800,air,9m,J-280,1,9.0,40.0,21.99,NaN,804.6,743.90,NaN,743.8,94.8,7.90,163593.0,1443745.0,1.07,81.4,134.0,23724.0,24005.0,*,*,A,,1,251123164800,False,False,False,False,52.6,0.113312,0,1,0,0,0,0,2025,11,23,16,48,0
805660,2025-11-24 09:28:00,251124,92800,air,9m,J-280,1,9.0,40.0,21.82,NaN,810.0,749.78,NaN,749.9,94.8,8.00,165123.0,1475891.0,1.15,81.6,134.4,23889.0,24193.0,*,*,A,,1,251124092800,False,False,False,False,52.8,0.111880,0,1,0,0,0,0,2025,11,24,9,28,0
805704,2025-11-25 00:08:00,251125,800,air,9m,J-280,1,9.0,40.0,22.02,NaN,810.7,760.41,NaN,760.6,94.6,7.97,167760.0,1495030.0,1.13,81.2,134.0,24138.0,24444.0,*,*,A,,1,251125000800,False,False,False,False,52.8,0.112212,0,1,0,0,0,0,2025,11,25,0,8,0
806121,2025-12-02 13:39:00,251202,133900,air,9m,J-280,1,9.0,40.0,21.74,NaN,793.6,742.34,NaN,742.3,94.6,7.94,161849.0,1436140.0,1.12,81.2,133.6,23567.0,23849.0,*,*,A,,1,251202133900,False,False,False,False,52.4,0.112697,0,1,0,0,0,0,2025,12,2,13,39,0
806180,2025-12-03 09:40:00,251203,94000,air,9m,J-280,1,9.0,40.0,21.46,NaN,800.8,747.35,NaN,747.5,94.6,7.91,164067.0,1449694.0,1.05,81.2,133.8,23753.0,23992.0,*,*,A,,1,251203094000,False,False,False,False,52.6,0.113174,0,1,0,0,0,0,2025,12,3,9,40,0
806728,2025-12-11 03:04:00,251211,30400,air,9m,J-280,1,9.0,40.0,20.28,NaN,800.7,748.88,NaN,748.8,94.2,7.88,163312.0,1438343.0,1.14,81.0,133.2,24237.0,24495.0,*,*,A,,1,251211030400,False,False,False,False,52.2,0.113542,0,1,0,0,0,0,2025,12,11,3,4,0
806792,2025-12-12 00:24:00,251212,2400,air,9m,J-280,1,9.0,40.0,20.43,NaN,803.6,752.04,NaN,752.2,94.2,7.90,164312.0,1449788.0,1.10,80.8,133.2,24214.0,24477.0,*,*,A,,1,251212002400,False,False,False,False,52.4,0.113335,0,1,0,0,0,0,2025,12,12,0,24,0
807140,2025-12-16 22:07:00,251216,220700,air,9m,J-286,1,9.0,40.0,20.72,NaN,801.2,751.05,NaN,751.0,94.6,7.92,166298.0,1472565.0,1.13,81.4,134.0,24184.0,24467.0,*,*,A,,1,251216220700,False,False,False,False,52.6,0.112931,0,1,0,0,0,0,2025,12,16,22,7,0
807274,2025-12-18 19:28:00,251218,192800,air,9m,J-286,1,9.0,40.0,20.65,NaN,791.1,742.25,NaN,742.3,94.4,7.79,165842.0,1443338.0,1.14,81.2,133.4,23650.0,23984.0,*,*,A,,1,251218192800,False,False,False,False,52.2,0.114902,0,1,0,0,0,0,2025,12,18,19,28,0
807512,2025-12-22 04:11:00,251222,41100,air,9m,J-286,1,9.0,40.0,20.90,NaN,802.3,752.30,NaN,752.3,94.4,7.93,173150.0,1534328.0,1.07,81.0,134.0,23877.0,24144.0,*,*,A,,1,251222041100,False,False,False,False,53.0,0.112851,0,1,0,0,0,0,2025,12,22,4,11,0
807540,2025-12-22 13:31:00,251222,133100,air,9m,J-286,1,9.0,40.0,20.77,NaN,802.0,751.72,NaN,751.7,94.6,7.97,175589.0,1564546.0,1.07,81.2,134.2,23926.0,24240.0,*,*,A,,1,251222133100,False,False,False,False,53.0,0.112230,0,1,0,0,0,0,2025,12,22,13,31,0
808051,2025-12-29 18:17:00,251229,181700,air,9m,J-286,1,9.0,40.0,20.85,NaN,820.2,771.02,NaN,771.3,94.2,7.91,175113.0,1549721.0,1.07,80.8,133.8,23926.0,24235.0,*,*,A,,1,251229181700,False,False,False,False,53.0,0.112996,0,1,0,0,0,0,2025,12,29,18,17,0

In [ ]:
### env