In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
sns.set_theme(style='darkgrid')
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
raw_data = pd.read_csv('../data/processed/mhd_ch4_ml_v2.csv')
raw_data.head()

/tmp/ipykernel_878/748870625.py:7: DtypeWarning: Columns (37) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_data = pd.read_csv('../data/processed/mhd_ch4_ml_v2.csv')

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p,CH4_flag_ht_bin,CH4_flag_a_bin,label1,datetime_str,datetime,is_ht_999,is_area_999,is_rt_zero,is_w_zero,duration,is_duration_spike,baseline_drift,ht_area_ratio,last_std_time,seconds_since_last_std,type_std,type_air,type_tank,type_blank,type_cal,type_other,last_cal_time,seconds_since_last_cal,year,month,day,hour,minute,seconds,psamp_roll_mean_10,pamb_roll_mean_10,pflow_roll_mean_10,tmod_roll_mean_10,psamp_roll_mean_100,pamb_roll_mean_100,pflow_roll_mean_100,tmod_roll_mean_100,psamp_roll_std_10,pamb_roll_std_10,pflow_roll_std_10,CH4_rt_roll_std_10,psamp_roll_std_100,pamb_roll_std_100,pflow_roll_std_100,CH4_rt_roll_std_100,psamp_diff_1,pflow_diff_1,CH4_area_diff_1,psamp_lag_1,pflow_lag_1
0,940216,142900,air,10m,G-024,3,10.0,40.00,32.27,NaN,841.9,761.10,NaN,761.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,,1,1,1,940216142900,1994-02-16 14:29:00,False,False,True,True,0.0,False,0.0,NaN,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,14,29,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,940216,144900,air,10m,G-024,3,10.0,40.00,32.48,NaN,840.4,761.07,NaN,761.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,,1,1,1,940216144900,1994-02-16 14:49:00,False,False,True,True,0.0,False,0.0,NaN,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,14,49,0,761.100000,761.100000,841.900000,40.000000,761.100000,761.100000,841.900000,40.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,761.10,841.9
2,940216,150900,air,10m,G-024,3,10.0,40.01,32.75,NaN,839.4,760.99,NaN,760.9,109.8,2.60,190908.0,496440.0,0.63,102.0,135.4,10063.0,10029.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,,1,1,1,940216150900,1994-02-16 15:09:00,False,False,False,False,33.4,False,-34.0,0.384554,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,15,9,0,761.085000,761.150000,841.150000,40.000000,761.085000,761.150000,841.150000,40.000000,0.021213,0.070711,1.060660,0.000000,0.021213,0.070711,1.060660,0.000000,-0.03,-1.5,0.0,761.07,840.4
3,940216,152900,air,10m,G-024,3,10.0,40.00,32.92,NaN,839.6,760.96,NaN,760.9,94.8,6.85,151667.0,1065982.0,1.02,86.2,129.0,99999.0,99999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,,,,,0,0,0,940216152900,1994-02-16 15:29:00,False,False,False,False,42.8,False,0.0,0.142279,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,15,29,0,761.053333,761.066667,840.566667,40.003333,761.053333,761.066667,840.566667,40.003333,0.056862,0.152753,1.258306,63.393060,0.056862,0.152753,1.258306,63.393060,-0.08,-1.0,496440.0,760.99,839.4
4,940216,180000,air,10m,G-024,3,10.0,40.00,33.31,NaN,845.4,760.72,NaN,760.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,,1,1,1,940216180000,1994-02-16 18:00:00,False,False,True,True,0.0,False,0.0,NaN,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,18,0,0,761.030000,761.025000,840.325000,40.002500,761.030000,761.025000,840.325000,40.002500,0.065828,0.150000,1.135415,59.379542,0.065828,0.150000,1.135415,59.379542,-0.03,0.2,569542.0,760.96,839.6

In [2]:
raw_data.isna().sum()

date                           0
time                           0
type                           0
sample                         0
standard                       0
port                           0
ht                             0
tmod                      112284
tamb                      112285
lab_temp                  817954
pflow                       2402
psamp                       2330
ploop                     817954
pamb                        2404
CH4_rt                      1590
CH4_w                       1590
CH4_ht                      1590
CH4_area                    1590
CH4_skew                    1590
CH4_start_time              1590
CH4_end_time                1590
CH4_start_level             1590
CH4_end_level               1590
CH4_Rl_ht                  51247
CH4_Rl_a                   49492
CH4_Rl                     58674
CH4_norm_ht                51247
CH4_norm_a                 51247
CH4_norm_w                 51247
CH4_R_ht                   51247
CH4_R_a                    49492
CH4_R                      58674
CH4_C_ht                   52743
CH4_C_a                    50993
CH4_C                      59835
CH4_std_stdev              21817
CH4_std_rep               471913
CH4_Cstd                       0
CH4_flag_ht                    0
CH4_flag_a                     0
CH4_flag                       0
CH4_flag_p                     0
CH4_flag_ht_bin                0
CH4_flag_a_bin                 0
label1                         0
datetime_str                   0
datetime                       0
is_ht_999                      0
is_area_999                    0
is_rt_zero                     0
is_w_zero                      0
duration                    1590
is_duration_spike              0
baseline_drift              1590
ht_area_ratio              18296
last_std_time                 74
seconds_since_last_std        74
type_std                       0
type_air                       0
type_tank                      0
type_blank                     0
type_cal                       0
type_other                     0
last_cal_time                173
seconds_since_last_cal       173
year                           0
month                          0
day                            0
hour                           0
minute                         0
seconds                        0
psamp_roll_mean_10          1559
pamb_roll_mean_10           1593
pflow_roll_mean_10          1559
tmod_roll_mean_10         111489
psamp_roll_mean_100          557
pamb_roll_mean_100           558
pflow_roll_mean_100          557
tmod_roll_mean_100        109309
psamp_roll_std_10           1708
pamb_roll_std_10            1718
pflow_roll_std_10           1708
CH4_rt_roll_std_10          1460
psamp_roll_std_100           564
pamb_roll_std_100            565
pflow_roll_std_100           564
CH4_rt_roll_std_100          973
psamp_diff_1                2555
pflow_diff_1                2701
CH4_area_diff_1             1639
psamp_lag_1                 2331
pflow_lag_1                 2403
dtype: int64

condition: ht = 0 -> CH4_C = Nan -> air and std together (std error air std) flagged

if it is label2 = 1

In [3]:
# chec ht = 0 and c is nan
data = raw_data.copy()
data= data.drop(data[data['year']==2026].index)
data['is_ht_zero_and_C_Nan'] = ((data['CH4_ht'] == 0)&(data['CH4_C'].isna())).astype(int)
data.head()

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p,CH4_flag_ht_bin,CH4_flag_a_bin,label1,datetime_str,datetime,is_ht_999,is_area_999,is_rt_zero,is_w_zero,duration,is_duration_spike,baseline_drift,ht_area_ratio,last_std_time,seconds_since_last_std,type_std,type_air,type_tank,type_blank,type_cal,type_other,last_cal_time,seconds_since_last_cal,year,month,day,hour,minute,seconds,psamp_roll_mean_10,pamb_roll_mean_10,pflow_roll_mean_10,tmod_roll_mean_10,psamp_roll_mean_100,pamb_roll_mean_100,pflow_roll_mean_100,tmod_roll_mean_100,psamp_roll_std_10,pamb_roll_std_10,pflow_roll_std_10,CH4_rt_roll_std_10,psamp_roll_std_100,pamb_roll_std_100,pflow_roll_std_100,CH4_rt_roll_std_100,psamp_diff_1,pflow_diff_1,CH4_area_diff_1,psamp_lag_1,pflow_lag_1,is_ht_zero_and_C_Nan
0,940216,142900,air,10m,G-024,3,10.0,40.00,32.27,NaN,841.9,761.10,NaN,761.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,,1,1,1,940216142900,1994-02-16 14:29:00,False,False,True,True,0.0,False,0.0,NaN,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,14,29,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,940216,144900,air,10m,G-024,3,10.0,40.00,32.48,NaN,840.4,761.07,NaN,761.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,,1,1,1,940216144900,1994-02-16 14:49:00,False,False,True,True,0.0,False,0.0,NaN,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,14,49,0,761.100000,761.100000,841.900000,40.000000,761.100000,761.100000,841.900000,40.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,761.10,841.9,1
2,940216,150900,air,10m,G-024,3,10.0,40.01,32.75,NaN,839.4,760.99,NaN,760.9,109.8,2.60,190908.0,496440.0,0.63,102.0,135.4,10063.0,10029.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,,1,1,1,940216150900,1994-02-16 15:09:00,False,False,False,False,33.4,False,-34.0,0.384554,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,15,9,0,761.085000,761.150000,841.150000,40.000000,761.085000,761.150000,841.150000,40.000000,0.021213,0.070711,1.060660,0.000000,0.021213,0.070711,1.060660,0.000000,-0.03,-1.5,0.0,761.07,840.4,0
3,940216,152900,air,10m,G-024,3,10.0,40.00,32.92,NaN,839.6,760.96,NaN,760.9,94.8,6.85,151667.0,1065982.0,1.02,86.2,129.0,99999.0,99999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,,,,,0,0,0,940216152900,1994-02-16 15:29:00,False,False,False,False,42.8,False,0.0,0.142279,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,15,29,0,761.053333,761.066667,840.566667,40.003333,761.053333,761.066667,840.566667,40.003333,0.056862,0.152753,1.258306,63.393060,0.056862,0.152753,1.258306,63.393060,-0.08,-1.0,496440.0,760.99,839.4,0
4,940216,180000,air,10m,G-024,3,10.0,40.00,33.31,NaN,845.4,760.72,NaN,760.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,,1,1,1,940216180000,1994-02-16 18:00:00,False,False,True,True,0.0,False,0.0,NaN,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,18,0,0,761.030000,761.025000,840.325000,40.002500,761.030000,761.025000,840.325000,40.002500,0.065828,0.150000,1.135415,59.379542,0.065828,0.150000,1.135415,59.379542,-0.03,0.2,569542.0,760.96,839.6,1

In [4]:
data['previous_point_type'] = data['type'].shift(1)
data['next_point_type'] =data['type'].shift(-1)

In [5]:
# prvious is std, next is air
first_index = data[((data['is_ht_zero_and_C_Nan']==1)&((data['type'] == 'std')|(data['type'] == 'air')) & (data['previous_point_type']=='std')&((data['next_point_type']=='air')))].index.tolist()
first_index

[1852,
 8362,
 17866,
 23048,
 34409,
 36836,
 36842,
 42012,
 42791,
 50469,
 52619,
 59354,
 65204,
 68423,
 68628,
 69993,
 76509,
 76550,
 76621,
 76626,
 78863,
 91847,
 96893,
 102143,
 102146,
 113751,
 116652,
 122354,
 122519,
 122534,
 123244,
 124163,
 124194,
 125896,
 129964,
 130260,
 136202,
 144561,
 150213,
 157423,
 164448,
 165196,
 166250,
 168772,
 169139,
 170128,
 180582,
 184809,
 185661,
 188425,
 196840,
 213553,
 213638,
 214131,
 214188,
 214690,
 218304,
 218335,
 221369,
 238494,
 238565,
 238708,
 242234,
 257590,
 265541,
 265610,
 267596,
 268874,
 270649,
 272792,
 273143,
 276806,
 291836,
 291907,
 291978,
 292049,
 292120,
 292191,
 292264,
 292335,
 292404,
 292475,
 292546,
 292617,
 304380,
 308100,
 309189,
 311860,
 323247,
 323252,
 323297,
 323324,
 323334,
 323344,
 323352,
 323353,
 323358,
 323361,
 336296,
 336367,
 336438,
 336509,
 342336,
 405608,
 411310,
 425738,
 425809,
 453776,
 474999,
 475070,
 475141,
 490701,
 490772,
 490843,
 492763,
 501648,
 516193,
 520210,
 520281,
 520352,
 520423,
 520494,
 520525,
 520564,
 520635,
 520706,
 520777,
 520848,
 520919,
 520990,
 521061,
 521132,
 521203,
 521274,
 521345,
 521416,
 521487,
 521558,
 521629,
 521700,
 521771,
 521842,
 521913,
 521984,
 522055,
 522126,
 522197,
 522230,
 522435,
 523249,
 523320,
 523391,
 523462,
 523533,
 523604,
 523675,
 523744,
 523815,
 523886,
 523957,
 525374,
 525445,
 543065,
 560789,
 585072,
 585075,
 617205,
 619817,
 619995,
 655771,
 655842,
 655913,
 655984,
 656006,
 656039,
 658026,
 658310,
 669547,
 688036,
 688107,
 716199,
 716242,
 716313,
 719070,
 719141,
 719850,
 720350,
 725506,
 725549,
 737741,
 737768,
 737839,
 737910,
 737981,
 738052,
 738123,
 738549,
 738620,
 738691,
 738762,
 738833,
 738904,
 738975,
 739046,
 739117,
 739188,
 739259,
 739330,
 739401,
 739472,
 739543,
 739614,
 739685,
 739754,
 739825,
 739896,
 739967,
 740038,
 740109,
 740180,
 740251,
 740322,
 740393,
 740464,
 740535,
 740606,
 740677,
 740748,
 740819,
 740890,
 740961,
 741032,
 741103,
 741171,
 741242,
 741313,
 741384,
 746706,
 746739,
 749053,
 758735,
 774322,
 774345,
 792633,
 792704,
 792775,
 798462]

In [6]:
# previous is air,next is std
second_index = data[((data['is_ht_zero_and_C_Nan']==1)&((data['type'] == 'std')|(data['type'] == 'air'))&(data['previous_point_type']=='std')&((data['next_point_type']=='air')))].index.tolist()
second_index

[1852,
 8362,
 17866,
 23048,
 34409,
 36836,
 36842,
 42012,
 42791,
 50469,
 52619,
 59354,
 65204,
 68423,
 68628,
 69993,
 76509,
 76550,
 76621,
 76626,
 78863,
 91847,
 96893,
 102143,
 102146,
 113751,
 116652,
 122354,
 122519,
 122534,
 123244,
 124163,
 124194,
 125896,
 129964,
 130260,
 136202,
 144561,
 150213,
 157423,
 164448,
 165196,
 166250,
 168772,
 169139,
 170128,
 180582,
 184809,
 185661,
 188425,
 196840,
 213553,
 213638,
 214131,
 214188,
 214690,
 218304,
 218335,
 221369,
 238494,
 238565,
 238708,
 242234,
 257590,
 265541,
 265610,
 267596,
 268874,
 270649,
 272792,
 273143,
 276806,
 291836,
 291907,
 291978,
 292049,
 292120,
 292191,
 292264,
 292335,
 292404,
 292475,
 292546,
 292617,
 304380,
 308100,
 309189,
 311860,
 323247,
 323252,
 323297,
 323324,
 323334,
 323344,
 323352,
 323353,
 323358,
 323361,
 336296,
 336367,
 336438,
 336509,
 342336,
 405608,
 411310,
 425738,
 425809,
 453776,
 474999,
 475070,
 475141,
 490701,
 490772,
 490843,
 492763,
 501648,
 516193,
 520210,
 520281,
 520352,
 520423,
 520494,
 520525,
 520564,
 520635,
 520706,
 520777,
 520848,
 520919,
 520990,
 521061,
 521132,
 521203,
 521274,
 521345,
 521416,
 521487,
 521558,
 521629,
 521700,
 521771,
 521842,
 521913,
 521984,
 522055,
 522126,
 522197,
 522230,
 522435,
 523249,
 523320,
 523391,
 523462,
 523533,
 523604,
 523675,
 523744,
 523815,
 523886,
 523957,
 525374,
 525445,
 543065,
 560789,
 585072,
 585075,
 617205,
 619817,
 619995,
 655771,
 655842,
 655913,
 655984,
 656006,
 656039,
 658026,
 658310,
 669547,
 688036,
 688107,
 716199,
 716242,
 716313,
 719070,
 719141,
 719850,
 720350,
 725506,
 725549,
 737741,
 737768,
 737839,
 737910,
 737981,
 738052,
 738123,
 738549,
 738620,
 738691,
 738762,
 738833,
 738904,
 738975,
 739046,
 739117,
 739188,
 739259,
 739330,
 739401,
 739472,
 739543,
 739614,
 739685,
 739754,
 739825,
 739896,
 739967,
 740038,
 740109,
 740180,
 740251,
 740322,
 740393,
 740464,
 740535,
 740606,
 740677,
 740748,
 740819,
 740890,
 740961,
 741032,
 741103,
 741171,
 741242,
 741313,
 741384,
 746706,
 746739,
 749053,
 758735,
 774322,
 774345,
 792633,
 792704,
 792775,
 798462]

In [7]:
data[((data['is_ht_zero_and_C_Nan']==1)&(data['previous_point_type']=='std')&((data['type'] == 'std')|(data['type'] == 'air'))&((data['next_point_type']=='air')))]

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p,CH4_flag_ht_bin,CH4_flag_a_bin,label1,datetime_str,datetime,is_ht_999,is_area_999,is_rt_zero,is_w_zero,duration,is_duration_spike,baseline_drift,ht_area_ratio,last_std_time,seconds_since_last_std,type_std,type_air,type_tank,type_blank,type_cal,type_other,last_cal_time,seconds_since_last_cal,year,month,day,hour,minute,seconds,psamp_roll_mean_10,pamb_roll_mean_10,pflow_roll_mean_10,tmod_roll_mean_10,psamp_roll_mean_100,pamb_roll_mean_100,pflow_roll_mean_100,tmod_roll_mean_100,psamp_roll_std_10,pamb_roll_std_10,pflow_roll_std_10,CH4_rt_roll_std_10,psamp_roll_std_100,pamb_roll_std_100,pflow_roll_std_100,CH4_rt_roll_std_100,psamp_diff_1,pflow_diff_1,CH4_area_diff_1,psamp_lag_1,pflow_lag_1,is_ht_zero_and_C_Nan,previous_point_type,next_point_type
1852,940318,130500,std,G-024,G-024,1,0.0,40.06,20.56,NaN,837.3,745.30,NaN,747.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.698,NaN,1692.489,F,F,,,1,1,1,940318130500,1994-03-18 13:05:00,False,False,True,True,0.0,False,0.0,NaN,1994-03-18 10:13:00,10320.0,1,0,0,0,0,0,1994-03-13 10:05:00,442800.0,1994,3,18,13,5,0,752.219000,752.160000,837.250000,40.000000,759.453000,759.451000,845.107000,39.999700,0.916339,0.915545,4.648118,0.289828,3.387688,3.423080,6.141912,0.304385,-0.03,10.5,-88921.0,751.23,840.6,1,std,air
8362,940624,134100,std,G-028,G-028,1,0.0,NaN,NaN,NaN,838.1,751.23,NaN,751.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.032,NaN,1672.724,F,F,,,1,1,1,940624134100,1994-06-24 13:41:00,False,False,True,True,0.0,False,0.0,NaN,1994-06-24 13:13:00,1680.0,1,0,0,0,0,0,1994-06-19 21:47:00,402840.0,1994,6,24,13,41,0,751.092000,751.100000,827.780000,40.002000,756.599300,756.572000,841.207000,40.000500,0.176874,0.194365,27.039633,41.226685,3.956428,3.948023,11.526739,13.751329,0.06,87.3,0.0,751.26,839.1,1,std,air
17866,941105,151800,std,G-032,G-032,1,0.0,40.02,25.39,NaN,822.2,746.18,NaN,746.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.410,NaN,1679.84,F,F,,,1,1,1,941105151800,1994-11-05 15:18:00,False,False,True,True,0.0,False,0.0,NaN,1994-11-05 13:56:00,4920.0,1,0,0,0,0,0,1994-10-30 21:50:00,494880.0,1994,11,5,15,18,0,747.908000,747.920000,819.500000,39.999000,743.944500,743.986000,822.637000,39.999800,0.064429,0.042164,24.982705,40.931601,4.048176,4.048943,8.526070,13.664916,-0.07,75.7,0.0,747.89,824.3,1,std,air
23048,950117,230000,std,G-032,G-032,1,0.0,36.71,16.06,NaN,818.5,717.46,NaN,718.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1679.84,F,F,,,1,1,1,950117230000,1995-01-17 23:00:00,False,False,True,True,0.0,False,0.0,NaN,1995-01-17 20:22:00,9480.0,1,0,0,0,0,0,1995-01-15 22:18:00,175320.0,1995,1,17,23,0,0,709.726000,709.510000,793.400000,39.527000,735.359500,735.250000,822.919000,39.952100,1.555829,1.430190,30.884516,47.118027,12.346885,12.447575,18.337921,16.712479,1.73,5.1,0.0,709.83,812.2,1,std,air
34409,950628,141100,std,G-036,G-036,1,0.0,40.02,26.47,NaN,857.2,761.25,NaN,761.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.695,NaN,1698.794,F,F,,,1,1,1,950628141100,1995-06-28 14:11:00,False,False,True,True,0.0,False,0.0,NaN,1995-06-28 12:39:00,5520.0,1,0,0,0,0,0,1995-06-25 21:56:00,231300.0,1995,6,28,14,11,0,763.363000,763.390000,841.250000,40.001000,764.991400,765.005000,858.099000,40.000300,0.136141,0.144914,41.143171,50.400688,1.156876,1.154733,14.522059,19.165455,-0.21,97.3,0.0,763.03,861.2,1,std,air
36836,950801,192900,std,G-036,G-036,1,0.0,40.01,27.07,NaN,852.8,760.19,NaN,760.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.452,NaN,1698.794,F,F,,,1,1,1,950801192900,1995-08-01 19:29:00,False,False,True,True,0.0,False,0.0,NaN,1995-08-01 18:30:00,3540.0,1,0,0,0,0,0,1995-07-30 21:48:00,164460.0,1995,8,1,19,29,0,759.599000,759.660000,833.600000,40.000000,758.363500,758.393000,847.488000,40.000200,0.245694,0.347051,39.051220,46.980677,0.731266,0.752136,14.081410,16.707475,0.38,93.9,0.0,760.19,854.2,1,std,air
36842,950801,224100,std,G-036,G-036,1,0.0,NaN,NaN,NaN,851.4,760.70,NaN,760.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.546,NaN,1698.794,F,F,,,1,1,1,950801224100,1995-08-01 22:41:00,False,False,True,True,0.0,False,0.0,NaN,1995-08-01 22:24:00,1020.0,1,0,0,0,0,0,1995-07-30 21:48:00,175980.0,1995,8,1,22,41,0,760.236000,760.325000,832.740000,40.000000,758.478900,758.474490,847.553000,40.000202,0.506539,0.449603,38.474846,32.266667,0.899307,0.885078,14.017770,26.686694,-1.05,-1.7,NaN,759.85,850.9,1,std,air
42012,951014,102300,std,G-037,G-037,1,0.0,40.03,22.32,NaN,835.4,749.02,NaN,750.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.458,NaN,1685.169,F,F,,,1,1,1,951014102300,1995-10-14 10:23:00,False,False,True,True,0.0,False,0.0,NaN,1995-10-14 08:10:00,7980.0,1,0,0,0,0,0,1995-10-08 22:23:00,475200.0,1995,10,14,10,23,0,752.788000,752.780000,831.990000,40.000000,755.713700,755.718000,842.192000,40.001000,0.073454,0.103280,27.609638,41.542958,1.668793,1.678346,9.442679,13.877105,0.00,86.4,0.0,752.88,839.9,1,std,air
42791,951025,111400,std,G-037,G-037,1,0.0,40.03,23.09,NaN,829.7,742.64,NaN,743.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.191,NaN,1685.169,F,F,,,1,1,1,951025111400,1995-10-25 11:14:00,False,False,True,True,0.0,False,0.0,NaN,1995-10-25 09:35:00,5940.0,1,0,0,0,0,0,1995-10-22 22:12:00,219720.0,1995,10,25,11,14,0,743.451000,743.560000,823.140000,40.000000,738.515800,738.574000,827.141000,40.000300,0.775076,0.767680,27.621980,41.415558,2.370815,2.388382,9.132903,13.865636,0.37,86.2,0.0,744.49,831.0,1,std,air
50469,960212,92800,std,G-041,G-041,1,0.0,40.00,20.40,NaN,821.2,746.79,NaN,747.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.080,NaN,1704.86,F,F,,,1,1,1,960212092800,1996-02-12 09:28:00,False,False,True,True,0.0,False,0.0,NaN,1996-02-12 08:33:00,3300.0,1,0,0,0,0,0,1996-02-11 21:52:00,41760.0,1996,2,12,9,28,0,744.705000,744.890000,810.730000,39.998000,757.770000,747.158000,829.726000,40.000100,1.017985,1.097927,35.044291,31.110706,76.492847,3.923130,15.044041,9.873792,0.63,73.1,-172409.0,746.30,819.7,1,std,air
52619,960314,201700,std,G-041,G-041,1,0.0,40.13,10.57,NaN,837.9,740.08,NaN,741.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1704.86,F,F,,,1,1,1,960314201700,1996-03-14 20:17:00,False,False,True,True,0.0,False,0.0,NaN,1996-03-13 22:51:00,77160.0,1,0,0,0,0,0,1996-03-10 22:08:00,338940.0,1996,3,14,20,17,0,746.340000,746.320000,826.700000,40.002000,746.212700,746.225000,834.114000,40.000500,0.192642,0.229976,28.931260,42.195634,0.362084,0.374267,11.377019,14.017449,0.00,80.4,0.0,746.04,827.2,1,std,air
59354,960619,123600,std,J-007,J-007,1,0.0,NaN,NaN,NaN,846.9,756.75,NaN,756.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.651,NaN,1814.104,F,F,,,1,1,1,960619123600,1996-06-19 12:36:00,False,False,True,True,0.0,False,0.0,NaN,1996-06-19 11:52:00,2640.0,1,0,0,0,0,0,1996-06-16 21:49:00,226020.0,1996,6,19,12,36,0,757.756000,757.760000,843.450000,40.002000,759.846900,759.860000,853.267000,40.000500,0.247934,0.254733,30.018596,42.090384,1.386068,1.389644,9.984554,14.050400,-0.10,90.4,0.0,757.41,848.6,1,std,air
65204,960910,111400,std,J-007,J-007,1,0.0,40.00,22.40,NaN,866.7,769.44,NaN,769.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.436,NaN,1814.104,F,F,,,1,1,1,960910111400,1996-09-10 11:14:00,False,False,True,True,0.0,False,0.0,NaN,1996-09-10 10:10:00,3840.0,1,0,0,0,0,0,1996-09-08 21:46:00,134880.0,1996,9,10,11,14,0,769.869000,769.890000,865.300000,40.000000,770.787681,770.789855,864.373913,40.000400,0.066742,0.087560,1.507021,31.369794,0.789782,0.777277,16.346241,43.975534,0.05,2.3,1646589.0,769.82,866.7,1,std,air
68423,961026,11200,std,J-007,J-007,1,0.0,40.01,20.62,NaN,835.7,754.12,NaN,754.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.476,NaN,1814.104,F,F,,,1,1,1,961026011200,1996-10-26 01:12:00,False,False,True,True,0.0,False,0.0,NaN,1996-10-26 00:32:00,2400.0,1,0,0,0,0,0,1996-10-20 22:19:00,442380.0,1996,10,26,1,12,0,752.713000,752.800000,842.330000,40.002000,748.636800,748.670000,837.720000,40.000400,0.623450,0.598145,8.064194,0.000000,1.864410,1.887626,7.591635,40.496658,0.16,-11.9,0.0,753.60,835.5,1,std,air
68628,961029,131300,std,J-007,J-007,1,0.0,40.05,18.48,NaN,845.4,757.34,NaN,759.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.359,NaN,1814.104,F,F,,,1,1,1,961029131300,1996-10-29 13:13:00,False,False,True,True,0.0,False,0.0,NaN,1996-10-28 22:57:00,51360.0,1,0,0,0,0,0,1996-10-26 23:59:00,220440.0,1996,10,29,13,13,0,748.682500,748.900000,838.625000,40.000000,735.951170,735.957447,824.787234,40.000440,0.998645,0.860233,7.918070,47.794751,8.935060,8.954431,11.630024,16.981889,NaN,NaN,0.0,NaN,NaN,1,std,air
69993,961118,10500,std,J-007,J-007,1,0.0,40.00,25.64,NaN,849.8,758.70,NaN,758.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.752,NaN,1814.104,F,F,,,1,1,1,961118010500,1996-11-18 01:05:00,False,False,True,True,0.0,False,0.0,NaN,1996-11-18 00:25:00,2400.0,1,0,0,0,0,0,1996-11-17 02:44:00,80460.0,1996,11,18,1,5,0,759.208000,759.220000,853.860000,39.998000,766.303900,760.414000,856.341000,40.000900,0.159847,0.193218,4.911483,0.000000,61.171276,0.986271,3.879657,49.576445,0.00,-11.6,0.0,758.98,849.5,1,std,air
76509,970218,103100,std,J-012,J-012,1,0.0,40.02,15.36,NaN,853.1,742.60,NaN,742.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.565,NaN,1830.624,F,F,,,1,1,1,970218103100,1997-02-18 10:31:00,False,False,True,True,0.0,False,0.0,NaN,1997-02-17 21:20:00,47460.0,1,0,0,0,0,0,1997-02-16 02:58:00,199980.0,1997,2,18,10,31,0,737.141000,737.190000,817.130000,40.002000,739.033200,739.054000,831.642000,39.998800,0.466439,0.481779,33.421784,41.890763,3.722283,3.738104,14.028457,14.037807,0.05,95.4,0.0,737.71,834.5,1,std,air
76550,970219,10100,std,J-012,J-012,1,0.0,40.00,23.97,NaN,848.7,754.04,NaN,753.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1830.624,F,F,,,1,1,1,970219010100,1997-02-19 01:01:00,False,False,True,True,0.0,False,0.0,NaN,1997-02-19 00:21:00,2400.0,1,0,0,0,0,0,1997-02-16 02:58:00,252180.0,1997,2,19,1,1,0,756.489000,756.400000,848.290000,40.001000,743.661800,743.680000,834.347000,40.000400,0.689355,0.700793,4.654138,0.000000,8.574072,8.606739,19.478916,49.606628,-0.29,8.8,0.0,755.21,850.2,1,std,air
76621,970220,10300,std,J-012,J-012,1,0.0,NaN,NaN,NaN,847.4,752.10,NaN,752.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1830.624,F,F,,,1,1,1,970220010300,1997-02-20 01:03:00,False,False,True,True,0.0,False,0.0,NaN,1997-02-20 00:23:00,2400.0,1,0,0,0,0,0,1997-02-16 02:58:00,338700.0,1997,2,20,1,3,0,750.665000,750.780000,841.850000,NaN,746.889200,746.927000,836.264000,40.000899,0.601096,0.657943,4.391722,51.103885,7.565502,7.537983,15.029201,35.881097,0.15,7.0,-1613150.0,751.50,846.9,1,std,air
76626,970224,105000,std,J-012,J-012,1,0.0,40.00,20.37,NaN,825.9,728.59,NaN,728.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.130,NaN,1830.624,F,F,,,1,1,1,970224105000,1997-02-24 10:50:00,False,False,True,True,0.0,False,0.0,NaN,1997-02-20 02:23:00,376020.0,1,0,0,0,0,0,1997-02-16 02:58:00,719520.0,1997,2,24,10,50,0,751.505000,751.650000,843.887500,NaN,746.772143,746.809184,835.942857,40.000833,0.514310,0.486973,3.985129,50.903870,7.596815,7.568016,14.992596,35.881097,NaN,NaN,0.0,NaN,NaN,1,std,air
78863,970328,4500,std,J-012,J-012,1,0.0,40.00,23.36,NaN,861.9,765.16,NaN,765.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1830.624,F,F,,,1,1,1,970328004500,1997-03-28 00:45:00,False,False,True,True,0.0,False,0.0,NaN,1997-03-28 00:05:00,2400.0,1,0,0,0,0,0,1997-03-23 02:59:00,423960.0,1997,3,28,0,45,0,763.724000,763.850000,855.590000,39.998000,758.005300,758.039000,861.657000,39.999400,0.706513,0.694822,6.088870,50.406829,2.999199,3.034412,19.432906,44.484029,0.24,9.3,-1313808.0,764.83,862.6,1,std,air
91847,970929,81500,std,J-016,J-016,1,0.0,40.00,20.10,NaN,865.6,760.40,NaN,760.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.950,NaN,1813.938,F,F,,,1,1,1,970929081500,1997-09-29 08:15:00,False,False,True,True,0.0,False,0.0,NaN,1997-09-28 04:59:00,98160.0,1,0,0,0,0,0,1997-09-28 02:39:00,106560.0,1997,9,29,8,15,0,756.580000,NaN,838.600000,NaN,768.940989,761.184444,862.124176,39.998889,NaN,NaN,NaN,30.753096,82.090873,2.196980,12.031083,9.705034,NaN,NaN,-1762192.0,NaN,NaN,1,std,air
96893,971210,5500,std,J-020,J-020,1,0.0,NaN,NaN,NaN,832.2,735.79,NaN,735.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.391,NaN,1832.32,F,F,,,1,1,1,971210005500,1997-12-10 00:55:00,False,False,True,True,0.0,False,0.0,NaN,1997-12-10 00:15:00,2400.0,1,0,0,0,0,0,1997-12-07 02:31:00,253440.0,1997,12,10,0,55,0,737.553000,737.470000,827.130000,NaN,742.819500,742.807000,833.741000,NaN,1.221902,1.165285,7.746834,0.000000,2.034333,2.061982,13.577678,43.149143,-0.21,14.9,0.0,736.20,833.1,1,std,air
102143,980222,144900,std,J-020,J-020,1,0.0,NaN,NaN,NaN,889.2,766.54,NaN,766.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.095,NaN,1832.32,F,F,,,1,1,1,980222144900,1998-02-22 14:49:00,False,False,True,True,0.0,False,0.0,NaN,1998-02-22 11:21:00,12480.0,1,0,0,0,0,0,1998-02-22 03:00:00,42540.0,1998,2,22,14,49,0,NaN,NaN,NaN,NaN,768.735732,751.682716,862.545122,39.999268,NaN,NaN,NaN,30.078859,95.333764,5.198697,16.977183,9.538413,NaN,NaN,1621949.0,NaN,NaN,1,std,air
102146,980222,154400,std,J-020,J-020,1,0.0,40.00,20.82,NaN,885.8,767.12,NaN,767.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.991,NaN,1832.32,F,F,,,1,1,1,980222154400,1998-02-22 15:44:00,False,False,True,True,0.0,False,0.0,NaN,1998-02-22 15:29:00,900.0,1,0,0,0,0,0,1998-02-22 03:00:00,45840.0,1998,2,22,15,44,0,766.770000,766.900000,874.966667,NaN,769.435976,752.393827,863.271951,39.999114,0.278747,0.200000,22.690159,49.127426,95.245350,5.882524,17.071869,18.773080,0.39,38.1,0.0,767.08,886.9,1,std,air
113751,980811,11000,std,J-025,J-025,1,0.0,40.00,21.21,NaN,811.2,758.12,NaN,758.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.420,NaN,1836.745,F,F,,,1,1,1,980811011000,1998-08-11 01:10:00,False,False,True,True,0.0,False,0.0,NaN,1998-08-11 00:29:00,2460.0,1,0,0,0,0,0,1998-08-09 02:47:00,166980.0,1998,8,11,1,10,0,758.370000,758.360000,806.530000,39.999000,758.125900,758.138000,805.700000,39.999800,0.178076,0.150555,4.846316,0.000000,0.598905,0.596756,5.879256,42.279739,-0.07,8.8,0.0,758.12,811.1,1,std,air
116652,980921,11700,std,J-025,J-025,1,0.0,40.00,20.51,NaN,821.5,769.65,NaN,769.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.579,NaN,1836.745,F,F,,,1,1,1,980921011700,1998-09-21 01:17:00,False,False,True,True,0.0,False,0.0,NaN,1998-09-21 00:37:00,2400.0,1,0,0,0,0,0,1998-09-20 02:56:00,80460.0,1998,9,21,1,17,0,769.573000,769.610000,816.760000,39.999000,773.234000,768.052000,816.220000,39.999500,0.091536,0.087560,5.031059,0.642564,60.711060,1.060444,4.749120,36.483392,-0.05,9.3,-32067.0,769.58,821.3,1,std,air
122354,990101,164200,std,J-025,J-025,1,0.0,40.00,21.13,NaN,782.9,733.10,NaN,732.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.699,NaN,1836.745,F,F,,,1,1,1,990101164200,1999-01-01 16:42:00,False,False,True,True,0.0,False,0.0,NaN,1999-01-01 15:46:00,3360.0,1,0,0,0,0,0,1998-12-26 12:04:00,535080.0,1999,1,1,16,42,0,734.913000,734.880000,779.680000,40.001000,735.851300,735.870000,785.170000,40.000426,0.400557,0.446716,15.495935,43.049656,1.028716,1.015983,5.127752,14.384121,-0.27,48.2,0.0,734.29,783.8,1,std,air
122519,990104,13600,std,J-025,J-025,1,0.0,39.99,18.40,NaN,784.8,735.64,NaN,735.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.569,NaN,1836.745,F,F,,,1,1,1,990104013600,1999-01-04 01:36:00,False,False,True,True,0.0,False,0.0,NaN,1999-01-04 00:03:00,5580.0,1,0,0,0,0,0,1999-01-03 03:03:00,81180.0,1999,1,4,1,36,0,735.609000,735.560000,780.010000,40.002000,750.759400,739.516000,788.652000,40.000100,0.211998,0.222111,15.328148,43.123847,70.711809,3.186801,6.234257,14.383664,0.17,47.6,0.0,735.37,784.0,1,std,air
122534,990104,80600,std,J-025,J-025,1,0.0,40.00,23.08,NaN,788.3,739.56,NaN,739.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.646,NaN,1836.745,F,F,,,1,1,1,990104080600,1999-01-04 08:06:00,False,False,True,True,0.0,False,0.0,NaN,1999-01-04 07:51:00,900.0,1,0,0,0,0,0,1999-01-03 03:03:00,104580.0,1999,1,4,8,6,0,736.265556,736.311111,785.188889,39.998889,748.762323,739.270707,788.349495,39.999697,0.654353,0.603002,1.162373,0.000000,59.320494,3.362435,6.366772,38.565193,NaN,NaN,0.0,NaN,NaN,1,std,air
123244,990114,110300,std,J-025,J-025,1,0.0,39.99,20.79,NaN,797.0,747.85,NaN,748.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.640,NaN,1836.745,F,F,,,1,1,1,990114110300,1999-01-14 11:03:00,False,False,True,True,0.0,False,0.0,NaN,1999-01-14 10:41:00,1320.0,1,0,0,0,0,0,1999-01-10 02:57:00,374760.0,1999,1,14,11,3,0,749.060000,749.116667,798.914286,40.004000,750.888351,750.896875,800.885567,39.999800,0.867852,0.842417,0.958173,42.986385,1.920392,1.885984,2.093442,14.343922,NaN,NaN,0.0,NaN,NaN,1,std,air
124163,990127,141700,std,J-025,J-025,1,0.0,40.01,21.32,NaN,809.0,758.75,NaN,758.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.933,NaN,1836.745,F,F,,,1,1,1,990127141700,1999-01-27 14:17:00,False,False,True,True,0.0,False,0.0,NaN,1999-01-27 13:42:00,2100.0,1,0,0,0,0,0,1999-01-24 02:51:00,300360.0,1999,1,27,14,17,0,758.748000,758.770000,810.140000,39.999000,754.957900,754.979000,804.778000,39.999700,0.081622,0.115950,1.579873,42.922752,2.993407,3.023988,3.684628,36.552756,0.18,-2.3,0.0,758.81,809.2,1,std,air
124194,990128,5700,std,J-025,J-025,1,0.0,39.99,21.19,NaN,809.3,758.87,NaN,758.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.064,NaN,1836.745,F,F,,,1,1,1,990128005700,1999-01-28 00:57:00,False,False,True,True,0.0,False,0.0,NaN,1999-01-28 00:17:00,2400.0,1,0,0,0,0,0,1999-01-24 02:51:00,338760.0,1999,1,28,0,57,0,758.868000,758.880000,810.390000,39.999000,757.405100,757.439000,807.940000,39.999400,0.113216,0.131656,1.463975,0.000000,1.449692,1.426651,2.259749,49.942204,-0.03,-2.8,0.0,758.77,808.8,1,std,air
125896,990221,71800,std,J-030,J-030,1,0.0,40.00,25.72,NaN,798.0,752.57,NaN,752.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.289,NaN,1839.437,F,F,,,1,1,1,990221071800,1999-02-21 07:18:00,False,False,True,True,0.0,False,0.0,NaN,1999-02-21 06:38:00,2400.0,1,0,0,0,0,0,1999-02-21 04:18:00,10800.0,1999,2,21,7,18,0,803.507000,752.290000,799.140000,40.000000,764.850909,757.755682,806.537079,39.999000,110.541813,0.338132,2.342458,0.000000,73.835139,2.504793,3.714021,42.184083,0.03,-4.0,0.0,752.31,797.8,1,std,air

In [8]:
import numpy as np

In [9]:
data['is_bad_std'] = ((data['type'] == 'std') & (data['is_ht_zero_and_C_Nan']==1)).astype(int)

data['is_normal_std'] =((data['type'] == 'std') & (data['is_ht_zero_and_C_Nan']==0)).astype(int)

data['error_state'] = (np.where(data['is_bad_std'], True,
                                np.where(data['is_normal_std'], False, np.nan))).astype(float)

# detect error serires
data['error_state'] = data['error_state'].ffill()

data['is_protential_flagged_air'] = ((data['error_state'] == True) & (data['type'] == 'air')).astype(int)

#print(data[data['is_protential_flagged_air'] == 1])
(data['is_protential_flagged_air'] == 1).sum()
#potential error air data
print(((data['is_protential_flagged_air'] == 1)&(data['label1'] == 0)).sum())

data[(data['is_protential_flagged_air'] == 1)&(data['label1'] == 0)&(data['is_ht_zero_and_C_Nan']==1)]

225

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p,CH4_flag_ht_bin,CH4_flag_a_bin,label1,datetime_str,datetime,is_ht_999,is_area_999,is_rt_zero,is_w_zero,duration,is_duration_spike,baseline_drift,ht_area_ratio,last_std_time,seconds_since_last_std,type_std,type_air,type_tank,type_blank,type_cal,type_other,last_cal_time,seconds_since_last_cal,year,month,day,hour,minute,seconds,psamp_roll_mean_10,pamb_roll_mean_10,pflow_roll_mean_10,tmod_roll_mean_10,psamp_roll_mean_100,pamb_roll_mean_100,pflow_roll_mean_100,tmod_roll_mean_100,psamp_roll_std_10,pamb_roll_std_10,pflow_roll_std_10,CH4_rt_roll_std_10,psamp_roll_std_100,pamb_roll_std_100,pflow_roll_std_100,CH4_rt_roll_std_100,psamp_diff_1,pflow_diff_1,CH4_area_diff_1,psamp_lag_1,pflow_lag_1,is_ht_zero_and_C_Nan,previous_point_type,next_point_type,is_bad_std,is_normal_std,error_state,is_protential_flagged_air
792621,250523,204100,air,9m,J-280,1,9.0,40.0,19.54,NaN,807.4,758.74,NaN,758.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.523,NaN,2004.399,,,A,,0,0,0,250523204100,2025-05-23 20:41:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-23 19:41:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43769160.0,2025,5,23,20,41,0,759.200,759.17,807.46,40.0,762.3992,762.397,810.922,40.0,0.230892,0.240601,1.099697,30.807676,1.813599,1.825324,1.975434,9.724407,-0.11,0.3,-1149542.0,758.81,807.8,1,std,std,0,0,1.0,1
792623,250523,212100,air,9m,J-280,1,9.0,40.0,19.61,NaN,806.9,758.55,NaN,758.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.656,NaN,2004.399,,,A,,0,0,0,250523212100,2025-05-23 21:21:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-23 20:21:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43771560.0,2025,5,23,21,21,0,759.061,759.01,807.66,40.0,762.2923,762.288,810.817,40.0,0.232687,0.237814,0.754542,47.062512,1.866030,1.879785,2.004795,16.671296,0.08,0.6,0.0,758.82,808.0,1,std,std,0,0,1.0,1
792625,250523,220100,air,9m,J-280,1,9.0,40.0,19.96,NaN,801.2,758.30,NaN,758.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.674,NaN,2004.399,,,A,,0,0,0,250523220100,2025-05-23 22:01:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-23 21:01:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43773960.0,2025,5,23,22,1,0,758.883,758.87,807.46,40.0,762.1779,762.174,810.695,40.0,0.255519,0.305687,0.735149,51.355424,1.919469,1.933209,2.041903,21.299524,-0.10,0.4,0.0,758.45,807.3,1,std,std,0,0,1.0,1
792627,250523,224100,air,9m,J-280,1,9.0,40.0,20.88,NaN,804.4,758.11,NaN,758.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.727,NaN,2004.399,,,A,,0,0,0,250523224100,2025-05-23 22:41:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-23 21:41:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43776360.0,2025,5,23,22,41,0,758.695,758.67,806.69,40.0,762.0604,762.057,810.515,40.0,0.325278,0.377271,2.047465,47.080904,1.977715,1.995614,2.251302,24.934814,-0.15,5.8,0.0,758.15,807.0,1,std,std,0,0,1.0,1
792629,250523,232100,air,9m,J-280,1,9.0,40.0,20.41,NaN,804.3,757.76,NaN,757.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.792,NaN,2004.399,,,A,,0,0,0,250523232100,2025-05-23 23:21:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-23 22:21:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43778760.0,2025,5,23,23,21,0,758.480,758.43,806.43,40.0,761.9386,761.932,810.389,40.0,0.341663,0.377271,2.090747,30.800584,2.034441,2.052979,2.348991,27.967936,-0.16,2.4,0.0,757.95,806.8,1,std,std,0,0,1.0,1
792631,250524,100,air,9m,J-280,1,9.0,40.0,19.51,NaN,802.0,757.29,NaN,757.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.846,NaN,2004.399,,,A,,0,0,0,250524000100,2025-05-24 00:01:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-23 23:01:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43781160.0,2025,5,24,0,1,0,758.251,758.21,806.00,40.0,761.8108,761.803,810.237,40.0,0.391874,0.384274,2.083800,0.000000,2.094459,2.108878,2.420270,30.578282,-0.08,2.4,0.0,757.68,806.7,1,std,std,0,0,1.0,1
792634,250524,12100,air,9m,J-280,1,9.0,40.0,20.67,NaN,803.0,756.81,NaN,756.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.048,NaN,2004.399,,,A,,0,0,0,250524012100,2025-05-24 01:21:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 00:21:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43785960.0,2025,5,24,1,21,0,757.797,757.71,805.23,40.0,761.6021,761.590,809.995,40.0,0.482426,0.513052,2.175137,0.000000,2.196528,2.219769,2.564496,33.910176,-0.26,-0.2,0.0,757.01,806.2,1,std,std,0,0,1.0,1
792636,250524,20100,air,9m,J-280,1,9.0,40.0,20.61,NaN,801.0,756.69,NaN,756.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.468,NaN,2004.399,,,A,,0,0,0,250524020100,2025-05-24 02:01:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 01:01:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43788360.0,2025,5,24,2,1,0,757.480,757.41,805.25,40.0,761.4567,761.444,809.849,40.0,0.520598,0.550656,1.739891,0.000000,2.269172,2.292778,2.674628,35.827804,-0.04,2.7,0.0,756.77,805.7,1,std,std,0,0,1.0,1
792638,250524,24100,air,9m,J-280,1,9.0,40.0,19.74,NaN,802.7,756.05,NaN,756.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.156,NaN,2004.399,,,A,,0,0,0,250524024100,2025-05-24 02:41:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 01:41:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43790760.0,2025,5,24,2,41,0,757.159,757.10,804.72,40.0,761.3072,761.295,809.651,40.0,0.520842,0.539547,2.074608,0.000000,2.342596,2.366747,2.817460,37.546350,-0.33,4.1,0.0,756.36,805.1,1,std,std,0,0,1.0,1
792640,250524,32100,air,9m,J-280,1,9.0,40.0,19.56,NaN,801.3,755.59,NaN,755.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.610,NaN,2004.399,,,A,,0,0,0,250524032100,2025-05-24 03:21:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 02:21:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43793160.0,2025,5,24,3,21,0,756.790,756.74,804.36,40.0,761.1495,761.137,809.485,40.0,0.551422,0.560159,2.028245,0.000000,2.427763,2.450754,2.918640,39.091071,-0.08,2.1,0.0,755.97,804.8,1,std,std,0,0,1.0,1
792642,250524,40100,air,9m,J-280,1,9.0,40.0,19.70,NaN,798.7,755.16,NaN,755.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.305,NaN,2004.399,,,A,,0,0,0,250524040100,2025-05-24 04:01:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 03:01:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43795560.0,2025,5,24,4,1,0,756.401,756.30,804.09,40.0,760.9809,760.965,809.324,40.0,0.606565,0.611010,1.964377,0.000000,2.517997,2.548217,3.049958,40.483720,-0.10,3.4,0.0,755.49,804.7,1,std,std,0,0,1.0,1
792644,250524,44100,air,9m,J-280,1,9.0,40.0,20.70,NaN,800.3,754.90,NaN,754.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.882,NaN,2004.399,,,A,,0,0,0,250524044100,2025-05-24 04:41:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 03:41:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43797960.0,2025,5,24,4,41,0,756.009,755.94,803.13,40.0,760.8061,760.790,809.104,40.0,0.635181,0.685079,2.231616,0.000000,2.610506,2.643746,3.231534,41.738672,0.04,5.6,0.0,755.20,804.3,1,std,std,0,0,1.0,1
792646,250524,52100,air,9m,J-280,1,9.0,40.0,20.08,NaN,800.6,754.65,NaN,754.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.795,NaN,2004.399,,,A,,0,0,0,250524052100,2025-05-24 05:21:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 04:21:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43800360.0,2025,5,24,5,21,0,755.618,755.52,802.65,40.0,760.6206,760.600,808.888,40.0,0.636532,0.705219,2.214222,0.000000,2.698098,2.736140,3.349032,42.869207,-0.13,3.3,0.0,754.77,803.6,1,std,std,0,0,1.0,1
792648,250524,60100,air,9m,J-280,1,9.0,40.0,19.52,NaN,797.3,754.40,NaN,754.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.725,NaN,2004.399,,,A,,0,0,0,250524060100,2025-05-24 06:01:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 05:01:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43802760.0,2025,5,24,6,1,0,755.226,755.13,802.45,40.0,760.4300,760.410,808.671,40.0,0.541832,0.567744,2.106208,0.000000,2.782105,2.819395,3.439500,43.885208,-0.17,2.9,0.0,754.48,803.5,1,std,std,0,0,1.0,1
792650,250524,64100,air,9m,J-280,1,9.0,40.0,19.74,NaN,800.6,754.12,NaN,754.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.862,NaN,2004.399,,,A,,0,0,0,250524064100,2025-05-24 06:41:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 05:41:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43805160.0,2025,5,24,6,41,0,754.891,754.77,801.76,40.0,760.2325,760.211,808.418,40.0,0.457492,0.442342,2.512723,0.000000,2.856971,2.899247,3.604525,44.793425,-0.13,6.0,0.0,754.27,803.3,1,std,std,0,0,1.0,1
792652,250524,72100,air,9m,J-280,1,9.0,40.0,20.37,NaN,800.0,753.93,NaN,754.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.022,NaN,2004.399,,,A,,0,0,0,250524072100,2025-05-24 07:21:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 06:21:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43807560.0,2025,5,24,7,21,0,754.581,754.50,801.51,40.0,760.0263,760.008,808.194,40.0,0.438772,0.418994,2.356763,0.000000,2.927866,2.971436,3.667350,45.597553,-0.26,2.3,0.0,753.86,802.9,1,std,std,0,0,1.0,1
792654,250524,80100,air,9m,J-280,1,9.0,40.0,20.67,NaN,800.5,753.77,NaN,753.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.078,NaN,2004.399,,,A,,0,0,0,250524080100,2025-05-24 08:01:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 07:01:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43809960.0,2025,5,24,8,1,0,754.325,754.26,801.49,40.0,759.8170,759.798,807.960,40.0,0.378337,0.333999,2.061526,0.000000,2.984226,3.024712,3.725560,46.305380,-0.06,2.8,0.0,753.87,802.8,1,std,std,0,0,1.0,1
792656,250524,84100,air,9m,J-280,1,9.0,40.0,19.58,NaN,798.2,753.37,NaN,753.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.278,NaN,2004.399,,,A,,0,0,0,250524084100,2025-05-24 08:41:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 07:41:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43812360.0,2025,5,24,8,41,0,754.091,754.04,801.42,40.0,759.6053,759.584,807.750,40.0,0.350443,0.368782,1.965706,0.000000,3.037786,3.080723,3.782909,46.921263,-0.21,2.2,0.0,753.56,802.7,1,std,std,0,0,1.0,1
792658,250524,92100,air,9m,J-280,1,9.0,40.0,19.72,NaN,799.8,753.26,NaN,753.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.496,NaN,2004.399,,,A,,0,0,0,250524092100,2025-05-24 09:21:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 08:21:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43814760.0,2025,5,24,9,21,0,753.842,753.82,801.08,40.0,759.3913,759.371,807.499,40.0,0.367478,0.319026,2.112292,0.000000,3.096172,3.129407,3.861399,47.447208,-0.10,4.3,0.0,753.27,802.5,1,std,std,0,0,1.0,1
792660,250524,100100,air,9m,J-280,1,9.0,40.0,20.80,NaN,799.9,753.07,NaN,752.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.720,NaN,2004.399,,,A,,0,0,0,250524100100,2025-05-24 10:01:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 09:01:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43817160.0,2025,5,24,10,1,0,753.612,753.64,801.22,40.0,759.1739,759.153,807.264,40.0,0.344216,0.302581,1.620562,0.000000,3.142830,3.165229,3.895984,47.889218,-0.15,2.4,0.0,753.11,802.2,1,std,std,0,0,1.0,1
792662,250524,104100,air,9m,J-280,1,9.0,40.0,19.65,NaN,797.8,752.84,NaN,752.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.968,NaN,2004.399,,,A,,0,0,0,250524104100,2025-05-24 10:41:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 09:41:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43819560.0,2025,5,24,10,41,0,753.411,753.39,801.04,40.0,758.9542,758.927,807.048,40.0,0.356447,0.401248,1.569996,0.000000,3.183985,3.211056,3.945320,48.248132,-0.17,1.9,0.0,752.90,801.8,1,std,std,0,0,1.0,1
792664,250524,112100,air,9m,J-280,1,9.0,40.0,19.61,NaN,799.3,752.32,NaN,752.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.143,NaN,2004.399,,,A,,0,0,0,250524112100,2025-05-24 11:21:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 10:21:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43821960.0,2025,5,24,11,21,0,753.173,753.12,800.69,40.0,758.7362,758.706,806.792,40.0,0.351759,0.426354,1.747665,0.000000,3.231040,3.262267,4.010408,48.524010,-0.26,3.7,0.0,752.58,801.5,1,std,std,0,0,1.0,1
792666,250524,120100,air,9m,J-280,1,9.0,40.0,19.98,NaN,798.6,751.88,NaN,752.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.465,NaN,2004.399,,,A,,0,0,0,250524120100,2025-05-24 12:01:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 11:01:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43824360.0,2025,5,24,12,1,0,752.879,752.83,800.43,40.0,758.5115,758.482,806.578,40.0,0.432986,0.529255,1.668033,0.000000,3.287588,3.323695,4.065812,48.721735,-0.25,2.0,0.0,752.07,801.3,1,std,std,0,0,1.0,1
792668,250524,124100,air,9m,J-280,1,9.0,40.0,20.79,NaN,796.3,751.44,NaN,751.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.719,NaN,2004.399,,,A,,0,0,0,250524124100,2025-05-24 12:41:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 11:41:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43826760.0,2025,5,24,12,41,0,752.561,752.53,800.31,40.0,758.2807,758.255,806.331,40.0,0.574213,0.516505,1.460936,0.000000,3.350530,3.374574,4.101409,48.840565,-0.30,2.3,0.0,751.58,800.9,1,std,std,0,0,1.0,1
792670,250524,132100,air,9m,J-280,1,9.0,40.0,20.11,NaN,798.2,750.90,NaN,750.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.152,NaN,2004.399,,,A,,0,0,0,250524132100,2025-05-24 13:21:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 12:21:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43829160.0,2025,5,24,13,21,0,752.193,752.10,799.77,40.0,758.0497,758.017,806.061,40.0,0.649667,0.598145,1.780793,0.000000,3.422517,3.447589,4.186580,48.881075,-0.19,4.0,0.0,751.25,800.3,1,std,std,0,0,1.0,1
792672,250524,140100,air,9m,J-280,1,9.0,40.0,19.67,NaN,797.8,750.39,NaN,750.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.707,NaN,2004.399,,,A,,0,0,0,250524140100,2025-05-24 14:01:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 13:01:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43831560.0,2025,5,24,14,1,0,751.745,751.66,799.40,40.0,757.8112,757.773,805.811,40.0,0.727557,0.772010,1.683251,0.000000,3.507611,3.535644,4.229285,48.843460,-0.31,1.6,0.0,750.59,799.8,1,std,std,0,0,1.0,1
792674,250524,144100,air,9m,J-280,1,9.0,40.0,20.30,NaN,786.2,749.64,NaN,749.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.761,NaN,2004.399,,,A,,0,0,0,250524144100,2025-05-24 14:41:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 13:41:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43833960.0,2025,5,24,14,41,0,751.250,751.13,799.17,40.0,757.5642,757.518,805.552,40.0,0.747277,0.894489,1.512944,0.000000,3.597361,3.634220,4.273916,48.727539,-0.31,1.4,0.0,750.08,799.2,1,std,std,0,0,1.0,1
792676,250524,152100,air,9m,J-280,1,9.0,40.0,19.76,NaN,791.7,749.36,NaN,749.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.877,NaN,2004.399,,,A,,0,0,0,250524152100,2025-05-24 15:21:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 14:21:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43836360.0,2025,5,24,15,21,0,750.731,750.59,797.58,40.0,757.3068,757.257,805.173,40.0,0.813981,0.965459,4.208932,0.000000,3.697201,3.738775,4.662311,48.532750,-0.08,12.3,0.0,749.56,798.5,1,std,std,0,0,1.0,1
792678,250524,160100,air,9m,J-280,1,9.0,40.0,19.72,NaN,792.0,748.99,NaN,749.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.805,NaN,2004.399,,,A,,0,0,0,250524160100,2025-05-24 16:01:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 15:01:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43838760.0,2025,5,24,16,1,0,750.239,750.05,796.64,40.0,757.0458,756.992,804.849,40.0,0.801851,0.780669,4.394239,0.000000,3.794440,3.827352,4.814760,48.258140,-0.18,6.7,0.0,749.18,798.4,1,std,std,0,0,1.0,1
792680,250524,164100,air,9m,J-280,1,9.0,40.0,20.35,NaN,795.2,748.58,NaN,748.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A,,0,0,0,250524164100,2025-05-24 16:41:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 15:41:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43841160.0,2025,5,24,16,41,0,749.753,749.61,796.00,40.0,756.7742,756.720,804.547,40.0,0.705330,0.627960,4.473875,0.000000,3.880597,3.905991,4.960764,47.902335,-0.15,6.2,0.0,748.84,798.2,1,std,std,0,0,1.0,1
792682,250524,172100,air,9m,J-280,1,9.0,40.0,19.60,NaN,792.9,748.56,NaN,748.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A,,0,0,0,250524172100,2025-05-24 17:21:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 16:21:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43843560.0,2025,5,24,17,21,0,749.322,749.25,795.49,40.0,756.4999,756.452,804.254,40.0,0.606352,0.452769,4.239877,0.000000,3.964602,3.983894,5.001079,47.460941,0.02,2.5,0.0,748.60,797.7,1,std,std,0,0,1.0,1
792684,250524,180100,air,9m,J-280,1,9.0,40.0,20.65,NaN,794.3,748.13,NaN,748.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A,,0,0,0,250524180100,2025-05-24 18:01:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 17:01:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43845960.0,2025,5,24,18,1,0,748.972,748.95,794.82,40.0,756.2273,756.177,803.935,40.0,0.444867,0.406202,4.062785,0.000000,4.037810,4.055694,5.073249,46.936653,-0.15,4.5,0.0,748.41,797.4,1,std,std,0,0,1.0,1
792686,250524,184100,air,9m,J-280,1,9.0,40.0,20.31,NaN,794.3,747.77,NaN,747.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A,,0,0,0,250524184100,2025-05-24 18:41:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 17:41:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43848360.0,2025,5,24,18,41,0,748.667,748.67,795.50,40.0,755.9523,755.898,803.654,40.0,0.431304,0.483161,2.625093,0.000000,4.115479,4.128834,5.131728,46.324112,-0.11,2.9,0.0,748.02,797.2,1,std,std,0,0,1.0,1
792688,250524,192200,air,9m,J-280,1,9.0,40.0,19.49,NaN,794.2,747.96,NaN,748.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A,,0,0,0,250524192200,2025-05-24 19:22:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 18:21:00,3660.0,0,1,0,0,0,0,2024-01-03 06:35:00,43850820.0,2025,5,24,19,22,0,748.380,748.41,795.62,40.0,755.6732,755.624,803.358,40.0,0.408248,0.435762,2.178583,0.000000,4.183439,4.192806,5.161790,45.616831,0.13,2.7,0.0,747.90,797.0,1,std,std,0,0,1.0,1
792690,250524,200200,air,9m,J-280,1,9.0,40.0,19.70,NaN,793.8,747.80,NaN,748.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A,,0,0,0,250524200200,2025-05-24 20:02:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 19:02:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43853220.0,2025,5,24,20,2,0,748.188,748.20,795.75,40.0,755.3992,755.350,803.060,40.0,0.317798,0.362093,1.751983,0.000000,4.231534,4.241105,5.166970,44.816203,-0.01,3.1,0.0,747.95,797.3,1,std,std,0,0,1.0,1

In [10]:
data.columns

Index(['date', 'time', 'type', 'sample', 'standard', 'port', 'ht', 'tmod',
       'tamb', 'lab_temp', 'pflow', 'psamp', 'ploop', 'pamb', 'CH4_rt',
       'CH4_w', 'CH4_ht', 'CH4_area', 'CH4_skew', 'CH4_start_time',
       'CH4_end_time', 'CH4_start_level', 'CH4_end_level', 'CH4_Rl_ht',
       'CH4_Rl_a', 'CH4_Rl', 'CH4_norm_ht', 'CH4_norm_a', 'CH4_norm_w',
       'CH4_R_ht', 'CH4_R_a', 'CH4_R', 'CH4_C_ht', 'CH4_C_a', 'CH4_C',
       'CH4_std_stdev', 'CH4_std_rep', 'CH4_Cstd', 'CH4_flag_ht', 'CH4_flag_a',
       'CH4_flag', 'CH4_flag_p', 'CH4_flag_ht_bin', 'CH4_flag_a_bin', 'label1',
       'datetime_str', 'datetime', 'is_ht_999', 'is_area_999', 'is_rt_zero',
       'is_w_zero', 'duration', 'is_duration_spike', 'baseline_drift',
       'ht_area_ratio', 'last_std_time', 'seconds_since_last_std', 'type_std',
       'type_air', 'type_tank', 'type_blank', 'type_cal', 'type_other',
       'last_cal_time', 'seconds_since_last_cal', 'year', 'month', 'day',
       'hour', 'minute', 'seconds', 'psamp_roll_mean_10', 'pamb_roll_mean_10',
       'pflow_roll_mean_10', 'tmod_roll_mean_10', 'psamp_roll_mean_100',
       'pamb_roll_mean_100', 'pflow_roll_mean_100', 'tmod_roll_mean_100',
       'psamp_roll_std_10', 'pamb_roll_std_10', 'pflow_roll_std_10',
       'CH4_rt_roll_std_10', 'psamp_roll_std_100', 'pamb_roll_std_100',
       'pflow_roll_std_100', 'CH4_rt_roll_std_100', 'psamp_diff_1',
       'pflow_diff_1', 'CH4_area_diff_1', 'psamp_lag_1', 'pflow_lag_1',
       'is_ht_zero_and_C_Nan', 'previous_point_type', 'next_point_type',
       'is_bad_std', 'is_normal_std', 'error_state',
       'is_protential_flagged_air'],
      dtype='object')

In [11]:
data['date'] = data['date'].astype(str).str.zfill(6)
data['time'] = data['time'].astype(str).str.zfill(6)
data.head()

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p,CH4_flag_ht_bin,CH4_flag_a_bin,label1,datetime_str,datetime,is_ht_999,is_area_999,is_rt_zero,is_w_zero,duration,is_duration_spike,baseline_drift,ht_area_ratio,last_std_time,seconds_since_last_std,type_std,type_air,type_tank,type_blank,type_cal,type_other,last_cal_time,seconds_since_last_cal,year,month,day,hour,minute,seconds,psamp_roll_mean_10,pamb_roll_mean_10,pflow_roll_mean_10,tmod_roll_mean_10,psamp_roll_mean_100,pamb_roll_mean_100,pflow_roll_mean_100,tmod_roll_mean_100,psamp_roll_std_10,pamb_roll_std_10,pflow_roll_std_10,CH4_rt_roll_std_10,psamp_roll_std_100,pamb_roll_std_100,pflow_roll_std_100,CH4_rt_roll_std_100,psamp_diff_1,pflow_diff_1,CH4_area_diff_1,psamp_lag_1,pflow_lag_1,is_ht_zero_and_C_Nan,previous_point_type,next_point_type,is_bad_std,is_normal_std,error_state,is_protential_flagged_air
0,940216,142900,air,10m,G-024,3,10.0,40.00,32.27,NaN,841.9,761.10,NaN,761.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,,1,1,1,940216142900,1994-02-16 14:29:00,False,False,True,True,0.0,False,0.0,NaN,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,14,29,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,None,air,0,0,NaN,0
1,940216,144900,air,10m,G-024,3,10.0,40.00,32.48,NaN,840.4,761.07,NaN,761.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,,1,1,1,940216144900,1994-02-16 14:49:00,False,False,True,True,0.0,False,0.0,NaN,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,14,49,0,761.100000,761.100000,841.900000,40.000000,761.100000,761.100000,841.900000,40.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,761.10,841.9,1,air,air,0,0,NaN,0
2,940216,150900,air,10m,G-024,3,10.0,40.01,32.75,NaN,839.4,760.99,NaN,760.9,109.8,2.60,190908.0,496440.0,0.63,102.0,135.4,10063.0,10029.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,,1,1,1,940216150900,1994-02-16 15:09:00,False,False,False,False,33.4,False,-34.0,0.384554,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,15,9,0,761.085000,761.150000,841.150000,40.000000,761.085000,761.150000,841.150000,40.000000,0.021213,0.070711,1.060660,0.000000,0.021213,0.070711,1.060660,0.000000,-0.03,-1.5,0.0,761.07,840.4,0,air,air,0,0,NaN,0
3,940216,152900,air,10m,G-024,3,10.0,40.00,32.92,NaN,839.6,760.96,NaN,760.9,94.8,6.85,151667.0,1065982.0,1.02,86.2,129.0,99999.0,99999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,,,,,0,0,0,940216152900,1994-02-16 15:29:00,False,False,False,False,42.8,False,0.0,0.142279,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,15,29,0,761.053333,761.066667,840.566667,40.003333,761.053333,761.066667,840.566667,40.003333,0.056862,0.152753,1.258306,63.393060,0.056862,0.152753,1.258306,63.393060,-0.08,-1.0,496440.0,760.99,839.4,0,air,air,0,0,NaN,0
4,940216,180000,air,10m,G-024,3,10.0,40.00,33.31,NaN,845.4,760.72,NaN,760.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,,1,1,1,940216180000,1994-02-16 18:00:00,False,False,True,True,0.0,False,0.0,NaN,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,18,0,0,761.030000,761.025000,840.325000,40.002500,761.030000,761.025000,840.325000,40.002500,0.065828,0.150000,1.135415,59.379542,0.065828,0.150000,1.135415,59.379542,-0.03,0.2,569542.0,760.96,839.6,1,air,air,0,0,NaN,0

In [12]:
data[(data['is_protential_flagged_air'] == 1)&(data['label1'] == 0)&(data['is_ht_zero_and_C_Nan']==1)]

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p,CH4_flag_ht_bin,CH4_flag_a_bin,label1,datetime_str,datetime,is_ht_999,is_area_999,is_rt_zero,is_w_zero,duration,is_duration_spike,baseline_drift,ht_area_ratio,last_std_time,seconds_since_last_std,type_std,type_air,type_tank,type_blank,type_cal,type_other,last_cal_time,seconds_since_last_cal,year,month,day,hour,minute,seconds,psamp_roll_mean_10,pamb_roll_mean_10,pflow_roll_mean_10,tmod_roll_mean_10,psamp_roll_mean_100,pamb_roll_mean_100,pflow_roll_mean_100,tmod_roll_mean_100,psamp_roll_std_10,pamb_roll_std_10,pflow_roll_std_10,CH4_rt_roll_std_10,psamp_roll_std_100,pamb_roll_std_100,pflow_roll_std_100,CH4_rt_roll_std_100,psamp_diff_1,pflow_diff_1,CH4_area_diff_1,psamp_lag_1,pflow_lag_1,is_ht_zero_and_C_Nan,previous_point_type,next_point_type,is_bad_std,is_normal_std,error_state,is_protential_flagged_air
792621,250523,204100,air,9m,J-280,1,9.0,40.0,19.54,NaN,807.4,758.74,NaN,758.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.523,NaN,2004.399,,,A,,0,0,0,250523204100,2025-05-23 20:41:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-23 19:41:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43769160.0,2025,5,23,20,41,0,759.200,759.17,807.46,40.0,762.3992,762.397,810.922,40.0,0.230892,0.240601,1.099697,30.807676,1.813599,1.825324,1.975434,9.724407,-0.11,0.3,-1149542.0,758.81,807.8,1,std,std,0,0,1.0,1
792623,250523,212100,air,9m,J-280,1,9.0,40.0,19.61,NaN,806.9,758.55,NaN,758.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.656,NaN,2004.399,,,A,,0,0,0,250523212100,2025-05-23 21:21:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-23 20:21:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43771560.0,2025,5,23,21,21,0,759.061,759.01,807.66,40.0,762.2923,762.288,810.817,40.0,0.232687,0.237814,0.754542,47.062512,1.866030,1.879785,2.004795,16.671296,0.08,0.6,0.0,758.82,808.0,1,std,std,0,0,1.0,1
792625,250523,220100,air,9m,J-280,1,9.0,40.0,19.96,NaN,801.2,758.30,NaN,758.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.674,NaN,2004.399,,,A,,0,0,0,250523220100,2025-05-23 22:01:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-23 21:01:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43773960.0,2025,5,23,22,1,0,758.883,758.87,807.46,40.0,762.1779,762.174,810.695,40.0,0.255519,0.305687,0.735149,51.355424,1.919469,1.933209,2.041903,21.299524,-0.10,0.4,0.0,758.45,807.3,1,std,std,0,0,1.0,1
792627,250523,224100,air,9m,J-280,1,9.0,40.0,20.88,NaN,804.4,758.11,NaN,758.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.727,NaN,2004.399,,,A,,0,0,0,250523224100,2025-05-23 22:41:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-23 21:41:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43776360.0,2025,5,23,22,41,0,758.695,758.67,806.69,40.0,762.0604,762.057,810.515,40.0,0.325278,0.377271,2.047465,47.080904,1.977715,1.995614,2.251302,24.934814,-0.15,5.8,0.0,758.15,807.0,1,std,std,0,0,1.0,1
792629,250523,232100,air,9m,J-280,1,9.0,40.0,20.41,NaN,804.3,757.76,NaN,757.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.792,NaN,2004.399,,,A,,0,0,0,250523232100,2025-05-23 23:21:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-23 22:21:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43778760.0,2025,5,23,23,21,0,758.480,758.43,806.43,40.0,761.9386,761.932,810.389,40.0,0.341663,0.377271,2.090747,30.800584,2.034441,2.052979,2.348991,27.967936,-0.16,2.4,0.0,757.95,806.8,1,std,std,0,0,1.0,1
792631,250524,000100,air,9m,J-280,1,9.0,40.0,19.51,NaN,802.0,757.29,NaN,757.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.846,NaN,2004.399,,,A,,0,0,0,250524000100,2025-05-24 00:01:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-23 23:01:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43781160.0,2025,5,24,0,1,0,758.251,758.21,806.00,40.0,761.8108,761.803,810.237,40.0,0.391874,0.384274,2.083800,0.000000,2.094459,2.108878,2.420270,30.578282,-0.08,2.4,0.0,757.68,806.7,1,std,std,0,0,1.0,1
792634,250524,012100,air,9m,J-280,1,9.0,40.0,20.67,NaN,803.0,756.81,NaN,756.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.048,NaN,2004.399,,,A,,0,0,0,250524012100,2025-05-24 01:21:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 00:21:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43785960.0,2025,5,24,1,21,0,757.797,757.71,805.23,40.0,761.6021,761.590,809.995,40.0,0.482426,0.513052,2.175137,0.000000,2.196528,2.219769,2.564496,33.910176,-0.26,-0.2,0.0,757.01,806.2,1,std,std,0,0,1.0,1
792636,250524,020100,air,9m,J-280,1,9.0,40.0,20.61,NaN,801.0,756.69,NaN,756.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.468,NaN,2004.399,,,A,,0,0,0,250524020100,2025-05-24 02:01:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 01:01:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43788360.0,2025,5,24,2,1,0,757.480,757.41,805.25,40.0,761.4567,761.444,809.849,40.0,0.520598,0.550656,1.739891,0.000000,2.269172,2.292778,2.674628,35.827804,-0.04,2.7,0.0,756.77,805.7,1,std,std,0,0,1.0,1
792638,250524,024100,air,9m,J-280,1,9.0,40.0,19.74,NaN,802.7,756.05,NaN,756.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.156,NaN,2004.399,,,A,,0,0,0,250524024100,2025-05-24 02:41:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 01:41:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43790760.0,2025,5,24,2,41,0,757.159,757.10,804.72,40.0,761.3072,761.295,809.651,40.0,0.520842,0.539547,2.074608,0.000000,2.342596,2.366747,2.817460,37.546350,-0.33,4.1,0.0,756.36,805.1,1,std,std,0,0,1.0,1
792640,250524,032100,air,9m,J-280,1,9.0,40.0,19.56,NaN,801.3,755.59,NaN,755.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.610,NaN,2004.399,,,A,,0,0,0,250524032100,2025-05-24 03:21:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 02:21:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43793160.0,2025,5,24,3,21,0,756.790,756.74,804.36,40.0,761.1495,761.137,809.485,40.0,0.551422,0.560159,2.028245,0.000000,2.427763,2.450754,2.918640,39.091071,-0.08,2.1,0.0,755.97,804.8,1,std,std,0,0,1.0,1
792642,250524,040100,air,9m,J-280,1,9.0,40.0,19.70,NaN,798.7,755.16,NaN,755.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.305,NaN,2004.399,,,A,,0,0,0,250524040100,2025-05-24 04:01:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 03:01:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43795560.0,2025,5,24,4,1,0,756.401,756.30,804.09,40.0,760.9809,760.965,809.324,40.0,0.606565,0.611010,1.964377,0.000000,2.517997,2.548217,3.049958,40.483720,-0.10,3.4,0.0,755.49,804.7,1,std,std,0,0,1.0,1
792644,250524,044100,air,9m,J-280,1,9.0,40.0,20.70,NaN,800.3,754.90,NaN,754.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.882,NaN,2004.399,,,A,,0,0,0,250524044100,2025-05-24 04:41:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 03:41:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43797960.0,2025,5,24,4,41,0,756.009,755.94,803.13,40.0,760.8061,760.790,809.104,40.0,0.635181,0.685079,2.231616,0.000000,2.610506,2.643746,3.231534,41.738672,0.04,5.6,0.0,755.20,804.3,1,std,std,0,0,1.0,1
792646,250524,052100,air,9m,J-280,1,9.0,40.0,20.08,NaN,800.6,754.65,NaN,754.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.795,NaN,2004.399,,,A,,0,0,0,250524052100,2025-05-24 05:21:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 04:21:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43800360.0,2025,5,24,5,21,0,755.618,755.52,802.65,40.0,760.6206,760.600,808.888,40.0,0.636532,0.705219,2.214222,0.000000,2.698098,2.736140,3.349032,42.869207,-0.13,3.3,0.0,754.77,803.6,1,std,std,0,0,1.0,1
792648,250524,060100,air,9m,J-280,1,9.0,40.0,19.52,NaN,797.3,754.40,NaN,754.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.725,NaN,2004.399,,,A,,0,0,0,250524060100,2025-05-24 06:01:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 05:01:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43802760.0,2025,5,24,6,1,0,755.226,755.13,802.45,40.0,760.4300,760.410,808.671,40.0,0.541832,0.567744,2.106208,0.000000,2.782105,2.819395,3.439500,43.885208,-0.17,2.9,0.0,754.48,803.5,1,std,std,0,0,1.0,1
792650,250524,064100,air,9m,J-280,1,9.0,40.0,19.74,NaN,800.6,754.12,NaN,754.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.862,NaN,2004.399,,,A,,0,0,0,250524064100,2025-05-24 06:41:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 05:41:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43805160.0,2025,5,24,6,41,0,754.891,754.77,801.76,40.0,760.2325,760.211,808.418,40.0,0.457492,0.442342,2.512723,0.000000,2.856971,2.899247,3.604525,44.793425,-0.13,6.0,0.0,754.27,803.3,1,std,std,0,0,1.0,1
792652,250524,072100,air,9m,J-280,1,9.0,40.0,20.37,NaN,800.0,753.93,NaN,754.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.022,NaN,2004.399,,,A,,0,0,0,250524072100,2025-05-24 07:21:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 06:21:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43807560.0,2025,5,24,7,21,0,754.581,754.50,801.51,40.0,760.0263,760.008,808.194,40.0,0.438772,0.418994,2.356763,0.000000,2.927866,2.971436,3.667350,45.597553,-0.26,2.3,0.0,753.86,802.9,1,std,std,0,0,1.0,1
792654,250524,080100,air,9m,J-280,1,9.0,40.0,20.67,NaN,800.5,753.77,NaN,753.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.078,NaN,2004.399,,,A,,0,0,0,250524080100,2025-05-24 08:01:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 07:01:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43809960.0,2025,5,24,8,1,0,754.325,754.26,801.49,40.0,759.8170,759.798,807.960,40.0,0.378337,0.333999,2.061526,0.000000,2.984226,3.024712,3.725560,46.305380,-0.06,2.8,0.0,753.87,802.8,1,std,std,0,0,1.0,1
792656,250524,084100,air,9m,J-280,1,9.0,40.0,19.58,NaN,798.2,753.37,NaN,753.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.278,NaN,2004.399,,,A,,0,0,0,250524084100,2025-05-24 08:41:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 07:41:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43812360.0,2025,5,24,8,41,0,754.091,754.04,801.42,40.0,759.6053,759.584,807.750,40.0,0.350443,0.368782,1.965706,0.000000,3.037786,3.080723,3.782909,46.921263,-0.21,2.2,0.0,753.56,802.7,1,std,std,0,0,1.0,1
792658,250524,092100,air,9m,J-280,1,9.0,40.0,19.72,NaN,799.8,753.26,NaN,753.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.496,NaN,2004.399,,,A,,0,0,0,250524092100,2025-05-24 09:21:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 08:21:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43814760.0,2025,5,24,9,21,0,753.842,753.82,801.08,40.0,759.3913,759.371,807.499,40.0,0.367478,0.319026,2.112292,0.000000,3.096172,3.129407,3.861399,47.447208,-0.10,4.3,0.0,753.27,802.5,1,std,std,0,0,1.0,1
792660,250524,100100,air,9m,J-280,1,9.0,40.0,20.80,NaN,799.9,753.07,NaN,752.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.720,NaN,2004.399,,,A,,0,0,0,250524100100,2025-05-24 10:01:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 09:01:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43817160.0,2025,5,24,10,1,0,753.612,753.64,801.22,40.0,759.1739,759.153,807.264,40.0,0.344216,0.302581,1.620562,0.000000,3.142830,3.165229,3.895984,47.889218,-0.15,2.4,0.0,753.11,802.2,1,std,std,0,0,1.0,1
792662,250524,104100,air,9m,J-280,1,9.0,40.0,19.65,NaN,797.8,752.84,NaN,752.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.968,NaN,2004.399,,,A,,0,0,0,250524104100,2025-05-24 10:41:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 09:41:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43819560.0,2025,5,24,10,41,0,753.411,753.39,801.04,40.0,758.9542,758.927,807.048,40.0,0.356447,0.401248,1.569996,0.000000,3.183985,3.211056,3.945320,48.248132,-0.17,1.9,0.0,752.90,801.8,1,std,std,0,0,1.0,1
792664,250524,112100,air,9m,J-280,1,9.0,40.0,19.61,NaN,799.3,752.32,NaN,752.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.143,NaN,2004.399,,,A,,0,0,0,250524112100,2025-05-24 11:21:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 10:21:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43821960.0,2025,5,24,11,21,0,753.173,753.12,800.69,40.0,758.7362,758.706,806.792,40.0,0.351759,0.426354,1.747665,0.000000,3.231040,3.262267,4.010408,48.524010,-0.26,3.7,0.0,752.58,801.5,1,std,std,0,0,1.0,1
792666,250524,120100,air,9m,J-280,1,9.0,40.0,19.98,NaN,798.6,751.88,NaN,752.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.465,NaN,2004.399,,,A,,0,0,0,250524120100,2025-05-24 12:01:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 11:01:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43824360.0,2025,5,24,12,1,0,752.879,752.83,800.43,40.0,758.5115,758.482,806.578,40.0,0.432986,0.529255,1.668033,0.000000,3.287588,3.323695,4.065812,48.721735,-0.25,2.0,0.0,752.07,801.3,1,std,std,0,0,1.0,1
792668,250524,124100,air,9m,J-280,1,9.0,40.0,20.79,NaN,796.3,751.44,NaN,751.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.719,NaN,2004.399,,,A,,0,0,0,250524124100,2025-05-24 12:41:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 11:41:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43826760.0,2025,5,24,12,41,0,752.561,752.53,800.31,40.0,758.2807,758.255,806.331,40.0,0.574213,0.516505,1.460936,0.000000,3.350530,3.374574,4.101409,48.840565,-0.30,2.3,0.0,751.58,800.9,1,std,std,0,0,1.0,1
792670,250524,132100,air,9m,J-280,1,9.0,40.0,20.11,NaN,798.2,750.90,NaN,750.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.152,NaN,2004.399,,,A,,0,0,0,250524132100,2025-05-24 13:21:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 12:21:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43829160.0,2025,5,24,13,21,0,752.193,752.10,799.77,40.0,758.0497,758.017,806.061,40.0,0.649667,0.598145,1.780793,0.000000,3.422517,3.447589,4.186580,48.881075,-0.19,4.0,0.0,751.25,800.3,1,std,std,0,0,1.0,1
792672,250524,140100,air,9m,J-280,1,9.0,40.0,19.67,NaN,797.8,750.39,NaN,750.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.707,NaN,2004.399,,,A,,0,0,0,250524140100,2025-05-24 14:01:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 13:01:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43831560.0,2025,5,24,14,1,0,751.745,751.66,799.40,40.0,757.8112,757.773,805.811,40.0,0.727557,0.772010,1.683251,0.000000,3.507611,3.535644,4.229285,48.843460,-0.31,1.6,0.0,750.59,799.8,1,std,std,0,0,1.0,1
792674,250524,144100,air,9m,J-280,1,9.0,40.0,20.30,NaN,786.2,749.64,NaN,749.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.761,NaN,2004.399,,,A,,0,0,0,250524144100,2025-05-24 14:41:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 13:41:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43833960.0,2025,5,24,14,41,0,751.250,751.13,799.17,40.0,757.5642,757.518,805.552,40.0,0.747277,0.894489,1.512944,0.000000,3.597361,3.634220,4.273916,48.727539,-0.31,1.4,0.0,750.08,799.2,1,std,std,0,0,1.0,1
792676,250524,152100,air,9m,J-280,1,9.0,40.0,19.76,NaN,791.7,749.36,NaN,749.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.877,NaN,2004.399,,,A,,0,0,0,250524152100,2025-05-24 15:21:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 14:21:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43836360.0,2025,5,24,15,21,0,750.731,750.59,797.58,40.0,757.3068,757.257,805.173,40.0,0.813981,0.965459,4.208932,0.000000,3.697201,3.738775,4.662311,48.532750,-0.08,12.3,0.0,749.56,798.5,1,std,std,0,0,1.0,1
792678,250524,160100,air,9m,J-280,1,9.0,40.0,19.72,NaN,792.0,748.99,NaN,749.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.805,NaN,2004.399,,,A,,0,0,0,250524160100,2025-05-24 16:01:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 15:01:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43838760.0,2025,5,24,16,1,0,750.239,750.05,796.64,40.0,757.0458,756.992,804.849,40.0,0.801851,0.780669,4.394239,0.000000,3.794440,3.827352,4.814760,48.258140,-0.18,6.7,0.0,749.18,798.4,1,std,std,0,0,1.0,1
792680,250524,164100,air,9m,J-280,1,9.0,40.0,20.35,NaN,795.2,748.58,NaN,748.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A,,0,0,0,250524164100,2025-05-24 16:41:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 15:41:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43841160.0,2025,5,24,16,41,0,749.753,749.61,796.00,40.0,756.7742,756.720,804.547,40.0,0.705330,0.627960,4.473875,0.000000,3.880597,3.905991,4.960764,47.902335,-0.15,6.2,0.0,748.84,798.2,1,std,std,0,0,1.0,1
792682,250524,172100,air,9m,J-280,1,9.0,40.0,19.60,NaN,792.9,748.56,NaN,748.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A,,0,0,0,250524172100,2025-05-24 17:21:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 16:21:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43843560.0,2025,5,24,17,21,0,749.322,749.25,795.49,40.0,756.4999,756.452,804.254,40.0,0.606352,0.452769,4.239877,0.000000,3.964602,3.983894,5.001079,47.460941,0.02,2.5,0.0,748.60,797.7,1,std,std,0,0,1.0,1
792684,250524,180100,air,9m,J-280,1,9.0,40.0,20.65,NaN,794.3,748.13,NaN,748.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A,,0,0,0,250524180100,2025-05-24 18:01:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 17:01:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43845960.0,2025,5,24,18,1,0,748.972,748.95,794.82,40.0,756.2273,756.177,803.935,40.0,0.444867,0.406202,4.062785,0.000000,4.037810,4.055694,5.073249,46.936653,-0.15,4.5,0.0,748.41,797.4,1,std,std,0,0,1.0,1
792686,250524,184100,air,9m,J-280,1,9.0,40.0,20.31,NaN,794.3,747.77,NaN,747.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A,,0,0,0,250524184100,2025-05-24 18:41:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 17:41:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43848360.0,2025,5,24,18,41,0,748.667,748.67,795.50,40.0,755.9523,755.898,803.654,40.0,0.431304,0.483161,2.625093,0.000000,4.115479,4.128834,5.131728,46.324112,-0.11,2.9,0.0,748.02,797.2,1,std,std,0,0,1.0,1
792688,250524,192200,air,9m,J-280,1,9.0,40.0,19.49,NaN,794.2,747.96,NaN,748.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A,,0,0,0,250524192200,2025-05-24 19:22:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 18:21:00,3660.0,0,1,0,0,0,0,2024-01-03 06:35:00,43850820.0,2025,5,24,19,22,0,748.380,748.41,795.62,40.0,755.6732,755.624,803.358,40.0,0.408248,0.435762,2.178583,0.000000,4.183439,4.192806,5.161790,45.616831,0.13,2.7,0.0,747.90,797.0,1,std,std,0,0,1.0,1
792690,250524,200200,air,9m,J-280,1,9.0,40.0,19.70,NaN,793.8,747.80,NaN,748.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A,,0,0,0,250524200200,2025-05-24 20:02:00,False,False,True,True,0.0,False,0.0,NaN,2025-05-24 19:02:00,3600.0,0,1,0,0,0,0,2024-01-03 06:35:00,43853220.0,2025,5,24,20,2,0,748.188,748.20,795.75,40.0,755.3992,755.350,803.060,40.0,0.317798,0.362093,1.751983,0.000000,4.231534,4.241105,5.166970,44.816203,-0.01,3.1,0.0,747.95,797.3,1,std,std,0,0,1.0,1

In [13]:
cols = ['date', 'time', 'type', 'sample', 'standard', 'port', 'ht', 'tmod',
       'tamb', 'lab_temp', 'pflow', 'psamp', 'ploop', 'pamb', 'CH4_rt',
       'CH4_w', 'CH4_ht', 'CH4_area', 'CH4_skew', 'CH4_start_time',
       'CH4_end_time', 'CH4_start_level', 'CH4_end_level', 'CH4_Rl_ht',
       'CH4_Rl_a', 'CH4_Rl', 'CH4_norm_ht', 'CH4_norm_a', 'CH4_norm_w',
       'CH4_R_ht', 'CH4_R_a', 'CH4_R', 'CH4_C_ht', 'CH4_C_a', 'CH4_C',
       'CH4_std_stdev', 'CH4_std_rep', 'CH4_Cstd', 'CH4_flag_ht', 'CH4_flag_a',
       'CH4_flag']

In [14]:
((data['is_protential_flagged_air'] == 1)&(data['label1'] == 0)&(data['is_ht_zero_and_C_Nan']==1)).sum()

np.int64(89)

In [15]:
data.head()

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p,CH4_flag_ht_bin,CH4_flag_a_bin,label1,datetime_str,datetime,is_ht_999,is_area_999,is_rt_zero,is_w_zero,duration,is_duration_spike,baseline_drift,ht_area_ratio,last_std_time,seconds_since_last_std,type_std,type_air,type_tank,type_blank,type_cal,type_other,last_cal_time,seconds_since_last_cal,year,month,day,hour,minute,seconds,psamp_roll_mean_10,pamb_roll_mean_10,pflow_roll_mean_10,tmod_roll_mean_10,psamp_roll_mean_100,pamb_roll_mean_100,pflow_roll_mean_100,tmod_roll_mean_100,psamp_roll_std_10,pamb_roll_std_10,pflow_roll_std_10,CH4_rt_roll_std_10,psamp_roll_std_100,pamb_roll_std_100,pflow_roll_std_100,CH4_rt_roll_std_100,psamp_diff_1,pflow_diff_1,CH4_area_diff_1,psamp_lag_1,pflow_lag_1,is_ht_zero_and_C_Nan,previous_point_type,next_point_type,is_bad_std,is_normal_std,error_state,is_protential_flagged_air
0,940216,142900,air,10m,G-024,3,10.0,40.00,32.27,NaN,841.9,761.10,NaN,761.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,,1,1,1,940216142900,1994-02-16 14:29:00,False,False,True,True,0.0,False,0.0,NaN,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,14,29,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,None,air,0,0,NaN,0
1,940216,144900,air,10m,G-024,3,10.0,40.00,32.48,NaN,840.4,761.07,NaN,761.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,,1,1,1,940216144900,1994-02-16 14:49:00,False,False,True,True,0.0,False,0.0,NaN,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,14,49,0,761.100000,761.100000,841.900000,40.000000,761.100000,761.100000,841.900000,40.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,761.10,841.9,1,air,air,0,0,NaN,0
2,940216,150900,air,10m,G-024,3,10.0,40.01,32.75,NaN,839.4,760.99,NaN,760.9,109.8,2.60,190908.0,496440.0,0.63,102.0,135.4,10063.0,10029.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,,1,1,1,940216150900,1994-02-16 15:09:00,False,False,False,False,33.4,False,-34.0,0.384554,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,15,9,0,761.085000,761.150000,841.150000,40.000000,761.085000,761.150000,841.150000,40.000000,0.021213,0.070711,1.060660,0.000000,0.021213,0.070711,1.060660,0.000000,-0.03,-1.5,0.0,761.07,840.4,0,air,air,0,0,NaN,0
3,940216,152900,air,10m,G-024,3,10.0,40.00,32.92,NaN,839.6,760.96,NaN,760.9,94.8,6.85,151667.0,1065982.0,1.02,86.2,129.0,99999.0,99999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,,,,,0,0,0,940216152900,1994-02-16 15:29:00,False,False,False,False,42.8,False,0.0,0.142279,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,15,29,0,761.053333,761.066667,840.566667,40.003333,761.053333,761.066667,840.566667,40.003333,0.056862,0.152753,1.258306,63.393060,0.056862,0.152753,1.258306,63.393060,-0.08,-1.0,496440.0,760.99,839.4,0,air,air,0,0,NaN,0
4,940216,180000,air,10m,G-024,3,10.0,40.00,33.31,NaN,845.4,760.72,NaN,760.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,,1,1,1,940216180000,1994-02-16 18:00:00,False,False,True,True,0.0,False,0.0,NaN,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,18,0,0,761.030000,761.025000,840.325000,40.002500,761.030000,761.025000,840.325000,40.002500,0.065828,0.150000,1.135415,59.379542,0.065828,0.150000,1.135415,59.379542,-0.03,0.2,569542.0,760.96,839.6,1,air,air,0,0,NaN,0

In [17]:
data.columns

Index(['date', 'time', 'type', 'sample', 'standard', 'port', 'ht', 'tmod',
       'tamb', 'lab_temp', 'pflow', 'psamp', 'ploop', 'pamb', 'CH4_rt',
       'CH4_w', 'CH4_ht', 'CH4_area', 'CH4_skew', 'CH4_start_time',
       'CH4_end_time', 'CH4_start_level', 'CH4_end_level', 'CH4_Rl_ht',
       'CH4_Rl_a', 'CH4_Rl', 'CH4_norm_ht', 'CH4_norm_a', 'CH4_norm_w',
       'CH4_R_ht', 'CH4_R_a', 'CH4_R', 'CH4_C_ht', 'CH4_C_a', 'CH4_C',
       'CH4_std_stdev', 'CH4_std_rep', 'CH4_Cstd', 'CH4_flag_ht', 'CH4_flag_a',
       'CH4_flag', 'CH4_flag_p', 'CH4_flag_ht_bin', 'CH4_flag_a_bin', 'label1',
       'datetime_str', 'datetime', 'is_ht_999', 'is_area_999', 'is_rt_zero',
       'is_w_zero', 'duration', 'is_duration_spike', 'baseline_drift',
       'ht_area_ratio', 'last_std_time', 'seconds_since_last_std', 'type_std',
       'type_air', 'type_tank', 'type_blank', 'type_cal', 'type_other',
       'last_cal_time', 'seconds_since_last_cal', 'year', 'month', 'day',
       'hour', 'minute', 'seconds', 'psamp_roll_mean_10', 'pamb_roll_mean_10',
       'pflow_roll_mean_10', 'tmod_roll_mean_10', 'psamp_roll_mean_100',
       'pamb_roll_mean_100', 'pflow_roll_mean_100', 'tmod_roll_mean_100',
       'psamp_roll_std_10', 'pamb_roll_std_10', 'pflow_roll_std_10',
       'CH4_rt_roll_std_10', 'psamp_roll_std_100', 'pamb_roll_std_100',
       'pflow_roll_std_100', 'CH4_rt_roll_std_100', 'psamp_diff_1',
       'pflow_diff_1', 'CH4_area_diff_1', 'psamp_lag_1', 'pflow_lag_1',
       'is_ht_zero_and_C_Nan', 'previous_point_type', 'next_point_type',
       'is_bad_std', 'is_normal_std', 'error_state',
       'is_protential_flagged_air'],
      dtype='object')

In [16]:
needed_features = ['date', 'time', 'type', 'sample', 'standard', 'port', 'ht','datetime', 'tmod', 'tamb', 'pflow', 'psamp', 'pamb', 'CH4_rt', 'CH4_w',
       'CH4_ht', 'CH4_area', 'CH4_skew', 'CH4_start_time', 'CH4_end_time',
       'CH4_start_level', 'CH4_end_level', 'duration', 'year', 'month', 'day',
       'hour', 'minute', 'seconds','is_ht_zero_and_C_Nan','is_bad_std', 'is_normal_std', 'is_protential_flagged_air','label1']

new_data = data[needed_features]

new_data.to_csv('../data/processed/mhd_ch4_simple_v2.csv')

In [15]:
potential_data = data[(data['is_protential_flagged_air'] == 1)&(data['label1'] == 0)&(data['is_ht_zero_and_C_Nan']==1)]
potential_data = potential_data[cols]
potential_data

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag
792621,250523,204100,air,9m,J-280,1,9.0,40.0,19.54,NaN,807.4,758.74,NaN,758.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.523,NaN,2004.399,,,A
792623,250523,212100,air,9m,J-280,1,9.0,40.0,19.61,NaN,806.9,758.55,NaN,758.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.656,NaN,2004.399,,,A
792625,250523,220100,air,9m,J-280,1,9.0,40.0,19.96,NaN,801.2,758.30,NaN,758.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.674,NaN,2004.399,,,A
792627,250523,224100,air,9m,J-280,1,9.0,40.0,20.88,NaN,804.4,758.11,NaN,758.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.727,NaN,2004.399,,,A
792629,250523,232100,air,9m,J-280,1,9.0,40.0,20.41,NaN,804.3,757.76,NaN,757.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.792,NaN,2004.399,,,A
792631,250524,000100,air,9m,J-280,1,9.0,40.0,19.51,NaN,802.0,757.29,NaN,757.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.846,NaN,2004.399,,,A
792634,250524,012100,air,9m,J-280,1,9.0,40.0,20.67,NaN,803.0,756.81,NaN,756.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.048,NaN,2004.399,,,A
792636,250524,020100,air,9m,J-280,1,9.0,40.0,20.61,NaN,801.0,756.69,NaN,756.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.468,NaN,2004.399,,,A
792638,250524,024100,air,9m,J-280,1,9.0,40.0,19.74,NaN,802.7,756.05,NaN,756.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.156,NaN,2004.399,,,A
792640,250524,032100,air,9m,J-280,1,9.0,40.0,19.56,NaN,801.3,755.59,NaN,755.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.610,NaN,2004.399,,,A
792642,250524,040100,air,9m,J-280,1,9.0,40.0,19.70,NaN,798.7,755.16,NaN,755.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.305,NaN,2004.399,,,A
792644,250524,044100,air,9m,J-280,1,9.0,40.0,20.70,NaN,800.3,754.90,NaN,754.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.882,NaN,2004.399,,,A
792646,250524,052100,air,9m,J-280,1,9.0,40.0,20.08,NaN,800.6,754.65,NaN,754.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.795,NaN,2004.399,,,A
792648,250524,060100,air,9m,J-280,1,9.0,40.0,19.52,NaN,797.3,754.40,NaN,754.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.725,NaN,2004.399,,,A
792650,250524,064100,air,9m,J-280,1,9.0,40.0,19.74,NaN,800.6,754.12,NaN,754.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.862,NaN,2004.399,,,A
792652,250524,072100,air,9m,J-280,1,9.0,40.0,20.37,NaN,800.0,753.93,NaN,754.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.022,NaN,2004.399,,,A
792654,250524,080100,air,9m,J-280,1,9.0,40.0,20.67,NaN,800.5,753.77,NaN,753.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.078,NaN,2004.399,,,A
792656,250524,084100,air,9m,J-280,1,9.0,40.0,19.58,NaN,798.2,753.37,NaN,753.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.278,NaN,2004.399,,,A
792658,250524,092100,air,9m,J-280,1,9.0,40.0,19.72,NaN,799.8,753.26,NaN,753.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.496,NaN,2004.399,,,A
792660,250524,100100,air,9m,J-280,1,9.0,40.0,20.80,NaN,799.9,753.07,NaN,752.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.720,NaN,2004.399,,,A
792662,250524,104100,air,9m,J-280,1,9.0,40.0,19.65,NaN,797.8,752.84,NaN,752.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.968,NaN,2004.399,,,A
792664,250524,112100,air,9m,J-280,1,9.0,40.0,19.61,NaN,799.3,752.32,NaN,752.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.143,NaN,2004.399,,,A
792666,250524,120100,air,9m,J-280,1,9.0,40.0,19.98,NaN,798.6,751.88,NaN,752.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.465,NaN,2004.399,,,A
792668,250524,124100,air,9m,J-280,1,9.0,40.0,20.79,NaN,796.3,751.44,NaN,751.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.719,NaN,2004.399,,,A
792670,250524,132100,air,9m,J-280,1,9.0,40.0,20.11,NaN,798.2,750.90,NaN,750.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.152,NaN,2004.399,,,A
792672,250524,140100,air,9m,J-280,1,9.0,40.0,19.67,NaN,797.8,750.39,NaN,750.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.707,NaN,2004.399,,,A
792674,250524,144100,air,9m,J-280,1,9.0,40.0,20.30,NaN,786.2,749.64,NaN,749.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.761,NaN,2004.399,,,A
792676,250524,152100,air,9m,J-280,1,9.0,40.0,19.76,NaN,791.7,749.36,NaN,749.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.877,NaN,2004.399,,,A
792678,250524,160100,air,9m,J-280,1,9.0,40.0,19.72,NaN,792.0,748.99,NaN,749.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.805,NaN,2004.399,,,A
792680,250524,164100,air,9m,J-280,1,9.0,40.0,20.35,NaN,795.2,748.58,NaN,748.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792682,250524,172100,air,9m,J-280,1,9.0,40.0,19.60,NaN,792.9,748.56,NaN,748.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792684,250524,180100,air,9m,J-280,1,9.0,40.0,20.65,NaN,794.3,748.13,NaN,748.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792686,250524,184100,air,9m,J-280,1,9.0,40.0,20.31,NaN,794.3,747.77,NaN,747.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792688,250524,192200,air,9m,J-280,1,9.0,40.0,19.49,NaN,794.2,747.96,NaN,748.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792690,250524,200200,air,9m,J-280,1,9.0,40.0,19.70,NaN,793.8,747.80,NaN,748.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792692,250524,204200,air,9m,J-280,1,9.0,40.0,20.13,NaN,789.3,748.67,NaN,749.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792694,250524,212200,air,9m,J-280,1,9.0,40.0,20.60,NaN,795.7,749.58,NaN,749.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792696,250524,220200,air,9m,J-280,1,9.0,40.0,20.76,NaN,796.2,750.25,NaN,750.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792698,250524,224200,air,9m,J-280,1,9.0,40.0,20.82,NaN,797.5,751.21,NaN,751.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792700,250524,232200,air,9m,J-280,1,9.0,40.0,20.76,NaN,798.0,751.52,NaN,751.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792702,250525,000200,air,9m,J-280,1,9.0,40.0,20.67,NaN,799.1,751.68,NaN,751.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792705,250525,012200,air,9m,J-280,1,9.0,40.0,20.73,NaN,799.9,752.26,NaN,752.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792707,250525,020200,air,9m,J-280,1,9.0,40.0,20.75,NaN,800.2,752.61,NaN,752.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792709,250525,024200,air,9m,J-280,1,9.0,40.0,20.86,NaN,800.6,752.67,NaN,752.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792711,250525,032200,air,9m,J-280,1,9.0,40.0,20.97,NaN,800.7,752.73,NaN,752.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792713,250525,040200,air,9m,J-280,1,9.0,40.0,20.99,NaN,800.0,752.78,NaN,752.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792715,250525,044200,air,9m,J-280,1,9.0,40.0,20.45,NaN,799.8,752.94,NaN,752.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792717,250525,052200,air,9m,J-280,1,9.0,40.0,19.77,NaN,800.2,753.19,NaN,753.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792719,250525,060200,air,9m,J-280,1,9.0,40.0,19.70,NaN,800.8,753.19,NaN,753.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792721,250525,064200,air,9m,J-280,1,9.0,40.0,19.78,NaN,801.0,753.48,NaN,753.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792723,250525,072200,air,9m,J-280,1,9.0,40.0,19.76,NaN,801.0,753.97,NaN,753.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792725,250525,080200,air,9m,J-280,1,9.0,40.0,19.97,NaN,801.2,753.92,NaN,754.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792727,250525,084200,air,9m,J-280,1,9.0,40.0,19.94,NaN,801.5,753.98,NaN,753.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792729,250525,092200,air,9m,J-280,1,9.0,40.0,19.83,NaN,801.5,754.08,NaN,754.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792731,250525,100200,air,9m,J-280,1,9.0,40.0,19.78,NaN,801.4,753.99,NaN,753.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792733,250525,104200,air,9m,J-280,1,9.0,40.0,20.28,NaN,801.6,754.05,NaN,754.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792735,250525,112200,air,9m,J-280,1,9.0,40.0,20.56,NaN,801.5,754.21,NaN,754.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792737,250525,120200,air,9m,J-280,1,9.0,40.0,20.70,NaN,801.6,754.27,NaN,754.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792739,250525,124200,air,9m,J-280,1,9.0,40.0,20.83,NaN,801.7,754.30,NaN,754.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792741,250525,132200,air,9m,J-280,1,9.0,40.0,20.51,NaN,801.6,754.24,NaN,754.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792743,250525,140200,air,9m,J-280,1,9.0,40.0,20.08,NaN,801.5,754.36,NaN,754.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.399,,,A
792745,250525,144200,air,9m,J-280,1,9.0,40.0,19.82,NaN,802.0,754.70,NaN,754.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.600,NaN,2004.399,,,A
792747,250525,152200,air,9m,J-280,1,9.0,40.0,19.80,NaN,802.0,754.65,NaN,754.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.600,NaN,2004.399,,,A
792749,250525,160200,air,9m,J-280,1,9.0,40.0,19.68,NaN,802.2,754.85,NaN,755.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.600,NaN,2004.399,,,A
792751,250525,164200,air,9m,J-280,1,9.0,40.0,19.69,NaN,802.6,754.92,NaN,754.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.600,NaN,2004.399,,,A
792753,250525,172200,air,9m,J-280,1,9.0,40.0,19.76,NaN,802.9,755.05,NaN,755.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.025,NaN,2004.399,,,A
792755,250525,180200,air,9m,J-280,1,9.0,40.0,20.08,NaN,803.1,754.94,NaN,755.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.834,NaN,2004.399,,,A
792757,250525,184200,air,9m,J-280,1,9.0,40.0,20.42,NaN,802.8,755.13,NaN,755.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.321,NaN,2004.399,,,A
792759,250525,192200,air,9m,J-280,1,9.0,40.0,20.57,NaN,803.1,755.37,NaN,755.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.638,NaN,2004.399,,,A
792761,250525,200200,air,9m,J-280,1,9.0,40.0,20.77,NaN,803.1,755.35,NaN,755.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.470,NaN,2004.399,,,A
792763,250525,204200,air,9m,J-280,1,9.0,40.0,20.77,NaN,803.2,755.51,NaN,755.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.834,NaN,2004.399,,,A
792765,250525,212200,air,9m,J-280,1,9.0,40.0,20.30,NaN,803.4,755.75,NaN,755.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.389,NaN,2004.399,,,A
792767,250525,220200,air,9m,J-280,1,9.0,40.0,19.83,NaN,803.8,755.97,NaN,755.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.921,NaN,2004.399,,,A
792769,250525,224200,air,9m,J-280,1,9.0,40.0,19.85,NaN,803.7,755.75,NaN,755.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.690,NaN,2004.399,,,A
792771,250525,232200,air,9m,J-280,1,9.0,40.0,20.56,NaN,804.2,755.67,NaN,756.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.395,NaN,2004.399,,,A
792773,250526,000200,air,9m,J-280,1,9.0,40.0,20.82,NaN,804.1,755.78,NaN,755.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.154,NaN,2004.399,,,A
792776,250526,012200,air,9m,J-280,1,9.0,40.0,19.99,NaN,804.2,755.78,NaN,755.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.902,NaN,2004.399,,,A
792778,250526,020200,air,9m,J-280,1,9.0,40.0,19.83,NaN,804.2,755.27,NaN,755.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.861,NaN,2004.399,,,A
792780,250526,024200,air,9m,J-280,1,9.0,40.0,20.67,NaN,803.8,755.40,NaN,755.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.900,NaN,2004.399,,,A
792782,250526,032200,air,9m,J-280,1,9.0,40.0,20.72,NaN,803.8,755.15,NaN,755.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.805,NaN,2004.399,,,A
792784,250526,040200,air,9m,J-280,1,9.0,40.0,20.93,NaN,803.3,755.18,NaN,755.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.696,NaN,2004.399,,,A
792786,250526,044200,air,9m,J-280,1,9.0,40.0,20.54,NaN,803.2,754.86,NaN,754.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.530,NaN,2004.399,,,A
792788,250526,052200,air,9m,J-280,1,9.0,40.0,19.84,NaN,802.8,754.83,NaN,755.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.318,NaN,2004.399,,,A
792790,250526,060200,air,9m,J-280,1,9.0,40.0,19.85,NaN,802.7,754.80,NaN,754.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.104,NaN,2004.399,,,A
792792,250526,064200,air,9m,J-280,1,9.0,40.0,20.56,NaN,802.9,755.10,NaN,754.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.913,NaN,2004.399,,,A
792794,250526,072200,air,9m,J-280,1,9.0,40.0,20.73,NaN,802.8,754.69,NaN,754.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.835,NaN,2004.399,,,A
792796,250526,080200,air,9m,J-280,1,9.0,40.0,20.92,NaN,802.8,754.26,NaN,754.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.018,NaN,2004.399,,,A
792798,250526,084200,air,9m,J-280,1,9.0,40.0,20.57,NaN,803.0,754.03,NaN,753.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.242,NaN,2004.399,,,A
792800,250526,092200,air,9m,J-280,1,9.0,40.0,19.91,NaN,802.2,753.93,NaN,753.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.349,NaN,2004.399,,,A

In [63]:
potential_data.to_csv('../data/processed/flagged.csv', index=False,na_rep='nan')

In [ ]:
from 250523	204100	 to 250526	092200	
and two from 260518	51200