In [20]:
import pandas as pd
import numpy as np
import seaborn as sns
sns.set_theme(style='darkgrid')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [21]:
raw_data = pd.read_csv('../data/processed/mhd_ch4_simple_v1.csv')
raw_data.head()

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p,label1,datetime_str,datetime,is_ht_999,is_area_999,is_rt_zero,is_w_zero,duration,ht_area_ratio,type_std,type_air,type_tank,type_blank,type_cal,type_other,year,month,day,hour,minute,seconds
0,940216,142900,air,10m,G-024,3,10.0,40.00,32.27,NaN,841.9,761.10,NaN,761.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216142900,1994-02-16 14:29:00,False,False,True,True,0.0,NaN,0,1,0,0,0,0,1994,2,16,14,29,0
1,940216,144900,air,10m,G-024,3,10.0,40.00,32.48,NaN,840.4,761.07,NaN,761.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216144900,1994-02-16 14:49:00,False,False,True,True,0.0,NaN,0,1,0,0,0,0,1994,2,16,14,49,0
2,940216,150900,air,10m,G-024,3,10.0,40.01,32.75,NaN,839.4,760.99,NaN,760.9,109.8,2.60,190908.0,496440.0,0.63,102.0,135.4,10063.0,10029.0,F,F,,,1,940216150900,1994-02-16 15:09:00,False,False,False,False,33.4,0.384554,0,1,0,0,0,0,1994,2,16,15,9,0
3,940216,152900,air,10m,G-024,3,10.0,40.00,32.92,NaN,839.6,760.96,NaN,760.9,94.8,6.85,151667.0,1065982.0,1.02,86.2,129.0,99999.0,99999.0,,,,,0,940216152900,1994-02-16 15:29:00,False,False,False,False,42.8,0.142279,0,1,0,0,0,0,1994,2,16,15,29,0
4,940216,180000,air,10m,G-024,3,10.0,40.00,33.31,NaN,845.4,760.72,NaN,760.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216180000,1994-02-16 18:00:00,False,False,True,True,0.0,NaN,0,1,0,0,0,0,1994,2,16,18,0,0

In [80]:
data = raw_data.copy()
data = data.drop(data[data['year']==2026].index)
data.tail()

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p,label1,datetime_str,datetime,is_ht_999,is_area_999,is_rt_zero,is_w_zero,duration,ht_area_ratio,type_std,type_air,type_tank,type_blank,type_cal,type_other,year,month,day,hour,minute,seconds
808206,251231,223800,std,J-286,J-286,3,0.0,40.0,21.01,NaN,817.8,765.45,NaN,765.7,94.0,7.83,170066.0,1489856.0,1.16,80.8,133.4,23823.0,24073.0,,,A,,0,251231223800,2025-12-31 22:38:00,False,False,False,False,52.6,0.114149,1,0,0,0,0,0,2025,12,31,22,38,0
808207,251231,225800,air,9m,J-286,1,9.0,40.0,20.74,NaN,813.2,765.28,NaN,765.2,94.0,7.85,171821.0,1508117.0,1.16,80.8,133.4,23750.0,24058.0,,,A,,0,251231225800,2025-12-31 22:58:00,False,False,False,False,52.6,0.113931,0,1,0,0,0,0,2025,12,31,22,58,0
808208,251231,231800,std,J-286,J-286,3,0.0,40.0,20.88,NaN,817.5,765.08,NaN,764.9,94.2,7.84,169569.0,1487622.0,1.06,80.8,133.6,23740.0,24030.0,,,A,,0,251231231800,2025-12-31 23:18:00,False,False,False,False,52.8,0.113987,1,0,0,0,0,0,2025,12,31,23,18,0
808209,251231,233800,air,9m,J-286,1,9.0,40.0,20.79,NaN,813.3,765.05,NaN,765.0,94.2,7.86,170281.0,1496142.0,1.07,80.8,133.6,23756.0,24015.0,,,A,,0,251231233800,2025-12-31 23:38:00,False,False,False,False,52.8,0.113813,0,1,0,0,0,0,2025,12,31,23,38,0
808210,251231,235800,std,J-286,J-286,3,0.0,NaN,NaN,NaN,817.4,764.90,NaN,NaN,94.2,7.83,169985.0,1489453.0,1.09,80.8,133.4,23691.0,24015.0,,,A,,0,251231235800,2025-12-31 23:58:00,False,False,False,False,52.6,0.114126,1,0,0,0,0,0,2025,12,31,23,58,0

In [81]:
def types_convert(type_name):
    """
    This fnuction is used for type classification
    """
    t = str(type_name).lower().strip()

    if 'cal' in t:
        return 'cal'
    elif 'std' in t:
        return 'std'
    elif 'air' == t:
        return 'air'
    elif 'tank' in t:
        return 'tank'
    elif 'blank' in t:
        return 'blank'
    else:
        return 'other'

In [82]:
data['type_norm'] = data['type'].apply(types_convert)
data['type_norm'].unique()

<StringArray>
['air', 'std', 'tank', 'cal', 'blank', 'other']
Length: 6, dtype: str

In [83]:
data = data.sort_values('datetime').reset_index(drop=True) # order by time
data.head()

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p,label1,datetime_str,datetime,is_ht_999,is_area_999,is_rt_zero,is_w_zero,duration,ht_area_ratio,type_std,type_air,type_tank,type_blank,type_cal,type_other,year,month,day,hour,minute,seconds,type_norm
0,940216,142900,air,10m,G-024,3,10.0,40.00,32.27,NaN,841.9,761.10,NaN,761.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216142900,1994-02-16 14:29:00,False,False,True,True,0.0,NaN,0,1,0,0,0,0,1994,2,16,14,29,0,air
1,940216,144900,air,10m,G-024,3,10.0,40.00,32.48,NaN,840.4,761.07,NaN,761.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216144900,1994-02-16 14:49:00,False,False,True,True,0.0,NaN,0,1,0,0,0,0,1994,2,16,14,49,0,air
2,940216,150900,air,10m,G-024,3,10.0,40.01,32.75,NaN,839.4,760.99,NaN,760.9,109.8,2.60,190908.0,496440.0,0.63,102.0,135.4,10063.0,10029.0,F,F,,,1,940216150900,1994-02-16 15:09:00,False,False,False,False,33.4,0.384554,0,1,0,0,0,0,1994,2,16,15,9,0,air
3,940216,152900,air,10m,G-024,3,10.0,40.00,32.92,NaN,839.6,760.96,NaN,760.9,94.8,6.85,151667.0,1065982.0,1.02,86.2,129.0,99999.0,99999.0,,,,,0,940216152900,1994-02-16 15:29:00,False,False,False,False,42.8,0.142279,0,1,0,0,0,0,1994,2,16,15,29,0,air
4,940216,180000,air,10m,G-024,3,10.0,40.00,33.31,NaN,845.4,760.72,NaN,760.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216180000,1994-02-16 18:00:00,False,False,True,True,0.0,NaN,0,1,0,0,0,0,1994,2,16,18,0,0,air

In [84]:
data['datetime'] = pd.to_datetime(data['datetime'])
data['time_diff'] = data['datetime'].diff() # calculate the time interval with theprevious record
data.head()

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p,label1,datetime_str,datetime,is_ht_999,is_area_999,is_rt_zero,is_w_zero,duration,ht_area_ratio,type_std,type_air,type_tank,type_blank,type_cal,type_other,year,month,day,hour,minute,seconds,type_norm,time_diff
0,940216,142900,air,10m,G-024,3,10.0,40.00,32.27,NaN,841.9,761.10,NaN,761.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216142900,1994-02-16 14:29:00,False,False,True,True,0.0,NaN,0,1,0,0,0,0,1994,2,16,14,29,0,air,NaT
1,940216,144900,air,10m,G-024,3,10.0,40.00,32.48,NaN,840.4,761.07,NaN,761.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216144900,1994-02-16 14:49:00,False,False,True,True,0.0,NaN,0,1,0,0,0,0,1994,2,16,14,49,0,air,0 days 00:20:00
2,940216,150900,air,10m,G-024,3,10.0,40.01,32.75,NaN,839.4,760.99,NaN,760.9,109.8,2.60,190908.0,496440.0,0.63,102.0,135.4,10063.0,10029.0,F,F,,,1,940216150900,1994-02-16 15:09:00,False,False,False,False,33.4,0.384554,0,1,0,0,0,0,1994,2,16,15,9,0,air,0 days 00:20:00
3,940216,152900,air,10m,G-024,3,10.0,40.00,32.92,NaN,839.6,760.96,NaN,760.9,94.8,6.85,151667.0,1065982.0,1.02,86.2,129.0,99999.0,99999.0,,,,,0,940216152900,1994-02-16 15:29:00,False,False,False,False,42.8,0.142279,0,1,0,0,0,0,1994,2,16,15,29,0,air,0 days 00:20:00
4,940216,180000,air,10m,G-024,3,10.0,40.00,33.31,NaN,845.4,760.72,NaN,760.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216180000,1994-02-16 18:00:00,False,False,True,True,0.0,NaN,0,1,0,0,0,0,1994,2,16,18,0,0,air,0 days 02:31:00

In [85]:
data = data.sort_values(['type_norm', 'datetime']).reset_index(drop=True)

data['time_diff'] = data.groupby('type_norm')['datetime'].diff()
new_session = (data['time_diff'] > pd.Timedelta(days=30)) | (data)['time_diff'].isna()

data['session_id'] = data['type_norm'].astype(str) + '_ss_' + new_session.groupby(data['type_norm']).cumsum().astype(str)

data.head()

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p,label1,datetime_str,datetime,is_ht_999,is_area_999,is_rt_zero,is_w_zero,duration,ht_area_ratio,type_std,type_air,type_tank,type_blank,type_cal,type_other,year,month,day,hour,minute,seconds,type_norm,time_diff,session_id
0,940216,142900,air,10m,G-024,3,10.0,40.00,32.27,NaN,841.9,761.10,NaN,761.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216142900,1994-02-16 14:29:00,False,False,True,True,0.0,NaN,0,1,0,0,0,0,1994,2,16,14,29,0,air,NaT,air_ss_1
1,940216,144900,air,10m,G-024,3,10.0,40.00,32.48,NaN,840.4,761.07,NaN,761.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216144900,1994-02-16 14:49:00,False,False,True,True,0.0,NaN,0,1,0,0,0,0,1994,2,16,14,49,0,air,0 days 00:20:00,air_ss_1
2,940216,150900,air,10m,G-024,3,10.0,40.01,32.75,NaN,839.4,760.99,NaN,760.9,109.8,2.60,190908.0,496440.0,0.63,102.0,135.4,10063.0,10029.0,F,F,,,1,940216150900,1994-02-16 15:09:00,False,False,False,False,33.4,0.384554,0,1,0,0,0,0,1994,2,16,15,9,0,air,0 days 00:20:00,air_ss_1
3,940216,152900,air,10m,G-024,3,10.0,40.00,32.92,NaN,839.6,760.96,NaN,760.9,94.8,6.85,151667.0,1065982.0,1.02,86.2,129.0,99999.0,99999.0,,,,,0,940216152900,1994-02-16 15:29:00,False,False,False,False,42.8,0.142279,0,1,0,0,0,0,1994,2,16,15,29,0,air,0 days 00:20:00,air_ss_1
4,940216,180000,air,10m,G-024,3,10.0,40.00,33.31,NaN,845.4,760.72,NaN,760.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216180000,1994-02-16 18:00:00,False,False,True,True,0.0,NaN,0,1,0,0,0,0,1994,2,16,18,0,0,air,0 days 02:31:00,air_ss_1

In [86]:
data['session_id'].unique()

<StringArray>
[  'air_ss_1', 'blank_ss_1', 'blank_ss_2', 'blank_ss_3', 'blank_ss_4',
 'blank_ss_5', 'blank_ss_6', 'blank_ss_7', 'blank_ss_8', 'blank_ss_9',
 ...
 'tank_ss_90', 'tank_ss_91', 'tank_ss_92', 'tank_ss_93', 'tank_ss_94',
 'tank_ss_95', 'tank_ss_96', 'tank_ss_97', 'tank_ss_98', 'tank_ss_99']
Length: 441, dtype: str

In [87]:
feature_cols = [
    #'sample'	,'standard',	
    #'port'	,'ht',
    'tmod'	,'tamb',
    'pflow', 'psamp',
    'pamb'	,
    'CH4_rt',	'CH4_w',	'CH4_ht'	,
    'CH4_area',	'CH4_skew'	,
    'CH4_start_time',	'CH4_end_time'	,'CH4_start_level',	'CH4_end_level',

    #'is_ht_999', 'is_area_999', 'is_rt_zero', 'is_w_zero',
    'duration', 
    'ht_area_ratio',
    #'type_air', 'type_blank', 'type_cal', 'type_other', 'type_std', 'type_tank',
    #'year', 'month', 'day', 'hour', 'minute', 'seconds'
]

In [ ]:
###handle NAN valuesmedian fill nan
for col in feature_cols:
    # first: fill in with previous value
    data[col] = data.groupby('session_id')[col].transform(lambda x: x.ffill())
    #second: median
    expanding_median = data.groupby('session_id')[col].transform(
        lambda x: x.expanding(min_periods=1).median()
    )
    data[col] = data[col].fillna(expanding_median)
    # third: whole type median
    type_median = data.groupby('type_norm')[col].transform('median')
    data[col] = data[col].fillna(type_median)
    # fourth: 0
    data[col] = data[col].fillna(0)

In [89]:
data.head()

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p,label1,datetime_str,datetime,is_ht_999,is_area_999,is_rt_zero,is_w_zero,duration,ht_area_ratio,type_std,type_air,type_tank,type_blank,type_cal,type_other,year,month,day,hour,minute,seconds,type_norm,time_diff,session_id
0,940216,142900,air,10m,G-024,3,10.0,40.00,32.27,NaN,841.9,761.10,NaN,761.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216142900,1994-02-16 14:29:00,False,False,True,True,0.0,0.115385,0,1,0,0,0,0,1994,2,16,14,29,0,air,NaT,air_ss_1
1,940216,144900,air,10m,G-024,3,10.0,40.00,32.48,NaN,840.4,761.07,NaN,761.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216144900,1994-02-16 14:49:00,False,False,True,True,0.0,0.115385,0,1,0,0,0,0,1994,2,16,14,49,0,air,0 days 00:20:00,air_ss_1
2,940216,150900,air,10m,G-024,3,10.0,40.01,32.75,NaN,839.4,760.99,NaN,760.9,109.8,2.60,190908.0,496440.0,0.63,102.0,135.4,10063.0,10029.0,F,F,,,1,940216150900,1994-02-16 15:09:00,False,False,False,False,33.4,0.384554,0,1,0,0,0,0,1994,2,16,15,9,0,air,0 days 00:20:00,air_ss_1
3,940216,152900,air,10m,G-024,3,10.0,40.00,32.92,NaN,839.6,760.96,NaN,760.9,94.8,6.85,151667.0,1065982.0,1.02,86.2,129.0,99999.0,99999.0,,,,,0,940216152900,1994-02-16 15:29:00,False,False,False,False,42.8,0.142279,0,1,0,0,0,0,1994,2,16,15,29,0,air,0 days 00:20:00,air_ss_1
4,940216,180000,air,10m,G-024,3,10.0,40.00,33.31,NaN,845.4,760.72,NaN,760.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216180000,1994-02-16 18:00:00,False,False,True,True,0.0,0.142279,0,1,0,0,0,0,1994,2,16,18,0,0,air,0 days 02:31:00,air_ss_1

In [90]:
data.tail()

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p,label1,datetime_str,datetime,is_ht_999,is_area_999,is_rt_zero,is_w_zero,duration,ht_area_ratio,type_std,type_air,type_tank,type_blank,type_cal,type_other,year,month,day,hour,minute,seconds,type_norm,time_diff,session_id
808206,251208,62300,tank,H-095,J-280,115,0.0,40.0,21.71,NaN,787.2,742.71,NaN,742.9,94.2,7.82,147364.0,1289677.0,1.13,81.2,132.8,23518.0,23807.0,,,A,,0,251208062300,2025-12-08 06:23:00,False,False,False,False,51.6,0.114264,0,0,1,0,0,0,2025,12,8,6,23,0,tank,0 days 00:40:00,tank_ss_99
808207,251208,70300,tank,H-095,J-280,115,0.0,40.0,21.53,NaN,786.8,742.57,NaN,742.5,94.2,7.82,147329.0,1286825.0,1.14,81.2,132.8,23550.0,23813.0,,,A,,0,251208070300,2025-12-08 07:03:00,False,False,False,False,51.6,0.114490,0,0,1,0,0,0,2025,12,8,7,3,0,tank,0 days 00:40:00,tank_ss_99
808208,251208,74300,tank,H-095,J-280,115,0.0,40.0,21.68,NaN,787.7,743.11,NaN,743.0,94.2,7.80,147748.0,1287184.0,1.14,81.2,132.8,23573.0,23815.0,,,A,,0,251208074300,2025-12-08 07:43:00,False,False,False,False,51.6,0.114784,0,0,1,0,0,0,2025,12,8,7,43,0,tank,0 days 00:40:00,tank_ss_99
808209,251208,82300,tank,H-095,J-280,115,0.0,40.0,21.42,NaN,788.0,743.72,NaN,743.5,94.2,7.82,147891.0,1292634.0,1.15,81.2,132.8,23559.0,23864.0,,,A,,0,251208082300,2025-12-08 08:23:00,False,False,False,False,51.6,0.114411,0,0,1,0,0,0,2025,12,8,8,23,0,tank,0 days 00:40:00,tank_ss_99
808210,251208,90300,tank,H-095,J-280,115,0.0,40.0,21.74,NaN,788.4,744.06,NaN,743.9,94.2,7.81,148261.0,1293777.0,1.13,81.2,132.8,23552.0,23839.0,,,A,,0,251208090300,2025-12-08 09:03:00,False,False,False,False,51.6,0.114595,0,0,1,0,0,0,2025,12,8,9,3,0,tank,0 days 00:40:00,tank_ss_99

In [91]:
data['datetime'] = pd.to_datetime(data['datetime'])

### residual calculation

In [92]:
data = data.set_index('datetime')

for col in feature_cols:
    drift_values=data.groupby('session_id')[col].transform(
        lambda x: x.rolling(window='30D', min_periods=1).mean()
    ) # average

    data[f'{col}_drift_30_days'] = drift_values
    data[f'{col}_residual'] = data[col] - data[f'{col}_drift_30_days']
data = data.reset_index()
data.head()

,datetime,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p,label1,datetime_str,is_ht_999,is_area_999,is_rt_zero,is_w_zero,duration,ht_area_ratio,type_std,type_air,type_tank,type_blank,type_cal,type_other,year,month,day,hour,minute,seconds,type_norm,time_diff,session_id,tmod_drift_30_days,tmod_residual,tamb_drift_30_days,tamb_residual,pflow_drift_30_days,pflow_residual,psamp_drift_30_days,psamp_residual,pamb_drift_30_days,pamb_residual,CH4_rt_drift_30_days,CH4_rt_residual,CH4_w_drift_30_days,CH4_w_residual,CH4_ht_drift_30_days,CH4_ht_residual,CH4_area_drift_30_days,CH4_area_residual,CH4_skew_drift_30_days,CH4_skew_residual,CH4_start_time_drift_30_days,CH4_start_time_residual,CH4_end_time_drift_30_days,CH4_end_time_residual,CH4_start_level_drift_30_days,CH4_start_level_residual,CH4_end_level_drift_30_days,CH4_end_level_residual,duration_drift_30_days,duration_residual,ht_area_ratio_drift_30_days,ht_area_ratio_residual
0,1994-02-16 14:29:00,940216,142900,air,10m,G-024,3,10.0,40.00,32.27,NaN,841.9,761.10,NaN,761.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216142900,False,False,True,True,0.0,0.115385,0,1,0,0,0,0,1994,2,16,14,29,0,air,NaT,air_ss_1,40.000000,0.000000,32.270,0.000,841.900000,0.000000,761.100000,0.000000,761.100000,0.000000,0.00,0.00,0.000000,0.000000,0.00,0.00,0.0,0.0,0.0000,0.0000,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.115385,0.000000
1,1994-02-16 14:49:00,940216,144900,air,10m,G-024,3,10.0,40.00,32.48,NaN,840.4,761.07,NaN,761.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216144900,False,False,True,True,0.0,0.115385,0,1,0,0,0,0,1994,2,16,14,49,0,air,0 days 00:20:00,air_ss_1,40.000000,0.000000,32.375,0.105,841.150000,-0.750000,761.085000,-0.015000,761.150000,0.050000,0.00,0.00,0.000000,0.000000,0.00,0.00,0.0,0.0,0.0000,0.0000,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.115385,0.000000
2,1994-02-16 15:09:00,940216,150900,air,10m,G-024,3,10.0,40.01,32.75,NaN,839.4,760.99,NaN,760.9,109.8,2.60,190908.0,496440.0,0.63,102.0,135.4,10063.0,10029.0,F,F,,,1,940216150900,False,False,False,False,33.4,0.384554,0,1,0,0,0,0,1994,2,16,15,9,0,air,0 days 00:20:00,air_ss_1,40.003333,0.006667,32.500,0.250,840.566667,-1.166667,761.053333,-0.063333,761.066667,-0.166667,36.60,73.20,0.866667,1.733333,63636.00,127272.00,165480.0,330960.0,0.2100,0.4200,34.00,68.00,45.133333,90.266667,3354.333333,6708.666667,3343.0,6686.0,11.133333,22.266667,0.205108,0.179446
3,1994-02-16 15:29:00,940216,152900,air,10m,G-024,3,10.0,40.00,32.92,NaN,839.6,760.96,NaN,760.9,94.8,6.85,151667.0,1065982.0,1.02,86.2,129.0,99999.0,99999.0,,,,,0,940216152900,False,False,False,False,42.8,0.142279,0,1,0,0,0,0,1994,2,16,15,29,0,air,0 days 00:20:00,air_ss_1,40.002500,-0.002500,32.605,0.315,840.325000,-0.725000,761.030000,-0.070000,761.025000,-0.125000,51.15,43.65,2.362500,4.487500,85643.75,66023.25,390605.5,675376.5,0.4125,0.6075,47.05,39.15,66.100000,62.900000,27515.500000,72483.500000,27507.0,72492.0,19.050000,23.750000,0.189401,-0.047122
4,1994-02-16 18:00:00,940216,180000,air,10m,G-024,3,10.0,40.00,33.31,NaN,845.4,760.72,NaN,760.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,F,F,,,1,940216180000,False,False,True,True,0.0,0.142279,0,1,0,0,0,0,1994,2,16,18,0,0,air,0 days 02:31:00,air_ss_1,40.002000,-0.002000,32.746,0.564,841.340000,4.060000,760.968000,-0.248000,760.940000,-0.340000,40.92,-40.92,1.890000,-1.890000,68515.00,-68515.00,312484.4,-312484.4,0.3300,-0.3300,37.64,-37.64,52.880000,-52.880000,22012.400000,-22012.400000,22005.6,-22005.6,15.240000,-15.240000,0.179977,-0.037697

In [93]:
data['session_age'] = data.groupby('session_id')['datetime'].transform(
    lambda x: (x - x.min()).dt.total_seconds() / (24*60*60)
)

In [94]:
data.tail()

,datetime,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p,label1,datetime_str,is_ht_999,is_area_999,is_rt_zero,is_w_zero,duration,ht_area_ratio,type_std,type_air,type_tank,type_blank,type_cal,type_other,year,month,day,hour,minute,seconds,type_norm,time_diff,session_id,tmod_drift_30_days,tmod_residual,tamb_drift_30_days,tamb_residual,pflow_drift_30_days,pflow_residual,psamp_drift_30_days,psamp_residual,pamb_drift_30_days,pamb_residual,CH4_rt_drift_30_days,CH4_rt_residual,CH4_w_drift_30_days,CH4_w_residual,CH4_ht_drift_30_days,CH4_ht_residual,CH4_area_drift_30_days,CH4_area_residual,CH4_skew_drift_30_days,CH4_skew_residual,CH4_start_time_drift_30_days,CH4_start_time_residual,CH4_end_time_drift_30_days,CH4_end_time_residual,CH4_start_level_drift_30_days,CH4_start_level_residual,CH4_end_level_drift_30_days,CH4_end_level_residual,duration_drift_30_days,duration_residual,ht_area_ratio_drift_30_days,ht_area_ratio_residual,session_age
808206,2025-12-08 06:23:00,251208,62300,tank,H-095,J-280,115,0.0,40.0,21.71,NaN,787.2,742.71,NaN,742.9,94.2,7.82,147364.0,1289677.0,1.13,81.2,132.8,23518.0,23807.0,,,A,,0,251208062300,False,False,False,False,51.6,0.114264,0,0,1,0,0,0,2025,12,8,6,23,0,tank,0 days 00:40:00,tank_ss_99,40.0,0.0,21.314554,0.395446,788.993069,-1.793069,743.106238,-0.396238,743.152475,-0.252475,94.952475,-0.752475,7.823168,-0.003168,161139.504950,-13775.504950,1.408726e+06,-119048.861386,1.100792,0.029208,81.726733,-0.526733,133.932673,-1.132673,24190.603960,-672.603960,24469.069307,-662.069307,52.205941,-0.605941,0.114390,-0.000126,184.140972
808207,2025-12-08 07:03:00,251208,70300,tank,H-095,J-280,115,0.0,40.0,21.53,NaN,786.8,742.57,NaN,742.5,94.2,7.82,147329.0,1286825.0,1.14,81.2,132.8,23550.0,23813.0,,,A,,0,251208070300,False,False,False,False,51.6,0.114490,0,0,1,0,0,0,2025,12,8,7,3,0,tank,0 days 00:40:00,tank_ss_99,40.0,0.0,21.320891,0.209109,788.886139,-2.086139,743.004257,-0.434257,743.048515,-0.548515,94.944554,-0.744554,7.822970,-0.002970,161101.366337,-13772.366337,1.408348e+06,-121523.158416,1.101782,0.038218,81.722772,-0.522772,133.924752,-1.124752,24180.613861,-630.613861,24459.059406,-646.059406,52.201980,-0.601980,0.114394,0.000096,184.168750
808208,2025-12-08 07:43:00,251208,74300,tank,H-095,J-280,115,0.0,40.0,21.68,NaN,787.7,743.11,NaN,743.0,94.2,7.80,147748.0,1287184.0,1.14,81.2,132.8,23573.0,23815.0,,,A,,0,251208074300,False,False,False,False,51.6,0.114784,0,0,1,0,0,0,2025,12,8,7,43,0,tank,0 days 00:40:00,tank_ss_99,40.0,0.0,21.325743,0.354257,788.786139,-1.086139,742.904752,0.205248,742.946535,0.053465,94.938614,-0.738614,7.822574,-0.022574,161067.326733,-13319.326733,1.407979e+06,-120795.445545,1.101980,0.038020,81.718812,-0.518812,133.918812,-1.118812,24171.396040,-598.396040,24449.514851,-634.514851,52.200000,-0.600000,0.114400,0.000383,184.196528
808209,2025-12-08 08:23:00,251208,82300,tank,H-095,J-280,115,0.0,40.0,21.42,NaN,788.0,743.72,NaN,743.5,94.2,7.82,147891.0,1292634.0,1.15,81.2,132.8,23559.0,23864.0,,,A,,0,251208082300,False,False,False,False,51.6,0.114411,0,0,1,0,0,0,2025,12,8,8,23,0,tank,0 days 00:40:00,tank_ss_99,40.0,0.0,21.330891,0.089109,788.689109,-0.689109,742.808416,0.911584,742.848515,0.651485,94.930693,-0.730693,7.822277,-0.002277,161027.000000,-13136.000000,1.407600e+06,-114966.247525,1.102178,0.047822,81.712871,-0.512871,133.908911,-1.108911,24160.425743,-601.425743,24439.148515,-575.148515,52.196040,-0.596040,0.114403,0.000008,184.224306
808210,2025-12-08 09:03:00,251208,90300,tank,H-095,J-280,115,0.0,40.0,21.74,NaN,788.4,744.06,NaN,743.9,94.2,7.81,148261.0,1293777.0,1.13,81.2,132.8,23552.0,23839.0,,,A,,0,251208090300,False,False,False,False,51.6,0.114595,0,0,1,0,0,0,2025,12,8,9,3,0,tank,0 days 00:40:00,tank_ss_99,40.0,0.0,21.342574,0.397426,788.592079,-0.192079,742.712772,1.347228,742.751485,1.148515,94.922772,-0.722772,7.822079,-0.012079,160988.534653,-12727.534653,1.407245e+06,-113468.128713,1.102673,0.027327,81.706931,-0.506931,133.899010,-1.099010,24150.049505,-598.049505,24428.801980,-589.801980,52.192079,-0.592079,0.114404,0.000191,184.252083

#### Scaler

In [95]:
data.columns

Index(['datetime', 'date', 'time', 'type', 'sample', 'standard', 'port', 'ht',
       'tmod', 'tamb', 'lab_temp', 'pflow', 'psamp', 'ploop', 'pamb', 'CH4_rt',
       'CH4_w', 'CH4_ht', 'CH4_area', 'CH4_skew', 'CH4_start_time',
       'CH4_end_time', 'CH4_start_level', 'CH4_end_level', 'CH4_flag_ht',
       'CH4_flag_a', 'CH4_flag', 'CH4_flag_p', 'label1', 'datetime_str',
       'is_ht_999', 'is_area_999', 'is_rt_zero', 'is_w_zero', 'duration',
       'ht_area_ratio', 'type_std', 'type_air', 'type_tank', 'type_blank',
       'type_cal', 'type_other', 'year', 'month', 'day', 'hour', 'minute',
       'seconds', 'type_norm', 'time_diff', 'session_id', 'tmod_drift_30_days',
       'tmod_residual', 'tamb_drift_30_days', 'tamb_residual',
       'pflow_drift_30_days', 'pflow_residual', 'psamp_drift_30_days',
       'psamp_residual', 'pamb_drift_30_days', 'pamb_residual',
       'CH4_rt_drift_30_days', 'CH4_rt_residual', 'CH4_w_drift_30_days',
       'CH4_w_residual', 'CH4_ht_drift_30_days', 'CH4_ht_residual',
       'CH4_area_drift_30_days', 'CH4_area_residual', 'CH4_skew_drift_30_days',
       'CH4_skew_residual', 'CH4_start_time_drift_30_days',
       'CH4_start_time_residual', 'CH4_end_time_drift_30_days',
       'CH4_end_time_residual', 'CH4_start_level_drift_30_days',
       'CH4_start_level_residual', 'CH4_end_level_drift_30_days',
       'CH4_end_level_residual', 'duration_drift_30_days', 'duration_residual',
       'ht_area_ratio_drift_30_days', 'ht_area_ratio_residual', 'session_age'],
      dtype='str')

In [96]:
model_features = [#'port', 'ht',
   #'sample'	,'standard',	
    #'port'	,'ht',
    'tmod'	,'tamb',
    'pflow', 'psamp',
    'pamb'	,
    'CH4_rt',	'CH4_w',	'CH4_ht'	,
    'CH4_area',	'CH4_skew'	,
    'CH4_start_time', 'CH4_end_time', 'CH4_start_level', 'CH4_end_level',

    #'is_ht_999', 'is_area_999', 'is_rt_zero', 'is_w_zero',
    'duration', 
    'ht_area_ratio',
    #'type_air', 'type_blank', 'type_cal', 'type_other', 'type_std', 'type_tank',
    #'year', 'month', 'day', 'hour', 'minute', 'seconds'

       'type_norm', 'time_diff', 'session_id', 'tmod_drift_30_days',
       'tmod_residual', 'tamb_drift_30_days', 'tamb_residual',

       'pflow_drift_30_days', 'pflow_residual', 'psamp_drift_30_days',
       'psamp_residual', 'pamb_drift_30_days', 'pamb_residual',

       'CH4_rt_drift_30_days', 'CH4_rt_residual', 'CH4_w_drift_30_days',
       'CH4_w_residual', 'CH4_ht_drift_30_days', 'CH4_ht_residual',

       'CH4_area_drift_30_days', 'CH4_area_residual', 'CH4_skew_drift_30_days',
       'CH4_skew_residual', 'CH4_start_time_drift_30_days',
       'CH4_start_time_residual', 'CH4_end_time_drift_30_days',
       'CH4_end_time_residual', 'CH4_start_level_drift_30_days',
       'CH4_start_level_residual', 'CH4_end_level_drift_30_days',
       
       'CH4_end_level_residual', 'duration_drift_30_days',
       'duration_residual', 'ht_area_ratio_drift_30_days', 'ht_area_ratio_residual', 'session_age']

In [99]:
from sklearn.preprocessing import MinMaxScaler
import torch
from torch.utils.data import DataLoader, TensorDataset

X_raw = data[model_features].values

#===== scaler

scaler = MinMaxScaler() # for session_age 
X_scaled = scaler.fit_transform(X_raw)

X_tensor = torch.tensor(X_scaled, dtype=torch.float32)

dataset = TensorDataset(X_tensor)
train_loader = DataLoader(dataset, batch_size=128, shuffle=True, num_workers=0)

print(f"Shape:{X_tensor.shape}")

AttributeError: partially initialized module 'torch' from '/home/ellie/research_project/.venv/lib/python3.13/site-packages/torch/__init__.py' has no attribute 'nn' (most likely due to a circular import)

In [100]:
import sys

print(sys.executable)

/home/ellie/research_project/.venv/bin/python

In [ ]:
import torch.nn as nn
class GCAutoencoder(nn.Module):
    def __init__(self, input_dim=26):
        super(GCAutoencoder, self).__init__()

        self.encoder = nn.Sequential(
            nn.Linear(input_dim, 16),
            nn.ReLU(),
            nn.Linear(16, 8),
            nn.ReLU(),
            nn.Linear(8,3)
        )

        self.decoder = nn.Sequential(
            nn.Linear(3,8),
            nn.ReLU(),
            nn.Linear(8,16),
            nn.ReLU(),
            nn.Linear(16, input_dim)
        )

    def forward(self, x):
        embedding = self.encoder(x)

        reconstructed = self.decoder(embedding)
        return reconstructed, embedding
        
model = GCAutoencoder(input_dim=38)
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)